---
title: "AHA Global Proteomics"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects/Janet Snell-Bergeon/AHA collaborative grant/Proteomics"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant"
}
knitr::opts_knit$set(root.dir = home_dir)
library(arsenal)
library(skimr)
library(knitr)
library(tidyverse)
```

```{r}
# Import
proteins = read.csv("./Data_Cleaned/global_proteome.csv",na.strings = "")
manifest = read.csv("./Data_Cleaned/global_manifest.csv",na.strings = "")
qc_samples = manifest$File.ID[grep("QC",manifest$Sample.Type)]
res_samples = manifest$File.ID[grep("Sample",manifest$Sample.Type)]
# Split into normalized and raw
raw_df = proteins %>% select(Protein.FDR.Confidence..Combined:Gene.ID,
                             Abundance..F1..Sample:Abundance..F287..Sample)
normalized_df = proteins %>% select(Protein.FDR.Confidence..Combined:Gene.ID,
                             Abundances..Normalized...F1..Sample:Abundances..Normalized...F287..Sample)
# Rename columns
colnames(raw_df) = sub("Abundance..","",colnames(raw_df))
colnames(raw_df) = sub("..Sample","",colnames(raw_df))
colnames(normalized_df) = sub("Abundance..","",colnames(normalized_df))
colnames(normalized_df) = sub("..Sample","",colnames(normalized_df))
```

# Preprocessing

## Compound QC

```{r}
# Check compounds with > 20% missing values in research samples
res_missing <- which(rowSums(is.na(raw_df[,res_samples]))/length(res_samples) > 0.2)
# Check compounds with > 80% missing values in QC samples
qc_missing <- which(rowSums(is.na(raw_df[,qc_samples]))/length(qc_samples) > 0.8)
comp_missing = unique(c(res_missing,qc_missing))
if (length(comp_missing)>0){raw_df <- raw_df[-comp_missing,]}
```

Removed `r length(res_missing)` compounds missing in > 20% of research samples and `r length(qc_samples)` compounds missing in > 80% of QC samples (a total of `r length(comp_missing)` accounting for compounds missing in both).

## Sample QC

```{r}
# Check for samples with > 80% missing compounds
sample_missing <- which(colSums(is.na(raw_df[,res_samples]))/nrow(raw_df) > 0.8)
if (length(sample_missing)>0){raw_df <- raw_df[,-sample_missing]}
```

Removed `r length(sample_missing)` samples missing > 80% of compounds.

## Data Skim (log Transformed)

```{r}
df = raw_df
df[,c(res_samples,qc_samples)] = lapply(df[,c(res_samples,qc_samples)], log)
skim(df)
```
