---
title: "AHA Glycated Proteomics"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/peds/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant/Proteomics")
library(arsenal)
library(skimr)
library(knitr)
library(mixOmics)
library(tidyverse)
```

```{r data import and clean,echo=FALSE}
# Protein abundance
abundance <- read.csv("./Data_Cleaned/peptide_abundance.csv")
# List protein names
proteins <- colnames(abundance)[3:ncol(abundance)]
# Add CAC group and demographic info 
demographics <- read.csv("./Data_Cleaned/demographics.csv")
cac_group <- read.csv("./Data_Cleaned/cac_groups.csv")
abundance <- left_join(abundance,demographics,by = "StudyID")
abundance <- left_join(abundance,cac_group[,c("StudyID","GROUP")],by = "StudyID")
abundance$CACprog <- ifelse(abundance$c3 - abundance$c1 >= 2.5,
                                         "Progression","No Progression")
abundance$CACprog[is.na(abundance$CACprog)] <- "Unknown"
# Remove, format, and order columns
abundance$StudyID <- as.factor(abundance$StudyID)
abundance <- abundance %>% 
  dplyr::select(StudyID,gender,age,race,GROUP,CACprog,hba1cV1,all_of(proteins))
# Peptide sequences
sequence <- read.csv("./Data_Cleaned/peptide_sequence.csv")
# Sample injection order
sample_order <- read.csv("./Data_Cleaned/sample_acquisition.csv")
```

# PLS-DA

```{r plsda,echo=FALSE,cache=TRUE}
# Sex
Y <- as.factor(abundance$gender)
X = abundance[,8:ncol(abundance)]
# 5 components
plsda.res <- plsda(X, Y, ncomp = 5) 
plotIndiv(plsda.res,title = "PLS-DA by Sex",
          pch = 20,ind.names = F,ellipse = T,legend = T)
# Race
Y <- as.factor(abundance$race)
# 5 components
plsda.res <- plsda(X, Y, ncomp = 5) 
plotIndiv(plsda.res,title = "PLS-DA by Race",
          pch = 20,ind.names = F,ellipse = T,legend = T)
# CAC group
Y <- as.factor(abundance$GROUP)
# 5 components
plsda.res <- plsda(X, Y, ncomp = 5) 
plotIndiv(plsda.res,title = "PLS-DA by CAC Group",
          pch = 20,ind.names = F,ellipse = T,legend = T)
```

# sPLS-DA

```{r splsda,echo=FALSE,cache=TRUE,warning=FALSE,message=FALSE}
# Sex
Y <- as.factor(abundance$gender)
tune.splsda <- tune.splsda(X, Y, ncomp = 5) 
choice.keepX <- tune.splsda$choice.keepX[1:2]
## sPLS-DA function
splsda.res <- splsda(X, Y, ncomp = 2, keepX = choice.keepX)
plotIndiv(splsda.res,title = "sPLS-DA by Sex",
          pch = 20,ind.names = F,ellipse = T,legend = T)
# Race
Y <- as.factor(abundance$race)
tune.splsda <- tune.splsda(X, Y, ncomp = 5) 
choice.keepX <- tune.splsda$choice.keepX[1:2]
## sPLS-DA function
splsda.res <- splsda(X, Y, ncomp = 2, keepX = choice.keepX)
plotIndiv(splsda.res,title = "sPLS-DA by Race",
          pch = 20,ind.names = F,ellipse = T,legend = T)
# Group
Y <- as.factor(abundance$GROUP)
tune.splsda <- tune.splsda(X, Y, ncomp = 5) 
choice.keepX <- tune.splsda$choice.keepX[1:2]
## sPLS-DA function
splsda.res <- splsda(X, Y, ncomp = 2, keepX = choice.keepX)
plotIndiv(splsda.res,title = "sPLS-DA by CAC Group",
          pch = 20,ind.names = F,ellipse = T,legend = T)
```

