---
title: "Maki Nakayama and Aaron Michels - CD8 Table 1"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
library(knitr)
library(tableone)

knitr::opts_chunk$set(echo = TRUE)

# read in table 1 data
t1d <- read.csv("T:\\Maki Nakayama\\CD-8 Elispot\\Data raw\\From Aaron\\CD8 Elispot Data 03172020 T1D.csv")
t1d$group <- "New Onset T1D"
t1d$Age..years. <- t1d$Age.at.Dx..years.
t1d$gadpos <- ifelse(t1d$GAD65..nl...20.>=20,1,0)
t1d$ia2pos <- ifelse(t1d$IA.2..nl...5.>=5,1,0)
t1d$iaapos <- ifelse(t1d$IAA..nl...0.01.>=0.01,1,0)
t1d$znt8pos <- ifelse(t1d$ZnT8..nl...0.02.>=0.02,1,0)
t1d$numpos <-  t1d$ia2pos + t1d$gadpos + t1d$iaapos + t1d$znt8pos
t1d$multpos <- ifelse(t1d$numpos>=1,1,0)
t1d <- t1d[,c("Sample.ID","Age..years.","Sex","Race.Ethnicity","Hispanic","Duration.to.visit..days.",
           "gadpos","ia2pos","iaapos","znt8pos","multpos","group")]

control <- read.csv("T:\\Maki Nakayama\\CD-8 Elispot\\Data raw\\From Aaron\\CD8 Elispot Data 03172020 Control.csv")
control$group <- "Non-diabetic"
control$Duration.to.visit..days. <- NA
control$gadpos <- NA
control$ia2pos <- NA
control$iaapos <- NA
control$znt8pos <- NA
control$multpos <- NA
control <- control[,c("Sample.ID","Age..years.","Sex","Race.Ethnicity","Hispanic","Duration.to.visit..days.",
           "gadpos","ia2pos","iaapos","znt8pos","multpos","group")]

alldata <- rbind(t1d,control)
alldata <- alldata[!is.na(alldata$Age..years.),]
alldata$Sex <- droplevels(alldata$Sex)
alldata$Race.Ethnicity <- droplevels(alldata$Race.Ethnicity)
alldata$Hispanic <- droplevels(alldata$Hispanic)

demovars <- c("Age..years.","Sex","Race.Ethnicity","Hispanic","Duration.to.visit..days.",
           "gadpos","ia2pos","iaapos","znt8pos","multpos")
nonnorm <- "Duration.to.visit..days."
exact <- c("Sex","Race.Ethnicity","Hispanic")
t1 <- CreateTableOne(vars=demovars, data=alldata,strata="group")
t1 <- print(t1,varLabels=TRUE,showAllLevels=TRUE,nonnorm=nonnorm,exact=exact)


```


```{r, echo=FALSE}
kable(t1,caption = "Table 1.  Demographics and immunologic characteristics.")
```

