---
title: "cgmanalysis Comparison"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,dpi = 600,fig.width=8,fig.height=6)
knitr::opts_knit$set(root.dir = "Z:/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Kaan Akturk/cgmanalysis Comparisons/Medtronic, Dexcom, Libre")
library(arsenal)
library(skimr)
library(knitr)
library(caret)
library(cgmanalysis)
library(tidyverse)
library(blandr)
library(TOSTER)
library(patchwork)
```

```{r cgmanalysis,eval=FALSE}
# Get cgmanalysis variables
cgmvariables("Cleaned/Dexcom","Cleaned/",outputname = "dexcom_results")
cgmvariables("Cleaned/Libre","Cleaned/",outputname = "libre_results")
cgmvariables("Cleaned/Medtronic","Cleaned/",outputname = "medtronic_results",
             customintervals = list(c(40,50),c(50,70),c(180,250),c(250,400)))
```

# Dexcom vs. cgmanalysis

```{r compare results dexcom}
# Read in results from Dexcom, format name
dexcom_software <- read.csv("./Dexcom/Patient List_Dexcom.csv",stringsAsFactors = F)
dexcom_software$Patient.Name <- tolower(dexcom_software$Patient.Name)
colnames(dexcom_software)[2] <- "subject_id"
# Read in results from package, multiply
dexcom_package <- read.csv("./Cleaned/dexcom_results.csv",stringsAsFactors = F)
# Merge
dexcom_package <- left_join(dexcom_package,dexcom_software,by = "subject_id")
# Select columns
dexcom_package <- dexcom_package %>% select(subject_id,
                                            percent_time_under_54,X.54,
                                            percent_time_under_70,X.70,
                                            percent_time_70_180,X70.180,
                                            percent_time_over_180,X.180,
                                            percent_time_over_250,X.250,
                                            cv,CV,
                                            standard_deviation,SD)
# Divide software CV by 100, round all columns
dexcom_package$CV <- dexcom_package$CV / 100
dexcom_package[,2:ncol(dexcom_package)] <- 
  lapply(dexcom_package[,2:ncol(dexcom_package)],function(x) round(x,1))
```

## Plots

### Linear Models

```{r dexcom lm plots}
# Make plots
label_u54  = c(paste("NRMSE:",
                     round(RMSE(dexcom_package$percent_time_under_54,
                                dexcom_package$X.54)/mean(dexcom_package$X.54),3)),
               paste("R^2:",round(R2(dexcom_package$percent_time_under_54,
                                     dexcom_package$X.54),3)))
coord_x = 1
coord_y = 4
under_54 <- ggplot(dexcom_package,aes(x = percent_time_under_54,y = X.54)) +
  geom_point() + theme_bw() + geom_abline() + 
  xlab("cgmanalysis Package") + ylab("Dexcom Software") + 
  coord_fixed(ratio = 1,xlim = c(0,4),ylim = c(0,4)) +
  ggtitle("% Time Under 54 mg/dL") +
  annotate("text",x = coord_x,y = c(coord_y, 0.92*coord_y),label=label_u54,parse = T)

label_u70  = c(paste("NRMSE:",
                     round(RMSE(dexcom_package$percent_time_under_70,
                                dexcom_package$X.70)/mean(dexcom_package$X.70),3)),
               paste("R^2:",round(R2(dexcom_package$percent_time_under_70,
                                     dexcom_package$X.70),3)))
coord_x = 3.5
coord_y = 15
under_70 <- ggplot(dexcom_package,aes(x = percent_time_under_70,y = X.70)) +
  geom_point() + theme_bw() + geom_abline() + 
  xlab("cgmanalysis Package") + ylab("Dexcom Software") + 
  coord_fixed(ratio = 1,xlim = c(0,15),ylim = c(0,15)) +
  ggtitle("% Time Under 70 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_u70,parse = T)

label_70_180 = c(paste("NRMSE:",
                       round(RMSE(dexcom_package$percent_time_70_180,
                                  dexcom_package$X70.180)/mean(dexcom_package$X70.180),3)),
                 paste("R^2:",round(R2(dexcom_package$percent_time_70_180,
                                       dexcom_package$X70.180),3)))
coord_x = 40
coord_y = 100
tir_70_180 <- ggplot(dexcom_package,aes(x = percent_time_70_180,y = X70.180)) +
  geom_point() + theme_bw() + geom_abline() + 
  xlab("cgmanalysis Package") + ylab("Dexcom Software") + 
  coord_fixed(ratio = 1,xlim = c(20,100),ylim = c(20,100)) +
  ggtitle("% Time 70 - 180 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y),label=label_70_180,parse = T)

label_over_180 = c(paste("NRMSE:",round(RMSE(dexcom_package$percent_time_over_180,
                                             dexcom_package$X.180)/mean(dexcom_package$X.180),3)),
                   paste("R^2:",round(R2(dexcom_package$percent_time_over_180,
                                         dexcom_package$X.180),3)))
coord_x = 22
coord_y = 82.5
over_180 <- ggplot(dexcom_package,aes(x = percent_time_over_180,y = X.180)) +
  geom_point() + theme_bw() + geom_abline() + 
  xlab("cgmanalysis Package") + ylab("Dexcom Software") + 
  coord_fixed(ratio = 1,xlim = c(0,85),ylim = c(0,85)) +
  ggtitle("% Time Over 180 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_over_180,parse=T)

label_over_250 = c(paste("NRMSE:",round(RMSE(dexcom_package$percent_time_over_250,
                                             dexcom_package$X.250)/mean(dexcom_package$X.250),3)),
                   paste("R^2:",round(R2(dexcom_package$percent_time_over_250,
                                         dexcom_package$X.250),3)))
coord_x = 10
coord_y = 40
over_250 <- ggplot(dexcom_package,aes(x = percent_time_over_250,y = X.250)) +
  geom_point() + theme_bw() + geom_abline() + 
  xlab("cgmanalysis Package") + ylab("Dexcom Software") + 
  coord_fixed(ratio = 1,xlim = c(0,40),ylim = c(0,40)) +
  ggtitle("% Time Over 250 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_over_250,parse=T)

label_sd = c(paste("NRMSE:",round(RMSE(dexcom_package$percent_time_over_180,
                                       dexcom_package$X.180)/mean(dexcom_package$X.180),3)),
             paste("R^2:",round(R2(dexcom_package$percent_time_over_180,
                                   dexcom_package$X.180),3)))
coord_x = 40
coord_y = 100
sd <- ggplot(dexcom_package,aes(x = standard_deviation,y = SD)) +
  geom_point() + theme_bw() + geom_abline() + 
  xlab("cgmanalysis Package") + ylab("Dexcom Software") + 
  coord_fixed(ratio = 1,xlim = c(20,100),ylim = c(20,100)) +
  ggtitle("Standard Deviation") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_sd,parse=T)
# Layout
(under_54 | under_70 | tir_70_180) / (over_180 | over_250 | sd)
```

### Bland-Altman

```{r dexcom b-a plot}
# Make plots
under_54 <- blandr.draw(dexcom_package$percent_time_under_54,
                        dexcom_package$X.54,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Under 54 mg/dL")
under_70 <- blandr.draw(dexcom_package$percent_time_under_70,
                        dexcom_package$X.70,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Under 70 mg/dL")
tir_70_180 <- blandr.draw(dexcom_package$percent_time_70_180,
                          dexcom_package$X70.180,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time 70 - 180 mg/dL")
over_180 <- blandr.draw(dexcom_package$percent_time_over_180,
                        dexcom_package$X.180,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Over 180 mg/dL")
over_250 <- blandr.draw(dexcom_package$percent_time_over_250,
                        dexcom_package$X.250,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Over 250 mg/dL")
sd <- blandr.draw(dexcom_package$standard_deviation,
                  dexcom_package$SD,ciDisplay = F) + 
  theme_bw() + ggtitle("Standard Deviation")
# Layout
(under_54 | under_70 | tir_70_180) / (over_180 | over_250 | sd)
```

# Dexcom vs. Tandem vs. cgmanalysis

```{r dex tandem data}
dexcom_tandem = read.csv("./tandem_dex_pdfs.csv",stringsAsFactors = F)
dexcom_tandem = round(dexcom_tandem)
```

```{r dex tandem package data}
dexcom_tandem_package = read.csv("./tandem_dex_package.csv",stringsAsFactors = F)
dexcom_tandem_package = dexcom_tandem_package %>%
  select(id,percent_time_under_54,percent_time_under_70,
         percent_time_70_180,percent_time_over_180,percent_time_over_250,
         standard_deviation)
# Get device and separate out id
dexcom_tandem_package$device =
  ifelse(grepl("Dexcom",dexcom_tandem_package$id),"dex","tandem")
dexcom_tandem_package$id =
  as.numeric(sapply(strsplit(dexcom_tandem_package$id,"-"),"[[",1))
# To wider
dexcom_tandem_package = dexcom_tandem_package %>%
  pivot_wider(id_cols = "id",names_from = "device",
              values_from = c("percent_time_under_54","percent_time_under_70",
                              "percent_time_70_180","percent_time_over_180",
                              "percent_time_over_250","standard_deviation"))
colnames(dexcom_tandem_package) =
  gsub("standard_deviation","sd",colnames(dexcom_tandem_package))
# Round
dexcom_tandem_package = round(dexcom_tandem_package)
# Combine all three
dexcom_tandem_package = inner_join(dexcom_tandem,dexcom_tandem_package,by = "id")
```

### Tandem vs. cgmanalysis

## Plots

### Linear Models

```{r tandem lm plots}
# Make plots
label_u54 = c(paste("NRMSE:",round(RMSE(dexcom_tandem_package$percent_time_under_54_tandem,
                                        dexcom_tandem_package$tandem_u54)/
                                     mean(dexcom_tandem_package$tandem_u54),3)),
              paste("R^2:",round(R2(dexcom_tandem_package$percent_time_under_54_tandem,
                                    dexcom_tandem_package$tandem_u54),3)))
coord_x = 0.35
coord_y = 2
under_54 <- ggplot(dexcom_tandem_package,aes(x = percent_time_under_54_tandem,y = tandem_u54)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Tandem Software") +
  coord_fixed(ratio = 1,xlim = c(0,2),ylim = c(0,2)) +
  ggtitle("% Time Under 54 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y),label=label_u54,parse=T)

label_u70 = c(paste("NRMSE:",round(RMSE(dexcom_tandem_package$percent_time_under_70_tandem,
                                        dexcom_tandem_package$tandem_u70)/
                                     mean(dexcom_tandem_package$tandem_u70),3)),
              paste("R^2:",round(R2(dexcom_tandem_package$percent_time_under_70_tandem,
                                    dexcom_tandem_package$tandem_u70),3)))
coord_x = 1.8
coord_y = 7
under_70 <- ggplot(dexcom_tandem_package,aes(x = percent_time_under_70_tandem,y = tandem_u70)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Tandem Software") +
  coord_fixed(ratio = 1,xlim = c(0,7),ylim = c(0,7)) +
  ggtitle("% Time Under 70 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_u70,parse=T)

label_70_180 = c(paste("NRMSE:",round(RMSE(dexcom_tandem_package$percent_time_70_180_tandem,
                                           dexcom_tandem_package$tandem_70_180)/
                                        mean(dexcom_tandem_package$tandem_70_180),3)),
                 paste("R^2:",round(R2(dexcom_tandem_package$percent_time_70_180_tandem,
                                       dexcom_tandem_package$tandem_70_180),3)))
coord_x = 55
coord_y = 85
tir_70_180 <- ggplot(dexcom_tandem_package,aes(x=percent_time_70_180_tandem,y=tandem_70_180)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Tandem Software") +
  coord_fixed(ratio = 1,xlim = c(45,85),ylim = c(45,85)) +
  ggtitle("% Time 70 - 180 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.95*coord_y), label=label_70_180,parse = T)

label_over_180 = c(paste("NRMSE:",round(RMSE(dexcom_tandem_package$percent_time_over_180_tandem,
                                             dexcom_tandem_package$tandem_a180)/
                                          mean(dexcom_tandem_package$tandem_a180),3)),
                   paste("R^2:",round(R2(dexcom_tandem_package$percent_time_over_180_tandem,
                                         dexcom_tandem_package$tandem_a180),3)))
coord_x = 20
coord_y = 50
over_180 <- ggplot(dexcom_tandem_package,aes(x = percent_time_over_180_tandem,y = tandem_a180)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Tandem Software") +
  coord_fixed(ratio = 1,xlim = c(10,50),ylim = c(10,50)) +
  ggtitle("% Time Over 180 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_over_180,parse = T)

label_over_250 = c(paste("NRMSE:",round(RMSE(dexcom_tandem_package$percent_time_over_250_tandem,
                                             dexcom_tandem_package$tandem_a250)/
                                          mean(dexcom_tandem_package$tandem_a250),3)),
                   paste("R^2:",round(R2(dexcom_tandem_package$percent_time_over_250_tandem,
                                         dexcom_tandem_package$tandem_a250),3)))
coord_x = 5
coord_y = 20
over_250 <- ggplot(dexcom_tandem_package,aes(x = percent_time_over_250_tandem,y = tandem_a250)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Tandem Software") +
  coord_fixed(ratio = 1,xlim = c(0,20),ylim = c(0,20)) +
  ggtitle("% Time Over 250 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_over_250,parse = T)

label_sd = c(paste("NRMSE:",round(RMSE(dexcom_tandem_package$sd_tandem,
                                       dexcom_tandem_package$tandem_sd)/
                                    mean(dexcom_tandem_package$tandem_sd),3)),
             paste("R^2:",round(R2(dexcom_tandem_package$sd_tandem,
                                   dexcom_tandem_package$tandem_sd),3)))
coord_x = 50
coord_y = 75
sd <- ggplot(dexcom_tandem_package,aes(x = sd_tandem,y = tandem_sd)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Tandem Software") +
  coord_fixed(ratio = 1,xlim = c(40,75),ylim = c(40,75)) +
  ggtitle("Standard Deviation") +
  annotate("text",x=coord_x, y=c(coord_y, 0.95*coord_y), label=label_sd,parse=T)

(under_54 | under_70 | tir_70_180) / (over_180 | over_250 | sd)
```

### Bland-Altman

```{r tandem b-a plot}
# Make plots
under_54 <- blandr.draw(dexcom_tandem_package$percent_time_under_54_tandem,
                        dexcom_tandem_package$tandem_u54,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Under 54 mg/dL")
under_70 <- blandr.draw(dexcom_tandem_package$percent_time_under_70_tandem,
                        dexcom_tandem_package$tandem_u70,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Under 70 mg/dL") 
tir_70_180 <- blandr.draw(dexcom_tandem_package$percent_time_70_180_tandem,
                          dexcom_tandem_package$tandem_70_180,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time 70 - 180 mg/dL")
over_180 <- blandr.draw(dexcom_tandem_package$percent_time_over_180_tandem,
                        dexcom_tandem_package$tandem_a180,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Over 180 mg/dL")
over_250 <- blandr.draw(dexcom_tandem_package$percent_time_over_250_tandem,
                        dexcom_tandem_package$tandem_a250,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Over 250 mg/dL")
sd <- blandr.draw(dexcom_tandem_package$sd_tandem,
                  dexcom_tandem_package$sd_tandem,ciDisplay = F) + 
  theme_bw() + ggtitle("Standard Deviation")
# Layout
(under_54 | under_70 | tir_70_180) / (over_180 | over_250 | sd)
```

# Libre vs. cgmanalysis

```{r compare results libre}
# Read in results from Libre, format name
libre_software <- read.csv("Libre/Patient List_Libre.csv",stringsAsFactors = F)
libre_software$Patient.Name <- tolower(libre_software$Patient.Name)
colnames(libre_software)[2] <- "subject_id"
# Read in results from package, multiply
libre_package <- read.csv("Cleaned/libre_results.csv",stringsAsFactors = F)
# Merge
libre_package <- left_join(libre_package,libre_software,by = "subject_id")
# Select columns
libre_package <- libre_package %>% select(subject_id,
                                          percent_time_under_54,X.54,
                                          percent_time_under_70,X.70,
                                          percent_time_70_180,X70.180,
                                          percent_time_over_180,X.180,
                                          percent_time_over_250,X.250,
                                          cv,CV,
                                          standard_deviation,SD)
# Divide software CV by 100, round all columns
libre_package$CV <- libre_package$CV / 100
libre_package[,2:ncol(libre_package)] <-
  lapply(libre_package[,2:ncol(libre_package)],round)
```

## Plots

### Linear Models

```{r libre lm plots}
# Make plots
label_u54 = c(paste("NRMSE:",round(RMSE(libre_package$percent_time_under_54,
                                        libre_package$X.54)/
                                     mean(libre_package$X.54),3)),
              paste("R^2:",round(R2(libre_package$percent_time_under_54,
                                    libre_package$X.54),3)))
coord_x = 4
coord_y = 15
under_54 <- ggplot(libre_package,aes(x = percent_time_under_54,y = X.54)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Libre Software") +
  coord_fixed(ratio = 1,xlim = c(0,15),ylim = c(0,15)) +
  ggtitle("% Time Under 54 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_u54,parse=T)

label_u70 = c(paste("NRMSE:",round(RMSE(libre_package$percent_time_under_70,
                                        libre_package$X.70)/
                                     mean(libre_package$X.70),3)),
              paste("R^2:",round(R2(libre_package$percent_time_under_70,
                                    libre_package$X.70),3)))
coord_x = 6
coord_y = 22
under_70 <- ggplot(libre_package,aes(x = percent_time_under_70,y = X.70)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Libre Software") +
  coord_fixed(ratio = 1,xlim = c(0,22),ylim = c(0,22)) +
  ggtitle("% Time Under 70 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_u70,parse=T)

label_70_180 = c(paste("NRMSE:",round(RMSE(libre_package$percent_time_70_180,
                                           libre_package$X70.180)/
                                        mean(libre_package$X70.180),3)),
                 paste("R^2:",round(R2(libre_package$percent_time_70_180,
                                       libre_package$X70.180),3)))
coord_x = 23
coord_y = 100
tir_70_180 <- ggplot(libre_package,aes(x = percent_time_70_180,y = X70.180)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Libre Software") +
  coord_fixed(ratio = 1,xlim = c(0,100),ylim = c(0,100)) +
  ggtitle("% Time 70 - 180 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_70_180,parse=T)

label_over_180 = c(paste("NRMSE:",round(RMSE(libre_package$percent_time_over_180,
                                             libre_package$X.180)/
                                          mean(libre_package$X.180),3)),
                   paste("R^2:",round(R2(libre_package$percent_time_over_180,
                                         libre_package$X.180),3)))
coord_x = 25
coord_y = 100
over_180 <- ggplot(libre_package,aes(x = percent_time_over_180,y = X.180)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Libre Software") +
  coord_fixed(ratio = 1,xlim = c(0,100),ylim = c(0,100)) +
  ggtitle("% Time Over 180 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_over_180,parse=T)

label_over_250 = c(paste("NRMSE:",round(RMSE(libre_package$percent_time_over_250,
                                             libre_package$X.250)/
                                          mean(libre_package$X.250),3)),
                   paste("R^2:",round(R2(libre_package$percent_time_over_250,
                                         libre_package$X.250),3)))
coord_x = 20
coord_y = 80
over_250 <- ggplot(libre_package,aes(x = percent_time_over_250,y = X.250)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Libre Software") +
  coord_fixed(ratio = 1,xlim = c(0,80),ylim = c(0,80)) +
  ggtitle("% Time Over 250 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_over_250,parse=T)

label_sd = c(paste("NRMSE:",round(RMSE(libre_package$standard_deviation,
                                       libre_package$SD)/
                                    mean(libre_package$SD),3)),
             paste("R^2:",round(R2(libre_package$standard_deviation,
                                   libre_package$SD),3)))
coord_x = 45
coord_y = 115
sd <- ggplot(libre_package,aes(x = standard_deviation,y = SD)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Libre Software") +
  coord_fixed(ratio = 1,xlim = c(20,115),ylim = c(20,115)) +
  ggtitle("Standard Deviation") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_sd,parse=T)

(under_54 | under_70 | tir_70_180) / (over_180 | over_250 | sd)
```

### Bland-Altman

```{r libre b-a plot}
# Make plots
under_54 <- blandr.draw(libre_package$percent_time_under_54,
                        libre_package$X.54,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Under 54 mg/dL")
under_70 <- blandr.draw(libre_package$percent_time_under_70,
                        libre_package$X.70,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Under 70 mg/dL")
tir_70_180 <- blandr.draw(libre_package$percent_time_70_180,
                          libre_package$X70.180,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time 70 - 180 mg/dL")
over_180 <- blandr.draw(libre_package$percent_time_over_180,
                        libre_package$X.180,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Over 180 mg/dL")
over_250 <- blandr.draw(libre_package$percent_time_over_250,
                        libre_package$X.250,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Over 250 mg/dL")
sd <- blandr.draw(libre_package$standard_deviation,
                  libre_package$SD,ciDisplay = F) + 
  theme_bw() + ggtitle("Standard Deviation")
# Layout
(under_54 | under_70 | tir_70_180) / (over_180 | over_250 | sd)
```

# Medtronic vs. cgmanalysis

```{r compare results medtronic}
# Read in results from Medtronic, format name
medtronic_software <- read.csv("Medtronic/Patient Sheet_Medtronic.csv",
                               stringsAsFactors = F)
medtronic_software$Name <- tolower(medtronic_software$Name)
colnames(medtronic_software)[2] <- "subject_id"
# Read in results from package, multiply
medtronic_package <- read.csv("Cleaned/medtronic_results.csv",stringsAsFactors = F)
# Merge
medtronic_package <- left_join(medtronic_package,medtronic_software,by = "subject_id")
# Select columns
medtronic_package <- medtronic_package %>% select(subject_id,
                                                  percent_time_40_50,X.40.50.,
                                                  percent_time_50_70,X.50.70.,
                                                  percent_time_70_180,X.70.180.TIR,
                                                  percent_time_180_250,X.180.250.,
                                                  percent_time_250_400,X.250.400.)
# Divide software CV by 100, round all columns
medtronic_package[,2:ncol(medtronic_package)] <-
  lapply(medtronic_package[,2:ncol(medtronic_package)],round)
medtronic_package = medtronic_package[complete.cases(medtronic_package),]
```

## Plots

### Linear Models

```{r medtronic lm plots}
# Make plots
label_40_50 = c(paste("NRMSE:",round(RMSE(medtronic_package$percent_time_40_50,
                                          medtronic_package$X.40.50.)/
                                       mean(medtronic_package$X.40.50.),3)),
                paste("R^2:",round(R2(medtronic_package$percent_time_40_50,
                                      medtronic_package$X.40.50.),3)))
coord_x = 0.5
coord_y = 2
tir_40_50 <- ggplot(medtronic_package,aes(x = percent_time_40_50,y = X.40.50.)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Medtronic Software") +
  coord_fixed(ratio = 1,xlim = c(0,2),ylim = c(0,2)) +
  ggtitle("% Time 40 - 50 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_40_50,parse=T)

label_50_70 = c(paste("NRMSE:",round(RMSE(medtronic_package$percent_time_50_70,
                                          medtronic_package$X.50.70.)/
                                       mean(medtronic_package$X.50.70.),3)),
                paste("R^2:",round(R2(medtronic_package$percent_time_50_70,
                                      medtronic_package$X.50.70.),3)))
coord_x = 2.5
coord_y = 10
tir_50_70 <- ggplot(medtronic_package,aes(x = percent_time_50_70,y = X.50.70.)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Medtronic Software") +
  coord_fixed(ratio = 1,xlim = c(0,10),ylim = c(0,10)) +
  ggtitle("% Time 50 - 70 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y), label=label_50_70,parse=T)

label_70_180 = c(paste("NRMSE:",round(RMSE(medtronic_package$percent_time_70_180,
                                           medtronic_package$X.70.180.TIR)/
                                        mean(medtronic_package$X.70.180.TIR),3)),
                 paste("R^2:",round(R2(medtronic_package$percent_time_70_180,
                                       medtronic_package$X.70.180.TIR),3)))
coord_x = 45
coord_y = 90
tir_70_180 <- ggplot(medtronic_package,aes(x = percent_time_70_180,y = X.70.180.TIR)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Medtronic Software") +
  coord_fixed(ratio = 1,xlim = c(30,90),ylim = c(30,90)) +
  ggtitle("% Time 70 - 180 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.95*coord_y),parse=T,label=label_70_180)

label_180_250 = c(paste("NRMSE:",round(RMSE(medtronic_package$percent_time_180_250,
                                            medtronic_package$X.180.250.)/
                                         mean(medtronic_package$X.180.250.),3)),
                  paste("R^2:",round(R2(medtronic_package$percent_time_180_250,
                                        medtronic_package$X.180.250.),3)))
coord_x = 10
coord_y = 45
tir_180_250 <- ggplot(medtronic_package,aes(x = percent_time_180_250,y = X.180.250.)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Medtronic Software") +
  coord_fixed(ratio = 1,xlim = c(0,45),ylim = c(0,45)) +
  ggtitle("% Time 180 - 250 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y),parse=T,label=label_180_250)

label_250_400 = c(paste("NRMSE:",round(RMSE(medtronic_package$percent_time_250_400,
                                            medtronic_package$X.250.400.)/
                                         mean(medtronic_package$X.250.400.),3)),
                  paste("R^2:",round(R2(medtronic_package$percent_time_250_400,
                                        medtronic_package$X.250.400.),3)))
coord_x = 7.5
coord_y = 35
tir_250_400 <- ggplot(medtronic_package,aes(x = percent_time_250_400,y = X.250.400.)) +
  geom_point() + theme_bw() + geom_abline() +
  xlab("cgmanalysis Package") + ylab("Medtronic Software") +
  coord_fixed(ratio = 1,xlim = c(0,35),ylim = c(0,35)) +
  ggtitle("% Time 250 - 400 mg/dL") +
  annotate("text",x=coord_x, y=c(coord_y, 0.92*coord_y),parse=T,label=label_250_400)

(tir_40_50 | tir_50_70 | tir_70_180) / (tir_180_250 | tir_250_400)
```

### Bland-Altman

```{r medtronic b-a plot}
# Make plots
tir_40_50 <- blandr.draw(medtronic_package$percent_time_40_50,
                         medtronic_package$X.40.50.,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time 40 - 50 mg/dL")
tir_50_70 <- blandr.draw(medtronic_package$percent_time_50_70,
                         medtronic_package$X.50.70.,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time 50 - 70 mg/dL")
tir_70_180 <- blandr.draw(medtronic_package$percent_time_70_180,
                          medtronic_package$X.70.180.TIR,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time 70 - 180 mg/dL")
tir_180_250 <- blandr.draw(medtronic_package$percent_time_180_250,
                           medtronic_package$X.180.250.,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time 180 - 250 mg/dL")
over_250 <- blandr.draw(medtronic_package$percent_time_250_400,
                        medtronic_package$X.250.400.,ciDisplay = F) + 
  theme_bw() + ggtitle("% Time Over 250 mg/dL")
# Layout
(tir_40_50| tir_50_70 | tir_70_180) / (tir_180_250 | over_250)
```
