---
title: "Clinic vs. active vs. inactive"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: rtf_document
---

```{r setup, include=FALSE}

library(tableone)
library(knitr)
library(haven)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

```

```{r, include=FALSE}
data <- read.csv("/Volumes/BDC-1/Projects/Andrea Steck/Morgan Sooy DKA update/table1.csv")
data <- read_sas("/Volumes/BDC-1/Projects/Andrea Steck/Morgan Sooy DKA update/table1.sas7bdat")
data$English <- as.factor(data$English)
data$DKA_sev_mild <- as.factor(ifelse(data$DKA_sev=="Mild DKA", 1, 0))
data$DKA_sev_severe <- as.factor(ifelse(data$DKA_sev=="Severe DKA", 1, 0))
data$DKA_sev_none <- as.factor(ifelse(data$DKA_sev=="No DKA", 1, 0))
data$DKA_sev_unknown <- as.factor(ifelse(data$DKA_sev=="Unknown", 1, 0))
data$Sex <- as.factor(data$Sex)
data$Sex <- relevel(data$Sex, ref = "Male")

t1 <- CreateTableOne(data=data, vars=c("Age_AtOnset","InitalA1c","Sex","race_eth","new_ins","DKA","DKA_sev",
                                       "DKA_sev_mild","DKA_sev_severe","DKA_sev_none","DKA_sev_unknown",
                                       "Rural_or_non_rural","English"), strata="active_inactive_clinic")
t1 <- print(t1)
```

```{r, echo=FALSE}
kable(t1)
```
