---
title: "DKA analysis update (Morgan Sooy & Andrea Steck)"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects/Andrea Steck/Morgan Sooy DKA update/"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)

setwd(home_dir)
```

```{r data, include=FALSE}
data <- read.csv("./Data_raw/10.26.22_Sooy_FinalThesis_Dataset LP.csv", na.strings = c(""," ","."))

# counts of people in any study by 12, 13, 14 months of follow-up PRIOR to T1D dx

# numbers of patients with 1, 2 years of follow-up post-dx (all pts)

```


```{r echo=FALSE}
kable(t1,caption = "")
```
<br>
