---
title: "Pregnancy CGM Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, include=FALSE}
# Load libraries and functions
library(cgmanalysis)
library(lubridate)
source('~/Documents/GitHub/Tim-and-Laura/tim_R_functions.R')
pathstart <- os.check()
```

```{r echo=FALSE}
# Format for CGM package
infolder <- paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Laura Tim projects/Sarit Polsky/Pregnancy/Data_Raw/CGM Files")
outfolder <- paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Laura Tim projects/Sarit Polsky/Pregnancy/Data_Cleaned/Formatted CGM Files")
files <- list.files(infolder,full.names = TRUE)
for (f in files) {
  table <- read.csv(f,stringsAsFactors = F)
  if (colnames(table)[1] == "PatientInfoField") {
    id <- table$PatientInfoValue[1]
    table <- table[,c("GlucoseDisplayTime","GlucoseValue")]
  } else {
    id <- gsub(".txt Formatted R.csv","",basename(f))
    table <- table[,c("DateTime","GlucoseValue")]
    table$DateTime <- gsub("T"," ",table$DateTime)
    table$DateTime <- ymd_hms(table$DateTime)
  }
  colnames(table) <- c("timestamp","sensorglucose")
  table$subjectid <- NA
  table$subjectid[1] <- id
  table <- table[,c("subjectid","timestamp","sensorglucose")]
  file <- basename(f)
  write.csv(table,file = paste0(outfolder,"/",file),row.names = F)
}
```

```{r echo=FALSE}
input <- paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Laura Tim projects/Sarit Polsky/Pregnancy/Data_Cleaned/Formatted CGM Files")
output <- paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Laura Tim projects/Sarit Polsky/Pregnancy/Data_Cleaned")
cgmvariables(input,output,"Pregnancy Variables")
```