---
title: "AHA Metabolomics"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant")
library(tableone)
library(skimr)
library(knitr)
library(mixOmics)
library(tidyverse)
```

```{r echo=FALSE}
# Read in
raw_metab <- read.csv("./Data_Cleaned/CIL global metabolomics data matrix_20190725_Import.csv",na.strings = "",stringsAsFactors = F)
# Subset
metab <- raw_metab %>% 
  mutate(compound = coalesce(HMDB.No.,LI.Library.No.),
         neutralmass = Neutral.Mass..Da.,
         rt = RT..s.,
         masserror = coalesce(Mass.Error..ppm.,Mass.Error..ppm..1),
         rterror = coalesce(RT.Error..s.,RT.Error..s..1)) %>% 
  dplyr::select(compound,neutralmass,rt,masserror,rterror,
                IsoMS_results_QC01_190618171010_converted.csv:IsoMS_results_S227_Batch07_1400_RA8_converted.csv)
colnames(metab) <- gsub("IsoMS_results_","",colnames(metab))
colnames(metab) <- gsub("*_.*","",colnames(metab))
# Read in sample list
sample_list <- read.csv("./Data_Cleaned/sample_list.csv")
# Match injection number to sample ID
ids <- sample_list$SampleID[match(colnames(metab),sample_list$Injection)]
ids <- ids[which(!is.na(ids))]
# Replace column names
colnames(metab)[which(colnames(metab) == "S001"):ncol(metab)] <- ids
```