---
title: "Targeted Metabolomics"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant")

home_dir = ifelse(.Platform$OS.type != "unix","T:/Janet Snell-Bergeon/AHA collaborative grant/Metabolomics",
                  "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant")
knitr::opts_knit$set(root.dir = home_dir)

library(tableone)
library(skimr)
library(knitr)
library(survival)
library(mediation)
library(nnet)
library(mixOmics)
library(tidyverse)
```

```{r echo=FALSE}
# Import new data
targeted <- read.csv("./Data_Cleaned/targeted.csv")
# Three progression groups
cac_groups <- read.table("./Data_Raw/CAC Trajectories 3 groups.txt",sep = "\t",
                         header = T)
# CAC progression - increase in square root calcium volume >= 2.5 between baseline and visit 3
targeted$CACp <- as.factor(ifelse(targeted$c3 - targeted$c1 >= 2.5,"Progression","No Progression"))
# New CAC groups
targeted <- left_join(targeted,cac_groups[,c("StudyID","GROUP")],by = "StudyID")
```

<!-- # CAC Progression -->

<!-- ```{r CACp unadjusted,echo=FALSE,message=FALSE} -->
<!-- # Logistic regression -->
<!-- logits <- lapply(colnames(targeted)[which(colnames(targeted) == "Betaine"): -->
<!--                                       which(colnames(targeted)=="linoleic.acid")],  -->
<!--                  function(var){ -->
<!--                    #print(var) -->
<!--                    formula <- as.formula(paste0("factor(CACp) ~ ",var)) -->
<!--                    mod <- glm(formula, data = targeted, family = "binomial")  -->
<!--                    cfs <- as.data.frame(summary(mod)$coefficients) -->
<!--                    cfs$metabolite <- rownames(cfs) -->
<!--                    cfs}) -->
<!-- # Combine into one dataframe -->
<!-- metab_logits <- bind_rows(logits) -->
<!-- # Remove intercept estimates -->
<!-- metab_logits <- metab_logits %>%  -->
<!--   filter(!(metabolite %in% c("(Intercept)","age","sex"))) %>%  -->
<!--   select(metabolite,Estimate,`Std. Error`,`Pr(>|z|)`) -->
<!-- # Sort by p value -->
<!-- metab_logits <- metab_logits %>% arrange(`Pr(>|z|)`) -->
<!-- # Adjust p values -->
<!-- metab_logits$`Pr(>|z|)` <- p.adjust(metab_logits$`Pr(>|z|)`, method = "fdr") -->
<!-- # Results -->
<!-- kable(metab_logits, caption = "CAC progession no covariates, FDR-adjusted p values") -->
<!-- ``` -->

<!-- \pagebreak -->

<!-- ```{r CACp adjusted,echo=FALSE,message=FALSE} -->
<!-- # Logistic regression -->
<!-- logits <- lapply(colnames(targeted)[which(colnames(targeted) == "Betaine"): -->
<!--                                       which(colnames(targeted)=="linoleic.acid")],  -->
<!--                  function(var){ -->
<!--                    #print(var) -->
<!--                    formula <- as.formula(paste0("factor(CACp) ~ ",var,"+age+sex")) -->
<!--                    mod <- glm(formula, data = targeted, family = "binomial")  -->
<!--                    cfs <- as.data.frame(summary(mod)$coefficients) -->
<!--                    cfs$metabolite <- rownames(cfs) -->
<!--                    cfs}) -->
<!-- # Combine into one dataframe -->
<!-- metab_logits <- bind_rows(logits) -->
<!-- # Remove intercept estimates -->
<!-- metab_logits <- metab_logits %>%  -->
<!--   filter(!(metabolite %in% c("(Intercept)","age","sex"))) %>%  -->
<!--   select(metabolite,Estimate,`Std. Error`,`Pr(>|z|)`) -->
<!-- # Sort by p value -->
<!-- metab_logits <- metab_logits %>% arrange(`Pr(>|z|)`) -->
<!-- # Adjust p values -->
<!-- metab_logits$`Pr(>|z|)` <- p.adjust(metab_logits$`Pr(>|z|)`, method = "fdr") -->
<!-- # Results -->
<!-- kable(metab_logits,  -->
<!--       caption = "CAC progession adjusted for age and sex, FDR-adjusted p values") -->
<!-- ``` -->

<!-- \pagebreak -->

<!-- # CAC Group -->

<!-- ```{r CAC group unadjusted,echo=FALSE,include=FALSE} -->
<!-- # Multinomial logistic regression on CACGROUP - adjust for known markers -->
<!-- multinom_logits <- lapply(colnames(targeted)[which(colnames(targeted) == "Betaine"): -->
<!--                                       which(colnames(targeted)=="linoleic.acid")],  -->
<!--                  function(var){ -->
<!--                    #print(var) -->
<!--                    formula <- as.formula(paste0("factor(GROUP) ~ ",var)) -->
<!--                    mod <- multinom(formula, data = targeted,trace = F)  -->
<!--                    coeffs <- as.data.frame(summary(mod)$coefficients)[[var]] -->
<!--                    ses <- as.data.frame(summary(mod)$standard.errors)[[var]] -->
<!--                    z <- coeffs/ses -->
<!--                    ps <- (1 - pnorm(abs(z), 0, 1))*2 -->
<!--                    results <- as.data.frame(cbind(c(2,3),coeffs,ses,ps)) -->
<!--                    results$metab <- paste(var) -->
<!--                    colnames(results) <- c("CAC Group","Estimate","SE", -->
<!--                                           "p value","Metabolite") -->
<!--                    results -->
<!--                    }) -->
<!-- # Single DF -->
<!-- multinom_metab_logits <- bind_rows(multinom_logits) -->
<!-- multinom_metab_logits <- multinom_metab_logits %>%  -->
<!--   select(Metabolite,`CAC Group`,Estimate,SE,`p value`) -->
<!-- # Rename metabolites, sort by p value -->
<!-- multinom_metab_logits <- multinom_metab_logits %>% arrange(`p value`) -->
<!-- # Adjust p values -->
<!-- multinom_metab_logits$`p value` <- p.adjust(multinom_metab_logits$`p value`, -->
<!--                                             method = "fdr") -->
<!-- # List significant metabolites -->
<!-- metabs <- multinom_metab_logits$Metabolite[multinom_metab_logits$`p value` < 0.05] -->
<!-- ``` -->

<!-- ```{r echo=FALSE} -->
<!-- # Univariate results -->
<!-- kable(multinom_metab_logits,  -->
<!--       caption = "CAC group no covariates, FDR-adjusted p values") -->
<!-- ``` -->

<!-- \pagebreak -->

<!-- ```{r CAC group adjusted,echo=FALSE,include=FALSE} -->
<!-- # Multinomial logistic regression on CACGROUP - adjust for known markers -->
<!-- multinom_logits <- lapply(colnames(targeted)[which(colnames(targeted) == "Betaine"): -->
<!--                                       which(colnames(targeted)=="linoleic.acid")],  -->
<!--                  function(var){ -->
<!--                    #print(var) -->
<!--                    formula <- as.formula(paste0("factor(GROUP) ~ ",var,"+age+sex")) -->
<!--                    mod <- multinom(formula, data = targeted,trace=F)  -->
<!--                    coeffs <- as.data.frame(summary(mod)$coefficients)[[var]] -->
<!--                    ses <- as.data.frame(summary(mod)$standard.errors)[[var]] -->
<!--                    z <- coeffs/ses -->
<!--                    ps <- (1 - pnorm(abs(z), 0, 1))*2 -->
<!--                    results <- as.data.frame(cbind(c(2,3),coeffs,ses,ps)) -->
<!--                    results$metab <- paste(var) -->
<!--                    colnames(results) <- c("CAC Group","Estimate","SE", -->
<!--                                           "p value","Metabolite") -->
<!--                    results -->
<!--                    }) -->
<!-- # Single DF -->
<!-- multinom_metab_logits <- bind_rows(multinom_logits) -->
<!-- multinom_metab_logits <- multinom_metab_logits %>%  -->
<!--   select(Metabolite,`CAC Group`,Estimate,SE,`p value`) -->
<!-- # Sort by p value -->
<!-- multinom_metab_logits <- multinom_metab_logits %>% arrange(`p value`) -->
<!-- # Adjust p values -->
<!-- multinom_metab_logits$`p value` <- p.adjust(multinom_metab_logits$`p value`, -->
<!--                                             method = "fdr") -->
<!-- ``` -->

<!-- ```{r echo=FALSE} -->
<!-- # Adjusted results -->
<!-- kable(multinom_metab_logits,  -->
<!--       caption = "CAC group adjusted for age and sex, FDR-adjusted p values") -->
<!-- ``` -->

<!-- \pagebreak -->

<!-- # Mediation -->

<!-- ```{r echo=FALSE,results="asis"} -->
<!-- # Age -->
<!-- cat('\n')   -->
<!-- cat("## Age ","\n") # Heading -->
<!-- cat('\n') -->
<!-- # Outcome and age -->
<!-- c <- multinom(factor(GROUP) ~ age, data = targeted,trace = F) -->
<!-- coeffs <- as.data.frame(summary(c)$coefficients)[["age"]] -->
<!-- ses <- as.data.frame(summary(c)$standard.errors)[["age"]] -->
<!-- z <- coeffs/ses -->
<!-- ps <- (1 - pnorm(abs(z), 0, 1))*2 -->
<!-- cres <- as.data.frame(cbind(c(2,3),coeffs,ses,ps)) -->
<!-- cres$ps <- format.pval(cres$ps,eps = 0.0001) -->
<!-- colnames(cres) <- c("CAC Group","Estimate","SE","p value") -->
<!-- kable(cres,caption = "Association between CAC group and age") -->
<!-- # Loop through significant metabolites -->
<!-- for (var in metabs) { -->
<!--   cat('\n')   -->
<!--   cat("### ", var, "\n") # Heading -->
<!--   cat('\n') -->
<!--   a <- lm(as.formula(paste0(var, "~ age")), data = targeted) # Metabolite by age -->
<!--   ares <- as.data.frame(summary(a)$coefficients) -->
<!--   print(kable(ares,caption = paste0("Association between age and ",var))) -->
<!--   b <- multinom(as.formula(paste0("factor(GROUP) ~ age +",var)), # Full model -->
<!--                 data = targeted,trace = F) -->
<!--   coeffs <- as.data.frame(summary(b)$coefficients)[["age"]] -->
<!--   ses <- as.data.frame(summary(b)$standard.errors)[["age"]] -->
<!--   z <- coeffs/ses -->
<!--   ps <- (1 - pnorm(abs(z), 0, 1))*2 -->
<!--   bres <- as.data.frame(cbind(c(2,3),coeffs,ses,ps)) -->
<!--   bres$ps <- format.pval(bres$ps,eps = 0.0001) -->
<!--   colnames(bres) <- c("CAC Group","Estimate","SE","p value") -->
<!--   print(kable(bres,caption = paste0("Association between CAC group and age, adjusted for ",var))) -->
<!-- } -->
<!-- ``` -->

<!-- \pagebreak -->

<!-- ```{r echo=FALSE,results="asis"} -->
<!-- # Sex -->
<!-- cat('\n')   -->
<!-- cat("## Sex ","\n") # Heading -->
<!-- cat('\n') -->
<!-- # Outcome and sex -->
<!-- c <- multinom(factor(GROUP) ~ sex, data = targeted,trace = F) -->
<!-- coeffs <- as.data.frame(summary(c)$coefficients)[["sex"]] -->
<!-- ses <- as.data.frame(summary(c)$standard.errors)[["sex"]] -->
<!-- z <- coeffs/ses -->
<!-- ps <- (1 - pnorm(abs(z), 0, 1))*2 -->
<!-- cres <- as.data.frame(cbind(c(2,3),coeffs,ses,ps)) -->
<!-- cres$ps <- format.pval(cres$ps,eps = 0.0001) -->
<!-- colnames(cres) <- c("CAC Group","Estimate","SE","p value") -->
<!-- kable(cres,caption = "Association between CAC group and sex") -->
<!-- # Loop through significant metabolites -->
<!-- # for (var in metabs) { -->
<!-- #   cat('\n') -->
<!-- #   cat("## ", var, "\n") # Heading -->
<!-- #   cat('\n') -->
<!-- #   a <- lm(as.formula(paste0(var, "~ sex")), data = targeted) # Metabolite by sex -->
<!-- #   ares <- as.data.frame(summary(a)$coefficients) -->
<!-- #   print(kable(ares,caption = paste0("Association between sex and ",var))) -->
<!-- #   b <- multinom(as.formula(paste0("factor(GROUP) ~ sex +",var)), # Full model -->
<!-- #                 data = targeted,trace = F) -->
<!-- #   coeffs <- as.data.frame(summary(b)$coefficients)[["sex"]] -->
<!-- #   ses <- as.data.frame(summary(b)$standard.errors)[["sex"]] -->
<!-- #   z <- coeffs/ses -->
<!-- #   ps <- (1 - pnorm(abs(z), 0, 1))*2 -->
<!-- #   bres <- as.data.frame(cbind(c(2,3),coeffs,ses,ps)) -->
<!-- #   bres$ps <- format.pval(bres$ps,eps = 0.0001) -->
<!-- #   colnames(bres) <- c("CAC Group","Estimate","SE","p value") -->
<!-- #   print(kable(bres,caption = paste0("Association between CAC group and sex, adjusted for ",var))) -->
<!-- # } -->
<!-- ``` -->

# PLS-DA

```{r echo=FALSE}
Y <- as.factor(targeted$GROUP)
X <- as.matrix(targeted[,which(colnames(targeted) == "Betaine"):which(colnames(targeted)=="linoleic.acid")])
plsda.res <- plsda(X, Y, ncomp = 5)
plotIndiv(plsda.res,ind.names = FALSE, legend = TRUE, ellipse = TRUE,title = 'PLS-DA')
```

# PCA

```{r echo=FALSE, message=FALSE}
tune.pca(X, ncomp = 10, center = TRUE, scale = FALSE)
pca.res <- pca(X, ncomp = 3, center = TRUE, scale = FALSE)
plotIndiv(pca.res,group = targeted$GROUP, legend = TRUE, title = 'PCA',pch = 20,
          ind.names = F)
```
