---
title: "AHA Untargeted Metabolomics"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant/Metabolomics")
library(arsenal)
library(skimr)
library(knitr)
library(NormalizeMets)
library(mixOmics)
library(metabomxtr)
library(tidyverse)
```

```{r missing data,echo=FALSE}
# Read in raw data
raw_data <- read.csv("./Data_Cleaned/metabolomics_without_imputation.csv",
                     stringsAsFactors = F,na.strings = c("","NA"))
# Format
data <- raw_data %>% 
  mutate(compound = coalesce(HMDB.No.,LI.Library.No.),
         neutralmass = Neutral.Mass..Da.,
         rt = RT..s.,
         masserror = coalesce(Mass.Error..ppm.,Mass.Error..ppm..1),
         rterror = coalesce(RT.Error..s.,RT.Error..s..1)) %>%
  select(compound,neutralmass,rt,masserror,rterror,
                IsoMS_results_QC01_190618171010_converted.csv:
                  IsoMS_results_S227_Batch07_1400_RA8_converted.csv)
data$compound <- paste(data$compound,data$neutralmass,data$rt,sep = "")
# Rename columns
colnames(data) <- gsub("IsoMS_results_","",colnames(data))
colnames(data) <- gsub("*_.*","",colnames(data))
# Import clinical data and sample list
clinical <- read.csv("./Data_Cleaned/targeted.csv",stringsAsFactors = F)
# Three progression groups
cac_groups <- read.table("./Data_Raw/CAC Trajectories 3 groups.txt",sep = "\t",
                         header = T)
# CAC progression - increase in square root calcium volume >= 2.5 between baseline and visit 3
clinical$CACp <- as.factor(ifelse(targeted$c3 - targeted$c1 >= 2.5,"Progression","No Progression"))
# New CAC groups
clinical <- left_join(clinical,cac_groups[,c("StudyID","GROUP")],by = "StudyID")
clinical$GROUP <- as.factor(clinical$GROUP)
samples <- read.csv("./Data_Cleaned/sample_list.csv")
# Match sample number to subject ID
clinical$GlobalSampleID <- as.character(samples$Injection[match(clinical$StudyID,samples$SampleID)])
clinical$Batch <- samples$Batch[match(clinical$StudyID,samples$SampleID)]
# Relevant columns
clinical <- clinical %>%
  select(GlobalSampleID,gender,age,sex,race,CACp,GROUP,Batch) %>%
  filter(!is.na(GlobalSampleID))
# Data matrix
X <- data %>% select(QC01:S227)
# Transpose - samples in rows
X <- as.data.frame(t(X))
colnames(X) <- data$compound
X$GlobalSampleID <- as.character(rownames(X))
# Add clinical data
X <- left_join(X,clinical,by = "GlobalSampleID")
# Remove QC
X <- X %>% select(GlobalSampleID,age:GROUP,everything()) %>% 
  filter(!(grepl("QC",GlobalSampleID)))
# Check distributions
skim(X)
```

```{r echo=FALSE}
# Try mixture model with first two metabolites
# Basic models
fullModel <- ~ GROUP|GROUP + age + sex + race
reducedModel <- ~ 1|age + sex + race
# Full model results
fullModelResults <- mxtrmod(ynames=c("AAA00768000187.1075194.4","AAA00759000101.096227.2"),
                            mxtrModel=fullModel,data=X)
fullModelResults
# Reduced model results
reducedModelResults<-mxtrmod(ynames=c("AAA00768000187.1075194.4","AAA00759000101.096227.2"),
                             mxtrModel=reducedModel,data=X,fullModel=fullModel)
reducedModelResults
```

<!-- # PCA -->

<!-- ```{r} -->
<!-- # Try PCA -->
<!-- pca <- pca(X,ncomp=5,center=T,scale=T) -->
<!-- plot(pca) -->
<!-- # Plots -->
<!-- plotIndiv(pca,group = df$GROUP,legend = T,ind.names = F,ellipse = TRUE, -->
<!--           title = "PCA comp 1-2 by CAC Group",pch = 20) -->

<!-- # PCA by batch -->
<!-- pca <- pca(X,ncomp=5,center=T,scale=T) -->
<!-- plot(pca) -->
<!-- # Plots -->
<!-- plotIndiv(pca,group = df$Batch,legend = T,ind.names = F,ellipse = TRUE, -->
<!--           title = "PCA comp 1-2 by Batch",pch = 20) -->
<!-- ``` -->

<!-- # PLS-DA -->

<!-- ## Group -->

<!-- ### Performance and Results -->

<!-- ```{r group plsda} -->
<!-- # Outcome -->
<!-- Y <- factor(df$GROUP) -->
<!-- # PLSDA -->
<!-- plsda <- plsda(X, Y, ncomp = 10,scale = T) -->
<!-- # Evaluate -->
<!-- perf.plsda <- perf(plsda, validation = "loo", folds = 5, -->
<!--                   progressBar = FALSE, auc = TRUE) -->
<!-- plot(perf.plsda, sd = TRUE, legend.position = "horizontal") -->
<!-- # Plots -->
<!-- plotIndiv(plsda,group = df$GROUP, ind.names = FALSE,pch = 20, -->
<!--           ellipse = TRUE, legend = TRUE, title = 'PLSDA on GROUP') -->
<!-- ``` -->

<!-- ### Heatmap -->

<!-- ```{r echo=FALSE,fig.width=8,fig.height=8} -->
<!-- cim(plsda) -->
<!-- ``` -->

<!-- ## Group and Sex -->

<!-- ### Performance and Results -->

<!-- ```{r sex and group plsda} -->
<!-- # Outcome -->
<!-- Y <- factor(df$sex_and_group) -->
<!-- # PLSDA -->
<!-- plsda <- plsda(X, Y, ncomp = 10,scale = T) -->
<!-- # Evaluate -->
<!-- perf.plsda <- perf(plsda, validation = "loo", folds = 5, -->
<!--                   progressBar = FALSE, auc = TRUE) -->
<!-- plot(perf.plsda, sd = TRUE, legend.position = "horizontal") -->
<!-- # Plots -->
<!-- plotIndiv(plsda,group = df$sex_and_group, ind.names = FALSE,pch = 20, -->
<!--           ellipse = TRUE, legend = TRUE, title = 'PLSDA on Sex and GROUP') -->
<!-- ``` -->

<!-- ### Heatmap -->

<!-- ```{r echo=FALSE,fig.width=8,fig.height=8} -->
<!-- cim(plsda) -->
<!-- ``` -->

<!-- ## Sex Only -->

<!-- ### Performance and Results -->

<!-- ```{r sex plsda} -->
<!-- # Outcome -->
<!-- Y <- factor(df$gender) -->
<!-- # PLSDA -->
<!-- plsda <- plsda(X, Y, ncomp = 10,scale = T) -->
<!-- # Evaluate -->
<!-- perf.plsda <- perf(plsda, validation = "loo", folds = 5, -->
<!--                   progressBar = FALSE, auc = TRUE) -->
<!-- plot(perf.plsda, sd = TRUE, legend.position = "horizontal") -->
<!-- # Plots -->
<!-- plotIndiv(plsda,group = df$gender, ind.names = FALSE,pch = 20, -->
<!--           ellipse = TRUE, legend = TRUE, title = 'PLSDA on Sex') -->
<!-- ``` -->

<!-- # sPLS-DA -->

<!-- ## Group -->

<!-- ### Performance and Results -->

<!-- ```{r group splsda} -->
<!-- Y <- factor(df$GROUP) -->
<!-- # sPLSDA tuning -->
<!-- tune.splsda <- tune.splsda(X, Y, ncomp = 4, validation = 'Mfold', folds = 5, -->
<!--                            progressBar = FALSE, dist = 'max.dist', -->
<!--                            nrepeat = 10) -->
<!-- choice.ncomp <- tune.splsda$choice.ncomp$ncomp -->
<!-- choice.keepX <- tune.splsda$choice.keepX[1:choice.ncomp] -->
<!-- # sPLS-DA -->
<!-- splsda.res <- splsda(X, Y, ncomp = choice.ncomp, keepX = choice.keepX) -->
<!-- # Model performance -->
<!-- perf.splsda <- perf(splsda.res, validation = "Mfold", folds = 5, -->
<!--                   progressBar = FALSE, auc = TRUE, nrepeat = 10) -->
<!-- plot(perf.splsda, sd = TRUE, legend.position = "horizontal") -->
<!-- perf.splsda$error.rate -->
<!-- plotIndiv(splsda.res,group = df$GROUP, ind.names = FALSE,pch = 20, -->
<!--           ellipse = TRUE, legend = TRUE, title = 'sPLSDA on GROUP') -->
<!-- ``` -->

<!-- ## Heatmap -->

<!-- ```{r echo=FALSE,fig.width=8,fig.height=8} -->
<!-- cim(splsda.res) -->
<!-- ``` -->

<!-- ## Group and Sex -->

<!-- ### Performance and Results -->

<!-- ```{r sex and group splsda} -->
<!-- Y <- factor(df$sex_and_group) -->
<!-- # sPLSDA tuning -->
<!-- tune.splsda <- tune.splsda(X, Y, ncomp = 4, validation = 'Mfold', folds = 5, -->
<!--                            progressBar = FALSE, dist = 'max.dist', -->
<!--                            nrepeat = 10) -->
<!-- choice.ncomp <- 2 -->
<!-- choice.keepX <- tune.splsda$choice.keepX[1:choice.ncomp] -->
<!-- # sPLS-DA -->
<!-- splsda.res <- splsda(X, Y, ncomp = choice.ncomp, keepX = choice.keepX) -->
<!-- # Model performance -->
<!-- perf.splsda <- perf(splsda.res, validation = "Mfold", folds = 5, -->
<!--                   progressBar = FALSE, auc = TRUE, nrepeat = 10) -->
<!-- plot(perf.splsda, sd = TRUE, legend.position = "horizontal") -->
<!-- perf.splsda$error.rate -->
<!-- plotIndiv(splsda.res,group = df$sex_and_group, ind.names = FALSE,pch = 20, -->
<!--           ellipse = TRUE, legend = TRUE, title = 'sPLSDA on Sex and GROUP') -->
<!-- ``` -->

<!-- ## Heatmap -->

<!-- ```{r echo=FALSE,fig.width=8,fig.height=8} -->
<!-- cim(splsda.res) -->
<!-- ``` -->

<!-- ## Sex Only -->

<!-- ### Performance and Results -->

<!-- ```{r sex splsda} -->
<!-- # Outcome -->
<!-- Y <- factor(df$gender) -->
<!-- # sPLSDA tuning -->
<!-- tune.splsda <- tune.splsda(X, Y, ncomp = 4, validation = 'Mfold', folds = 5, -->
<!--                            progressBar = FALSE, dist = 'max.dist', -->
<!--                            nrepeat = 10) -->
<!-- choice.ncomp <- tune.splsda$choice.ncomp$ncomp -->
<!-- choice.keepX <- tune.splsda$choice.keepX[1:choice.ncomp] -->
<!-- # sPLS-DA -->
<!-- splsda.res <- splsda(X, Y, ncomp = choice.ncomp, keepX = choice.keepX) -->
<!-- # Model performance -->
<!-- perf.splsda <- perf(splsda.res, validation = "Mfold", folds = 5, -->
<!--                   progressBar = FALSE, auc = TRUE, nrepeat = 10) -->
<!-- plot(perf.splsda, sd = TRUE, legend.position = "horizontal") -->
<!-- perf.splsda$error.rate -->
<!-- plotIndiv(splsda.res,group = df$gender, ind.names = FALSE,pch = 20, -->
<!--           ellipse = TRUE, legend = TRUE, title = 'sPLSDA on Sex') -->
<!-- ``` -->

<!-- ## Heatmap -->

<!-- ```{r echo=FALSE,fig.width=8,fig.height=8} -->
<!-- cim(splsda.res) -->
<!-- ``` -->

<!-- ## ANOVA -->

<!-- ### Sex Only -->

<!-- P values adjusted using the FDR method -->

<!-- ```{r anova sex,echo=FALSE} -->
<!-- anova_results <- lapply(metabolites, function(x){ -->
<!--   form <- as.formula(paste0(x,"~factor(gender)")) -->
<!--   mod <- aov(form,df[df$GROUP != "QC",]) -->
<!--   results <- broom::tidy(mod) -->
<!--   results[1,1] <- x -->
<!--   as.data.frame(results[1,]) -->
<!-- }) -->
<!-- anova_results <- bind_rows(anova_results) -->
<!-- anova_results <- anova_results %>% arrange(p.value) -->
<!-- anova_results$p.value <- p.adjust(anova_results$p.value,"fdr") -->
<!-- kable(anova_results[which(anova_results$p.value < 0.05),]) -->
<!-- ``` -->

<!-- ## Normalization -->

<!-- ```{r normalization,echo=FALSE,eval=FALSE} -->
<!-- # Metabolite data -->
<!-- featuredata <- df_qc[,9:(ncol(df_qc)-1)] -->
<!-- rownames(featuredata) <- df_qc$GlobalSampleID -->
<!-- # Injection order -->
<!-- sampledata <- read.csv("./Data_Cleaned/injection_seq.csv",stringsAsFactors = F) %>% -->
<!--   select(Injection,SampleName,Position) %>% -->
<!--   filter(Injection %in% rownames(featuredata)) -->
<!-- # Format sample data -->
<!-- sampledata$batch <- sapply(strsplit(sampledata$SampleName,"_"),`[`,2) -->
<!-- sampledata$batch[nrow(sampledata)] <- sampledata$batch[(nrow(sampledata)-1)] -->
<!-- sampledata$batch <- sub("Batch0","",sampledata$batch) -->
<!-- sampledata <- sampledata %>% fill(batch,.direction = "up") %>% -->
<!--   mutate(order = 1:n()) -->
<!-- rownames(sampledata) <- sampledata$GlobalSampleID -->
<!-- sampledata$class <- df_qc$GROUP[match(sampledata$Injection,df_qc$GlobalSampleID)] -->
<!-- sampledata$class[sampledata$class == "QC"] <- 0 -->
<!-- # Match sample and feature data, set rownames -->
<!-- featuredata <- featuredata[match(sampledata$Injection,rownames(featuredata)),] -->
<!-- featuredata <- as.data.frame(featuredata) -->
<!-- rownames(sampledata) <- sampledata$Injection -->
<!-- sampledata <- sampledata %>% select(batch,class,order) %>% as.data.frame() -->
<!-- # Normalize - saves output in working directory -->
<!-- normalized <- NormQcsamples(featuredata, sampledata, method = c("rlsc"), span = 0, -->
<!--   deg = 2, lg = TRUE, saveoutput = T) -->
<!-- ``` -->

<!-- ### PCA on Normalized Data -->

<!-- ```{r normalized,echo=FALSE} -->
<!-- df_qc <- read.csv("./Data_Cleaned/qcsample_results.csv") -->
<!-- df_qc$sampledata.class[is.na(df_qc$sampledata.class)] <- "QC" -->
<!-- X <- as.matrix(df_qc[,6:ncol(df_qc)]) -->
<!-- class(X) <- "numeric" -->
<!-- # Try PCA  -->
<!-- pca <- pca(X,ncomp=5,center=T,scale=T) -->
<!-- # Plots -->
<!-- plotIndiv(pca,group = df_qc$sampledata.class,legend = T,ind.names = F,ellipse = TRUE, -->
<!--           title = "PCA comp 1-2 by CAC Group",pch = 20) -->
<!-- # Plots -->
<!-- plotIndiv(pca,group = df_qc$sampledata.batch,legend = T,ind.names = F,ellipse = TRUE, -->
<!--           title = "PCA comp 1-2 by Batch",pch = 20) -->
<!-- ``` -->

<!-- ### Remove Potential Outliers -->

<!-- ```{r normalized no outliers,echo=FALSE} -->
<!-- X <- X[-c(172,235),] -->
<!-- pca <- pca(X,ncomp=5,center=T,scale=T) -->
<!-- # Plots -->
<!-- plotIndiv(pca,group = df_qc$sampledata.class[-c(172,235)],legend = T, -->
<!--           ind.names = F,ellipse = TRUE,pch = 20, -->
<!--           title = "PCA comp 1-2 by CAC Group") -->
<!-- # Plots -->
<!-- plotIndiv(pca,group = df_qc$sampledata.batch[-c(172,235)], -->
<!--           legend = T,ind.names = F,ellipse = TRUE,pch = 20, -->
<!--           title = "PCA comp 1-2 by Batch") -->
<!-- ``` -->

<!-- # sPLS-DA -->

<!-- ## Group -->

<!-- ### Performance and Results -->

<!-- ```{r group splsda normalized} -->
<!-- Y <- factor(df_qc$sampledata.class[-c(172,235)]) -->
<!-- # sPLSDA tuning -->
<!-- tune.splsda <- tune.splsda(X, Y, ncomp = 4, validation = 'Mfold', folds = 5, -->
<!--                            progressBar = FALSE, dist = 'max.dist', -->
<!--                            nrepeat = 10) -->
<!-- choice.ncomp <- tune.splsda$choice.ncomp$ncomp -->
<!-- choice.keepX <- tune.splsda$choice.keepX[1:choice.ncomp] -->
<!-- # sPLS-DA -->
<!-- splsda.res <- splsda(X, Y, ncomp = choice.ncomp, keepX = choice.keepX) -->
<!-- # Model performance -->
<!-- perf.splsda <- perf(splsda.res, validation = "Mfold", folds = 5, -->
<!--                   progressBar = FALSE, auc = TRUE, nrepeat = 10) -->
<!-- plot(perf.splsda, sd = TRUE, legend.position = "horizontal") -->
<!-- perf.splsda$error.rate -->
<!-- plotIndiv(splsda.res,group = df_qc$sampledata.class[-c(172,235)], -->
<!--           ind.names = FALSE,pch = 20, -->
<!--           ellipse = TRUE, legend = TRUE, title = 'sPLSDA on GROUP') -->
<!-- ``` -->

<!-- ### ANOVA -->

<!-- P values adjusted using the FDR method -->

<!-- ```{r anova sex normalized,echo=FALSE} -->
<!-- metabolites <- names(df_qc)[6:ncol(df_qc)] -->
<!-- anova_results <- lapply(metabolites, function(x){ -->
<!--   form <- as.formula(paste0(x,"~factor(sampledata.class)")) -->
<!--   mod <- aov(form,df_qc[-c(172,235,which(df_qc$sampledata.class == "QC")),]) -->
<!--   results <- broom::tidy(mod) -->
<!--   results[1,1] <- x -->
<!--   as.data.frame(results[1,]) -->
<!-- }) -->
<!-- anova_results <- bind_rows(anova_results) -->
<!-- anova_results <- anova_results %>% arrange(p.value) -->
<!-- anova_results$p.value <- p.adjust(anova_results$p.value,"fdr") -->
<!-- kable(anova_results[which(anova_results$p.value < 0.05),]) -->
<!-- ``` -->
