---
title: "Population Stratification"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = "/Users/timvigers/Documents/OneDrive - The University of Colorado Denver/simmons")
library(arsenal)
library(skimr)
library(knitr)
library(tidyverse)
```

```{r}
# Read in race info for Kimber's participants
kimber <- read.csv("./clinical.csv")
# Match to .fam IDs
fam <- read.table(file="./analysis/final_merge.fam",header=F)
fam$studyid <- gsub(".*_","",fam$V2)
fam$race <- kimber$Hispanic..0.N..1.Y.[match(fam$studyid,kimber$correct_labID)]
fam$race <- factor(fam$race,levels = c(0,1),labels = c("Non-Hispanic","Hispanic"))
fam$race <- as.character(fam$race)
# Biobank ids
biobank_demo <- read.csv("./Biobank Hispanic Patients - Compass Mapping File.csv")
fam$race[which(fam$studyid %in% biobank_demo$Arb_person_id)] <- "Hispanic"
# Reference races
race<- read.table(file="/Users/timvigers/Documents/Work/GWAS/G1K/Phase3/merged/phase3_corrected.psam",
                stringsAsFactors = F,header = F)
colnames(race) <- c("studyid","PAT","MAT","SEX","SuperPop","Population")
race <- full_join(race,fam[,c("studyid","race")],by = "studyid")
race <- race %>% mutate(pop = coalesce(race,Population))
race$superpop <- ifelse(race$pop == "Hispanic","Hispanic",
                        ifelse(race$pop == "Non-Hispanic","Non-Hispanic",race$SuperPop))
colnames(race)[1] <- "IID"

# Read in PCA
data<- read.table(file="./analysis/PCA.eigenvec",header=FALSE)
colnames(data) <- c("FID","IID",paste0("C",seq(1,ncol(data)-2)))
data$IID <- gsub(".*_","",data$IID)
# Join and plot
datafile<- left_join(data,race[,c("IID","superpop","pop")],by="IID")
# Plot (colorblind friendly)
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
ggplot(datafile,aes(x=C1,y=C2)) + 
  geom_point(aes(color = superpop)) + scale_color_manual(values=cbPalette) + theme_bw()
ggplot(datafile,aes(x=C2,y=C3)) + 
  geom_point(aes(color = superpop)) + scale_color_manual(values=cbPalette) + theme_bw()
ggplot(datafile,aes(x=C1,y=C3)) + 
  geom_point(aes(color = superpop)) + scale_color_manual(values=cbPalette) + theme_bw()
```