---
title: "Grant Proposal"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(skimr)
library(tidyverse)
```

```{r }
# Read in data
eda <- read.csv("/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/CWHR Metabolomics/Data_Cleaned/QClampHormones_All Data.csv")
eda$dia <- as.factor(ifelse(eda$dia == 0,"Yes","No"))
skim(eda) %>% kable()
```

### Cortisol

```{r }
ggplot(eda,aes(x=Cortisol,y=S3_GIR)) + geom_point()
summary(lm(S3_GIR~Cortisol+Progesterone,data = eda))$coefficients
summary(lm(S3_GIR~Cortisol,data = eda))$coefficients
```

### Estradiol

```{r }
ggplot(eda,aes(x=Estradiol,y=S3_GIR)) + geom_point()
summary(lm(S3_GIR~Estradiol+Progesterone,data = eda))$coefficients
summary(lm(S3_GIR~Estradiol,data = eda))$coefficients
```

### Progesterone

```{r }
ggplot(eda,aes(x=Progesterone,y=S3_GIR)) + geom_point()
summary(lm(S3_GIR~Progesterone,data = eda))$coefficients
```

### SHBG

```{r }
ggplot(eda,aes(x=SHBG,y=S3_GIR)) + geom_point()
summary(lm(S3_GIR~SHBG+Progesterone,data = eda))$coefficients
summary(lm(S3_GIR~SHBG,data = eda))$coefficients
```

### Testosterone

```{r }
ggplot(eda,aes(x=Testosterone,y=S3_GIR)) + geom_point()
summary(lm(S3_GIR~Testosterone+Progesterone,data = eda))$coefficients
summary(lm(S3_GIR~Testosterone,data = eda))$coefficients
```