---
title: ""
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(performance)
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r results='asis'}
df = read.csv("/Users/timvigers/Dropbox/Work/Viral Shah/ADA 2022/Data_Clean/combined_data.csv")
df$Group = cut(df$HbA1c,c(-Inf,5.7,Inf),labels = c("< 5.7","5.7 - 6.5"),right = F)
df$abs_diff = abs(df$Diff)
df$abs_diff_cat = cut(df$abs_diff,c(seq(0,1,0.1),Inf),right = F)
t = tableby(Group ~ abs_diff_cat,df)
summary(t)
```
