---
title: ""
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Bromocriptine/Data_Cleaned")
library(tableone)
library(skimr)
library(knitr)
library(tidyverse)
```

```{r echo=FALSE,include=FALSE}
# Import and format dates
# Adults
adult_dates <- read.csv("./Adult Enrollment Log.csv",na.strings = c("","NA"),
                        stringsAsFactors = F) %>%
  select(ID,X,Visit.1:Med.Start,Visit.3:Med.Start.1,Visit.6,Visit.7) %>%
  unite(ID,ID,X,sep = "")
adult_dates[,2:ncol(adult_dates)] <- lapply(adult_dates[,2:ncol(adult_dates)],
                                            lubridate::mdy)
adult_dates <- adult_dates %>% select(ID,Visit.1,Visit.4,Visit.7,Med.Start,Med.Start.1)
# Children
peds_dates <- read.csv("./Peds Enrollment Log.csv",na.strings = c("","NA"),
                       stringsAsFactors = F)
peds_dates <- peds_dates[-c(1),]
peds_dates <- peds_dates %>% select(SUBJECT.ID,Visit.1:Med.Start...P2)
peds_dates[,2:ncol(peds_dates)] <- lapply(peds_dates[,2:ncol(peds_dates)],
                                          lubridate::mdy)
colnames(peds_dates) <- c("ID","Visit.1","Visit.4","Visit.7","Med.Start","Med.Start.1")
# Combine
all_dates <- rbind(adult_dates,peds_dates)
colnames(all_dates)[which(colnames(all_dates)=="ID")] <- "subjectid"
```

```{r echo=FALSE,include=FALSE}
# Adult files
indir <- "./Cleaned Adult Files/All"
files <- list.files(indir,full.names = T)
out <- data.frame()
for (f in files) {
  df <- read.csv(f)
  df$subjectid <- sub("-0","-",df$subjectid)
  out <- rbind(out,df)
}
out$timestamp <- lubridate::ymd_hms(out$timestamp)
# Add dates
out <- left_join(out,all_dates,by="subjectid")
# Determine period
out$period <- 
  ifelse(out$timestamp < out$Med.Start & out$timestamp > (out$Med.Start-3),"Med1_3days",
         ifelse(out$timestamp < out$Med.Start.1 & out$timestamp > (out$Med.Start.1-3),"Med2_3days",
                ifelse(out$timestamp < out$Visit.4 & out$timestamp > (out$Visit.4-7),"Visit4_7days",
                       ifelse(out$timestamp < out$Visit.7 & out$timestamp > (out$Visit.7-7),"Visit7_7days","None"))))
out <- out %>% filter(period != "None")
# Split and write CSVs
out <- split(out,list(out$subjectid,out$period))
sapply(names(out), function(x){write.csv(out[[x]][1:3],file = paste0("./Cleaned Adult Files/By Subject/",x,".csv"),row.names = F)})
# Same again for peds
indir <- "./Cleaned Peds Files/All"
files <- list.files(indir,full.names = T)
out <- data.frame()
for (f in files) {
  df <- read.csv(f)
  df$subjectid <- sub("-0","-",df$subjectid)
  out <- rbind(out,df)
}
out$timestamp <- lubridate::ymd_hms(out$timestamp)
# Add dates
out <- left_join(out,all_dates,by="subjectid")
# Determine period
out$period <- 
  ifelse(out$timestamp < out$Med.Start & out$timestamp > (out$Med.Start-3),"Med1_3days",
         ifelse(out$timestamp < out$Med.Start.1 & out$timestamp > (out$Med.Start.1-3),"Med2_3days",
                ifelse(out$timestamp < out$Visit.4 & out$timestamp > (out$Visit.4-7),"Visit4_7days",
                       ifelse(out$timestamp < out$Visit.7 & out$timestamp > (out$Visit.7-7),"Visit7_7days","None"))))
out <- out %>% filter(period != "None")
# Split and write CSVs
out <- split(out,list(out$subjectid,out$period))
sapply(names(out), function(x){write.csv(out[[x]][1:3],file = paste0("./Cleaned Peds Files/By Subject/",x,".csv"),row.names = F)})
```