options merror mlogic mprint symbolgen spool;

libname merit 'y:/analysis of data/janet/merit';
                                                                                                                      

/* First parameter is the directory of where your files are stored. */                                                                  
/* Second parameter is the extension you are looking for.           */                                                                  

Proc printto log='templog.log' new;
Run;
%macro drive(dir,ext); 
   %local cnt filrf rc did memcnt name;
   %let cnt=0;
   %let filrf=mydir;
   %let rc=%sysfunc(filename(filrf,&dir));
   %let did=%sysfunc(dopen(&filrf));
   %if &did ne 0 %then %do;
      %let memcnt=%sysfunc(dnum(&did));
      %do i=1 %to &memcnt;
         %let name=%qscan(%qsysfunc(dread(&did,&i)),-1,.);
         %if %qupcase(%qsysfunc(dread(&did,&i))) ne %qupcase(&name) %then %do;
            %if %superq(ext) = %superq(name) %then %do;
               %let cnt=%eval(&cnt+1);
               %put %qsysfunc(dread(&did,&i));
               proc import datafile="&dir\%qsysfunc(dread(&did,&i))" out=dsn&cnt 
                  dbms=csv replace;
                  guessingrows=max;
				  filename subject_dates;
				  run;
			data dsn&cnt (keep=Subject_id subject_num subject_time event_type timestamp glucose_value);
			set dsn&cnt;
			informat Glucose_Value__mg_dL_ $4. ;
			if Glucose_Value__mg_dL_="High" then Glucose_Value__mg_dL_=401;
			else if Glucose_Value__mg_dL_="Low" then Glucose_Value__mg_dL_=39;
			glucose_value = .;
			glucose_value = Glucose_Value__mg_dL_;
			timestamp = Timestamp__YYYY_MM_DDThh_mm_ss_;
		 	filename="&dir\%qsysfunc(dread(&did,&i))";
			Filedates = substr(filename,length(filename)-31,28);
			Subject_time= substr(filedates,length(filedates)-20,21);
			Subject_ID= substr(filedates,length(filedates) -27,6);
			Subject = substr(filedates,length(filedates)-27,3);
			run;
			data cgm_new;
			set dsn1-dsn&cnt;
			cgm_time = timepart(timestamp);
			*put cgm_time=time.5;
			cgm_date = datepart(timestamp);
			*put cgm_date=date9.;
			*put subject_num =best3.;
			cgmdate = cgm_date;
			cgmtime = cgm_time;
			format cgmdate date9.;
			format cgmtime time5.;
			format subject_id $6.;
			length subject_id $6.;
			if glucose_value ne . then do;
				if glucose_value <54 then hypo54=100;
				else hypo54=0;
				if glucose_value <70 then hypo70=100;
				else hypo70=0;
				if glucose_value >180 then hyper180=100;
				else hyper180=0;
				if glucose_value >250 then hyper250 =100;
				else hyper250=0;
				if hypo70 = 0 and hyper180 = 0 then TIR=100;
				else TIR = 0;
				end;
			if event_type = "EGV";
		run;
            %end;
         %end;
       %end;
    %end;
  %else %put &dir cannot be opened.;

  %let rc=%sysfunc(dclose(&did));
  ;
%mend drive;
%drive(y:\merit study_23-1513\CGM Analysis,csv)
Proc printto log=log; run;

proc contents data=cgm_new;run;
proc means data=cgm_new;
	class subject_id;
	var glucose_value;
run;
proc print data=cgm_all (obs=50);
	where subject_id="129_EX";
run;
*** Import non-DEXCOM MERIT CGMs ***;
*** 128 ***;
proc print data=cgm_128_ex (obs=100);
run;
Data merit.CGM_obs_128_EX;
	set cgm_128_ex;

	Subject_ID = "128_EX";
	timestamp = EventDateTime;
	glucose_value = Readings__mg_dL_;
	format eventdatetime mdyampm19.;
	cgm_time = timepart(timestamp);
	put cgm_time=time.5;
	cgm_date = datepart(timestamp);
	put cgm_date=date9.;
	cgmdate = cgm_date;
	cgmtime = cgm_time;
	format cgmdate date9.;
	format cgmtime time5.;
	if glucose_value ne . then do;
			if glucose_value <54 then hypo54=100;
			else hypo54=0;
			if glucose_value <70 then hypo70=100;
			else hypo70=0;
			if glucose_value >180 then hyper180=100;
			else hyper180=0;
			if glucose_value >250 then hyper250 =100;
			else hyper250=0;
			if hypo70 = 0 and hyper180 = 0 then TIR=100;
			else TIR = 0;
	end;
	event_type = "EGV";
run;
*** 107 ***;
proc print data=cgm_obs_107_month3 (obs=10);
run;
proc sort data=cgm_obs_107_month1;
	by eventdatetime;
run;
proc sort data=cgm_obs_107_month2;
	by eventdatetime;
run;
proc sort data=cgm_obs_107_month3;
	by eventdatetime;
run;
data merit.cgm_obs_107 (keep = subject_id timestamp event_type glucose_value cgmdate cgmtime cgm_date cgm_time tir hyper180 hyper250 hypo54 hypo70);
	merge cgm_obs_107_month1 cgm_obs_107_month2 cgm_obs_107_month3;
	by eventdatetime;
	Subject_ID = "107_EX";
	timestamp = EventDateTime;
	glucose_value = Readings__mg_dL_;
	format eventdatetime mdyampm19.;
	cgm_time = timepart(timestamp);
	put cgm_time=time.5;
	cgm_date = datepart(timestamp);
	put cgm_date=date9.;
	cgmdate = cgm_date;
	cgmtime = cgm_time;
	format cgmdate date9.;
	format cgmtime time5.;
	if glucose_value ne . then do;
			if glucose_value <54 then hypo54=100;
			else hypo54=0;
			if glucose_value <70 then hypo70=100;
			else hypo70=0;
			if glucose_value >180 then hyper180=100;
			else hyper180=0;
			if glucose_value >250 then hyper250 =100;
			else hyper250=0;
			if hypo70 = 0 and hyper180 = 0 then TIR=100;
			else TIR = 0;
	end;
	event_type = "EGV";
run;
proc contents data=cgm_obs_114;
run;
proc print data=cgm_obs_114 (obs=10);
run;
data merit.cgm_obs_114 (keep= subject_id timestamp event_type glucose_value cgmdate cgmtime cgm_date cgm_time tir hyper180 hyper250 hypo54 hypo70);
	set cgm_obs_114;
	subject_id = "114_EX";
	glucose_value = CGM_Glucose_Value__mg_dl_;
	cgm_time = timepart(timestamp);
	*put cgm_time=time.5;
	cgm_date = datepart(timestamp);
	*put cgm_date=date9.;
	cgmdate = cgm_date;
	cgmtime = cgm_time;
	format cgmdate date9.;
	format cgmtime time5.;
	if glucose_value ne . then do;
			if glucose_value <54 then hypo54=100;
			else hypo54=0;
			if glucose_value <70 then hypo70=100;
			else hypo70=0;
			if glucose_value >180 then hyper180=100;
			else hyper180=0;
			if glucose_value >250 then hyper250 =100;
			else hyper250=0;
			if hypo70 = 0 and hyper180 = 0 then TIR=100;
			else TIR = 0;
	end;
	event_type = "EGV";
run;
proc contents data=merit.cgm_obs_114;run;
proc print data=merit.cgm_obs_114 (obs=10);run;
proc means data=merit.cgm_obs_114;
	*class cgmdate;
run;
proc contents data=cgm_obs_114;
run;
proc print data=cgm_obs_114 (obs=10);
run;
data cgm_obs_122;
	set cgm_122;
	if description ="EGV";
run;
data merit.cgm_obs_122 (keep= subject_id timestamp event_type glucose_value cgmdate cgmtime cgm_date cgm_time tir hyper180 hyper250 hypo54 hypo70);
	set cgm_obs_122;
	subject_id = "122_EX";
	event_type = "EGV";

	timestamp = EventDateTime;
	glucose_value = Readings__mg_dL_;
	format eventdatetime mdyampm19.;
	cgm_time = timepart(timestamp);
	put cgm_time=time.5;
	cgm_date = datepart(timestamp);
	put cgm_date=date9.;
	cgmdate = cgm_date;
	cgmtime = cgm_time;
	format cgmdate date9.;
	format cgmtime time5.;
	if glucose_value ne . then do;
			if glucose_value <54 then hypo54=100;
			else hypo54=0;
			if glucose_value <70 then hypo70=100;
			else hypo70=0;
			if glucose_value >180 then hyper180=100;
			else hyper180=0;
			if glucose_value >250 then hyper250 =100;
			else hyper250=0;
			if hypo70 = 0 and hyper180 = 0 then TIR=100;
			else TIR = 0;
	end;
	if event_type = "EGV" and timestamp ne .;
run;
proc print data=merit.cgm_obs_122 (obs=10);run;
proc means data=merit.cgm_obs_122;
	class cgmdate;
	var glucose_value;
run;
proc contents data=merit.cgm_obs_122;
run;
proc contents data=cgm_all;run;
**** Must run this ***;
data cgm_obs_all (keep = subject_id timestamp event_type glucose_value cgmdate cgmtime cgm_date cgm_time tir hyper180 hyper250 hypo54 hypo70);
	set cgm_all;
	where event_type = "EGV";
run;
proc print data=cgm_all (obs=50);
	where subject_id = "130_EX";
run;
proc contents data=merit.cgm_obs_107;run;
proc sort data=merit.cgm_obs_107;
	by subject_ID timestamp;
run;
proc sort data=merit.cgm_obs_114;
	by subject_ID timestamp;
run;
proc sort data=merit.cgm_obs_122;
	by subject_id timestamp;
run;
proc sort data=merit.cgm_obs_128_EX;
	by subject_id timestamp;
run;
data merit.cmg_obs_tandem;
	set merit.cgm_obs_128_ex merit.cgm_obs_122 merit.cgm_obs_114 merit.cgm_obs_107;
run;
*** Add in new CGM files ***;
data merit.cgm_obs_backup;
	set merit.cgm_obs_all;
run;
proc sort data=merit.cgm_obs_128_ex;
	by subject_id timestamp;
run;
proc sort data=merit.cgm_obs_all;
	by subject_ID timestamp;
run;
proc sort data=cgm_new;
	by subject_ID timestamp;
run;
data merit.cgm_obs_all;
 set merit.cgm_obs_all merit.cgm_obs_128_EX cgm_new;
run;
proc means data=merit.cgm_obs_all;
	class subject_id;
run;

*** Process data to calculate time differences and find duplicates ***;

proc sort data=merit.cgm_obs_all;
	by subject_id timestamp;
run;

data cgm_obs_loop;
	set merit.cgm_obs_all;
	by subject_id timestamp;
	if _N_=1 then do;
		prior_time=.;
		prior_glucose=.;
	end;
	prior_glucose = lag(glucose_value);
	prior_time=lag(cgmtime);
	time_diff = round((cgmtime - prior_time)/60);
	glu_diff = glucose_value - prior_glucose;
run;
proc means data=cgm_obs_loop;
	class subject_id;
run;
*** Remove Duplicates ***;
data cgm_obs_loop_nodups;
	set cgm_obs_loop;
	if time_diff =0 and glu_diff = 0 then delete;
	drop prior_glucose prior_time time_diff glu_diff;
run;
data cgm_obs_dups;
	set cgm_obs_loop;
	if time_diff=0 and glu_diff=0;
run;
proc print data=cgm_obs_loop;
	where time_diff=0 and glu_diff ne 0;
run;
proc print data=cgm_obs_dups (obs=500);
	run;
	proc print data=merit.cgm_obs_all;
		where subject_id = "101_EX" and cgmdate = 23612;
run;
*** Recalculate time diff and remove extra glucose values ***;
proc sort data=cgm_obs_loop_nodups;
	by subject_id timestamp;
run;
data merit.cgm_obs_clean;
	set cgm_obs_loop_nodups;
	by subject_id Timestamp; 
	*subject = .;
	*subject= 
	prior_time=lag(timestamp);
	prior_glucose=lag(glucose_value);
	glu_diff=round(glucose_value-lag(glucose_value));
	time_diff=round((timestamp-lag(timestamp))/60);

	if _N_=1 then do;
		time_diff=.;
		glu_diff=.;
		prior_time=.;
		prior_glucose=.;
	end;
	if time_diff >=5;
run;
proc print data=merit.cgm_obs_clean;
where time_diff=0 and glu_diff ne 0;
run;
proc means data=merit.cgm_obs_clean;
	class subject_id;
run;
*** Create dataset with extra glucose measures - outside of every 5 min ***;
data cgm_obs_extra;
	set cgm_obs_loop_nodups;
	by subject_id Timestamp; 

	prior_time=lag(timestamp);
	prior_glucose=lag(glucose_value);
	glu_diff=round(glucose_value-lag(glucose_value));
	time_diff=round((timestamp-lag(timestamp))/60);

	if _N_=1 then do;
		time_diff=.;
		glu_diff=.;
		prior_time=.;
		prior_glucose=.;
	end;
	if time_diff < 5;
run;
proc print data=cgm_obs_extra (obs=500);
run;
proc print data=merit.cgm_obs_clean (obs=50) ;
	where subject_id = "104_EX";
run;
*** Create daily summary of CGM data ***;
Proc sort data=merit.cgm_obs_clean;
	by subject_id cgmdate;
run;
proc means data=merit.cgm_obs_clean;
	class cgmdate;
	var  cgm_date glucose_value tir hypo54 hypo70 hyper180 hyper250;
	output out=cgm_obs_byday;
	by subject_id;
run;
proc print data=cgm_obs_byday ;
	where subject_id ="104_EX";
run;
*** means and SD overall by subject ID ***;
proc means data=merit.cgm_obs_clean;
	class subject_id;
	var  cgm_date glucose_value tir hypo54 hypo70 hyper180 hyper250;
	output out=cgm_obs_overall;
	*by subject_id;
run;
proc print data=cgm_obs_overall ;
	where subject_id ="104_EX";
run;
*** Output CGM means by day ***;
data cgm_obs_clean_means;
	set cgm_obs_byday;
	if _STAT_="MEAN" and cgmdate ne .;;
run;
proc print data=cgm_obs_clean_means;
run;
*** Out put glucose SD by day ***;
data cgm_obs_clean_glusd (keep=subject_id cgmdate glucose_sd);
	set cgm_obs_byday;
	glucose_sd = glucose_value;
	if _STAT_="STD" and cgmdate ne .;
run;
proc print data=cgm_obs_clean_glusd (obs=50);
run;
*** Create dataset combining means and glucose SD ***;
proc sort data=cgm_obs_clean_means;
	by subject_id cgmdate;
run;
proc sort data=cgm_obs_clean_glusd;
	by subject_id cgmdate;
run;
data merit.cgm_obs_clean_days (keep=subject_id cgmdate glucose_readings cgm_date glucose_value glucose_sd glucose_cv TIR hypo54 hypo70 hyper180 hyper250);
	merge cgm_obs_clean_glusd cgm_obs_clean_means;
	Glucose_readings = _FREQ_;
	Glucose_CV = (glucose_sd/glucose_value)*100;
	by subject_id cgmdate;
run;

proc sort data=merit.cgm_obs_clean_days;
	by subject_id cgm_date;
run;

proc print data=merit.cgm_obs_clean_days (obs=50);
run;
**** Create Rounded CGM times ***;
proc sort data=merit.cgm_obs_clean;
	by subject_id timestamp;
run;
data merit.cgm_obs_clean;
	set merit.cgm_obs_clean;
	cgm_time_min = cgmtime/60;
	cgm_time_rounded = round(cgm_time_min,5);
	cgm_hour = cgm_time_rounded/60;
run;
proc print data=merit.cgm_obs_clean (obs=288);
	var subject_id cgmdate cgmtime cgm_time cgm_time_min cgm_time_rounded cgm_hour;
run;

proc means data=merit.cgm_obs_clean;
	class subject_id cgm_time_rounded;
	var glucose_value tir hypo54 hypo70 hyper180 hyper250;
run;
**** Main CGM file with every 5 min glucose values ***;
proc contents data=merit.cgm_obs_clean order=varnum;
run;
*** CGM values aggregated by day ***;
proc contents data=merit.cgm_obs_clean_days order=varnum;
run;




**** Test importing Tandem CGM data ****;
proc contents data=adjust_cgm_209_v3;
run;
proc print data=adjust_cgm_209_v3 (obs=10);run;
proc printto log='templog.log' new;
proc printto log = log;
proc sort data=adjust_cgm_209v3;
	by timestamp;
run;
data adjust_cgm_209v3 (keep=subject timestamp sensorglucose);
	set adjust_cgm_209_v3;
	Subject = "209";
	timestamp = EventDateTime;
	sensorglucose = Readings__mg_dL_;
	format timestamp mdyampm19.;
	put timestamp mdyampm19.
run;
proc contents data=adjust_cgm_209v3;run;
proc print data=adjust_cgm_209v3 (obs=10);run;
proc sort data=adjust_cgm_209v3;
	by subject timestamp;
run;
data adjust_cgm_209v3_first;
	set adjust_cgm_209v3  ;
	by timestamp;
	end = .;
	end = last.timestamp;
	start = .;
	start = first_timestamp;
	*if end or _N_=1;
run;
proc means data=adjust_cgm_209v3 min max;
	var timestamp;
	by subject;
	output out=adjust_cgm_209v3_timestamps;
run;
proc print data=adjust_cgm_209v3_timestamps;
run;
proc print data=adjust_cgm_209v3_first ;run;
*** Creating output datasets for cgmanalysis ***;
%macro output_cgm(Var);
	proc sort data=merit.cgm_obs_phase;
	by subject_id timestamp;
run;
	data work.cgm_output;
		set merit.cgm_obs_phase;
		if subject_id = &var;
		*output out=&output_prefix.&var_val;
run;
%mend;
*%let output_prefix=cgm_obs;
*%let var_val = &var.;
%let dsname = "cgm_obs";
*%put &var_val;
%output_cgm("101_EX");
%output_cgm("102_EX");
proc contents data=cgm_output;run;
proc print data=cgm_output (obs=10);
run;
data merit.cgm_101EX (keep=timestamp sensorglucose);
	set cgm_output;
	sensorglucose = .;
	sensorglucose=glucose_value;
	*if phase="Follicular";
run;
data merit.cgm_102EX (keep=timestamp sensorglucose);
	set cgm_output;
	sensorglucose = .;
	sensorglucose=glucose_value;
	*if phase="Follicular";
run;
proc print data=merit.cgm_101ex_follicular (obs=10);run;
proc print data=merit.cgm_102ex (obs=10);run;
proc sort data=merit.cgm_obs_phase;
	by subject_id timestamp;
run;
