---
title: "HCL Overnight Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Erin Cobry/670g obs sleep")
library(arsenal)
library(cgmanalysis)
library(car)
library(skimr)
library(Hmisc)
library(knitr)
library(lme4)
library(nlme)
library(MASS)
library(tidyverse)
```

```{r data import and clean,echo=FALSE,include=FALSE}
# Import Cari's data
source("/Users/timvigers/Documents/GitHub/BDC-Code/Erin Cobry/AdvancedClosedLoopCl_R_2020-01-05_1101.r")
# Demographics
demographics <- data %>% 
  filter(redcap_event_name %in% c("baseline_arm_1","baseline_arm_2"),
         !is.na(child_ya))
# ID to match Erin's - clean Erin's then demographics
demographics$id <- paste0(demographics$record_id,demographics$demographics_initals)
# remove missing
no_data <- c("27","30LR","38SR","41SW")
demographics <- demographics %>% filter(!(id %in% no_data))
# Manually corrected a few dates in CSV file.
# Read in (manually converted to long format from Erin's Excel spreadsheet)
overnight_alarms <- read.csv("./Data_Cleaned/Overnight Alarm Data.csv",
                             na.strings = c("","No Data"))
# Column names
colnames(overnight_alarms) <- c("id","timepoint","start_date","end_date","num_nights",
                                "num_alarms","num_alarms_in_AM","perc_time_in_AM")
overnight_alarms <- overnight_alarms %>% filter(!(id %in% no_data))
# Format date columns
overnight_alarms[,c("start_date","end_date")] <- 
  lapply(overnight_alarms[,c("start_date","end_date")], 
         function(x) {lubridate::mdy(as.character(x))})
# Calculate number of nights 
overnight_alarms$num_nights <- as.numeric(difftime(overnight_alarms$end_date,
                                                   overnight_alarms$start_date,
                                                   units = "days"))
# Order timepoints
overnight_alarms$timepoint <- factor(overnight_alarms$timepoint,
                                     levels = c("Baseline","week 2",
                                                "T1","T2","T3","T4" ))
# Numeric timepoints in months
overnight_alarms$numeric_time <- 
  car::recode(overnight_alarms$timepoint,
              "'Baseline' = 0;'week 2' = 0.5;'T1' = 3;'T2' = 6;'T3' = 9;'T4' = 12")
# Get Erin's participants 
demographics <- demographics[which(demographics$id %in% overnight_alarms$id),]
# Combine CGM and pump hx levels
levels(demographics$demographics_cgmhx.factor) <-
  c("< 1 month","> 1 month","> 1 month","> 1 month","> 1 month","> 1 month")
levels(demographics$demographics_pumphx.factor) <-
  c("< 1 month","> 1 month","> 1 month","> 1 month","> 1 month","> 1 month")
```

# Table 1: Descriptive Characteristics

Excluding participants with no CGM data (27,30,38,41).

```{r table 1,echo=FALSE,results='asis'}
# Median for numerics
controls  <- tableby.control(numeric.stats=c("median", "q1q3"))
# Labels
labels <- list(demographics_t1d_duration = "Diabetes Dur. (years)", 
               demographics_ethnicity.factor = "Ethnicity",
               demographics_sex.factor = "Sex",
               demographics_cgmhx.factor = "CGM History", 
               demographics_pumphx.factor = "Pump History")
# Table 1
t1 <- tableby(~ demographics_age + demographics_t1d_duration + 
                demographics_sex.factor + demographics_ethnicity.factor +
                demographics_cgmhx.factor + demographics_pumphx.factor,
              data = demographics,control = controls)
# Print
summary(t1,labelTranslations = labels)
```

```{r clean CGM files,echo=FALSE,include=FALSE,eval=FALSE}
# Merge files and write CSVs with correct dates
# Files
cgm_files <- list.files("./Data_Raw/Project 2 - HCL Overnight Data Project_Zip/Project 2 - HCL Overnight Data Project",
                        recursive = T,full.names = T)
all_cgm <- data.frame()
# Clean all CGM files - this is extremely slow but only needs to be run once
for (file in cgm_files) {
  # Get ID
  id <- strsplit(file,"/")[[1]][5]
  if (id %in% no_data){
    next()
  }
  # Clean data
  table <- read.csv(file,stringsAsFactors = F,na.strings = "")
  sensor <- which(table$Patient.ID == "Sensor")[1]
  if (is.na(sensor)) {
    next()
  }
  table <- table[sensor:nrow(table),]
  colnames(table) <- as.character(table[2,])
  table <- table[which(!is.na(table$`Sensor Glucose (mg/dL)`) & 
                         table$Index != "Index"),]
  if (nrow(table) == 0) {
    next()
  }
  # Format columns
  table$timestamp <- lubridate::mdy_hms(paste(table$Date,table$Time))
  table$sensorglucose <- as.numeric(as.character(table$`Sensor Glucose (mg/dL)`))
  table$subjectid <- id
  table <- table[,c("subjectid","timestamp","sensorglucose")]
  table$timepoint <- NA
  # Get timepoints
  dates <- overnight_alarms[which(overnight_alarms$id == id),]
  # Baseline 
  start <- dates$start_date[dates$timepoint == "Baseline"]
  end <- dates$end_date[dates$timepoint == "Baseline"]
  table$timepoint[which(table$timestamp > start & table$timestamp <= end)] <- "Baseline"
  # week 2 
  start <- dates$start_date[dates$timepoint == "week 2"]
  end <- dates$end_date[dates$timepoint == "week 2"]
  table$timepoint[which(table$timestamp > start & table$timestamp <= end)] <- "week 2"
  # T1 
  start <- dates$start_date[dates$timepoint == "T1"]
  end <- dates$end_date[dates$timepoint == "T1"]
  table$timepoint[which(table$timestamp > start & table$timestamp <= end)] <- "T1"
  # T2 
  start <- dates$start_date[dates$timepoint == "T2"]
  end <- dates$end_date[dates$timepoint == "T2"]
  table$timepoint[which(table$timestamp > start & table$timestamp <= end)] <- "T2"
  # T3 
  start <- dates$start_date[dates$timepoint == "T3"]
  end <- dates$end_date[dates$timepoint == "T3"]
  table$timepoint[which(table$timestamp > start & table$timestamp <= end)] <- "T3"
  # T4 
  start <- dates$start_date[dates$timepoint == "T4"]
  end <- dates$end_date[dates$timepoint == "T4"]
  table$timepoint[which(table$timestamp > start & table$timestamp <= end)] <- "T4"
  # Remove readings with no time period
  table <- table[!is.na(table$timepoint),]
  # Add to big dataframe
  all_cgm <- rbind(all_cgm,table)
}
# Remove duplicates
all_cgm <- unique(all_cgm)
# Split and write CSVs
all_cgm <- split(all_cgm,list(all_cgm$subjectid,all_cgm$timepoint))
lapply(all_cgm,function(x){
  x <- as.data.frame(x)
  filename <- paste0("./Data_Cleaned/Cleaned CGM/",x$subjectid[1],"_",x$timepoint[1],".csv")
  write.csv(x,file = filename,row.names = F,na = "")
})
# CGM variables
cgmvariables("./Data_Cleaned/Cleaned CGM/","./Data_Cleaned",id_filename = T,outputname = "cgm_variables")
```

```{r cgm data,echo=FALSE,include=FALSE}
# Read in CGM data
cgm <- read.csv("./Data_Cleaned/cgm_variables.csv",stringsAsFactors = F)
# ID and timepoint
cgm$id <- sapply(strsplit(cgm$subject_id,"_"),`[[`,1)
cgm$timepoint <- sapply(strsplit(cgm$subject_id,"_"),`[[`,2)
cgm$timepoint <- factor(cgm$timepoint,levels = c("Baseline","week 2","T1","T2","T3","T4"))
# Select columns
cgm <- cgm %>% select(id,timepoint,nighttime_avg_sens_glucose,
                      percent_time_70_180_night,percent_time_under_70_night)
# Merge
overnight_alarms$id <- as.character(overnight_alarms$id)
overnight_alarms <- left_join(overnight_alarms,cgm,by = c("id","timepoint"))
# Write to CSV for SAS
overnight_alarms$log_num_nights <- log(overnight_alarms$num_nights)
write.csv(overnight_alarms,file = "./Data_Cleaned/alarms.csv",row.names = F,na = "")
```

# Longitudinal Analysis

## Histogram of Number of Alarms Per Day

```{r echo=FALSE}
overnight_alarms$alarms_per_day <- overnight_alarms$num_alarms / as.numeric(overnight_alarms$num_nights)
hist(overnight_alarms$alarms_per_day,main = "",xlab = "Number of Alarms")
# This looks very much like a Poisson distribution
```

## Plot

```{r echo=FALSE,warning=FALSE}
alarms_over_time <- 
  ggplot(overnight_alarms,aes(x = timepoint, y = alarms_per_day,group = id)) + 
  geom_line() + theme_bw()
alarms_over_time
```

## Model Results

```{r echo=FALSE, message=FALSE}
# Random intercept (not enough data for a random slope)
mod_ri_car1 <- glmmPQL(num_alarms ~ timepoint + perc_time_in_AM + 
                         offset(log(num_nights)),
                       random = ~1|id,data = overnight_alarms,
                       family = "poisson",
                       correlation = corCAR1(form = ~numeric_time))

results <- broom::tidy(mod_ri_car1,"fixed")
results$term <- c("(Intercept)","2 weeks","T1","T2","T3","T4","% Time in AM" )
results[,2:4] <- lapply(results[,2:4],function(x) round(x,3))
results$p.value <- format.pval(results$p.value,eps = 0.001)
kable(results)
```



# Questions

1. Did 39RS really have alarms in the 90s?
2. 8EG T3 - can I flip the dates?