---
title: "HCL and sleep: TIR and watch data"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tableone)
library(dplyr)
```

```{r echo=FALSE,include=FALSE}
source("T:\\Erin Cobry\\Prospective HCL and sleep study\\Data raw\\AdvancedHybridClosed-Demographics_R_2020-12-17_1648.r")
demo <- data
demo <- demo[!(demo$record_id %in% c(121,221)),]
demo_child <- subset(demo, record_id>=200)
demo_child$consent_date <- as.Date(as.character(demo_child$consent_date))
demo_adult <- subset(demo, record_id<200)
demo_adult$parent_bday <- as.Date(as.character(demo_adult$parent_bday))
# to calculate age, need to get consent date from child demo
consent <- demo_child %>% select(record_id, consent_date)
consent$record_id <- consent$record_id-100
demo_adult$consent_date <- NULL
demo_adult <- merge(demo_adult,consent,by="record_id",all.x=T,all.y = T)
demo_adult$age <- floor(((demo_adult$consent_date - demo_adult$parent_bday)/365.25))
demo_adult$age <- ifelse(demo_adult$age==0,NA,demo_adult$age)
demo_adult$parent_check_night <- as.numeric(demo_adult$parent_check_night)

source("T:\\Erin Cobry\\Prospective HCL and sleep study\\Data raw\\AdvancedHybridClosed-ATTDAbstracts2021_R_2020-12-17_1331.r")
data <- data[!(data$record_id %in% c(121,221)),]
child <- data[data$record_id>=200,]
adult <- data[data$record_id<200,]

# adult demo table
adult_demo_vars <- c("age","parent_gender.factor","race.factor","parent_check_night")
t1_adult <- CreateTableOne(data=demo_adult,vars=adult_demo_vars)
t1_adult <- print(t1_adult,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,nonnorm=c("age"),test = F)

# child demo table

```

# Background

# Methods

# Results


<br>

```{r, echo=FALSE, message=FALSE}
kable(t1,caption="Table 1. Demographics and clinical characteristics.")
```
