---
title: ""
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(performance)
library(knitr)
library(readxl)
library(lubridate)
library(table1)


# data upload
fakecarbs = read.csv("S:/Laura/BDC/Projects/Sarit Polsky/PICLS/Data_Clean/fake_carb_boluses.csv")
```

```{r functions, include = FALSE}
#  function to read sheet by sheet; from stack exchange
read_excel_allsheets <- function(filename, tibble = FALSE) {
    # I prefer straight data.frames
    # but if you like tidyverse tibbles (the default with read_excel)
    # then just pass tibble = TRUE
    sheets <- readxl::excel_sheets(filename)
    x <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
    if(!tibble) x <- lapply(x, as.data.frame)
    names(x) <- sheets
    x
}

# clean the gest dates data (we want the "rightmost column of dates" per sarit)
# currently the sheets have unnamed columns due to clinic notes or some other magic
clean_gd = function(df){
  df = df %>% select(-where(is.character)) %>% select(-where(is.logical))
  df
}


# function to get a date dataset and merge by dates
gest_df_clean = function(df){
  # x = subj_data %>% filter(ID == df)
  # select only gest week, day, and rightmost date col
  y = df %>% select(1,2,length(df))
  # get the last date column and rename it to "visit_date"
  y = y %>% mutate(visit_date = .[[3]]) %>% select(1,2,visit_date)
  return(y)
}


```

```{r data clean, include = FALSE}
# derive visit date from week and rand date
fakecarbs = fakecarbs %>% mutate(visit_date = mdy(Randomization.Date) + (7*Week.Num.))

# create reference lists
id_list = fakecarbs %>% select(ID) %>% unique() 
gest_dates = read_excel_allsheets("S:/Laura/BDC/Projects/Sarit Polsky/PICLS/Data_Raw/CURRENT_Gestational Age Calculator_v6 .xlsx")
#remove weird columns from gest dates
gest_dates = lapply(gest_dates, clean_gd)
gest_dates = keep(gest_dates, names(gest_dates) %in% id_list$ID)

# select "rightmost" column and gest week/day -> all subj down to 3 col
gest_dates = lapply(gest_dates, gest_df_clean)

# add id column to gestdates to combine later
gest_dates = lapply(seq(gest_dates), function(x) "[[<-"(gest_dates[[x]], paste0("ID"), value = names(gest_dates)[x]))

# combine into one reference df
gest_dates = Reduce(full_join,gest_dates)

# labor/delivery dates
d_dates = read.csv("S:/Laura/BDC/Projects/Sarit Polsky/PICLS/Data cleaning/CGM Data Check.csv") %>% mutate(ID = pid, deliverydate = mdy(Delivery.Date)) %>% select(ID, deliverydate)

# create analysis dataset and trimester var
analysis = left_join(fakecarbs, gest_dates) # joining on id and date -- perfectomundo
analysis = left_join(analysis, d_dates)
analysis = analysis %>% mutate(trimester = case_when(`Gestational Week` < 14 ~ "T1",
                                                    `Gestational Week` < 28 & `Gestational Week` >= 14 ~ "T2",
                                                    `Gestational Week`>= 28 & visit_date < deliverydate ~ "T3",
                                                    visit_date > deliverydate ~ "PP"))

analysis$trimester = factor(analysis$trimester, levels = c("T1", "T2", "T3", "PP"))
# 1st tri end: 13w6d, 2nd tri: 14w to 27w6d, 3rd tri: 28w until delivery

# metrics we interested in
analysis = analysis %>% mutate(ins_from_fc_percent = Total.Bolus.Volume.Associated.With.Fake.Carbs/Total.Bolus.Volume*100,
                               any_fc = ifelse(Total.Bolus.Volume.Associated.With.Fake.Carbs > 0, 1, 0))

# want % insulin from fake carbs (total bolus fake carbs/total bolus vol), avg per timepoint (trimesters)
# # bolus per week and avg per timepoint
# how many did/didnt put in fake carbs in each timepoint?
analysis_tri = analysis %>% group_by(ID, trimester) %>% summarise(mean_ins_from_fc_perc = mean(ins_from_fc_percent),
                                                   mean_weekly_bolus = mean(Number.of..Other..Events.With.Bolus),
                                                   visits_with_any_fc = sum(any_fc),
                                                   visits = length(ID)) %>% ungroup

```


```{r analysis, include = FALSE}
# table
analysis_tri_test = analysis_tri %>% filter(!is.na(trimester))
fct1 = table1(~ mean_ins_from_fc_perc + mean_weekly_bolus + visits_with_any_fc + visits | trimester, 
       data = analysis_tri_test)

# any fc
# check for subjects with no fake carbs whatsoever
no_fc_ids = analysis_tri_test %>% group_by(ID) %>% filter(sum(visits_with_any_fc) == 0) %>% summarise(ID, trimester) %>% unique()
# no fake carb put in by trimester
no_fc_tri = analysis_tri_test %>% filter(visits_with_any_fc == 0) %>% group_by(trimester) %>% summarise(no_inputted_fake_carbs=n())
```
# Data Remarks/Questions

# Methods
Subject visits were classified into Trimester. Variables were averaged within Subject-Trimester before aggregating into Trimester table.

# Analysis
## Fake Carbs by Trimester
```{r table1, echo=FALSE}
fct1
```


```{r did/nt fake carbs, echo = F}
print("No Fake Carbs inputted by Timepoint")
kable(no_fc_tri)
```