---
title: "High Risk Program"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tableone)
library(tidyverse)
library(nlme)
library(redcapAPI)
library(knitr)
# Check OS and alter file path accordingly.
if (.Platform$OS.type == "windows") {pathstart <- "//ucdenver.pvt/"} else if (.Platform$OS.type == "unix"){pathstart <- "/Volumes/"}
source("C:\\Users\\vigerst\\Documents\\GitHub\\Tim-and-Laura\\tim_R_functions.R")
```

```{r echo=FALSE,cache=TRUE}
# REDCap API data import
source("C:\\Users\\vigerst\\Documents\\GitHub\\BDC-Code\\api_tokens.R")
rcon <- redcapConnection(url = "https://redcap.ucdenver.edu/api/",
                         token = majidi_high_risk)
data_full <- exportRecords(rcon)
```

```{r echo=FALSE,include=FALSE}
dat <- data_full
dat$record_id <- as.character(dat$record_id)
# import start and end dates, merge with dat, fill down id columns
dates <- read.csv(paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Shideh Majidi/High Risk Program/data_Cleaned/StartEndDates.csv"))
dates <- dates %>% select(record_id,program_start_date,program_end_date,Gender)
dates$record_id <- as.character(dates$record_id)
dat <- left_join(dat,dates,by = "record_id") %>%
  fill(record_id,name,mrn,control,case_id,dob)
# Fix incorrect visit date.
dat$visitdate[which(dat$visitdate == "2006-04-01")] <- "2016-04-01"
# Re-format columns
dat$Gender <- as.factor(dat$Gender)
dat$a1c <- as.numeric(dat$a1c)
dat$visitdate <- lubridate::ymd(as.character(dat$visitdate))
dat$dob <- lubridate::ymd(as.character(dat$dob))
dat$program_start_date <- lubridate::mdy(as.character(dat$program_start_date))
dat$program_end_date <- lubridate::mdy(as.character(dat$program_end_date))
dat$case_id <- as.factor(dat$case_id)
dat$control <- as.factor(dat$control)
dat$sw <- as.character(dat$sw)
dat$lowbg <- as.numeric(dat$lowbg)
dat$targetbg <- as.numeric(dat$targetbg)
dat$highbg <- as.numeric(dat$highbg)
dat$hospitalbefore <- as.numeric(dat$hospitalbefore)
dat$hosp_dur <- as.numeric(dat$hosp_dur)
dat$hospitalpost <- as.numeric(dat$hospitalpost)
dat$nsbefore <- as.numeric(dat$nsbefore)
dat$ns_dur <- as.numeric(dat$ns_dur)
dat$nspost <- as.numeric(dat$nspost)
dat$cancelbefore <- as.numeric(dat$cancelbefore)
dat$cancel_dur <- as.numeric(dat$cancel_dur)
dat$cancelpost <- as.numeric(dat$cancelpost)
# Remove participants with unverifiable BGs
incorrect.bgs <- read.csv(paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Shideh Majidi/High Risk Program/data_Cleaned/NotVerifiedBG.csv"))
incorrect.bgs$Record.ID <- as.character(incorrect.bgs$Record.ID)
dat <- dat %>%
  filter(!(record_id %in% incorrect.bgs$Record.ID))
# Calculate days between visits, age, t1d duration. Find those with complete dat.
dat <- dat %>% 
  arrange(record_id) %>%
  group_by(record_id) %>%
  mutate(days = visitdate - lag(visitdate)) %>%
  mutate(Age = round(as.numeric(difftime(visitdate,dob,units = "days")/365.2425),3)) %>%
  mutate(T1Dyears = round(as.numeric(difftime(dx,dob,units = "days")/365.2425),3)) %>%
  mutate(base_a1c = a1c[2]) %>%
  mutate(complete = length(which(!is.na(visitdate))))
```

```{r echo=FALSE}
# Match each case to 1 control
match <- dat %>%
  group_by(record_id) %>%
  filter(row_number()==1)
match$treat <- ifelse(match$control == "No",1,0)
# find those with most dat
match <- match %>%
  group_by(case_id,treat) %>%
  filter(complete == max(complete)) %>%
  arrange(case_id,desc(treat))
# Remove case ID groups without only controls. If two controls are tied for 
# amount of dat, use baseline A1c as a tiebreaker.
match <- match %>%
  group_by(case_id) %>%
  mutate(a1c_diff = abs(base_a1c - base_a1c[1])) %>% 
  filter(n() > 1) %>%
  slice(c(1,which(a1c_diff == min(a1c_diff[2:n()])))) %>%
  arrange(case_id,treat)
# 4 cases were excluded based on unverifiable BG values, 
# so should be 31 cases and 31 controls.

# Remove all unnecessary controls and blank rows
dat <- dat %>%
  filter(record_id %in% match$record_id) %>%
  filter(!is.na(visitdate) | redcap_event_name == "event_1_arm_1")
# Record ID as factor
dat$record_id <- as.factor(as.numeric(dat$record_id))
```

<!-- # Background -->

<!-- The purpose of this analysis is to test whether the high risk program was successful in improving diabetes outcomes.  Outcomes of interest include frequency of visits, rates of no shows and cancellations, and measurements of glycemia. -->

<!-- # Methods -->

<!-- Participants who completed at least 5 visits were matched to controls.  Length of participation in the program varied, so for each participant, the same amount of time before and after the program was included in the analysis.   -->

<!-- For each outcome, the means before, during, and after the program were compared in participants and controls using linear mixed effects models.   -->

<!-- The rate of change (slopes) of each outcome was compared in participants and controls using interrupted time series models.  These models estimated the slopes during two time periods, and then compared the slopes between participants and controls.  Therefore, separate models were run for each of the three pairwise comparisons of time periods (before vs. during, during vs. after, and before vs. after).   -->

<!-- # Results -->

<!-- Table 1 shows descriptive statistics at baseline in participants and controls. -->

<!-- Comparisons of mean outcomes in participants and controls during the period before the intervention are shown in Table 2a.  Comparisons during the program are shown in Table 2b, and after the program are shown in Table 2c. -->

<!-- Each interrupted time series model (corresponding to one outcome and comparison of two time periods) is summarized in a separate table.  The estimates in the tables can be interpreted as in the following example: -->

<!-- - "Intercept: control" - this is the estimated value of the outcome in the controls at the earliest time period included in the model -->
<!-- - "Intercept: case" - this is the estimated value of the outcome in the participants at the earliest time period included in the model -->
<!-- - "Intercept: case-control" - this is the difference in the intercepts in the cases and participants -->
<!-- - "Slope(time) before k: control" - this is the estimate of the slope in the controls before the intervention -->
<!-- - "Slope(time) before k: case" - this is the estimate of the slope in the participants before the intervention -->
<!-- - "Slope(time) before k: case-con" - this is the difference in the slopes in the participants and controls before the intervention -->
<!-- - "Slope(time) after k: control" - this is the estimate of the slope in the controls after the intervention -->
<!-- - "Slope(time) after k: case" - this is the estimate of the slope in the participants after the intervention -->
<!-- - "Slope(time) after k: case-con" - this is the difference in the slopes in the participants and controls after the intervention -->
<!-- - "Slope(time) change k: control" - this is the estimate of the change in the slope (during-before) in controls -->
<!-- - "Slope(time) change k: case" - this is the estimate of the change in the slope (during-before) in participants -->
<!-- - "Slope(time) change k: case-con" - this is the estimate of the difference in the change in slopes between participants and controls -->

<!-- After the tables summarizing each of the interrupted time series models, there are figures which show the longitudinal trajectories of the outcomes over time, with regression lines for participants and controls superimposed. -->

```{r echo=FALSE,include=FALSE}
# Format data table
t1vars <- c("Age","T1Dyears","a1c","hospitalbefore","hosp_dur","hospitalpost",
            "nsbefore","ns_dur","nspost","cancelbefore","cancel_dur",
            "cancelpost","Gender","race_ethnicity","insurance","treatment___1",
            "treatment___2","treatment___3")
demos1 <- filter(dat, redcap_event_name == "event_1_arm_1") %>% 
  select("record_id","treatment___1","treatment___2","treatment___3",t1vars[-c(1,3)])
demos2 <- filter(dat, redcap_event_name == "event_2_arm_1") %>%
  select("record_id","control","case_id","a1c","Age")
demos <- merge(demos1,demos2, by = "record_id") %>%
  arrange(case_id,control)
# Make table 1
t1 <- CreateTableOne(t1vars,strata = "control",dat = demos,
                     testNonNormal = wilcox.test,
                     argsNonNormal = list(paired = TRUE),
                     testNormal = t.test,
                     argsNormal = list(paired = TRUE))

t1 <- print(t1,exact = c("insurance","race_ethnicity","treatment___3"),
            nonnormal = norm.check(demos,t1vars[1:12]))
```

### Table 1: Descriptive Statistics at Baseline Stratified by Group

```{r echo=FALSE}
kable(t1[,1:3])
```

```{r echo=FALSE}
# Add timepoint based on visit date, remove unnecessary rows.
dat$timepoint <- ifelse(dat$visitdate <= dat$program_start_date,"Before",
                         ifelse(dat$visitdate > dat$program_start_date & 
                                  dat$visitdate <= dat$program_end_date,"During","After"))
dat$timepoint <- factor(dat$timepoint,levels = c("Before","During","After"))
dat$record_id <- as.factor(dat$record_id)
dat$case_id <- as.factor(dat$case_id)
# Filter out rows with just demographic information
mixed <- dat %>% filter(!is.na(visitdate))
plot_mixed <- mixed %>%
  group_by(record_id,timepoint) %>%
  summarise(a1c = mean(a1c,na.rm = T),case_id = case_id[1],control = control[1])
# plot A1c by timepoint
plot <- ggplot(plot_mixed, aes(x=timepoint,y = a1c,group = record_id))+
  geom_line(aes(color = control)) +
  ylab("Average HbA1c") +
  xlab("Timepoint")
# Mixed model selection for A1c by timepoint
a1c_mod <- lme(a1c ~ timepoint * control,random=~1+record_id|case_id,dat = mixed,na.action = na.omit) # Not enough observations
```

### Figure 1: Average HbA1c by Timepoint
```{r echo=FALSE}
plot
```

### Table 2: Mixed Model with Random Intercep for Subject and Random Slope for Case ID
```{r echo=FALSE}
summary(a1c_mod)
summary(a1c_mod_2)
```
