---
title: "SEEDS Provider Survey Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,fig.width = 12,fig.height = 12,warning = FALSE)
library(redcapAPI)
library(Hmisc)
library(arsenal)
library(tidyverse)
library(performance)
library(usmap)
library(reshape2)
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects/Laurel Messer/SEEDS"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Laurel Messer/SEEDS"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Laurel Messer/SEEDS"
}
knitr::opts_knit$set(root.dir = home_dir)
rm(home_dir)
```

```{r include=FALSE}
api = read.table("./Data_Raw/api_token.txt")
rcon <- redcapConnection(url="https://redcap.ucdenver.edu/api/", token=api[1,1])
data = exportRecords(rcon)
```

```{r}
# Filter
data = data %>% filter(real_record == "Real")# Remove bots
# Change specialty types per Laurel
data$specialty[which(data$otherspecialty == "Pediatric Diabetology")] = "Pediatric Endocrinology"
data$specialty[which(data$otherspecialty == "Adult Gerontology Primary Care")] = 
  "Primary care-family medicine"
# Combine levels 
levels(data$specialty) = c("Primary Care","Primary Care","Primary Care","Primary Care",
                                  "Pediatric Endocrinology","Adult Endocrinology","Other")
levels(data$providertype) = c("Prescriber","Prescriber","Non-Prescriber",
                              "Prescriber","Non-Prescriber","Other")
# Drop "Other" providers
data = data %>% filter(specialty != "Other")
# Drop levels for categorical variables
cat_vars = c("gender","race","providertype","specialty","practicesetting",
             "medicare","medicaid","privateins","uninsured")
data[,cat_vars] = lapply(data[,cat_vars],droplevels)
# Continuous variables for table 1
con_vars = c("age","practiceyears","cgmpatientratio","pumppatientratio",
             "penpatientratio","hclpatientratio","educationtime")
```

# Table 1: Participant Characteristics

```{r results='asis'}
f = as.formula(paste0("specialty~",paste0(con_vars,collapse = "+"),"+",
                      paste0(cat_vars,collapse = "+")))
t1 = tableby(f,data = data)
summary(t1,pfootnote = T,labelTranslations = 
          list(age = "Age", practiceyears = "Practice Years",gender = "Gender",
               race = "Race",providertype = "Provider Type",
               practicesetting = "Practice Setting",
               medicare = "Medicare",medicaid = "Medicaid",
               privateins = "Private Insurance",
               uninsured = "No Insurance",educationtime = "Education Time",
               cgmpatientratio = "% on CGM",
               penpatientratio = "% on Smart Pen",hclpatientratio = "% on HCL",
               pumppatientratio = "% on Pump"))
```

# Respondents by State

```{r}
states = us_map(regions = "states")
state_count = data %>% count(practicestate) %>% 
  rename(state = "practicestate") 
plot_usmap(data = state_count, values = "n") + 
  scale_fill_continuous(name = "n")
kable(state_count %>% arrange(desc(n)))
```

# Online Diabetes Device Pathway Tools

```{r}
plot_df = data %>% select(record_id,specialty,deviceselectiontool:consulttool)
tools = colnames(plot_df)[3:ncol(plot_df)]
plot_df = melt(plot_df,id.vars = c("record_id","specialty"))
ggplot(plot_df,aes(x = variable,y = value,fill = specialty)) + 
  geom_boxplot(alpha = 0.5,width=0.5) +
  theme_bw() + xlab("Variable") + ylab("VAS Score") + 
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5, hjust=1)) + 
  scale_fill_discrete(name = "Specialty")
```

```{r}
ggplot(plot_df,aes(x = variable,y = value,fill = variable)) + 
  geom_boxplot(alpha = 0.5) +
  theme_bw() + xlab("Variable") + ylab("VAS Score") + 
  theme(axis.text.x = element_blank(),axis.ticks.x = element_blank()) + 
  facet_wrap(~specialty)
```

```{r}
old <- levels(plot_df$variable)
new <- c("Device Selection Tool","Insurance Coverage Tool","Automated Decision Support",
    "Online Data Platform","Device Training Contacts","Patient Education Modules",
    "Device Troubleshooting","Consultation With Expert")
order = plot_df %>% group_by(variable) %>% 
  summarise(m = median(value,na.rm = T)) %>% arrange(desc(m))
order$name = new[match(order$variable,old)]

plot_df$variable = factor(plot_df$variable,levels = order$variable,labels = order$name)

ggplot(plot_df,aes(x = variable,y = value,fill = specialty)) + 
  geom_boxplot(alpha = 0.5) +
  theme_bw() + xlab("Variable") + ylab("VAS Score") + 
  theme(axis.text.x = element_blank(),axis.ticks.x = element_blank(),
        axis.title.x = element_blank()) + 
  facet_wrap(~variable,scales = "free",strip.position = "bottom") +
  theme(legend.position = c(0.85,0.15),legend.key.size = unit(2, 'cm'),
        strip.text = element_text(size=20)) + 
  labs(fill = "Specialty")
```

## Tools Tables

```{r results='asis'}
labels(data[,tools]) = NULL
f = as.formula(paste0("specialty~",paste0(tools,collapse = "+")))
t = tableby(f,data = data,
            control = list(numeric.stats=c("N", "median", "q1q3")))
summary(t)
```
