---
title: "SEEDS Bot Hunting"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(lubridate)
library(DT)
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
rm(home_dir)
```

```{r}
df = read.csv("./Laurel Messer/SEEDS/Data_Cleaned/Complete_data_1-12-2022.csv",na.strings = "")
```

# Summary

```{r results='asis'}
# Time at end of consent to time at end of survey
df$time = difftime(mdy_hm(df$Survey.Timestamp.1),
                   mdy_hm(df$Survey.Timestamp),units = "mins")
# Table
t1 = tableby(~notest(time,"Nmiss","median","q1q3"),df)
summary(t1)
```

## Time < Q1

```{r}

```

# Matching names to email

```{r}
emails = tolower(sub("@.*","",df$Email.address))
names = tolower(paste0(df$First.name,df$Last.name))
initials = tolower(paste0(substr(df$First.name,1,1),substr(df$Last.name,1,1)))
```
