---
title: "Title"
author: "Laura Pyle & Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
    theme:
      light: flatly
      dark: darkly
bibliography: /Users/timvigers/Dropbox/Miscellaneous/zotero.bib
csl: /Users/timvigers/Dropbox/Miscellaneous/american-medical-association.csl
editor: source
---

```{r setup}
#| include: false
library(tidyverse)
library(clusterProfiler)
library(ReactomePA)
library(org.Hs.eg.db)
library(biomaRt)
knitr::opts_knit$set(root.dir = "~/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/BDC/Janet Snell-Bergeon/CACTI DCCT EDIC omics R01")
```

```{r data cleaning}
# Import results
res <- read.csv("Proteomics/Reports/DCCT EDIC CARV.csv", na.strings = "")
# Import annotations
load("./Data_Raw/annotations.RData")
# Add to dataframe
res$entrez <- protein_anotation$Entrez[match(res$protid, protein_anotation$UniProt)]
unadjusted <- res[, c("logFC", "entrez")]
names(unadjusted) <- res$entrez
unadjusted <- unadjusted[!is.na(names(unadjusted))]
# GSEA
y <- gsePathway(unadjusted, pvalueCutoff = 1, pAdjustMethod = "BH", verbose = FALSE)
```

# Protein-to-gene linkage

We used the `biomaRt` R package to link UniProt IDs to Entrez Gene IDs, based on Ensembl's most recent version of the Human Genes BioMart. A total of `r sum(is.na(res$entrez))` proteins were not linked to an Entrez ID.

See `~/GitHub/BDC-Code/Janet Snell-Bergeon/DCCT and EDIC/create_omics_linkage_file.R` for additional documentation.

# Table

```{r}
#| label: tbl-planets
#| tbl-cap: Planets
```

# Figure

```{r}
#| label: fig-planets
#| fig-cap: Planets
```
