---
title: "DCCT/EDIC"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_knit$set(root.dir = "T:/Janet Snell-Bergeon/CACTI DCCT EDIC omics R01/")
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/CACTI DCCT EDIC omics R01")
library(arsenal)
library(skimr)
library(knitr)
library(tidyverse)
library(caret)
library(limma)
library(tableone)
library(mixOmics)
```

```{r, echo=FALSE, warning=FALSE}

# getting weird errors from plsda and lasso - is something weird about the data?
# top 20 hits from 2nd component lists all proteins
# need to merge in protein descriptions

# Study information
#df = read.delim("T:/Janet Snell-Bergeon/CACTI DCCT EDIC omics R01/Raw data/QEDIC_WP_DDA_60SPD_StudyInformat.txt")
# Convert to categorical

# Janet merged in correct age and diabetes duration at the metabolomics visit
#df <- read.csv("T:/Janet Snell-Bergeon/CACTI DCCT EDIC omics R01/Raw data/QEDIC_WP_DDA_60SPD_StudyInformat.csv")
df <- read.csv("./Raw data/QEDIC_WP_DDA_60SPD_StudyInformat.csv")
# Proteins
#prot = read.delim("T:/Janet Snell-Bergeon/CACTI DCCT EDIC omics R01/Raw data/EDIC_WP_DDA_60SPD_Proteins.txt")
prot = read.delim("./Raw data/EDIC_WP_DDA_60SPD_Proteins.txt")
rownames(prot) = prot$Accession
X = prot[,grep("Normalized",colnames(prot))]
colnames(X) = sub("Abundances..Normalized...","",colnames(X))
colnames(X) = sub("..Sample","",colnames(X))
# Transpose proteins, log transform, and remove low variance items
X = as.data.frame(t(X))
no_var = caret::nearZeroVar(X)
X = X[,-c(no_var)]
X = log(X)
X$File.ID = rownames(X)
df = left_join(df,X,by = "File.ID")
# Clean up workspace
rm(X)

# looking at number of missing values
testprot <- prot
testprot$nmiss <- NA
testprot$nmiss <- apply(testprot, 1, function(x) sum(is.na(x)))
# some proteins are missing in 50 participants but that doesn't seem problematic

protnames <- row.names(prot)
nmiss_row <- apply(df[,names(df) %in% protnames],1,function(x) sum(is.na(x)))
# some people are missing 60-70 proteins but that doesn't seem problematic

# descriptive statistics
# VisitAge VisitDuration SEX BMI00	DBP00	SBP00	AER00	CHL00	TRG00	HDL00	LDL00 SMOKE00
# not sure which variable corresponds to baseline HbA1c
df$SMOKE00 <- as.factor(df$SMOKE00)
t1_vars <- c("VisitAge","VisitDuration","SEX","BMI00","DBP00","SBP00","AER00","CHL00","TRG00","HDL00","LDL00","SMOKE00")
t1 <- CreateTableOne(data=df,vars=t1_vars,strata = "CARV")
t1 <- print(t1,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = T)

# create contrast for CVD events
cvd_contrast <- ifelse(df$CARV==1,1,0)
cvd_contrast <- cbind(rep(1,nrow(df)),cvd_contrast)

# pull out the proteins and transpose for limma
ymat <- t(df[,names(df) %in% protnames])
# model for T1D vs. control
fit_cvd <- lmFit(ymat,cvd_contrast)
fit_cvd <- eBayes(fit_cvd)
# format results
results_cvd <- topTable(fit_cvd,coef = 2,number = nrow(ymat))
desc <- as.data.frame(prot[,"Description"])
desc$protid <- row.names(prot)
colnames(desc) <- c("Description","protid")
results_cvd$protid <- row.names(results_cvd)
results_cvd <- merge(results_cvd,desc,by="protid",all.x=T,all.y = T)
results_cvd <- results_cvd[order(results_cvd$adj.P.Val),] 
#write.csv(results_cvd,"B:\\Projects\\Janet Snell-Bergeon\\CACTI DCCT EDIC omics R01\\Reports\\DCCT EDIC CARV.csv")
write.csv(results_cvd,"./Reports/DCCT EDIC CARV.csv")
# need to adjust for tx
cvd_contrast_adj <- model.matrix(~CARV + GROUP , data=df)
fit_cvd_adj <- lmFit(ymat,cvd_contrast_adj)
fit_cvd_adj <- eBayes(fit_cvd_adj)
# format results
results_cvd_adj <- topTable(fit_cvd_adj,coef = 2,number = nrow(ymat))
results_cvd_adj$protid <- row.names(results_cvd_adj)
results_cvd_adj <- merge(results_cvd_adj,desc,by="protid",all.x=T,all.y = T)
results_cvd_adj <- results_cvd_adj[order(results_cvd_adj$adj.P.Val),] 
#write.csv(results_cvd_adj,"B:\\Projects\\Janet Snell-Bergeon\\CACTI DCCT EDIC omics R01\\Reports\\DCCT EDIC CARV adjusted GROUP.csv")
write.csv(results_cvd_adj,"./Reports/DCCT EDIC CARV adjusted GROUP.csv")

# adjust for sex, age, and duration
cvd_contrast_adj2 <- model.matrix(~CARV + GROUP + VisitAge + SEX + VisitDuration , data=df)
fit_cvd_adj2 <- lmFit(ymat,cvd_contrast_adj2)
fit_cvd_adj2 <- eBayes(fit_cvd_adj2)
# format results
results_cvd_adj2 <- topTable(fit_cvd_adj2,coef = 2,number = nrow(ymat))
results_cvd_adj2$protid <- row.names(results_cvd_adj2)
results_cvd_adj2 <- merge(results_cvd_adj2,desc,by="protid",all.x=T,all.y = T)
results_cvd_adj2 <- results_cvd_adj2[order(results_cvd_adj2$adj.P.Val),] 
#write.csv(results_cvd_adj2,"B:\\Projects\\Janet Snell-Bergeon\\CACTI DCCT EDIC omics R01\\Reports\\DCCT EDIC CARV adjusted GROUP VisitAge SEX Visit Duration.csv")
write.csv(results_cvd_adj2,"./Reports/DCCT EDIC CARV adjusted GROUP VisitAge SEX Visit Duration.csv")
# sensitivity analysis excluding the outliers on PCA
outliers <- c("F205","F233","F26","F169","F36","F171")
sens <- df[!df$File.ID %in% outliers,]
cvd_contrast_adj_sens <- model.matrix(~CARV + GROUP + VisitAge + SEX + VisitDuration , data=sens)
ymat_sens <- t(sens[,names(sens) %in% protnames])
fit_cvd_adj_sens <- lmFit(ymat_sens,cvd_contrast_adj_sens)
fit_cvd_adj_sens <- eBayes(fit_cvd_adj_sens)
# format results
results_cvd_adj_sens <- topTable(fit_cvd_adj_sens,coef = 2,number = nrow(ymat))
results_cvd_adj_sens$protid <- row.names(results_cvd_adj_sens)
results_cvd_adj_sens <- merge(results_cvd_adj_sens,desc,by="protid",all.x=T,all.y = T)
results_cvd_adj_sens <- results_cvd_adj_sens[order(results_cvd_adj_sens$adj.P.Val),] 
#write.csv(results_cvd_adj_sens,"B:\\Projects\\Janet Snell-Bergeon\\CACTI DCCT EDIC omics R01\\Reports\\DCCT EDIC CARV adjusted GROUP VisitAge SEX Visit Duration sensitivity analysis excluding outliers.csv")
write.csv(results_cvd_adj_sens,"./Reports/DCCT EDIC CARV adjusted GROUP VisitAge SEX Visit Duration sensitivity analysis excluding outliers.csv")
# write file for LASSO regression
lasso <- df[,names(df) %in% c(protnames,"CARV","VisitAge","SEX","VisitDuration")]
#write.csv(lasso,"B:\\Projects\\Janet Snell-Bergeon\\CACTI DCCT EDIC omics R01\\Clean data\\lasso.csv",row.names = F)
write.csv(lasso,"./Clean data/lasso.csv",row.names = F)
# sPLS-DA
plsda_carv <- splsda(df[,names(df) %in% protnames], Y=as.factor(df$CARV),ncomp = 2)

plsda_sens <- splsda(sens[,names(sens) %in% protnames], Y=as.factor(sens$CARV),ncomp = 2)

```

```{r, echo=FALSE}
kable(t1,caption="Descriptive statistics by CARV")
```

# Individual plot from sPLS-DA by CARV

```{r, echo=FALSE}
plotIndiv(plsda_carv, comp = c(1,2),
          ind.names = FALSE, 
          ellipse = TRUE, legend = TRUE, title="")
```

```{r, echo=FALSE,eval=FALSE}
# I have no idea why top_2 is retaining all the proteins.  Also need to merge in the protein names
plsda_carv_20 <- splsda(df[,names(df) %in% protnames], Y=as.factor(df$CARV),ncomp = 2,keepX = c(20,20))
top_1 <- selectVar(plsda_carv_20,comp=1)
top_2 <- selectVar(plsda_carv_20,comp=2)
```

# Ranking of top 20 proteins in terms of discrimination of CARV, for component 1

```{r, echo=FALSE,eval=FALSE}
top_1$value
```

# Ranking of top 20 proteins in terms of discrimination of CARV, for component 2

```{r, echo=FALSE,eval=FALSE}
top_2$value
```

```{r, echo=FALSE,eval=FALSE}
set.seed(3654)
plsda.perf = perf(plsda_carv0, validation = 'Mfold', folds = 3, 
                             progressBar = FALSE, nrepeat = 10, dist = 'max.dist',auc=TRUE)
# trying to tune parameters
tune <- tune.splsda(df[,names(df) %in% protnames], Y=as.factor(df$CARV),ncomp = 4,validation = 'Mfold',
                                 folds = 3, dist = 'max.dist', progressBar = FALSE,
                                 measure = "BER", nrepeat = 10)

# try with LOO instaed of mfold CV
plsda.perf = perf(plsda_carv, validation = 'loo', progressBar = FALSE, auc=TRUE)
auc_save <- plsda.perf$auc$`comp1`[1]    
auc_true <- as.numeric(plsda.perf$auc$comp1["AUC.mean"])
```

```{r plsda,cache=TRUE, warning=FALSE,eval=FALSE}
# Permutation testing - takes forever, make sure to cache
# n_perm <- 1000
# aucs <- vector(mode="numeric", length=n_perm)
# for (i in 1:n_perm) {
#   Y <- sample(as.factor(df$CARV),replace = F)
#   plsda_res <- plsda(df[,names(df) %in% protnames],Y,ncomp = 1)
#   perf_plsda <- perf(plsda_res,progressBar=FALSE, auc=TRUE,
#                    validation = "loo")
#   aucs[i] <- as.numeric(perf_plsda$auc$comp1["AUC.mean"])
# }
# ggplot(as.data.frame(aucs),aes(x=aucs)) + 
#   geom_histogram(binwidth = 0.01) + 
#   geom_vline(aes(xintercept=auc_true),color="red") + 
#   theme_bw() + xlab("AUC")
```

# Individual plot from sPLS-DA by CARV after excluding outliers

```{r, echo=FALSE}
plotIndiv(plsda_sens, comp = c(1,2),
          ind.names = FALSE, 
          ellipse = TRUE, legend = TRUE, title="")
```

