---
title: "EDIC Lipidomics"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_knit$set(root.dir = "Z:/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/EDIC/Lipidomics")
knitr::opts_knit$set(root.dir = "~/Documents/Work/Janet Snell-Bergeon/EDIC/Lipidomics")
library(PCAtools)
library(readxl)
library(tidyverse)
library(limma)
library(knitr)
```

```{r include=FALSE}
# Import
intensities = read.csv("./Data_Raw/EDIC lipidomics data matrix_Skyline_2021.02.25.csv",stringsAsFactors = F)
# Get compound info in separate frame
compound_info = intensities[,"LipidSpecies"]
intensities$LipidSpecies = NULL
# Transpose and format
intensities = as.data.frame(t(intensities))
names(compound_info) = colnames(intensities)
intensities$sample_id = gsub("\\.","-",rownames(intensities))
intensities = intensities %>% select(sample_id,everything())
intensities[,2:ncol(intensities)] = lapply(intensities[,2:ncol(intensities)],function(c){log(as.numeric(c))})
# Import sample injection order
injection_order = read_excel("./Data_Raw/EDIC lipidomics run order.xlsx")
colnames(injection_order) = "sample_id"
injection_order$sample_id = sub("QC-EDIC","EDIC-QC",injection_order$sample_id)
injection_order$sample_id[is.na(injection_order$sample_id)] = paste0("Failed-QC-",1:sum(is.na(injection_order$sample_id))) # For now assume that the missing are QCs
injection_order$injection_order = 1:nrow(injection_order)
# Batch information
batches = diff(c(0,grep("QC",injection_order$sample_id),nrow(injection_order)))
injection_order$batch = rep(1:length(batches),times = batches)
# Remove duplicates and QC for now
injection_order = injection_order[-c(which(duplicated(injection_order$sample_id)),grep("Failed-QC",injection_order$sample_id)),]
# Get sample info
sample.info = read.csv("./Data_Raw/QEDIC_WP_DDA_60SPD_StudyInformat.csv")
# Get sample IDs, add leading zeroes and "EDIC" to number
sample.info$sample_id = sample.info$ProteomicsSampleID
sample.info$sample_id = paste0("EDIC-",str_pad(sample.info$sample_id,3,"left",0))
sample.info = sample.info %>% select(sample_id,everything())
# Combine
sample.info = merge(injection_order,sample.info,all = T,by = "sample_id")
sample.info = sample.info[order(sample.info$injection_order),]
# Try two batches
sample.info$batch2 = ifelse(sample.info$batch < 6,1,2)
# Plot by HARD status
sample.info$class = sample.info$HARD
sample.info$class[which(is.na(sample.info$class))] = "QC"
sample.info$class = factor(sample.info$class)
# Column names
colnames(intensities)[2:ncol(intensities)] = compound_info
```

# Moderated T Tests

## CARV

### All

```{r results='asis'}
# limma stratified by storage time
sample.info$storage_time = sample.info$VisitAge - sample.info$AGE00
sample.info$storage_time = cut(sample.info$storage_time,2,labels = c("< 14",">= 14"))
low = sample.info[sample.info$storage_time=="< 14",]
high = sample.info[sample.info$storage_time==">= 14",]
# Make design matrix
carv <- model.matrix(~CARV,sample.info[!is.na(sample.info$storage_time),])
# Unadjusted models
y <- t(intensities[intensities$sample_id %in% sample.info[!is.na(sample.info$storage_time),"sample_id"],2:ncol(intensities)])
fit <- lmFit(y,carv)
fit <- eBayes(fit)
# Results
kable(topTable(fit,coef = 2))
```

### Stratified by Above or Below Median Storage Time

```{r results='asis'}
# Make design matrices
carv_low <- model.matrix(~CARV,low)
carv_high <- model.matrix(~CARV,high)
# Unadjusted models
y_low <- t(intensities[intensities$sample_id %in% low$sample_id,2:ncol(intensities)])
y_high <- t(intensities[intensities$sample_id %in% high$sample_id,2:ncol(intensities)])
fit_low <- lmFit(y_low,carv_low)
fit_low <- eBayes(fit_low)
fit_high <- lmFit(y_high,carv_high)
fit_high <- eBayes(fit_high)
# Results
kable(topTable(fit_low,coef = 2),caption = "Low Storage Time")
kable(topTable(fit_high,coef = 2),caption = "High Storage Time")
```

## HARD

### All

```{r results='asis'}
# Make design matrix
hard <- model.matrix(~HARD,sample.info[!is.na(sample.info$storage_time),])
# Unadjusted models
y <- t(intensities[intensities$sample_id %in% sample.info[!is.na(sample.info$storage_time),"sample_id"],2:ncol(intensities)])
fit <- lmFit(y,hard)
fit <- eBayes(fit)
# Results
kable(topTable(fit_low,coef = 2))
```

### Stratified by Above or Below Median Storage Time

```{r results='asis'}
# Make design matrices
hard_low <- model.matrix(~HARD,low)
hard_high <- model.matrix(~HARD,high)
# Unadjusted models
y_low <- t(intensities[intensities$sample_id %in% low$sample_id,2:ncol(intensities)])
y_high <- t(intensities[intensities$sample_id %in% high$sample_id,2:ncol(intensities)])
fit_low <- lmFit(y_low,hard_low)
fit_low <- eBayes(fit_low)
fit_high <- lmFit(y_high,hard_high)
fit_high <- eBayes(fit_high)
# Results
kable(topTable(fit_low,coef = 2),caption = "Low Storage Time")
kable(topTable(fit_high,coef = 2),caption = "High Storage Time")
```
