---
title: "670G Obs. ATTD 2019"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
library(tableone)
library(skimr)
library(knitr)
library(tidyverse)
```

```{r define functions,include=FALSE}
fill_NAs <- function(data,threshold,idcols) {
  na_thresh <- ceiling(threshold * ncol(data))-length(idcols) # Determine max NAs
  data <- data[rowSums(is.na(data)) < na_thresh,] # Remove rows with NAs over max
  k <- which(is.na(data), arr.ind=TRUE) # Find remaining NAs
  if(length(k)>0) {
    data[k] <- rowMeans(data[,colnames(data)[-idcols]],na.rm = T)[k[,1]] # Replace with means
  }
  data
}
```

```{r data import and formatting,echo=FALSE,include=FALSE}
# Import
source("./Cari Berget/ATTD Abstract 2019/Data_Cleaned/AdvancedClosedLoopCl_R_2019-09-30_1049.r")
# A1c as numeric
data$hba1c <- as.numeric(as.character(data$hba1c))
data$hba1c_baseline <- as.numeric(as.character(data$hba1c_baseline))
# Subjects who withdrew (per Cari)
withdrawn <- c("41","50")
# Demographics
demographics <- data %>% 
  filter(redcap_event_name %in% c("baseline_arm_1","baseline_arm_2"),
         !is.na(automode_start),!(record_id %in% withdrawn)) %>%
  select(record_id,demographics_dob,demographics_diabetesdx,automode_start,hba1c_date_b,
         hba1c_baseline,demographics_sex.factor,demographics_race.factor,demographics_ethnicity.factor,
         demographics_insurance.factor,demographics_cgmhx.factor,demographics_pumphx.factor) %>%
  mutate(age_at_am_start = round(as.numeric((difftime(automode_start,demographics_dob,units = "days"))/365.25),2),
         t1d_duration_at_am_start = round(as.numeric((difftime(automode_start,demographics_diabetesdx,units = "days"))/365.25),2))
# Survey data
# Young adults
# PAID
ya_paid <- data %>% select(record_id,redcap_event_name,ya_paid1:ya_paid20)
ya_paid <- fill_NAs(ya_paid,0.75,1:2)
# Score
ya_paid <- ya_paid %>% group_by(record_id,redcap_event_name) %>% 
  summarise(paid_score = (sum(ya_paid1:ya_paid20))*1.25)
# Get baseline and followup HFS scores
ya_hfs_b <- data %>% select(record_id,redcap_event_name,
                            ya_hfs_b_behave1:ya_hfs_b_behave15,
                            ya_hfs_b_worry16:ya_hfs_b_worry33) %>% 
  filter(redcap_event_name == "baseline_arm_2")
ya_hfs_f <- data %>% select(record_id,redcap_event_name,
                            ya_hfs_f_behave1:ya_hfs_f_behave15,
                            ya_hfs_f_worry16:ya_hfs_f_worry33) %>%
  filter(redcap_event_name != "baseline_arm_2")
# Change column names to match
colnames(ya_hfs_b) <- gsub("b_","",colnames(ya_hfs_b))
colnames(ya_hfs_f) <- gsub("f_","",colnames(ya_hfs_f))
# Bind
ya_hfs <- rbind(ya_hfs_b,ya_hfs_f)
# Split by HFS subscale, fill NAs
ya_hfs_behave <- ya_hfs %>% select(record_id,redcap_event_name,
                                   ya_hfs_behave1:ya_hfs_behave15)
ya_hfs_behave <- fill_NAs(ya_hfs_behave,0.75,1:2)
ya_hfs_worry <- ya_hfs %>% select(record_id,redcap_event_name,
                                   ya_hfs_worry16:ya_hfs_worry33)
ya_hfs_worry <- fill_NAs(ya_hfs_worry,0.75,1:2)
# Score
ya_hfs_behave <- ya_hfs_behave %>% group_by(record_id,redcap_event_name) %>% 
  summarise(behave_score = sum(ya_hfs_behave1:ya_hfs_behave15))
ya_hfs_worry <- ya_hfs_worry %>% group_by(record_id,redcap_event_name) %>% 
  summarise(worry_score = sum(ya_hfs_worry16:ya_hfs_worry33))
# Combine scores
# Put back into full dataframe
data <- left_join(data,ya_paid,by = c("record_id","redcap_event_name"))
data <- left_join(data,ya_hfs_behave,by = c("record_id","redcap_event_name"))
data <- left_join(data,ya_hfs_worry,by = c("record_id","redcap_event_name"))
# Child
# PAID Peds still needs 1 subtracted from each score (coded as 1-5 instead of 0-4)
```

```{r table 1,echo=FALSE}
cont_vars <- c("hba1c_baseline","age_at_am_start","t1d_duration_at_am_start")
cat_vars <- c("demographics_sex.factor","demographics_race.factor","demographics_ethnicity.factor",
              "demographics_insurance.factor","demographics_cgmhx.factor","demographics_pumphx.factor")
nonnormal <- c("t1d_duration_at_am_start") # A1c always reported as mean (SD)
t1 <- CreateTableOne(vars = c(cont_vars,cat_vars),data = demographics)
t1 <- print(t1,nonnormal = nonnormal,printToggle = F)
kable(t1)
```

