---
title: "DAISY longitudinal T-cell responses to hybrid insulin peptides"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:   
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
# required libraries
library(purrr)
library(tableone)
library(dplyr)
library(plyr)
library(zoo)
library(nlme)
library(lme4)
library(emmeans)
library(knitr)
library(car)
library(tidyr)
```

```{r, include=F}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

home_dir = ifelse(.Platform$OS.type != "unix","T:\\",
                  "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
knitr::opts_knit$set(root.dir = home_dir)

# data for fig 1b
dat1 <- read.csv("T:\\Aaron Michels\\Temporal development of T-cell repertoires\\Data raw\\fig_1b_s2.csv",na.strings = c(""," ","X"))
# wide to long
dat1_long <- dat1 %>% gather(tp,clonality,-c(ID,Group))
dat1_long$time <- ifelse(dat1_long$tp=="TP.1",1,
                         ifelse(dat1_long$tp=="TP.2",2,
                                ifelse(dat1_long$tp=="TP.3",3,4)))
dat1_long$l.clonality <- log(dat1_long$clonality)
dat1_long <- arrange(dat1_long,ID,time)
dat1_long_case <- dat1_long %>% filter(Group=="CASE")
dat1_long_control <- dat1_long %>% filter(Group=="CON")

# data for fig 1c
dat1_age <- read.csv("T:\\Aaron Michels\\Temporal development of T-cell repertoires\\Data raw\\fig_1b_s2_age.csv",na.strings = c(""," ","X"))
dat1_age$l.clonality <- log(dat1_age$Clonality)
dat1_age$TP <- as.factor(dat1_age$TP)
dat1_age_case <- dat1_age %>% filter(Group=="CASE")
dat1_age_control <- dat1_age %>% filter(Group=="CON")
```

# Background


# Methods

Log transformed clonality but residuals still don't look great - could consider other transformations

# Results

## Figure 1b - all samples

```{r, echo=FALSE, message=FALSE}
mod <- lme(l.clonality ~ tp,random=~1|ID,data = dat1_long,na.action = na.omit)
mod_anova <- anova.lme(mod, type="marginal")
mod_means <- emmeans(mod,"tp")
mod_pairs <-  pairs(mod_means,adjust="tukey")

kable(mod_anova,caption="Type 3 tests of fixed effects.",format.args = list(scientific = FALSE))
kable(mod_means,caption="Time point means.",format.args = list(scientific = FALSE))
kable(mod_pairs,caption="Pair-wise comparisons between time points.",format.args = list(scientific = FALSE))

qqnorm(resid(mod))
qqline(resid(mod))
```

## Figure 1b - controls

```{r, echo=FALSE, message=FALSE}
mod <- lme(clonality ~ tp,random=~1|ID,data = dat1_long_control,na.action = na.omit)
mod_anova <- anova.lme(mod, type="marginal")
mod_means <- emmeans(mod,"tp")
mod_pairs <-  pairs(mod_means,adjust="tukey")

kable(mod_anova,caption="Type 3 tests of fixed effects.",format.args = list(scientific = FALSE))
kable(mod_means,caption="Time point means.",format.args = list(scientific = FALSE))
kable(mod_pairs,caption="Pair-wise comparisons between time points.",format.args = list(scientific = FALSE))

qqnorm(resid(mod))
qqline(resid(mod))
```

## Figure 1b - cases

```{r, echo=FALSE, message=FALSE}
mod <- lme(clonality ~ tp,random=~1|ID,data = dat1_long_case,na.action = na.omit)
mod_anova <- anova.lme(mod, type="marginal")
mod_means <- emmeans(mod,"tp")
mod_pairs <-  pairs(mod_means,adjust="tukey")

kable(mod_anova,caption="Type 3 tests of fixed effects.",format.args = list(scientific = FALSE))
kable(mod_means,caption="Time point means.",format.args = list(scientific = FALSE))
kable(mod_pairs,caption="Pair-wise comparisons between time points.",format.args = list(scientific = FALSE))

qqnorm(resid(mod))
qqline(resid(mod))
```

## Figure 1c - all samples

```{r, echo=FALSE, message=FALSE}
mod <- lme(l.clonality ~ Age,random=~1|ID,data = dat1_age,na.action = na.omit)
mod_anova <- anova.lme(mod, type="marginal")

kable(mod_anova,caption="Type 3 tests of fixed effects.",format.args = list(scientific = FALSE))

qqnorm(resid(mod))
qqline(resid(mod))
```

## Figure 1c - controls

```{r, echo=FALSE, message=FALSE}
mod <- lme(l.clonality ~ Age,random=~1|ID,data = dat1_age_control,na.action = na.omit)
mod_anova <- anova.lme(mod, type="marginal")

kable(mod_anova,caption="Type 3 tests of fixed effects.",format.args = list(scientific = FALSE))

qqnorm(resid(mod))
qqline(resid(mod))
```

## Figure 1c - cases

```{r, echo=FALSE, message=FALSE}
mod <- lme(l.clonality ~ TP ,random=~1|ID,data = dat1_age_case,na.action = na.omit)
mod_anova <- anova.lme(mod, type="marginal")

kable(mod_anova,caption="Type 3 tests of fixed effects.",format.args = list(scientific = FALSE))

qqnorm(resid(mod))
qqline(resid(mod))
```