---
title: "First 10 Transition Participants"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/peds/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Viral Shah/NOVO Transition")
library(arsenal)
library(skimr)
library(knitr)
library(cgmanalysis)
library(tidyverse)
```

```{r echo=FALSE,eval=FALSE}
# Clean CGM data
cleandata("./Data_Raw/CGMs","./Data_Cleaned/CGMs")
# Calculate CGM variables
cgmvariables("./Data_Cleaned/CGMs","./Data_Cleaned",outputname = "cgm_data",
             id_filename = T)
```

### TIR Data

```{r echo=FALSE}
# Import group assignment and CGM summary statistics
groups = read.csv("./Data_Cleaned/groups.csv",na.strings = "")
cgm_data = read.csv("./Data_Cleaned/cgm_data.csv",na.strings = "")
# Get TIR and group assignment
cgm_data = cgm_data %>% select(subject_id,percent_time_70_180)
cgm_data = left_join(cgm_data,groups,by = "subject_id")
# Complete cases
cgm_data = cgm_data[complete.cases(cgm_data),]
# Sort and print
kable(arrange(cgm_data,as.numeric(subject_id)),
      col.names = c("ID","% TIR","Group"))
```

### Group Comparison

```{r echo=FALSE,results='asis'}
labels(cgm_data) = c(subject_id = "ID",percent_time_70_180 = "% TIR",
                     group = "Group")
t = tableby(group ~ kwt(percent_time_70_180,"median","q1q3"),cgm_data)
summary(t)
```