---
title: ""
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(performance)
library(knitr)
library(rlang)
library(usethis)
library(devtools)
# devtools::install_github('biodataganache/leapR')
library(leapR)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "Z:/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
rm(home_dir)

# load in master dataset
load("S:/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant/aha_master_data.Rdata")
```

```{r example}
data("protdata")
data("ncipid")
# read in the patient groups
# note this is the case not control group, idk why they are only using them
data("shortlist")

# use enrichment_in_pathways to calculate the most enriched pathways in a set of conditions
#     based on abundance in the pathway members versus abundance in non-pathway members
pathways = leapR(geneset=ncipid, enrichment_method='enrichment_in_pathway', datamatrix=protdata, primary_columns=shortlist)
```

```{r trying it}
# lets get some relevant data from the df
test = df %>% select(StudyID, global_proteins)
rownames(test) = test$StudyID
test =test %>% select(-StudyID) %>% as.matrix() %>% t()

test_geneset = list(names = global_proteins, desc = global_proteins, sizes = rep(1, length(global_proteins)))

test_pathways = leapR(geneset = test_geneset, enrichment_method='enrichment_in_pathway', datamatrix=test)
```