---
title: ""
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
library(readxl)
library(arsenal)
library(tidyverse)
library(performance)
library(knitr)
library(lubridate)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "S:/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
rm


# load in metab data
QAHA_Biomarkers_IDs = read_excel("S:/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant/Combined predictive model/QAHA_Biomarkers_IDs.xls")
```

```{r data clean, include = FALSE}
# the goal is to transform each of these metrics into a slope (visit max - visit1)/(datemax - date 1) - dates in years
test = QAHA_Biomarkers_IDs %>% select(StudyID, Date_V1:Date_V4, ACV1, acv2, acv3, acv4)
test$acv2 = as.numeric(test$acv2)
test$acv3 = as.numeric(test$acv3)
# All subjects have a visit 1 date but 14 have no acv1 -- drop these or use a 2 if they have it?
# All subjects with no visit 2 or 3 dates also dont have a acv value


# 13 subjects have an acv4 value but no date -- ask janet

# 8 subj with only acv1
options(scipen = 20)
test2 = test %>% mutate(slope_acv = case_when(!is.na(Date_V4) & !is.na(acv4) ~ (acv4 - ACV1)/(as.double(difftime(Date_V4, Date_V1, units = "days"))/365),
                                              !is.na(Date_V3) & !is.na(acv3) ~ (acv3 - ACV1)/(as.double(difftime(Date_V3, Date_V1, units = "days"))/365),
                                              !is.na(Date_V2) & !is.na(acv2) ~ (acv2 - ACV1)/(as.double(difftime(Date_V2, Date_V1, units = "days"))/365)
                                              ))

# 22 subj missing; 8 with only acv1, 14 without, of the 14, 9 have at least 2 dates -- exclude



# what is the normal range for acv? a few values in the thousands
# should we try and include those with 2 visits or do we need v1
# couldnt find egfr234
# list of other outcomes?



```
