---
title: "Title"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(Hmisc)
library(knitr)
library(readxl)
library(dplyr)
library(tableone)

clinical_h <- read_excel("B:\\Projects\\Andrea Gerard Gonzalez\\Transition to telehealth\\Data_raw\\Telemed Data Cleaup RJJ032321.xlsx", 
                         sheet = "Rpt3_Enc_Hispanic",na=c(""," ","N/A","NULL"))
clinical_nh <- read_excel("B:\\Projects\\Andrea Gerard Gonzalez\\Transition to telehealth\\Data_raw\\Telemed Data Cleaup RJJ032321.xlsx", 
                         sheet = "Rpt4_Enc_NonHispanic",na=c(""," ","N/A","NULL"))
clinical_lc <- read_excel("B:\\Projects\\Andrea Gerard Gonzalez\\Transition to telehealth\\Data_raw\\Telemed Data Cleaup RJJ032321.xlsx", 
                         sheet = "Rpt_Enc_LatinoClinic",na=c(""," ","N/A","NULL"))
noshow_h <- read_excel("B:\\Projects\\Andrea Gerard Gonzalez\\Transition to telehealth\\Data_raw\\Telemed Data Cleaup RJJ032321.xlsx", 
                         sheet = "Rpt5_CancelNoShow_Hispanic",na=c(""," ","N/A","NULL"))
noshow_nh <- read_excel("B:\\Projects\\Andrea Gerard Gonzalez\\Transition to telehealth\\Data_raw\\Telemed Data Cleaup RJJ032321.xlsx", 
                         sheet = "Rpt6_CancelNoShow_NonHispanic",na=c(""," ","N/A","NULL"))
noshow_lc <- read_excel("B:\\Projects\\Andrea Gerard Gonzalez\\Transition to telehealth\\Data_raw\\Telemed Data Cleaup RJJ032321.xlsx", 
                         sheet = "Rp_CancelNoShow_LatinoClinic",na=c(""," ","N/A","NULL"))

clinical_h$group <- "Hispanic"
clinical_nh$group <- "Non-Hispanic"
clinical_lc$group <- "Latino Clinic"
noshow_h$group <- "Hispanic"
noshow_nh$group <- "Non-Hispanic"
noshow_lc$group <- "Latino Clinic"
clinical_lc$`Appointment Notes` <- NULL
clinical <- rbind(clinical_h,clinical_nh,clinical_lc)
noshow <- rbind(noshow_h,noshow_nh,noshow_lc)

# get rid of duplicate rows
clinical <- unique(clinical)

# fix Ethnicity
clinical$Ethnicity <- ifelse(clinical$Ethnicity=="HISPANIC OR LATINO","Hispanic or Latino",clinical$Ethnicity)
clinical$Ethnicity <- ifelse(clinical$Ethnicity=="NOT HISPANIC OR LATINO","Not Hispanic or Latino",clinical$Ethnicity)
clinical$Ethnicity <- ifelse(clinical$Ethnicity=="NOT REPORTED","Not Reported",clinical$Ethnicity)
clinical$Ethnicity <- ifelse(clinical$Ethnicity=="UNKNOWN","Unknown",clinical$Ethnicity)

# fix Race
clinical$Race <- ifelse(clinical$Race=="OTHER","Other",clinical$Race)
clinical$Race <- ifelse(clinical$Race=="WHITE","White",clinical$Race)

# fix language
clinical$Language <- ifelse(clinical$Language=="ENGLISH","English",clinical$Language)
clinical$Language <- ifelse(clinical$Language=="SPANISH","Spanish",clinical$Language)

# make baseline dataframe using first visit 
clinical <- arrange(clinical,EPICMRN,VisitDate)
baseline <- clinical %>% group_by(EPICMRN) %>% slice_head(n=1)

# need to classify people wrt insulin regimen and tech use - can change over time
# first find # of different insulin regimens per person
insct <- clinical %>% group_by(EPICMRN) %>% count(InsulinRegimen)
insctct <- insct %>% group_by(EPICMRN) %>% count()
# about 15% have 2 types, only 1 person has 3, just use most recent
most_recent <- arrange(clinical,EPICMRN,desc(VisitDate))
most_recent <- most_recent %>% group_by(EPICMRN) %>% slice_head(n=1)
most_recent <- most_recent[,c("EPICMRN","InsulinRegimen","CGM")]
colnames(most_recent) <- c("EPICMRN","most_recent_ins","most_recent_CGM")
clinical <- merge(clinical,most_recent,by="EPICMRN",all.x = T,all.y = T)

# count number of visits, number of telehealth visits, number of noshows, number of cancellations
# total visits
visitnum <- clinical %>% group_by(EPICMRN) %>% count()
colnames(visitnum) <- c("EPICMRN","visitnum")
clinical <- merge(clinical,visitnum,by="EPICMRN",all.x=T,all.y=T)
# telemedicine visits
tele <- clinical[clinical$EncounterType=="TELEHEALTH",]
telenum <- tele %>% group_by(EPICMRN) %>% count()
colnames(telenum) <- c("EPICMRN","telenum")
clinical <- merge(clinical,telenum,by="EPICMRN",all.x = T,all.y = T)
clinical[is.na(clinical$telenum),]$telenum <- 0
clinical$per_tele <- clinical$telenum/clinical$visitnum*100
# noshows
ns <- noshow[noshow$ApptStatus=="No Show",]
nsnum <- ns %>% group_by(EPICMRN) %>% count()
colnames(nsnum) <- c("EPICMRN","nsnum")
clinical <- merge(clinical,nsnum,by="EPICMRN",all.x = T,all.y = T)
clinical[is.na(clinical$nsnum),]$nsnum <- 0
clinical$per_ns <- clinical$nsnum/clinical$visitnum*100
# when I merge noshows into clinical, there are some people who are only in noshow and therefore number of visits is 0 and percent noshow is NA
# cancellations
canc <- noshow[noshow$ApptStatus=="Canceled",]
cancnum <- canc %>% group_by(EPICMRN) %>% count()
colnames(cancnum) <- c("EPICMRN","cancnum")
clinical <- merge(clinical,cancnum,by="EPICMRN",all.x = T,all.y = T)
clinical[is.na(clinical$cancnum),]$cancnum <- 0
clinical$per_canc <- clinical$cancnum/clinical$visitnum*100

# how to summarize A1c, CGM % time - just take the average?  most recent?
mean_a1c <- clinical %>% group_by(EPICMRN) %>% summarise(mean_a1c=mean(A1cValue,na.rm=T))
clinical <- merge(clinical,mean_a1c,by="EPICMRN",all.x = T,all.y = T)
mean_cgmuse <- clinical[clinical$CGM=="Yes",] %>% group_by(EPICMRN) %>% summarise(mean_cgmuse=mean(CGMUsePercent,na.rm=T))
clinical <- merge(clinical,mean_cgmuse,by="EPICMRN",all.x = T,all.y = T)

# checking patients with no visits and some noshow or cancellation
check <- clinical[is.na(clinical$per_canc) | is.na(clinical$per_ns),]
# for these patients, create separate categorical variable
clinical$allnscanc <- as.factor(ifelse(is.na(clinical$visitnum) & (clinical$nsnum>0 | clinical$cancnum>0),1,0))
# NEED TO GET GROUP BACK FOR THE NOSHOW 

# labels
label(clinical$mean_cgmuse)="Mean % CGM use (if using CGM)"
label(clinical$most_recent_ins)="Most recent insulin regimen"
label(clinical$most_recent_CGM)="Most recent CGM use"
label(clinical$visitnum)="Number of visits"
label(clinical$telenum)="Number of telehealth visits"
label(clinical$per_tele)="% of visits as telehealth"
label(clinical$nsnum)="Number of no-shows"
label(clinical$per_ns)="No-shows as % of visits"
label(clinical$cancnum)="Number of cancellations"
label(clinical$per_canc)="Cancellations as % of visits"
label(clinical$mean_a1c)="Mean A1c"
label(clinical$allnscanc)="All visits no-show or cancelled"

# Baseline table
t1 <- CreateTableOne(vars=c("Age_VisitDate","Race","Ethnicity","Gender","Language","DiabetesDuration_LastVisitDate"), 
                     data=baseline, strata="group", test=TRUE)
t1 <- print(t1,varLabels=TRUE,showAllLevels=TRUE)

# Clinical and visit table
clintab <- CreateTableOne(vars=c("most_recent_ins","most_recent_CGM","visitnum","telenum","per_tele","nsnum","per_ns","cancnum","per_canc","allnscanc",
                                 "mean_a1c","mean_cgmuse"), data=clinical, strata="group", test=TRUE)
clintab <- print(clintab,varLabels=TRUE,showAllLevels=TRUE,nonnorm=c("mean_a1c","visitnum","telenum","per_tele","nsnum","per_ns","cancnum","per_canc","mean_cgmuse"))


```
# Background

# Methods

# Results


```{r, results='asis',tidy=TRUE, echo=FALSE}
kable(t1,caption="Table 1.  Baseline descriptive statistics by group.")
```

<br>

```{r, results='asis',tidy=TRUE, echo=FALSE}
kable(clintab,caption="Table 2.  Clinical and visit characteristics by group.")
```

<br>

