---
title: "CGM Sampling Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = "/Users/timvigers/670G real life study")
library(arsenal)
library(skimr)
library(knitr)
library(cgmanalysis)
library(tidyverse)
```

```{r import A1c data}
# Import
subjects <- read.csv("./Data_Cleaned/DATA Set 670 Master Updated.csv",na.strings = "")
# Names to lower case and no middle or suffixes for matching
subjects[,c("First.Name","Last.Name")] <- 
  lapply(subjects[,c("First.Name","Last.Name")],function(x){
    x <- tolower(x)
    x <- sub(" .*","",x)
  })
subjects$name <- paste0(subjects$First.Name,subjects$Last.Name)
# Set output directory
outdir <- "./Data_Cleaned/cgm"
```

```{r organize CGM data,eval=FALSE}
# Iterate through CGM data, format, and name
files <- list.files("./Data_Raw/Medtronic CGM Downloads",full.names = T)
for (f in files) {
  dat <- read.csv(f,na.strings = "")
  if (ncol(dat) > 5) {
    name <- tolower(paste0(dat$First.Name[1],dat$Last.Name[1]))
    m3date <- lubridate::mdy(subjects$A1c.date[match(name,subjects$name)])
    m6date <- lubridate::mdy(subjects$A1c.date.1[match(name,subjects$name)])
    # Format data
    cgm_start <- which(dat[,3] == "Sensor")[1]
    if (!is.na(cgm_start)){
      colnames(dat) <- dat[cgm_start+1,]
      dat <- dat[(cgm_start+2):nrow(dat),] 
    } else {
      colnames(dat) <- dat[3,]
    }
    colnames(dat)[grep("sensor glucose",tolower(colnames(dat)))] <- "sensorglucose"
    dat$timestamp <- lubridate::mdy_hms(paste(dat$Date,dat$Time))
    dat$subjectid <- name
    dat <- dat[,c("subjectid","timestamp","sensorglucose")]
  } else {
    name <- tolower(sub("_.*","",basename(f)))
    m3date <- lubridate::mdy(subjects$A1c.date[match(name,subjects$Last.Name)])
    m6date <- lubridate::mdy(subjects$A1c.date.1[match(name,subjects$Last.Name)])
    # Format data
    colnames(dat) <- dat[1,]
    colnames(dat)[grep("sensor glucose",tolower(colnames(dat)))] <- "sensorglucose"
    dat <- dat[-1,]
    dat$timestamp <- lubridate::mdy_hms(paste(dat$Date,dat$Time))
    dat$subjectid <- name
    dat <- dat[,c("subjectid","timestamp","sensorglucose")]
  }
  if (is.na(m3date) & is.na(m6date)){next}
  dat$sensorglucose <- suppressWarnings(as.numeric(dat$sensorglucose))
  dat <- dat[complete.cases(dat),]
  # Month 3
  if (!is.na(m3date)){
    m3day14 <- dat[dat$timestamp <= m3date & dat$timestamp >= (m3date-14),]
    m3day30 <- dat[dat$timestamp <= m3date & dat$timestamp >= (m3date-30),]
    m3day90 <- dat[dat$timestamp <= m3date & dat$timestamp >= (m3date-90),]
    # Write CSV files
    if (nrow(m3day14 > 0)){write.csv(m3day14,paste0(outdir,"/month3/day14/",name,"m3day14.csv"),na = "",row.names = F)}
    if (nrow(m3day30 > 0)){write.csv(m3day30,paste0(outdir,"/month3/day30/",name,"m3day30.csv"),na = "",row.names = F)}
    if (nrow(m3day90 > 0)){write.csv(m3day90,paste0(outdir,"/month3/day90/",name,"m3day90.csv"),na = "",row.names = F)}
  }
  # Month 6
  if (!is.na(m6date)){
    m6day14 <- dat[dat$timestamp <= m6date & dat$timestamp >= (m6date-14),]
    m6day30 <- dat[dat$timestamp <= m6date & dat$timestamp >= (m6date-30),]
    m6day90 <- dat[dat$timestamp <= m6date & dat$timestamp >= (m6date-90),]
    # Write CSV files
    if (nrow(m6day14 > 0)){write.csv(m6day14,paste0(outdir,"/month6/day14/",name,"m6day14.csv"),na = "",row.names = F)}
    if (nrow(m6day30 > 0)){write.csv(m6day30,paste0(outdir,"/month6/day30/",name,"m6day30.csv"),na = "",row.names = F)}
    if (nrow(m6day90 > 0)){write.csv(m6day90,paste0(outdir,"/month6/day90/",name,"m6day90.csv"),na = "",row.names = F)}
  }
}
```

```{r cgmvariables,eval=FALSE}
# CGM variables on each folder
cgmvariables("./Data_Cleaned/cgm/month3/day14","./Data_Cleaned/cgm/month3",
             outputname = "m3day14variables")
cgmvariables("./Data_Cleaned/cgm/month3/day30","./Data_Cleaned/cgm/month3",
             outputname = "m3day30variables")
cgmvariables("./Data_Cleaned/cgm/month3/day90","./Data_Cleaned/cgm/month3",
             outputname = "m3day90variables")
cgmvariables("./Data_Cleaned/cgm/month6/day14","./Data_Cleaned/cgm/month6",
             outputname = "m6day14variables")
cgmvariables("./Data_Cleaned/cgm/month6/day30","./Data_Cleaned/cgm/month6",
             outputname = "m6day30variables")
cgmvariables("./Data_Cleaned/cgm/month6/day90","./Data_Cleaned/cgm/month6",
             outputname = "m6day90variables")
```

```{r combine data}
vars <- c("percent_time_70_180","percent_time_over_250","percent_time_over_180",
          "percent_time_under_70","percent_time_under_54","cv","average_sensor")
# Import cgm variables - limit to those with > 10 days of data
m3day14 <- read.csv("./Data_Cleaned/cgm/month3/m3day14variables.csv") %>%
  filter(percent_cgm_wear >= 75) %>% mutate(timepoint = "m3",cutoff = 14) %>% 
  select(subject_id,timepoint,cutoff,all_of(vars)) %>% 
  left_join(subjects[,c("name","A1c..month.3.670g")],by = c("subject_id" = "name"))
m3day30 <- read.csv("./Data_Cleaned/cgm/month3/m3day30variables.csv") %>%
  filter(percent_cgm_wear >= 75) %>% mutate(timepoint = "m3",cutoff = 30) %>% 
  select(subject_id,timepoint,cutoff,all_of(vars)) %>% 
  left_join(subjects[,c("name","A1c..month.3.670g")],by = c("subject_id" = "name"))
m3day90 <- read.csv("./Data_Cleaned/cgm/month3/m3day90variables.csv") %>%
  filter(percent_cgm_wear >= 75) %>% mutate(timepoint = "m3",cutoff = 90) %>% 
  select(subject_id,timepoint,cutoff,all_of(vars)) %>% 
  left_join(subjects[,c("name","A1c..month.3.670g")],by = c("subject_id" = "name"))
m6day14 <- read.csv("./Data_Cleaned/cgm/month6/m6day14variables.csv") %>%
  filter(percent_cgm_wear >= 75) %>% mutate(timepoint = "m6",cutoff = 14) %>% 
  select(subject_id,timepoint,cutoff,all_of(vars)) %>% 
  left_join(subjects[,c("name","A1c.month.6.670g")],by = c("subject_id" = "name"))
m6day30 <- read.csv("./Data_Cleaned/cgm/month6/m6day30variables.csv") %>%
  filter(percent_cgm_wear >= 75) %>% mutate(timepoint = "m6",cutoff = 30) %>% 
  select(subject_id,timepoint,cutoff,all_of(vars)) %>% 
  left_join(subjects[,c("name","A1c.month.6.670g")],by = c("subject_id" = "name"))
m6day90 <- read.csv("./Data_Cleaned/cgm/month6/m6day90variables.csv") %>%
  filter(percent_cgm_wear >= 75) %>% mutate(timepoint = "m6",cutoff = 90) %>% 
  select(subject_id,timepoint,cutoff,all_of(vars)) %>% 
  left_join(subjects[,c("name","A1c.month.6.670g")],by = c("subject_id" = "name"))
```

```{r analysis}
corr_analysis <- function(df14,df30,df90,title){
  df1 <- cor(df14[,4:ncol(df14)],use = "pairwise.complete.obs")
  df2 <- cor(df30[,4:ncol(df30)],use = "pairwise.complete.obs")
  df3 <- cor(df90[,4:ncol(df90)],use = "pairwise.complete.obs")
  df <- bind_rows(df1[1:7,8],df2[1:7,8],df3[1:7,8])
  df <- df^2
  df$time <- c(14,30,90)
  df <- df %>% pivot_longer(-time)
  ggplot(df,aes(x = time,y = value,color = name)) + geom_line() + geom_point() +
    ylim(0,1) + ggtitle(title) + theme_bw() + 
    xlab("Days in Sampling Period") + ylab("R^2")
}
corr_analysis(m3day14,m3day30,m3day90,"3 Month A1c")
corr_analysis(m6day14,m6day30,m6day90,"6 Month A1c")
```
