---
title: "CAID"
author: "Kristen Campbell"
date: "3/13/2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r,echo=FALSE,message=FALSE,results='hide',warning=FALSE}
library(knitr)
source('S:/Shared Material/Shared Code/R/temp_table1.R')
options(scipen=999)
#code for data prep: 
source('C:/Users/campbkri/Documents/GitHub/BDC-Code/Kimber Simmons/CAID/data_prep.R')
source('C:/Users/campbkri/Documents/GitHub/BDC-Code/Kimber Simmons/CAID/family_hx.R')
source('C:/Users/campbkri/Documents/GitHub/BDC-Code/Kimber Simmons/CAID/labs.R')


#######Summary by Disease########
#ANY:
dat$baseline_tpo<-factor(dat$baseline_tpo,levels=c("POS","NEG","closest outside of 6mo window","never tested"))
dat$baseline_thy<-factor(dat$baseline_thy,levels=c("POS","NEG","closest outside of 6mo window","never tested"))
dat$baseline_ttg<-factor(dat$baseline_ttg,levels=c("POS","NEG","closest outside of 6mo window","never tested"))
dat$baseline_21<-factor(dat$baseline_21,levels=c("POS","NEG","closest outside of 6mo window","never tested"))
label(dat$baseline_21)<-"21-OH: Baseline Positive"
label(dat$baseline_thy)<-"Thyroglobulin Ab: Baseline Positive"
label(dat$baseline_tpo)<-"TPO Ab: Baseline Positive"
label(dat$baseline_ttg)<-"TTG IgA: Baseline Positive"
# sum.forkimber<-final_table(dat,c('baseline_tpo','baseline_thy','baseline_ttg','baseline_21'),
#                      dat$EPICMRN,margin=2,single=F,2,col.names=T, summary.stat='mean')

#refactor baseline:
dat$baseline_tpo_miss<-"missing"
dat$baseline_tpo_miss[dat$baseline_tpo=="POS"]<-"POS"
dat$baseline_tpo_miss[dat$baseline_tpo=="NEG"]<-"NEG"
label(dat$baseline_tpo_miss)<-"TPO Ab: Baseline Positive"
dat$baseline_thy_miss<-"missing"
dat$baseline_thy_miss[dat$baseline_thy=="POS"]<-"POS"
dat$baseline_thy_miss[dat$baseline_thy=="NEG"]<-"NEG"
label(dat$baseline_thy_miss)<-"Thyroglobulin Ab: Baseline Positive"
dat$baseline_21_miss<-"missing"
dat$baseline_21_miss[dat$baseline_21=="POS"]<-"POS"
dat$baseline_21_miss[dat$baseline_21=="NEG"]<-"NEG"
label(dat$baseline_21_miss)<-"21-OH: Baseline Positive"
dat$baseline_ttg_miss<-"missing"
dat$baseline_ttg_miss[dat$baseline_ttg=="POS"]<-"POS"
dat$baseline_ttg_miss[dat$baseline_ttg=="NEG"]<-"NEG"
label(dat$baseline_ttg_miss)<-"TTG IgA: Baseline Positive"

tab.any.caid<-final_table(dat,c('Age_AtDX','Gender','RaceEthinicity_cat','hispanic_yn','BMI_AtDX',
                                'MIAA_pos_neg','GADA_pos_neg','IA2_pos_neg','ZN_pos_neg',
                                #'pos_tpo','pos_thy','pos_ttg','pos_21',
                                'baseline_tpo_miss','baseline_thy_miss','baseline_ttg_miss','baseline_21_miss'),
                     dat$any_caid,margin=2,single=F,2,col.names=T, summary.stat='mean')

tab.any.caid

#THYROID:
tab.thy<-final_table(dat,c('Age_AtDX', 'Gender','RaceEthinicity_cat','hispanic_yn', 'BMI_AtDX',
                           'MIAA_pos_neg','GADA_pos_neg','IA2_pos_neg','ZN_pos_neg',
                           'baseline_tpo_miss','baseline_thy_miss'),
                     dat$thyroid_yn,margin=2,single=F,2,col.names=T, summary.stat='mean')

tab.thy
mean(dat$age_at_thyroid[dat$thyroid_yn==1],na.rm=T)
sd(dat$age_at_thyroid[dat$thyroid_yn==1],na.rm=T)

#CELIAC:
tab.cel<-final_table(dat,c('Age_AtDX', 'Gender','RaceEthinicity_cat','hispanic_yn', 'BMI_AtDX',
                           'MIAA_pos_neg','GADA_pos_neg','IA2_pos_neg','ZN_pos_neg',
                           'baseline_ttg_miss'),
                     dat$celiac_yn,margin=2,single=F,2,col.names=T, summary.stat='mean')

tab.cel

mean(dat$age_at_celiac[dat$celiac_yn==1],na.rm=T)
sd(dat$age_at_celiac[dat$celiac_yn==1],na.rm=T)


#ADDISON:
tab.add<-final_table(dat,c('Age_AtDX', 'Gender','RaceEthinicity_cat','hispanic_yn','BMI_AtDX',
                           'MIAA_pos_neg','GADA_pos_neg','IA2_pos_neg','ZN_pos_neg',
                           'baseline_21_miss'),
                     dat$addison_yn,margin=2,single=F,2,col.names=T, summary.stat='mean')

tab.add

mean(dat$age_at_add[dat$addison_yn==1],na.rm=T)
sd(dat$age_at_add[dat$addison_yn==1],na.rm=T)


###timing table:
tab.time<-final_table(dat,c('which_caid','caid_months_if_yes','caid_months_if_no',
                            'thyroid_timing','thyroid_months_if_yes',
                            'celiac_timing','celiac_months_if_yes',
                            'addison_timing','addison_months_if_yes'),
                     dat$EPICMRN,margin=2,single=F,2,col.names=T, summary.stat='mean')

tab.time

tab.celiac.grp<-final_table(dat,c('celiac_groups'),
                     dat$EPICMRN,margin=2,single=F,2,col.names=T, summary.stat='mean')
tab.celiac.grp

#####


#######FAMILY HISTORY TABLE########
# 
# tab.any<-final_table(dat.c.full,names(dat.c.full[,c(which(colnames(dat.c.full)=="Addison.s.disease_Any"):
#                                                   which(colnames(dat.c.full)=="Other_Any"))]),dat.c.full$EPICMRN,margin=2,single=T,2,col.names=T, summary.stat='median')
# tab.any$row_num<-rep(1:nrow(tab.any))
# #1st degree
# tab.1st<-final_table(dat.c.full,names(dat.c.full[,c(which(colnames(dat.c.full)=="Addison.s.disease_1stDegree"):
#                                                   which(colnames(dat.c.full)=="Other_1stDegree"))]),dat.c.full$EPICMRN,margin=2,single=T,2,col.names=T, summary.stat='median')
# tab.1st$row_num<-rep(1:nrow(tab.1st))
# 
# tab.oth<-final_table(dat.c.full,names(dat.c.full[,c(which(colnames(dat.c.full)=="Addison.s.disease_Other"):
#                                                   which(colnames(dat.c.full)=="Other_Other"))]),dat.c.full$EPICMRN,margin=2,single=T,2,col.names=T, summary.stat='median')
# tab.oth$row_num<-rep(1:nrow(tab.oth))
# 
# tab.co1<-merge(tab.any,tab.1st,by="row_num")
# tab.co<-merge(tab.co1,tab.oth,by="row_num")
# tab.co<-tab.co[c(2,3,5,7)]
# colnames(tab.co)<-c("Diagnosis","Any Family Member","1st Degree Family Member","Non-1st Degree Family Member")
# tab.co$Diagnosis<-substr(tab.co$Diagnosis,3,nchar(tab.co$Diagnosis)-6)
# tab.co$n<-as.numeric(sub(" *\\(.*", "", tab.co$`Any Family Member`))
# tab.co<-tab.co[order(tab.co$n,decreasing = T),]
# tab.co<-tab.co[,-5]

######LABS#####
# tab.labs<-final_table(dat,c('pos_ttg', 'timing_ttg','timing_cel_ttg',
#                            'pos_21','timing_21','timing_add_21',
#                            'pos_tpo', 'timing_tpo','timing_thy_tpo',
#                            'pos_thy', 'timing_thy','timing_thy_thy'),
#                      dat$EPICMRN,margin=2,single=F,2,col.names=T, summary.stat='mean')
# tab.labs


```

##CAID Summary Statistics

**Table 1: Demographics by ANY CAID (thyroid, celiac or addison's)**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(tab.any.caid, align = c("l", "l"))
```

**Table 1a: Demographics by Thyroid Disease**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(tab.thy, align = c("l", "l"))
```

**Table 1b: Demographics by Celiac's Disease**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(tab.cel, align = c("l", "l"))
```

**Celiac Groups**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(tab.celiac.grp, align = c("l", "l"))
```

**Table 1c: Demographics by Addison's Disease**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(tab.add, align = c("l", "l"))
```

**Table 3: Timing of Events**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(tab.time, align = c("l", "l"))
```

