---
title: "HCL and sleep: changes in sleep after starting Control IQ"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:   
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tableone)
library(dplyr)
library(stringr)
library(nlme)
library(naniar)
```

```{r echo=FALSE,include=FALSE}
# demographic data
source("T:\\Erin Cobry\\Prospective HCL and sleep study\\Data raw\\AdvancedHybridClosed-Demographics_R_2021-11-11_1646.r")
demo <- data
demo <- demo[!(demo$record_id %in% c(121,221,101,201,102,202,103,203,121,221,111,211,131,231,141,241)),]
demo_child <- subset(demo, record_id>=200)
demo_child$consent_date <- as.Date(as.character(demo_child$consent_date))
demo_adult <- subset(demo, record_id<200)
demo_adult$parent_bday <- as.Date(as.character(demo_adult$parent_bday))
# to calculate age, need to get consent date from child demo
consent <- demo_child %>% select(record_id, consent_date)
consent$record_id <- consent$record_id-100
demo_adult$consent_date <- NULL
demo_adult <- merge(demo_adult,consent,by="record_id",all.x=T,all.y = T)
demo_adult$age <- floor(((demo_adult$consent_date - demo_adult$parent_bday)/365.25))
demo_adult$age <- ifelse(demo_adult$age==0,NA,demo_adult$age)
demo_adult$parent_check_night <- as.numeric(demo_adult$parent_check_night)
# calculate child duration
demo_child$t1d_diagnosis <- as.Date(as.character(demo_child$t1d_diagnosis))
demo_child$t1d_duration <- as.numeric(((demo_child$consent_date - demo_child$t1d_diagnosis)/365.25))
# merge in insulin use, CGM use, HCL use from parent questionnaire
demo_child$cgm_start <- NULL
demo_child$pump_start <- NULL
demo_child$pump_brand.factor <- NULL
ins <- demo_adult[c("record_id","insulinmethod.factor","previous_cgm_use.factor","currenthcltech.factor","cgm_start","pump_start","pump_brand.factor")]
ins$record_id <- ins$record_id+100
demo_child$insulinmethod.factor <- NULL
demo_child$previous_cgm_use.factor <- NULL
demo_child$currenthcltech.factor <- NULL
demo_child <- merge(demo_child,ins,by="record_id",all.x=T,all.y=T)
demo_child$cgm_start <- as.Date(as.character(demo_child$cgm_start))
demo_child$pump_start <- as.Date(as.character(demo_child$pump_start))
demo_child$cons_age <- as.numeric(demo_child$cons_age)
demo_child$cgm_time <- demo_child$consent_date - demo_child$cgm_start
demo_child$cgm_ge1mo <- as.factor(ifelse(demo_child$cgm_time>=30,1,0))
demo_child$pump_time <- demo_child$consent_date - demo_child$pump_start
demo_child$pump_time <- ifelse(is.na(demo_child$pump_time),0,demo_child$pump_time)
demo_child$pump_ge1mo <- as.factor(ifelse(demo_child$pump_time>=30,1,0))
# is child 5 or older?
demo_child$age_ge5 <- ifelse(demo_child$cons_age>=5,1,0)
# merge child age into parent data
child_age <- demo_child %>% select(record_id, age_ge5)
child_age$record_id <- child_age$record_id-100
demo_adult <- merge(demo_adult,child_age,by="record_id",all.x=T,all.y = T)

# read in actigraphy data
source("T:\\Erin Cobry\\Prospective HCL and sleep study\\Data raw\\AdvancedHybridClosed-ATTDAbstracts2022_R_2021-11-08_2000.r")
data <- data[!(data$record_id %in% c(121,221,101,201,102,202,103,203,121,221,111,211,131,231,141,241)),]
# fix total sleep variable
data$totalsleep_avg <- as.character(data$totalsleep_avg)
data$hours <-  as.numeric(word(data$totalsleep_avg,1,sep=":"))
data$minutes <- as.numeric(word(data$totalsleep_avg,2,sep=":"))
data$totalsleep_avg_num <- data$hours + (data$minutes/60)
data$redcap_event_name.factor <- droplevels(data$redcap_event_name.factor)
# keep needed actigraphy variables
actigraphy <- data[,c("record_id","redcap_event_name","totalsleep_avg_num","sleepefficency_avg","waso_avg")]

# reshape actigraphy data
# create new actigraphy visit variable
actigraphy$visit <- ifelse(actigraphy$redcap_event_name %in% c("baseline_day_1_arm_1","baseline_day_1_arm_2"),"B",
                           ifelse(actigraphy$redcap_event_name %in% c("hcl_month_3_day_1_arm_1","hcl_month_3_day_1_arm_2"),"M3","M6"))
actigraphy_wide <- reshape(actigraphy, idvar = "record_id", timevar = "visit", direction = "wide")
#actigraphy_wide$d_tot <- as.numeric(actigraphy_wide$totalsleep_avg_num.WK1 - actigraphy_wide$totalsleep_avg_num.B)
#actigraphy_wide$d_eff <- as.numeric(actigraphy_wide$sleepefficency_avg.WK1 - actigraphy_wide$sleepefficency_avg.B)
#actigraphy_wide$d_waso <- as.numeric(actigraphy_wide$waso_avg.WK1 - actigraphy_wide$waso_avg.B)
#label(actigraphy_wide$d_tot) <- "Change in total sleep time"
#label(actigraphy_wide$d_eff) <- "Change in sleep efficiency"
#label(actigraphy_wide$d_waso) <- "Change in WASO"
actigraphy_wide_child <- actigraphy_wide[actigraphy_wide$record_id>=200,]
actigraphy_wide_adult <- actigraphy_wide[actigraphy_wide$record_id<200,]

# score FOH for adults - child version had missing question, so we may impute that later
behavior_vars <- c("snacks","alone","safe_side","higher_alone","feels_low","reduce_insulin","away","fast_acting","exercise_low","outing","nighttime")
worry_vars <- c("recognize","food","dizzy","asleep_low","embarrassing","low_alone","clumsy","behavior","no_one","accident","bad_evaluation",
                "seizure","complications_low","faint","having_low")
maintain_highBG_behavior_vars <- c("safe_side","higher_alone","away")
lowBG_worry_vars <- c("recognize","food","dizzy","asleep_low","low_alone","no_one","seizure","complications_low","faint","having_low")
negsocial_worry_vars <- c("embarrassing","clumsy","behavior","accident","bad_evaluation")
foh_adult <- data[data$record_id<200,c("record_id","redcap_event_name",behavior_vars,worry_vars)]
foh_adult$visit <- ifelse(foh_adult$redcap_event_name %in% c("baseline_day_1_arm_1","baseline_day_1_arm_2"),"B",
                           ifelse(foh_adult$redcap_event_name %in% c("hcl_month_3_day_1_arm_1","hcl_month_3_day_1_arm_2"),"M3","M6"))
# combine records from screening visit - not done at baseline
source("T:\\Erin Cobry\\Prospective HCL and sleep study\\Data raw\\AdvancedHybridClosed-ParentFOHSurvey_R_2021-11-12_1624.r")
foh_screen <- foh_screen %>% filter(redcap_event_name %in% c("enrollment_arm_1","enrollment_arm_2"))
foh_screen <- foh_screen %>% filter(record_id<200)
foh_screen <- foh_screen[,1:30]
foh_screen$visit <- "B"
foh_screen$redcap_repeat_instrument <- NULL
foh_screen$redcap_repeat_instance <- NULL
foh_adult <- foh_adult %>% filter(!visit=="B")
foh_adult <- rbind(foh_adult,foh_screen)
foh_adult <- foh_adult %>% arrange(record_id,visit)

# checking if anyone is missing items within the FOH survey - no
#a <- visdat::vis_dat(foh_adult)
# values are coded in REDCap as 1-5 but need to be 0-4 so subtract 1
foh_adult[,c(worry_vars,behavior_vars)]<- foh_adult[,c(worry_vars,behavior_vars)] - 1
foh_adult$foh_adult_total <- rowSums(foh_adult[,c(behavior_vars,worry_vars)],na.rm = F)
foh_adult$foh_adult_worry <- rowSums(foh_adult[,worry_vars],na.rm = F)
foh_adult$foh_adult_behavior <- rowSums(foh_adult[,behavior_vars],na.rm = F)
foh_adult$foh_adult_behavior_maintain <- rowSums(foh_adult[,maintain_highBG_behavior_vars],na.rm = F)
foh_adult$foh_adult_worry_lowBG <- rowSums(foh_adult[,lowBG_worry_vars],na.rm = F)
foh_adult$foh_adult_worry_negsocial <- rowSums(foh_adult[,negsocial_worry_vars],na.rm = F)
# keep only the vars we need
foh_adult <- foh_adult[,c("record_id","visit","foh_adult_total","foh_adult_worry","foh_adult_behavior","foh_adult_behavior_maintain",
                          "foh_adult_worry_lowBG","foh_adult_worry_negsocial")]
# reshape to wide
foh_adult$redcap_event_name <- NULL
foh_adult_wide <- reshape(foh_adult, idvar = "record_id", timevar = "visit", direction = "wide")

```

# Background

# Methods

# Results

```{r, echo=FALSE, message=FALSE}
# adult demo table
adult_demo_vars <- c("age","parent_gender.factor","race.factor","parent_check_night")
t1_adult <- CreateTableOne(data=demo_adult,vars=adult_demo_vars)
t1_adult <- print(t1_adult,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,nonnorm=c("age"),test = F)

kable(t1_adult,caption="Table 1a. Demographics and clinical characteristics in parents.")
```

```{r, echo=FALSE, message=FALSE}
# adult demo table by age group
adult_demo_vars <- c("age","parent_gender.factor","race.factor","parent_check_night")
t1_adult <- CreateTableOne(data=demo_adult,vars=adult_demo_vars,strata="age_ge5")
t1_adult <- print(t1_adult,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,nonnorm=c("age"),test = F)

kable(t1_adult,caption="Table 1b. Demographics and clinical characteristics in parents, by child age.")
```

```{r, echo=FALSE, message=FALSE}
# child demo table
child_demo_vars <- c("cons_age","childgender.factor","t1d_duration","insulinmethod.factor","pump_ge1mo","cgm_ge1mo")
t1_child <- CreateTableOne(data=demo_child,vars=child_demo_vars)
t1_child <- print(t1_child,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,nonnorm=c("t1d_duration"),test = F)

kable(t1_child,caption="Table 2a. Demographics and clinical characteristics in children.")
```

```{r, echo=FALSE, message=FALSE}
# child demo table
child_demo_vars <- c("cons_age","childgender.factor","t1d_duration","insulinmethod.factor","pump_ge1mo","cgm_ge1mo")
t1_child <- CreateTableOne(data=demo_child,vars=child_demo_vars,strata="age_ge5")
t1_child <- print(t1_child,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,nonnorm=c("t1d_duration"),test = F)

kable(t1_child,caption="Table 2b. Demographics and clinical characteristics in children, by child age.")
```

```{r, echo=FALSE, message=FALSE}
# adult actigraphy table
actvars <- c("totalsleep_avg_num.B","totalsleep_avg_num.M3","totalsleep_avg_num.M6",
             "sleepefficency_avg.B","sleepefficency_avg.M3","sleepefficency_avg.M6",
             "waso_avg.B","waso_avg.M3","waso_avg.M6")
act_table_adult <- CreateTableOne(data=actigraphy_wide_adult,vars=actvars)
act_table_adult <- print(act_table_adult,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = F)

kable(act_table_adult,caption="Table 3.  Adult actigraphy variables.")
```

```{r, echo=FALSE, message=FALSE}
# child actigraphy table
act_table_child <- CreateTableOne(data=actigraphy_wide_child,vars=actvars)
act_table_child <- print(act_table_child,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = F)

kable(act_table_child,caption="Table 4.  Child actigraphy variables.")
```

```{r, echo=FALSE, message=FALSE}
# table of adult FOH
foh_vars <- c("foh_adult_total.B","foh_adult_total.M3","foh_adult_total.M6",
              "foh_adult_worry.B","foh_adult_worry.M3","foh_adult_worry.M6",
              "foh_adult_behavior.B","foh_adult_behavior.M3","foh_adult_behavior.M6",
              "foh_adult_behavior_maintain.B","foh_adult_behavior_maintain.M3","foh_adult_behavior_maintain.M6",
              "foh_adult_worry_lowBG.B","foh_adult_worry_lowBG.M3","foh_adult_worry_lowBG.M6",
              "foh_adult_worry_negsocial.B","foh_adult_worry_negsocial.M3","foh_adult_worry_negsocial.M6")
foh_table <- CreateTableOne(data=foh_adult_wide,vars=foh_vars)
foh_table <- print(foh_table,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,test = F)

kable(foh_table,caption="Table 5.  Hypoglycemia fear scores in parents.")
```

