---
title: "ASBMR Abstract 2"
author: "Casey Sakamoto"
date: "5/3/2022"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(table1)
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "S:/Laura/BDC/Projects/Viral Shah/K23"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Viral Shah/K23"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Viral Shah/K23"
}
knitr::opts_knit$set(root.dir = home_dir)

setwd("S:/Laura/BDC/Projects/Viral Shah/K23")
rm(home_dir)
```


```{r data import and clean, include=FALSE}
# import data
BSTM_t1d <- read_csv("bstm_t1d_raw.csv")

# menopausal length? ACR?
# subject list: 5, 10 , 12, 13, 17, 28, 29, 34, 40, 45, 46, 47, 48
subj_list = c("1005_K","1010_K","1012_K","1013_K","1017_K","1028_K","1029_K","1034_K","1040_K","1045_K","1046_K","1047_K","1048_K")

# variable select
analysis = BSTM_t1d %>% filter(record_id %in% subj_list) %>% select(record_id, t1d_diagnosis,age, demo_gender1, fall_diab_duration, postmenopause_pill_42695d, are_you_currently_smoking_e66c9b, do_you_drink_3_or_more_uni_ca666a, hba1c_value_k, egfr,albumin_serum, creatinine_serum, pth_baseline, calcium_serum, p1np_baseline, ctx_baseline )

# some hba1c are listed with a % sign (LITERALLY WHY); need to remove that
analysis = analysis %>% mutate(hba1c = 
                                 case_when(str_detect(hba1c_value_k, "%") ~ as.numeric(str_sub(hba1c_value_k, 1,str_length(hba1c_value_k)-1)),
                                           TRUE ~ as.numeric(hba1c_value_k))) %>% select(-hba1c_value_k)

# need to fix ctx with the truncated values by dividing by 2
analysis = analysis %>% mutate(ctx_bl = 
                                 case_when(str_detect(ctx_baseline, "<") ~ (as.numeric(str_sub(ctx_baseline, 2))/2),
                                           TRUE ~ as.numeric(ctx_baseline)),
                              ) %>% select(-c( ctx_baseline))
```

```{r table 1 setup, include=FALSE}
# levels and labels
analysis$t1d_diagnosis = factor(analysis$t1d_diagnosis, labels = c("No T1D Diagnosis", "T1D Diagnosis"))
analysis$demo_gender1 = factor(analysis$demo_gender1, labels = c("Female"))
analysis$postmenopause_pill_42695d = factor(analysis$postmenopause_pill_42695d, labels = c("No HRT", "HRT"))
analysis$are_you_currently_smoking_e66c9b = factor(analysis$are_you_currently_smoking_e66c9b, labels = c("No", "Yes"))

label(analysis$fall_diab_duration) = "T1D Duration (Years)"
label(analysis$demo_gender1) = "Sex"
label(analysis$age) = "Age"
label(analysis$postmenopause_pill_42695d) = "HRT"
label(analysis$are_you_currently_smoking_e66c9b) = "Current Smoker"
label(analysis$hba1c) = "HBA1C"
label(analysis$egfr) = "eGFR"
label(analysis$albumin_serum) = "Serum Albumin"
label(analysis$creatinine_serum) = "Serum Creatinine"
label(analysis$pth_baseline) = "PTH"
label(analysis$calcium_serum) = "Calcium"
label(analysis$p1np_baseline) = "P1NP"
label(analysis$ctx_bl) = "CTX"


demogs = table1(~age+demo_gender1+fall_diab_duration+postmenopause_pill_42695d+are_you_currently_smoking_e66c9b+ hba1c+egfr+pth_baseline+calcium_serum+p1np_baseline+ctx_bl|t1d_diagnosis,
       data=analysis, overall = FALSE,  render.continuous=c(.="Mean (SD)"))
```

# Baseline Characteristics
```{r table1}
demogs
```
