---
title: "HCL and Sleep CGM Clean"
author: "Casey Sakamoto"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(cgmanalysis)

knitr::opts_knit$set(root.dir = "S:/Laura/BDC/Projects/Erin Cobry/ADA 2022/HCL and Sleep/Data_Raw")
```

```{r}
# doesnt run for subj 209 w2 with removegaps = t
# doesnt run for subj 227

# note 227 files are empty and 228, 233 m6, remoing them from the file list
cleandata("cgm raw","cgm clean", verbose = T, removegaps = F )
cgmvariables("cgm clean",
             outputdirectory = "cgmvariables",
             outputname = "HCLSleep_cgm",
             id_filename = T)
```



```{r}
# load in cleaned set
HCLSleep_cgm <- read.csv("S:/Laura/BDC/Projects/Erin Cobry/ADA 2022/HCL and Sleep/Data_Raw/cgmvariables/HCLSleep_cgm.csv")

# clean it more
HCLSleep_cgm_final = HCLSleep_cgm %>% mutate(id = as.numeric(sapply(strsplit(subject_id,"_"), `[`, 1)),
                                             vis = sapply(strsplit(subject_id,"_"), `[`, 2)) %>% select(-subject_id)
```


```{r}
# write csv for merging
write.csv(HCLSleep_cgm_final, file = "HCLSLEEP_CGM.csv")
```

