---
title: "ZnT8 Trasnporter Haploinsufficiency"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(dplyr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

home_dir = ifelse(.Platform$OS.type != "unix","B:/Projects/Howard Davidson/Zinc transporter/Data raw",
                  "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
knitr::opts_knit$set(root.dir = home_dir)

```

```{r, include=FALSE}
# read in data
fig3 <- read.csv("./Fig 3 Calcuim Oscillation.csv")
fig3 <- data.frame(t(fig3))
colnames(fig3) <- "Calcium oscillation"
fig3$genotype <- ifelse(grepl("WT",rownames(fig3)),"WT",
                        ifelse(grepl("KO",rownames(fig3)),"KO","HE"))
fig3$treatment <- ifelse(grepl("Non",rownames(fig3)),"Non-treatment","Treatment")

fig4_atp <- read.csv("./Fig 4 ATP production.csv")
fig4_atp <- data.frame(t(fig4_atp))
colnames(fig4_atp) <- "ATP production"
fig4_atp$genotype <- ifelse(grepl("WT",rownames(fig4_atp)),"WT",
                        ifelse(grepl("KO",rownames(fig4_atp)),"KO","HE"))
fig4_atp$treatment <- ifelse(grepl("Non",rownames(fig4_atp)),"Non-treatment","Treatment")

fig4_basalresp <- read.csv("./Fig 4 Basal respiration.csv")
fig4_basalresp <- data.frame(t(fig4_basalresp))
colnames(fig4_basalresp) <- "ATP production"
fig4_basalresp$genotype <- ifelse(grepl("WT",rownames(fig4_basalresp)),"WT",
                        ifelse(grepl("KO",rownames(fig4_basalresp)),"KO","HE"))
fig4_basalresp$treatment <- ifelse(grepl("Non",rownames(fig4_basalresp)),"Non-treatment","Treatment")

fig4_maxresp <- read.csv("./Fig 4 Maximal respiration.csv")
fig4_maxresp <- data.frame(t(fig4_maxresp))
colnames(fig4_maxresp) <- "ATP production"
fig4_maxresp$genotype <- ifelse(grepl("WT",rownames(fig4_maxresp)),"WT",
                        ifelse(grepl("KO",rownames(fig4_maxresp)),"KO","HE"))
fig4_maxresp$treatment <- ifelse(grepl("Non",rownames(fig4_maxresp)),"Non-treatment","Treatment")

fig4_protonleak <- read.csv("./Fig 4 Proton leak.csv")
fig4_protonleak <- data.frame(t(fig4_protonleak))
colnames(fig4_protonleak) <- "ATP production"
fig4_protonleak$genotype <- ifelse(grepl("WT",rownames(fig4_protonleak)),"WT",
                        ifelse(grepl("KO",rownames(fig4_protonleak)),"KO","HE"))
fig4_protonleak$treatment <- ifelse(grepl("Non",rownames(fig4_protonleak)),"Non-treatment","Treatment")
```

# Background

# Methods

# Results

```{r echo=FALSE}
kable(t1,caption = "")
```

