---
title: "CGM FDA"
author: "Laura Pyle & Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
    theme:
      light: flatly
      dark: darkly
bibliography: /Users/timvigers/Documents/Miscellaneous/zotero.bib
csl: /Users/timvigers/GitHub/styles/american-medical-association.csl
editor: source
---

```{r libraries and import}
#| include: false
library(tidyverse)
library(tidyfun)
load("/Users/timvigers/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/BDC/Andrea Steck/Advanced CGM and OGTT/Data_Clean/fda_dataset.RData")
```

# Data cleaning

- Timestamps were rounded to the nearest 5-minutes.
- Missing glucose values were not interpolated.

# Figures

```{r}
#| label: fig-indiv-glucose
#| fig-cap: Individual glucose curves
#| message: false
fda_df |>
  ggplot(aes(y = Glucose, color = factor(ID))) +
  geom_spaghetti(alpha = 0.1) +
  facet_wrap(~Group) +
  theme(legend.position = "none")
```

```{r}
#| label: fig-mean-glucose
#| fig-cap: Mean glucose curves
#| message: false
fda_df |>
  group_by(Group) |>
  reframe(mean_gluc = mean(Glucose, na.rm = T)) |>
  mutate(smooth_mean = tfb(mean_gluc, verbose = FALSE)) |>
  ggplot(aes(y = smooth_mean, color = Group)) +
  geom_spaghetti(linewidth = 1.25, alpha = 1)
```


Start with a very simple Cox model
  Outcome is time to diagnosis, standard covariates (age, sex, BMI, etc.) plus TIR or something
  This will tell us more about the data
Maybe try a Cox lasso if possible
For data cleaning, keep it as raw as possible
