---
title: "Advanced CGM and OGTT: Joint Models"
author: "Tim Vigers"
date: "now"
date-format: "MMMM D, YYYY [at] hh:mm a"
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
---

```{r setup}
#| include: false
library(tidyverse)
library(plotly)
library(nlme)
library(JM)
library(ggsurvfit)
library(knitr)
home_dir <- "/Users/tim/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/BDC/Andrea Steck/Advanced CGM and OGTT"
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data cleaning}
# See BDC-Code/Andrea Steck/Advanced CGM and OGTT/create_analysis_dataset.R
load("./Data_Clean/analysis_dataset.RData")
# Calculate age and days from progression or last visit
cgm <- cgm %>%
  mutate(
    Age = as.numeric(difftime(dov_CGM, DOB, units = "days")) / 365.25,
    AgeEndpoint = as.numeric(difftime(LastVisitDate, DOB, units = "days")),
    CGMDaysFromEndpoint = as.numeric(difftime(
      dov_CGM,
      LastVisitDate,
      units = "days"
    ))
  )
# Exclude 05-01813's weird 2019-12-17 CGM per Brigs
cgm <- cgm %>% filter(!(ID == "05-01813" & dov_CGM == "2019-12-17"))
# Time periods per Andrea and Brigs
cgm <- cgm %>%
  mutate(
    nTime = as.numeric(Time),
    TimePeriod = case_when(
      nTime >= 82800 | nTime < 18000 ~ "11pm - 5am",
      nTime >= 18000 & nTime < 39600 ~ "5am - 11am",
      nTime >= 39600 & nTime < 61200 ~ "11am - 5pm",
      nTime >= 61200 & nTime < 82800 ~ "5pm - 11pm",
      .default = "other"
    ),
    # Shift numeric time so that 11pm is our 0
    nTime = ifelse(nTime >= 82800, nTime - 82800, nTime + 3600)
  )
cgm$TimePeriod <- factor(
  cgm$TimePeriod,
  levels = c("11pm - 5am", "5am - 11am", "11am - 5pm", "5pm - 11pm")
)
# For each CGM wear, calculate summary metrics for LMMs
cgm_lmm <- cgm %>%
  filter(CGMDaysFromEndpoint <= 0) %>%
  group_by(
    ID,
    Group,
    sex,
    Race_Ethn2,
    screen_FDR_GP,
    HLAGRP,
    Age
  ) %>%
  summarise(
    mean_glucose = mean(SensorValue, na.rm = TRUE),
    eA1c = (mean_glucose + 46.7) / 28.7,
    sd_glucose = sd(SensorValue, na.rm = TRUE),
    .groups = "drop"
  )
# Create survival dataset
cgm_surv <- cgm %>%
  group_by(
    ID,
    Group,
    sex,
    Race_Ethn2,
    screen_FDR_GP,
    HLAGRP
  ) %>%
  summarise(AgeEndpoint = unique(AgeEndpoint) / 365.25, .groups = "drop") %>%
  rename(Age = AgeEndpoint) %>%
  filter(ID %in% cgm_lmm$ID)
```

# Across the whole day

```{r}
#| label: fig-mean
#| fig-cap: Mean glucose over time
mean_plot <- ggplot(
  cgm_lmm,
  aes(x = Age, y = mean_glucose, color = ID)
) +
  geom_point(alpha = 0.1) +
  geom_line(alpha = 0.5) +
  theme_bw() +
  theme(legend.position = "none")
ggplotly(mean_plot)
```

```{r}
#| label: fig-sd
#| fig-cap: Glucose SD over time
sd_plot <- ggplot(
  cgm_lmm,
  aes(x = Age, y = sd_glucose, color = ID)
) +
  geom_point(alpha = 0.1) +
  geom_line(alpha = 0.5) +
  theme_bw() +
  theme(legend.position = "none")
ggplotly(sd_plot)
```

```{r}
survfit2(
  Surv(Age, as.numeric(Group == "Progressor")) ~ 1,
  data = cgm_surv
) |>
  ggsurvfit() +
  labs(
    x = "Age (years)",
    y = "Overall survival probability"
  ) +
  add_confidence_interval()
```

## Mean glucose

```{r}
lme_fit_mean <- lme(
  mean_glucose ~ Age + sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  random = ~ 1 | ID,
  data = cgm_lmm
)
cox_fit <- coxph(
  Surv(Age, as.numeric(Group == "Progressor")) ~
    sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  x = T,
  model = T,
  data = cgm_surv
)
joint_fit_mean <- jointModel(lme_fit_mean, cox_fit, timeVar = "Age")
s <- summary(joint_fit_mean)
kable(s$`CoefTable-Long`, caption = "Longitudinal Process", digits = 3)
kable(s$`CoefTable-Event`, caption = "Event Process", digits = 3)
```

## SD

```{r}
lme_fit_sd <- lme(
  sd_glucose ~ Age + sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  random = ~ 1 | ID,
  data = cgm_lmm
)
joint_fit_sd <- jointModel(lme_fit_sd, cox_fit, timeVar = "Age")
s <- summary(joint_fit_sd)
kable(s$`CoefTable-Long`, caption = "Longitudinal Process", digits = 3)
kable(s$`CoefTable-Event`, caption = "Event Process", digits = 3)
```

# By time period

```{r}
# For each CGM wear, calculate summary metrics by time period for LMMs
cgm_lmm <- cgm %>%
  filter(CGMDaysFromEndpoint <= 0) %>%
  group_by(
    ID,
    Group,
    sex,
    Race_Ethn2,
    screen_FDR_GP,
    HLAGRP,
    Age,
    TimePeriod
  ) %>%
  summarise(
    mean_glucose = mean(SensorValue, na.rm = TRUE),
    eA1c = (mean_glucose + 46.7) / 28.7,
    sd_glucose = sd(SensorValue, na.rm = TRUE),
    .groups = "drop"
  )
```

```{r}
#| label: fig-mean-period
#| fig-cap: Mean glucose over time by period
mean_plot <- ggplot(
  cgm_lmm,
  aes(x = Age, y = mean_glucose, color = ID)
) +
  geom_point(alpha = 0.1) +
  geom_line(alpha = 0.5) +
  theme_bw() +
  theme(legend.position = "none") +
  facet_wrap(~TimePeriod)
ggplotly(mean_plot)
```

```{r}
#| label: fig-sd-period
#| fig-cap: Glucose SD over time by period
sd_plot <- ggplot(
  cgm_lmm,
  aes(x = Age, y = sd_glucose, color = ID)
) +
  geom_point(alpha = 0.1) +
  geom_line(alpha = 0.5) +
  theme_bw() +
  theme(legend.position = "none") +
  facet_wrap(~TimePeriod)
ggplotly(sd_plot)
```

## 11pm - 5am

### Mean glucose

```{r}
lme_fit_mean <- lme(
  mean_glucose ~ Age + sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  random = ~ 1 | ID,
  data = cgm_lmm[cgm_lmm$TimePeriod == "11pm - 5am", ]
)
joint_fit_mean <- jointModel(lme_fit_mean, cox_fit, timeVar = "Age")
s <- summary(joint_fit_mean)
kable(s$`CoefTable-Long`, caption = "Longitudinal Process", digits = 3)
kable(s$`CoefTable-Event`, caption = "Event Process", digits = 3)
```

### SD

```{r}
lme_fit_sd <- lme(
  sd_glucose ~ Age + sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  random = ~ 1 | ID,
  data = cgm_lmm[cgm_lmm$TimePeriod == "11pm - 5am", ]
)
joint_fit_sd <- jointModel(lme_fit_sd, cox_fit, timeVar = "Age")
s <- summary(joint_fit_sd)
kable(s$`CoefTable-Long`, caption = "Longitudinal Process", digits = 3)
kable(s$`CoefTable-Event`, caption = "Event Process", digits = 3)
```

## 5am - 11am

### Mean glucose

```{r}
lme_fit_mean <- lme(
  mean_glucose ~ Age + sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  random = ~ 1 | ID,
  data = cgm_lmm[cgm_lmm$TimePeriod == "5am - 11am", ]
)
joint_fit_mean <- jointModel(lme_fit_mean, cox_fit, timeVar = "Age")
s <- summary(joint_fit_mean)
kable(s$`CoefTable-Long`, caption = "Longitudinal Process", digits = 3)
kable(s$`CoefTable-Event`, caption = "Event Process", digits = 3)
```

### SD

```{r}
lme_fit_sd <- lme(
  sd_glucose ~ Age + sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  random = ~ 1 | ID,
  data = cgm_lmm[cgm_lmm$TimePeriod == "5am - 11am", ]
)
joint_fit_sd <- jointModel(lme_fit_sd, cox_fit, timeVar = "Age")
s <- summary(joint_fit_sd)
kable(s$`CoefTable-Long`, caption = "Longitudinal Process", digits = 3)
kable(s$`CoefTable-Event`, caption = "Event Process", digits = 3)
```


## 11am - 5pm

### Mean glucose

```{r}
lme_fit_mean <- lme(
  mean_glucose ~ Age + sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  random = ~ 1 | ID,
  data = cgm_lmm[cgm_lmm$TimePeriod == "11am - 5pm", ]
)
joint_fit_mean <- jointModel(lme_fit_mean, cox_fit, timeVar = "Age")
s <- summary(joint_fit_mean)
kable(s$`CoefTable-Long`, caption = "Longitudinal Process", digits = 3)
kable(s$`CoefTable-Event`, caption = "Event Process", digits = 3)
```

### SD

```{r}
lme_fit_sd <- lme(
  sd_glucose ~ Age + sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  random = ~ 1 | ID,
  data = cgm_lmm[cgm_lmm$TimePeriod == "11am - 5pm", ]
)
joint_fit_sd <- jointModel(lme_fit_sd, cox_fit, timeVar = "Age")
s <- summary(joint_fit_sd)
kable(s$`CoefTable-Long`, caption = "Longitudinal Process", digits = 3)
kable(s$`CoefTable-Event`, caption = "Event Process", digits = 3)
```

## 5pm - 11pm

### Mean glucose

```{r}
lme_fit_mean <- lme(
  mean_glucose ~ Age + sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  random = ~ 1 | ID,
  data = cgm_lmm[cgm_lmm$TimePeriod == "5pm - 11pm", ]
)
joint_fit_mean <- jointModel(lme_fit_mean, cox_fit, timeVar = "Age")
s <- summary(joint_fit_mean)
kable(s$`CoefTable-Long`, caption = "Longitudinal Process", digits = 3)
kable(s$`CoefTable-Event`, caption = "Event Process", digits = 3)
```

### SD

```{r}
lme_fit_sd <- lme(
  sd_glucose ~ Age + sex + Race_Ethn2 + screen_FDR_GP + HLAGRP,
  random = ~ 1 | ID,
  data = cgm_lmm[cgm_lmm$TimePeriod == "5pm - 11pm", ]
)
joint_fit_sd <- jointModel(lme_fit_sd, cox_fit, timeVar = "Age")
s <- summary(joint_fit_sd)
kable(s$`CoefTable-Long`, caption = "Longitudinal Process", digits = 3)
kable(s$`CoefTable-Event`, caption = "Event Process", digits = 3)
```