---
title: "Eitan's Figures"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/BMD Lifespan")
library(sas7bdat)
library(tidyverse)
```

```{r echo=FALSE}
merall_use <- read.sas7bdat("./Data_raw/bmdlifespan10.10.19.sas7bdat")
merall_use$Agegroup <- as.factor(merall_use$Agegroup)
merall_use$MenopauseStatus <- 
  ifelse(merall_use$postmenopausal== 1,"Post-Menopausal",merall_use$PREMENOPAUSAL)
merall_use$MenopauseStatus[which(merall_use$MenopauseStatus=="1")] <- "Pre-Menopausal"
```

# By sex

## Lumbar Spine BMD

```{r echo=FALSE,dpi=1200}
by_sex <- merall_use %>% group_by(Sex,T1DStatus,Agegroup) %>% 
  summarise(mean = mean(BMDLumbarTotal),
            se = sd(BMDLumbarTotal)/sqrt(length(BMDLumbarTotal)))

by_sex_plot <- ggplot(by_sex,aes(Agegroup,mean,fill=T1DStatus)) + 
  geom_bar(stat = "identity",color="black",position=position_dodge()) + 
  geom_errorbar(aes(ymin=mean-se,ymax=mean+se),width = 0.3,
                position = position_dodge(0.9)) +
  facet_grid(~Sex) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  xlab("Age Group") +
  ylab("BMDLumbarTotal")
by_sex_plot
```

# By menopause status

## Lumbar BMD

```{r echo=FALSE,dpi=1200}
by_meno <- merall_use %>% filter(Sex=="F",!is.na(MenopauseStatus)) %>% 
  group_by(MenopauseStatus,T1DStatus,Agegroup) %>% 
  summarise(mean = mean(BMDLumbarTotal),
            se = sd(BMDLumbarTotal)/sqrt(length(BMDLumbarTotal)))

by_meno_plot <- ggplot(by_meno,aes(Agegroup,mean,fill=T1DStatus)) + 
  geom_bar(stat = "identity",color="black",position=position_dodge()) + 
  geom_errorbar(aes(ymin=mean-se,ymax=mean+se),width = 0.3,
                position = position_dodge(0.9)) +
  facet_grid(~MenopauseStatus) +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  ylab("BMDLumbarTotal")
by_meno_plot
```

## Left Hip BMD

```{r echo=FALSE,dpi=1200}
by_meno_hip <- merall_use %>% filter(Sex=="F",!is.na(MenopauseStatus)) %>% 
  group_by(MenopauseStatus,T1DStatus,Agegroup) %>% 
  summarise(mean = mean(BMDTotalLHip),
            se = sd(BMDTotalLHip)/sqrt(length(BMDTotalLHip)))

by_meno_hip_plot <- ggplot(by_meno_hip,aes(Agegroup,mean,fill=T1DStatus)) + 
  geom_bar(stat = "identity",color="black",position=position_dodge()) + 
  geom_errorbar(aes(ymin=mean-se,ymax=mean+se),width = 0.3,
                position = position_dodge(0.9)) +
  facet_grid(~MenopauseStatus) +
  theme_bw() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ylab("BMDTotalLHip")
by_meno_hip_plot
```

## Left Neck BMD

```{r echo=FALSE,dpi=1200}
by_meno_neck <- merall_use %>% filter(Sex=="F",!is.na(MenopauseStatus)) %>% 
  group_by(MenopauseStatus,T1DStatus,Agegroup) %>% 
  summarise(mean = mean(BMDLNeck),
            se = sd(BMDLNeck)/sqrt(length(BMDLNeck)))

by_meno_neck_plot <- ggplot(by_meno_neck,aes(Agegroup,mean,fill=T1DStatus)) + 
  geom_bar(stat = "identity",color="black",position=position_dodge()) + 
  geom_errorbar(aes(ymin=mean-se,ymax=mean+se),width = 0.3,
                position = position_dodge(0.9)) +
  facet_grid(~MenopauseStatus) +
  theme_bw() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ylab("BMDLNeck")
by_meno_neck_plot
```

# Age vs. Lumbar BMD

```{r echo=FALSE,message=FALSE,dpi=1200}
age_lumbar <- ggplot(merall_use,aes(AgeYr,BMDLumbarTotal,color=T1DStatus))+
  geom_point() +
  geom_smooth() +
  facet_grid(~Sex) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
age_lumbar
```