---
title: "BMT CGM Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(redcapAPI)
library(tableone)
library(skimr)
library(knitr)
library(tidyverse)
```

```{r include=FALSE,cache=TRUE}
# REDCap API data import
source("/Users/timvigers/Documents/GitHub/BDC-Code/api_tokens.R")
rcon <- redcapConnection(url = "https://redcap.ucdenver.edu/api/",
                         token = BMT_CGM)
data_full <- exportRecords(rcon)
# Format columns
data_full$bmi_percentile <- as.numeric(data_full$bmi_percentile)
```

```{r echo=FALSE}
# Get demographic info
demographics <- data_full %>% group_by(study_id) %>% filter(!is.na(mrn))
# Combine separate race columns into one
levels(demographics$race___0) <- c(NA,"AI or AN")
levels(demographics$race___1) <- c(NA,"Asian")
levels(demographics$race___2) <- c(NA,"African American")
levels(demographics$race___3) <- c(NA,"NH or PI")
levels(demographics$race___4) <- c(NA,"White")
levels(demographics$race___5) <- c(NA,"Hispanic")
levels(demographics$race___6) <- c(NA,"Other")
demographics <- demographics %>% ungroup() %>% unite("Race",race___0,race___1,race___2,race___3,race___4,race___5,race___6)
demographics$Race <- gsub("NA","",demographics$Race)
demographics$Race <- gsub("_","",demographics$Race)
demographics$Race[which(demographics$race_multi == "yes")] <- "Multiple"
demographics$Race[which(demographics$Race == "")] <- "Unknown"
# Calculate age at transplant
demographics$AgeTx <- as.numeric(difftime(demographics$date_of_tx,demographics$date_of_birth,units = "days")) / 365.25
```

## Table 1: Descriptive Characteristics

```{r echo=FALSE}
dem_vars <- c("AgeTx","bmi_percentile","gender","Race","tanner_stage","tx_type","primary_dx_cat","spec_dx_cat")
t1 <- CreateTableOne(dem_vars,data = demographics)
t1 <- print(t1, nonnormal = c("AgeTx","bmi_percentile"),printToggle = F)
kable(t1)
```

## Table 2: Feasibility/Safety

```{r echo=FALSE}
# Get CGM data
cgm_data <- data_full %>% filter(is.na(redcap_repeat_instrument)) %>%
  select(study_id,date_of_tx,
         sens1_place,plt1,transfuse1,bleed1,sens1_remove,sens1_reason,
         sens2_place,plt2,transfuse2,bleed2,sens2_remove,sens2_reason,
         sens3_place,plt3,transfuse3,bleed3,sens3_remove,sens3_reason,
         sens4_place,plt4,transfuse4,bleed4,sens4_remove,sens4_reason,
         sens5_place,plt5,transfuse5,bleed5,sens5_remove,sens5_reason,
         sens6_place,plt6,transfuse6,bleed6,sens6_remove,sens6_reason)

colnames(cgm_data) <- c("study_id","date_of_tx",
                        "sens_place.1","plt.1","transfuse.1","bleed.1","sens_remove.1","sens_reason.1",
                        "sens_place.2","plt.2","transfuse.2","bleed.2","sens_remove.2","sens_reason.2",
                        "sens_place.3","plt.3","transfuse.3","bleed.3","sens_remove.3","sens_reason.3",
                        "sens_place.4","plt.4","transfuse.4","bleed.4","sens_remove.4","sens_reason.4",
                        "sens_place.5","plt.5","transfuse.5","bleed.5","sens_remove.5","sens_reason.5",
                        "sens_place.6","plt.6","transfuse.6","bleed.6","sens_remove.6","sens_reason.6")

# Wide to long
cgm_data <- reshape(cgm_data,idvar = c("study_id","date_of_tx"),
                varying = colnames(cgm_data)[3:ncol(cgm_data)],
                direction = "long")
# Remove blank rows based on sensor placement date, format DF, calculate days of CGM wear
cgm_data <- cgm_data %>% filter(!is.na(sens_place)) %>% 
  arrange(as.numeric(study_id)) %>%
  mutate(days_worn_total = as.numeric(difftime(sens_remove,sens_place,units = 'days')),
         days_worn_pre_tx = 
           pmax(days_worn_total - pmax(as.numeric(difftime(sens_remove,date_of_tx,units = 'days')),0),0),
         days_worn_post_tx = 
           pmax(days_worn_total - pmax(as.numeric(difftime(date_of_tx,sens_place,units = 'days')),0),0))

check <- cgm_data %>% select(study_id,sens_place,sens_remove,date_of_tx,days_worn_total,days_worn_pre_tx,days_worn_post_tx)

# Summary variables
cgm_summary <- cgm_data %>% group_by(study_id) %>%
  summarise(num_cgms = n(),
            total_days_worn = sum(days_worn,na.rm = T),
            last_cgm_removal_post_tx = last(days_from_tx[which(sens_remove > date_of_tx)])) %>%
  arrange(as.numeric(study_id))
# Add AE information
ae <- data_full %>% filter(adv_event == "Yes") %>% select(study_id,adv_event:ae_attrib) %>%
  group_by(study_id) %>%
  summarise(bleeding = sum(ae_type___4 == "Checked",na.rm = T),
            infection = sum(ae_type___2 == "Checked",na.rm = T),
            skin_reaction = sum((ae_type___0 == "Checked" | ae_type___1 == "Checked"),na.rm = T),
            other = sum(ae_type___5 == "Checked",na.rm = T))
cgm_summary <- full_join(cgm_summary,ae,by = "study_id")
```

## Notes
- Number of CGMs was counted based on the number of non-missing sensor placement dates.
- "% of pre-HSCT hospital days with CGM in place" is actually just number of days, not a percentage (same for post).