---
title: "HCL Overnight Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(tools)
library(arsenal)
library(cgmanalysis)
library(car)
library(skimr)
library(Hmisc)
library(knitr)
library(lmerTest)
library(nlme)
library(performance)
library(MASS)
library(tidyverse)
library(broom)
library(broom.mixed)
library(lubridate)
library(emmeans)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r echo=FALSE,include=FALSE}
# Import Cari's data
source("~/GitHub/BDC-Code/Erin Cobry/Nocturnal Alarms/AdvancedClosedLoopCl_R_2020-01-05_1101.r")
# Demographics
demographics <- data %>% 
  filter(redcap_event_name %in% c("baseline_arm_1","baseline_arm_2"),
         !is.na(child_ya))
# remove missing
no_data <- c("27","30","38","41")
demographics <- demographics[-c(which(demographics$record_id %in% no_data)),]
# Manually corrected a few dates in CSV file.
# Read in (manually converted to long format from Erin's Excel spreadsheet)
overnight_alarms <- read.csv("./Erin Cobry/Nocturnal Alarms/Data_Cleaned/nocturnal_alarms.csv",
                             na.strings = c("","No Data"))
overnight_alarms = overnight_alarms[overnight_alarms$num_nights > 0,]
daytime_alarms = read.csv("./Erin Cobry/Nocturnal Alarms/Data_Cleaned/daytime_alarms.csv",
                          na.strings = c("","No Data"))
daytime_alarms = daytime_alarms[daytime_alarms$num_days > 0,]
# Match IDs and filter
dates = read.csv("./Erin Cobry/Nocturnal Alarms/Data_Cleaned/subject_dates.csv")
overnight_alarms$id = dates$id[match(gsub(" ","",overnight_alarms$id),tolower(gsub(" ","",dates$name)))]
overnight_alarms <- overnight_alarms %>% filter(!(id %in% no_data))
daytime_alarms$id = dates$id[match(gsub(" ","",daytime_alarms$id),tolower(gsub(" ","",dates$name)))]
daytime_alarms <- daytime_alarms %>% filter(!(id %in% no_data))
# Format date columns
overnight_alarms[,c("start_date","end_date")] <- 
  lapply(overnight_alarms[,c("start_date","end_date")], 
         function(x) {lubridate::mdy(as.character(x))})
daytime_alarms[,c("start_date","end_date")] <- 
  lapply(daytime_alarms[,c("start_date","end_date")], 
         function(x) {lubridate::mdy(as.character(x))})
# Numeric timepoints in months
overnight_alarms$numeric_time <- 
  car::recode(overnight_alarms$timepoint,
              "'Baseline' = 0;'Post' = 0.5;'T1' = 3;'T2' = 6;'T3' = 9;'T4' = 12")
overnight_alarms$numeric_time <- 
  as.numeric(as.character(overnight_alarms$numeric_time))
daytime_alarms$numeric_time <- 
  car::recode(daytime_alarms$timepoint,
              "'Baseline' = 0;'Post' = 0.5;'T1' = 3;'T2' = 6;'T3' = 9;'T4' = 12")
daytime_alarms$numeric_time <- 
  as.numeric(as.character(daytime_alarms$numeric_time))
# Combine nocturnal and daytime
overnight_alarms$hours = overnight_alarms$num_nights*8
overnight_alarms = overnight_alarms %>% 
  select(id:end_date,numeric_time,hours,num_alarms:other_alarms)
daytime_alarms$hours = daytime_alarms$num_days*16
daytime_alarms = daytime_alarms %>%
  select(id:end_date,numeric_time,hours,num_alarms:other_alarms)
# Get Erin's participants 
demographics <- demographics[which(demographics$record_id %in% overnight_alarms$id),]
# Combine CGM and pump hx levels
levels(demographics$demographics_cgmhx.factor) <-
  c("< 1 month","> 1 month","> 1 month","> 1 month","> 1 month","> 1 month")
levels(demographics$demographics_pumphx.factor) <-
  c("< 1 month","> 1 month","> 1 month","> 1 month","> 1 month","> 1 month")
# Time from AM start
demographics$id = as.numeric(demographics$record_id)
overnight_alarms = left_join(overnight_alarms,demographics[,c("id","automode_start")],by = "id")
overnight_alarms$automode_start = ymd(overnight_alarms$automode_start)
overnight_alarms$days_from_am_start = 
  as.numeric(difftime(overnight_alarms$start_date,
                      overnight_alarms$automode_start,units = "days"))
```

# Descriptive Characteristics

# *WHY IS N DIFFERENT HERE*

```{r echo=FALSE,results='asis'}
# Labels
labels <- list(demographics_t1d_duration = "Diabetes Dur. (years)", 
               demographics_ethnicity.factor = "Ethnicity",
               demographics_sex.factor = "Sex",
               demographics_cgmhx.factor = "CGM History", 
               demographics_pumphx.factor = "Pump History")
# Table 1
t1 <- tableby(~ hba1c + kwt(demographics_age,"median","q1q3","range") + 
                kwt(demographics_t1d_duration,"median","q1q3") + 
                demographics_sex.factor + demographics_ethnicity.factor +
                demographics_cgmhx.factor + demographics_pumphx.factor,
              data = demographics)
# Print
summary(t1,labelTranslations = labels)
```

```{r echo=FALSE,include=FALSE}
# Read in CGM data
cgm <- read.csv("./Erin Cobry/Nocturnal Alarms/Data_Cleaned/cgm_variables.csv",stringsAsFactors = F)
# ID and timepoint
cgm$id <- as.numeric(gsub("[[:alpha:]]","",sapply(strsplit(cgm$subject_id,"_"),`[[`,1)))
cgm$timepoint <- sapply(strsplit(cgm$subject_id,"_"),`[[`,2)
cgm$timepoint[cgm$timepoint == "week 2"] = "Post"
# Select columns
cgm <- cgm %>% select(id,timepoint,nighttime_avg_sens_glucose,
                      percent_time_70_180_night,percent_time_under_70_night)
# Merge
overnight_alarms <- left_join(overnight_alarms,cgm,by = c("id","timepoint"))
# Read in corrected AM data
am_correct <- read.csv("./Erin Cobry/Nocturnal Alarms/Data_Cleaned/REDCap AM Data.csv")
am_correct$timepoint[am_correct$timepoint == "week 2"] = "Post"
# Add to overnight alarms
overnight_alarms <- left_join(overnight_alarms,am_correct,by = c("id", "timepoint"))
# Order timepoints
overnight_alarms$timepoint <- factor(overnight_alarms$timepoint,
                                     levels = c("Baseline","Post","T1","T2","T3","T4" ))
levels(overnight_alarms$timepoint) <- c("Baseline","Week 2",
                                        "T1","T2","T3","T4" )
overnight_alarms = overnight_alarms %>% arrange(id,timepoint)
# Calc
# Remove discontinuers
discont = overnight_alarms %>% group_by(id) %>% 
  summarise(discont = any(sensor_wear <= 10,na.rm = T)) %>%
  filter(discont == T) %>% .$id
```

Discontinuers were defined as any participant who had $\leq$ 10% sensor wear at any timepoint. These participants were excluded from all models below. 

# Longitudinal Analysis

```{r echo=FALSE}
overnight_alarms = overnight_alarms %>% filter(!id %in% discont)
```

All alarms were analyzed using a linear mixed model with random intercept for participant.

```{r}
# Model function
fit_mod = function(outcome,df = overnight_alarms){
  # Random intercept (not enough data for a random slope)
  f = as.formula(paste0(outcome,"~ timepoint+offset(hours)+(1|id)"))
  list2env(list(f=f,df=df),.GlobalEnv)
  mod_ri <- glmer(f,family = poisson(),data = df)
  results <- tidy(mod_ri_car1,effects = "fixed",conf.int = T)
  results$term <- sub("timepoint","",results$term)
  results$p.value <- format.pval(results$p.value,eps = 0.001,digits = 2)
  # Anova
  an_res <- as.data.frame(Anova(mod_ri_car1,type = 3))
  list2env(list(an_res=an_res),.GlobalEnv)
  # Print
  cat("\n")
  cat("### Model Results - Unadjusted")
  cat("\n")
  cat("#### Comparison to Baseline")
  cat("\n")
  print(kable(results[,c("term","estimate","conf.low","conf.high","p.value")],digits = 2))
  # Timepoint means
  emm1 = emmeans(mod_ri_car1,~timepoint)
  means = data.frame(emm1)
  cat("\n")
  cat("#### Mean at Each Timepoint")
  cat("\n")
  print(kable(means,digits = 2))
  means$numeric_time = c(0,0.5,3,6,9,12)
  # Compare to week 2
  base = c(1,0,0,0,0,0)
  w2 = c(0,1,0,0,0,0)
  t1 = c(0,0,1,0,0,0)
  t2 = c(0,0,0,1,0,0)
  t3 = c(0,0,0,0,1,0)
  t4 = c(0,0,0,0,0,1)
  con = contrast(emm1,method = list("Baseline to Week 2"= w2 - base,
                                    "Week 2 to T1"=t1 - w2,
                                    "Week 2 to T2"=t2 - w2,
                                    "Week 2 to T3"=t3 - w2,
                                    "Week 2 to T4"=t4 - w2))
  cat("\n")
  cat("#### Comparison to Week 2")
  cat("\n")
  print(kable(con,digits = 2))
}
```

## Alarms per Hour (Night) By Timepoint

```{r echo=FALSE,message=FALSE,results='asis'}
#fit_mod(outcome = "num_alarms")
```
