---
title: "PICLS data cleaning"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---
  
```{r setup, include=FALSE}
library(readxl)
library(skimr)
library(DT)
library(dplyr)
```

# Baseline participant questionnaire

```{r }
# Baseline participant questionnaire
#source("C:/Users/pylell/Documents/GitHub/BDC-Code/Sarit Polsky/PICLS/Data cleaning/PICLSStudyHCLVsSAPTI-BaselineDemographics_R_2022-08-16_1707.r")
#baseline <- data
baseline <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI-BaselineParticipantQ_DATA_LABELS_2022-08-16_1734.csv",na.strings = c(""," "))
skim(baseline)
datatable(baseline)

baseline$ins_missing <- ifelse(baseline$Health.Insurance...choose.all.that.apply..choice.Aetna.=="Unchecked" &
                                 baseline$Health.Insurance...choose.all.that.apply..choice.Blue.Cross.Blue.Shield.=="Unchecked" &
                                 baseline$Health.Insurance...choose.all.that.apply..choice.Cigna.=="Unchecked" &
                                 baseline$Health.Insurance...choose.all.that.apply..choice.Humana.=="Unchecked" & 
                                 baseline$Health.Insurance...choose.all.that.apply..choice.Medicaid.=="Unchecked" &
                                 baseline$Health.Insurance...choose.all.that.apply..choice.Medicare.=="Unchecked" &
                                 baseline$Health.Insurance...choose.all.that.apply..choice.United.Health.Care.=="Unchecked" &
                                 baseline$Health.Insurance...choose.all.that.apply..choice.Other.=="Unchecked" &
                                 baseline$Health.Insurance...choose.all.that.apply..choice.Tricare.=="Unchecked",1,0)
```

# Obstetric history

```{r }
# obstetric history - enabled as survey
ob_hx <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI_DATA_2022-08-17_1712.csv",na.strings = c(""," "))
ob_hx <- ob_hx %>% filter(!is.na(redcap_repeat_instrument))
ob_hx$sum_comp <- rowSums(ob_hx[,c("obs_pregnancy_compl_types___1","obs_pregnancy_compl_types___2",
                                   "obs_pregnancy_compl_types___3","obs_pregnancy_compl_types___4",
                                   "obs_pregnancy_compl_types___5","obs_pregnancy_compl_types___6",
                                   "obs_pregnancy_compl_types___7","obs_pregnancy_compl_types___8")])
ob_hx$sum_labor_comp <- rowSums(ob_hx[,c("obs_labor_compl_types___1","obs_labor_compl_types___10",
                                         "obs_labor_compl_types___11","obs_labor_compl_types___12",
                                         "obs_labor_compl_types___13","obs_labor_compl_types___14",
                                         "obs_labor_compl_types___15","obs_labor_compl_types___16",
                                         "obs_labor_compl_types___17","obs_labor_compl_types___2",
                                         "obs_labor_compl_types___3","obs_labor_compl_types___4",
                                         "obs_labor_compl_types___5","obs_labor_compl_types___6",
                                         "obs_labor_compl_types___7","obs_labor_compl_types___8",
                                         "obs_labor_compl_types___9")])

skim(ob_hx)
datatable(ob_hx)
```

# Preconception

```{r }
# Preconception
precon <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI-Preconception_DATA_2022-08-17_1728.csv",na.strings = c(""," "))
skim(precon)
datatable(precon)
```

# Exemption

```{r }
# exemption waiver
waiver <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI-ExemptionWaiver_DATA_2022-08-17_2242.csv",na.strings = c(""," "))
waiver[,c("incl___1","incl___2","incl___3","incl___4","incl___5","incl___6","incl___7",
                                     "incl___8","incl___9","incl___10","incl___11","incl___12","incl___13")] <- apply(waiver[,c("incl___1","incl___2","incl___3","incl___4","incl___5","incl___6","incl___7",
                                     "incl___8","incl___9","incl___10","incl___11","incl___12","incl___13")],
                2,as.numeric)

waiver$sum_incl <- rowSums(waiver[,c("incl___1","incl___2","incl___3","incl___4","incl___5","incl___6","incl___7",
                                     "incl___8","incl___9","incl___10","incl___11","incl___12","incl___13")])

skim(waiver)
datatable(waiver)
```

# SMBG Questionnaire Run-in

```{r }
# started working on this form, not sure about range of insulin doses
# this is going to be a pain because of all the variables on the form

# SMBG run-in
smbg_runin <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI-SMBGQuestionnaireRun_DATA_2022-08-18_1643.csv",na.strings = c(""," "))
smbg_runin <- smbg_runin %>% filter(!is.na(smbg_runin$redcap_repeat_instance))

skim(smbg_runin)
datatable(smbg_runin)
```

# SMBG Questionnaire Randomization

```{r }
# SMBG randomization
smbg_rand <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI-SMBGQuestionnaireRan_DATA_2022-08-18_1644.csv",na.strings = c(""," "))

skim(smbg_rand)
datatable(smbg_rand)
```

# Acetaminophen

```{r }
# Acetaminophen
acet <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI-Acetaminophen_DATA_2022-08-19_2247.csv",na.strings = c(""," "))

skim(acet)
datatable(acet)
```

# Food Log

```{r }
# Food log
food_log <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI-FoodLog_DATA_2022-08-19_2255.csv",na.strings = c(""," "))
food_log <- food_log %>% filter(!is.na(redcap_repeat_instrument))

skim(food_log)
datatable(food_log)
```

# Nutrition counseling

```{r }
# nutrition counseling
nutcouns <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI-NutritionCounseling_DATA_2022-08-21_1205.csv",na.strings = c(""," "))

skim(nutcouns)
datatable(nutcouns)
```

# Retinopathy

```{r }
# Retinopathy
retinopathy <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI-Retinopathy_DATA_2022-08-21_1212.csv",na.strings = c(""," "))

skim(retinopathy)
datatable(retinopathy)
```

# Labs

```{r }
# Labs
labs <- read.csv("B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data files/PICLSStudyHCLVsSAPTI-Labs_DATA_LABELS_2022-10-26_1235.csv",na.strings = c(""," "))

# reshape dataset
# want 1 record per trimester, with a column for each type of result
labs0 <- labs %>% select(Participant.ID,Lab.Collection.Trimester,Date.lab.s..was.were.obtained,Lab.name,If.other..specify.lab.name,
                         Lab.value,Lab.units,If.other..specify.lab.units,Note..Please.notate.anything.important.about.the.lab.collection.that.was.not.previously.stated)
colnames(labs0) <- c("Participant.ID","Trimester","Lab.Date","Lab.Name","Other.Lab.Name","Lab.Value","Lab.Units","Other.Lab.Units","Notes")

labs1 <- labs %>% select(Participant.ID,Lab.Collection.Trimester,Date.lab.s..was.were.obtained.1,Lab.name.1,If.other..specify.lab.name.1,
                         Lab.value.1,Lab.units.1,If.other..specify.lab.units.1,Note..Please.notate.anything.important.about.the.lab.collection.that.was.not.previously.stated.1)
colnames(labs1) <- c("Participant.ID","Trimester","Lab.Date","Lab.Name","Other.Lab.Name","Lab.Value","Lab.Units","Other.Lab.Units","Notes")

labs2 <- labs %>% select(Participant.ID,Lab.Collection.Trimester,Date.lab.s..was.were.obtained.2,Lab.name.2,If.other..specify.lab.name.2,
                         Lab.value.2,Lab.units.2,If.other..specify.lab.units.2,Note..Please.notate.anything.important.about.the.lab.collection.that.was.not.previously.stated.2)
colnames(labs2) <- c("Participant.ID","Trimester","Lab.Date","Lab.Name","Other.Lab.Name","Lab.Value","Lab.Units","Other.Lab.Units","Notes")

labs3 <- labs %>% select(Participant.ID,Lab.Collection.Trimester,Date.lab.s..was.were.obtained.3,Lab.name.3,If.other..specify.lab.name.3,
                         Lab.value.3,Lab.units.3,If.other..specify.lab.units.3,Note..Please.notate.anything.important.about.the.lab.collection.that.was.not.previously.stated.3)
colnames(labs3) <- c("Participant.ID","Trimester","Lab.Date","Lab.Name","Other.Lab.Name","Lab.Value","Lab.Units","Other.Lab.Units","Notes")

labs4 <- labs %>% select(Participant.ID,Lab.Collection.Trimester,Date.lab.s..was.were.obtained.4,Lab.name.4,If.other..specify.lab.name.4,
                         Lab.value.4,Lab.units.4,If.other..specify.lab.units.4,Note..Please.notate.anything.important.about.the.lab.collection.that.was.not.previously.stated.4)
colnames(labs4) <- c("Participant.ID","Trimester","Lab.Date","Lab.Name","Other.Lab.Name","Lab.Value","Lab.Units","Other.Lab.Units","Notes")

labs5 <- labs %>% select(Participant.ID,Lab.Collection.Trimester,Date.lab.s..was.were.obtained.5,Lab.name.5,If.other..specify.lab.name.5,
                         Lab.value.5,Lab.units.5,If.other..specify.lab.units.5,Note..Please.notate.anything.important.about.the.lab.collection.that.was.not.previously.stated.5)
colnames(labs5) <- c("Participant.ID","Trimester","Lab.Date","Lab.Name","Other.Lab.Name","Lab.Value","Lab.Units","Other.Lab.Units","Notes")

labs6 <- labs %>% select(Participant.ID,Lab.Collection.Trimester,Date.lab.s..was.were.obtained.6,Lab.name.6,If.other..specify.lab.name.6,
                         Lab.value.6,Lab.units.6,If.other..specify.lab.units.6,Note..Please.notate.anything.important.about.the.lab.collection.that.was.not.previously.stated.6)
colnames(labs6) <- c("Participant.ID","Trimester","Lab.Date","Lab.Name","Other.Lab.Name","Lab.Value","Lab.Units","Other.Lab.Units","Notes")

labs7 <- labs %>% select(Participant.ID,Lab.Collection.Trimester,Date.lab.s..was.were.obtained.7,Lab.name.7,If.other..specify.lab.name.7,
                         Lab.value.7,Lab.units.7,If.other..specify.lab.units.7,Note..Please.notate.anything.important.about.the.lab.collection.that.was.not.previously.stated.7)
colnames(labs7) <- c("Participant.ID","Trimester","Lab.Date","Lab.Name","Other.Lab.Name","Lab.Value","Lab.Units","Other.Lab.Units","Notes")

labs8 <- labs %>% select(Participant.ID,Lab.Collection.Trimester,Date.lab.s..was.were.obtained.8,Lab.name.8,If.other..specify.lab.name.8,
                         Lab.value.8,Lab.units.8,If.other..specify.lab.units.8,Note..Please.notate.anything.important.about.the.lab.collection.that.was.not.previously.stated.8)
colnames(labs8) <- c("Participant.ID","Trimester","Lab.Date","Lab.Name","Other.Lab.Name","Lab.Value","Lab.Units","Other.Lab.Units","Notes")

labs9 <- labs %>% select(Participant.ID,Lab.Collection.Trimester,Date.lab.s..was.were.obtained.9,Lab.name.9,If.other..specify.lab.name.9,
                         Lab.value.9,Lab.units.9,If.other..specify.lab.units.9,Note..Please.notate.anything.important.about.the.lab.collection.that.was.not.previously.stated.9)
colnames(labs9) <- c("Participant.ID","Trimester","Lab.Date","Lab.Name","Other.Lab.Name","Lab.Value","Lab.Units","Other.Lab.Units","Notes")

labs_new <- rbind(labs0,labs1,labs2,labs3,labs4,labs5,labs6,labs7,labs8,labs9)
labs_new <- labs_new %>% select("Participant.ID","Trimester","Lab.Date","Lab.Name","Lab.Value","Lab.Units","Notes")
labs_new$Lab.Value <- ifelse(labs_new$Lab.Value=="<1",0.5,labs_new$Lab.Value)
labs_new$Lab.Value <- ifelse(labs_new$Lab.Value=="<130",65,labs_new$Lab.Value)
labs_new$Lab.Value <- ifelse(labs_new$Lab.Value=="<28",14,labs_new$Lab.Value)
labs_new$Lab.Value <- ifelse(labs_new$Lab.Value=="<4",2,labs_new$Lab.Value)
labs_new$Lab.Value <- ifelse(labs_new$Lab.Value=="<98",49,labs_new$Lab.Value)
labs_new$Lab.Value <- as.numeric(labs_new$Lab.Value)
# fix one lab name
labs_new$Lab.Name <- ifelse(labs_new$Lab.Name=="24-hour urine protein level","24-hour urine total protein level",labs_new$Lab.Name)

# now divide by type of assay and check units
creat_24 <- labs_new %>% filter(Lab.Name=="24-hour urine creatinine level")
creat_24$Lab.Value <- ifelse(creat_24$Lab.Units=="g/D",creat_24$Lab.Value*1000,creat_24$Lab.Value)
# there is still one value with units mL - not sure what to do with that
unit_prob <- creat_24 %>% filter(Lab.Units=="ml")

prot_24 <- labs_new %>% filter(Lab.Name=="24-hour urine total protein level")
prot_24$Lab.Units <- ifelse(prot_24$Lab.Units=="mg/dl","mg/dL",prot_24$Lab.Units)
# 6 entries have units mg/D
temp <- prot_24 %>% filter(Lab.Units=="mg/D")
unit_prob <- rbind(unit_prob,temp)

urine_vol_24 <- labs_new %>% filter(Lab.Name=="24-hour urine volume")
urine_vol_24$Lab.Units <- ifelse(urine_vol_24$Lab.Units=="ml","mL",urine_vol_24$Lab.Units)

hdl <- labs_new %>% filter(Lab.Name=="HDL level")
# no unit issues

serum_creat <- labs_new %>% filter(Lab.Name=="Serum creatinine")
# no unit issues

thyroglobulin <- labs_new %>% filter(Lab.Name=="Thyroglobulin antibody level")
# no unit issues

thyroid_perox <- labs_new %>% filter(Lab.Name=="Thyroid peroxidase antibody level")
# is IU/mL the same as U/mL?
thyroid_perox$Lab.Units <- ifelse(thyroid_perox$Lab.Units %in% c("IU/mL","U/ml"),"U/mL",thyroid_perox$Lab.Units)

tsh <- labs_new %>% filter(Lab.Name=="Thyroid stimulating hormone")
# one result has units mg/dL, not sure this is correct
temp <- tsh %>% filter(Lab.Units=="mg/dL")
unit_prob <- rbind(unit_prob,temp)

cholesterol <- labs_new %>% filter(Lab.Name=="Total cholesterol")
# no unit issues

trig <- labs_new %>% filter(Lab.Name=="Triglyceride level")
# no unit issues

a1c <- labs_new %>% filter(Lab.Name=="Venous hemoglobin A1C")
# no unit issues

unit_prob$Comment <- "Please check units"

# not sure what to do with these labs, should they be combined with others?
other <- labs_new %>% filter(Lab.Name=="Other")
other$Comment <- "Other lab - should this be included in database?"

checks <- rbind(unit_prob,other)

# checking ranges
# for now, will not check ranges on any assays that had unit issues
# can check: urine_vol_24, hdl, serum_creatinine, thyroglobulin, thyroid_perox, cholesterol, trig, a1c
urine_vol_24_range <- urine_vol_24 %>% filter(Lab.Value<800 | Lab.Value>2000)
# hdl range (38-89) seems fine
# serum creatinine (0.5-0.7) range seems fine
# thyroglobulin seems fine
thyroid_perox_range <- thyroid_perox %>% filter(Lab.Value>=35)
# cholesterol seems fine
# triglycerides seem fine
# a1c looks fine

range_check <- rbind(urine_vol_24_range,thyroid_perox_range)
range_check$Comment <- "Please check lab value, outside expected range"

checks <- rbind (checks, range_check)

# check for missing labs

write.csv(checks,"B:/Projects/Sarit Polsky/PICLS/Data cleaning/Data cleaning sheets/lab_checks.csv", row.names = F)

```