---
title: "6 Month Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(redcapAPI)
library(tidyverse)
library(knitr)
# Check OS and alter file path accordingly.
if (.Platform$OS.type == "windows") {pathstart <- "//ucdenver.pvt/"} else if (.Platform$OS.type == "unix"){pathstart <- "/Volumes/"}
```

```{r echo=FALSE,cache=TRUE,include=FALSE}
# REDCap API data import
source("/Users/timvigers/Documents/GitHub/BDC-Code/api_tokens.R")
# YA
rcon <- redcapConnection(url = "https://redcap.ucdenver.edu/api/",
                         token = YA670g)
ya_full <- exportRecords(rcon)
# Parents
rcon <- redcapConnection(url = "https://redcap.ucdenver.edu/api/",
                         token = Parent670g)
parent_full <- exportRecords(rcon)
# Child
rcon <- redcapConnection(url = "https://redcap.ucdenver.edu/api/",
                         token = Child670g)
child_full <- exportRecords(rcon)
# Read in baseline glycemic data
baseline_glycemic_csv <- read.csv("/Volumes/som-1/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Cari Berget/6 Month Manuscript/Data_Cleaned/670GChild_BaselineGlycemicData_14JAN2019.csv")
```

```{r echo=FALSE,cache=TRUE}
# Read in 
# Demographics
demographics_child <- child_full %>%
  select(record_id,automode_start,demographics_age:demographics_cgmhx)
demographics_ya <- ya_full %>%
  select(record_id,ya_automoste_start,ya_demographics_age:ya_demographics_cgmhx)
colnames(demographics_ya) <- sub("ya_","",colnames(demographics_ya))
colnames(demographics_ya)[2] <- "automode_start"
# Filter YA out of child data
ya <- as.character(demographics_ya$record_id)
demographics_child <- demographics_child[-c(which(demographics_child$record_id %in% ya)),]
child <- as.character(demographics_child$record_id)
demographics <- rbind(demographics_child,demographics_ya) %>%
  arrange(as.numeric(record_id))
# Never trained and withdrawn
withdrawn <- c("41","50") # Per Cari
never_trained <- demographics$record_id[which(is.na(demographics$automode_start))]
never_trained <- never_trained[which(!(never_trained %in% withdrawn))]
# Format glycemic data
glycemic_colnames <- c("record_id","days","hba1c","am_time","mm_time",
                       "sensor_wear","sensor_u54","sensor_55_69",
                       "sensor_70_180","sensor_181_250","sensor_g250",
                       "mean_sg","sd","bg_checks","calibrations",
                       "tdd","basal","bolus","amexits",
                       "amexit_day","amexit_hyper","amexit_hypo",
                       "amexit_manual","amexit_other")
# Baseline
baseline_hba1c <- child_full %>%
  select(record_id,hba1c_baseline)
baseline_hba1c$record_id <- as.integer(baseline_hba1c$record_id)
baseline_glycemic <- left_join(baseline_glycemic_csv,baseline_hba1c, by = "record_id")
colnames(baseline_glycemic) <- sub("_b","",colnames(baseline_glycemic))
colnames(baseline_glycemic)[ncol(baseline_glycemic)] <- "hba1c"
baseline_glycemic[,c(glycemic_colnames[which(!(glycemic_colnames %in% colnames(baseline_glycemic)))])] <- NA
baseline_glycemic <- baseline_glycemic[glycemic_colnames]
baseline_glycemic <- as.data.frame(lapply(baseline_glycemic, as.numeric))
baseline_glycemic$Timepoint <- "B"
# M1
m1_glycemic_child <- child_full %>%
  select(record_id,c_t1_date_m1,hba1c_m1,am_time_m1:amexits_other_m1) %>%
  filter(record_id %in% child)
m1_glycemic_child <- left_join(m1_glycemic_child,
                               demographics[,c("record_id","automode_start")],
                               by = "record_id")
m1_glycemic_child$days <- as.numeric(difftime(m1_glycemic_child$c_t1_date_m1,m1_glycemic_child$automode_start))
m1_glycemic_child <- m1_glycemic_child %>% select(record_id,days,hba1c_m1:amexits_other_m1)
colnames(m1_glycemic_child) <- glycemic_colnames
m1_glycemic_ya <- ya_full %>% 
  select(record_id,ya_t1_date_m1,ya_hba1c_t1_m1,ya_t1_am_time_m1:ya_t1_amexit_other_m1) %>%
  filter(record_id %in% ya)
m1_glycemic_ya <- left_join(m1_glycemic_ya,
                               demographics[,c("record_id","automode_start")],
                               by = "record_id")
m1_glycemic_ya$days <- as.numeric(difftime(m1_glycemic_ya$ya_t1_date_m1,m1_glycemic_ya$automode_start))
m1_glycemic_ya <- m1_glycemic_ya %>% select(record_id,days,ya_hba1c_t1_m1:ya_t1_amexit_other_m1)
colnames(m1_glycemic_ya) <- glycemic_colnames
m1_glycemic <- rbind(m1_glycemic_child,m1_glycemic_ya)
m1_glycemic <- as.data.frame(lapply(m1_glycemic, as.numeric))
m1_glycemic$Timepoint <- "M1"
# T1
t1_glycemic_child <- child_full %>%
  select(record_id,date_t1,c_hba1c_baseline_t1,c_t1_am_time:c_t2_amexits_other) %>%
  filter(record_id %in% child)
t1_glycemic_child <- left_join(t1_glycemic_child,
                               demographics[,c("record_id","automode_start")],
                               by = "record_id")
t1_glycemic_child$days <- as.numeric(difftime(t1_glycemic_child$date_t1,t1_glycemic_child$automode_start))
t1_glycemic_child <- t1_glycemic_child %>% select(record_id,days,c_hba1c_baseline_t1:c_t2_amexits_other)
colnames(t1_glycemic_child) <- glycemic_colnames
t1_glycemic_ya <- ya_full %>% 
  select(record_id,ya_t1_date,ya_hba1c_t1,ya_t1_am_time:ya_t1_amexit_other) %>%
  filter(record_id %in% ya)
t1_glycemic_ya <- left_join(t1_glycemic_ya,
                               demographics[,c("record_id","automode_start")],
                               by = "record_id")
t1_glycemic_ya$days <- as.numeric(difftime(t1_glycemic_ya$ya_t1_date,t1_glycemic_ya$automode_start))
t1_glycemic_ya <- t1_glycemic_ya %>% select(record_id,days,ya_hba1c_t1:ya_t1_amexit_other)
colnames(t1_glycemic_ya) <- glycemic_colnames
t1_glycemic <- rbind(t1_glycemic_child,t1_glycemic_ya) %>%
  arrange(as.numeric(record_id))
t1_glycemic <- as.data.frame(lapply(t1_glycemic, as.numeric))
t1_glycemic$Timepoint <- "T1"
# T2
t2_glycemic_child <- child_full %>%
  select(record_id,c_date_t2,c_hba1c_baseline_t2,c_t2_am_time:c_t2_amexit_other) %>%
  filter(record_id %in% child)
t2_glycemic_child <- left_join(t2_glycemic_child,
                               demographics[,c("record_id","automode_start")],
                               by = "record_id")
t2_glycemic_child$days <- as.numeric(difftime(t2_glycemic_child$c_date_t2,t2_glycemic_child$automode_start))
t2_glycemic_child <- t2_glycemic_child %>% select(record_id,days,c_hba1c_baseline_t2:c_t2_amexit_other)
colnames(t2_glycemic_child) <- glycemic_colnames
t2_glycemic_ya <- ya_full %>% 
  select(record_id,ya_t2_date,ya_hba1c_t2,ya_t2_am_time:ya_t2_amexit_other) %>%
  filter(record_id %in% ya)
t2_glycemic_ya <- left_join(t2_glycemic_ya,
                               demographics[,c("record_id","automode_start")],
                               by = "record_id")
t2_glycemic_ya$days <- as.numeric(difftime(t2_glycemic_ya$ya_t2_date,t2_glycemic_ya$automode_start))
t2_glycemic_ya <- t2_glycemic_ya %>% select(record_id,days,ya_hba1c_t2:ya_t2_amexit_other)
colnames(t2_glycemic_ya) <- glycemic_colnames
t2_glycemic <- rbind(t2_glycemic_child,t2_glycemic_ya) %>%
  arrange(as.numeric(record_id))
t2_glycemic <- as.data.frame(lapply(t2_glycemic, as.numeric))
t2_glycemic$Timepoint <- "T2"
# Bind timepoints, remove withdrawals and never trained
glycemic_data <- bind_rows(baseline_glycemic,m1_glycemic,t1_glycemic,t2_glycemic) %>%
  arrange(record_id,Timepoint) %>%
  select(record_id,Timepoint,days,hba1c:amexit_other) %>%
  filter(!(record_id %in% never_trained) & !(record_id %in% withdrawn))
# Discontinuers
t1_discont <- glycemic_data %>%
  filter(Timepoint == "T1", am_time < 10) %>%
  .$record_id
# Remove participant 10 from discontinuers, because she had AM > 10 at T2.
t1_discont <- t1_discont[-c(which(t1_discont == "10"))]
# T2 discontinuers
t2_discont <- glycemic_data %>%
  filter(Timepoint == "T2", am_time < 10) %>%
  .$record_id
t2_discont <- t2_discont[which(!(t2_discont %in% t1_discont))]
```

```{r echo=FALSE,include=FALSE,cache=TRUE}
# Format survey data
# Child
child_surveys_b <- child_full %>%
  select(record_id,timepoint_baselinesurvey:c_paid20)
colnames(child_surveys_b)[2] <- "Timepoint"
child_surveys_1 <- child_full %>%
  select(record_id,timepoint_survey1:c_paid20_t1)
colnames(child_surveys_1) <- sub("_t1","",colnames(child_surveys_1))
colnames(child_surveys_1)[2] <- "Timepoint"
child_surveys_2 <- child_full %>%
  select(record_id,timepoint_survey2:c_paid20_t2)
colnames(child_surveys_2) <- sub("_t2","",colnames(child_surveys_2))
colnames(child_surveys_2)[2] <- "Timepoint"
child_surveys_3 <- child_full %>%
  select(record_id,timepoint_survey3:c_paid20_t3)
colnames(child_surveys_3) <- sub("_t3","",colnames(child_surveys_3))
colnames(child_surveys_3)[2] <- "Timepoint"
child_surveys_4 <- child_full %>%
  select(record_id,timepoint_survey4:c_paid20_t4)
colnames(child_surveys_4) <- sub("_t4","",colnames(child_surveys_4))
colnames(child_surveys_4)[2] <- "Timepoint"
child_surveys <- bind_rows(child_surveys_b,child_surveys_1,child_surveys_2,
                           child_surveys_3,child_surveys_4)
child_surveys <- child_surveys %>%
  arrange(as.numeric(record_id),Timepoint)
colnames(child_surveys) <- sub("c_","",colnames(child_surveys))
colnames(child_surveys) <- sub("hfs_","",colnames(child_surveys))
# YA
ya_surveys_b <- ya_full %>%
  select(record_id,timepoint_baselinesurvey,ya_hfs_behave1_b:ya_hfs_worry18_b,
         ya_paid1_base:ya_paid20_base)
ya_surveys_b[,3:ncol(ya_surveys_b)] <- lapply(ya_surveys_b[,3:ncol(ya_surveys_b)],as.numeric)
colnames(ya_surveys_b)[2] <- "Timepoint"
colnames(ya_surveys_b)[3:ncol(ya_surveys_b)] <- 
  substr(colnames(ya_surveys_b)[3:ncol(ya_surveys_b)],1,
         nchar(colnames(ya_surveys_b)[3:ncol(ya_surveys_b)])-2)
colnames(ya_surveys_b) <- sub("_ba","",colnames(ya_surveys_b))
ya_surveys_1 <- ya_full %>%
  select(record_id,timepoint_survey1,ya_hfs_behave1_t1:ya_hfs_worry18_t1,
         ya_paid1_t1:ya_paid20_t1)
ya_surveys_1[,3:ncol(ya_surveys_1)] <- lapply(ya_surveys_1[,3:ncol(ya_surveys_1)],as.numeric)
colnames(ya_surveys_1) <- sub("_t1","",colnames(ya_surveys_1))
colnames(ya_surveys_1)[which(colnames(ya_surveys_1) == "ya_hfs_worry8_b")] <- "ya_hfs_worry8"
colnames(ya_surveys_1)[2] <- "Timepoint"
ya_surveys_2 <- ya_full %>%
  select(record_id,timepoint_survey2,ya_hfs_behave1_t2:ya_hfs_worry18_t2,
         ya_paid1_t2:ya_paid20_t2)
ya_surveys_2[,3:ncol(ya_surveys_2)] <- lapply(ya_surveys_2[,3:ncol(ya_surveys_2)],as.numeric)
colnames(ya_surveys_2) <- sub("_t2","",colnames(ya_surveys_2))
colnames(ya_surveys_2) <- sub("_b_t1","",colnames(ya_surveys_2))
colnames(ya_surveys_2)[2] <- "Timepoint"
ya_surveys_3 <- ya_full %>%
  select(record_id,timepoint_survey3,ya_hfs_behave1_t3:ya_hfs_worry18_t3,
         ya_paid1_t3:ya_paid20_t3)
ya_surveys_3[,3:ncol(ya_surveys_3)] <- lapply(ya_surveys_3[,3:ncol(ya_surveys_3)],as.numeric)
colnames(ya_surveys_3) <- sub("_t3","",colnames(ya_surveys_3))
colnames(ya_surveys_3) <- sub("_3","",colnames(ya_surveys_3))
colnames(ya_surveys_3)[2] <- "Timepoint"
ya_surveys_4 <- ya_full %>%
  select(record_id,timepoint_survey4,ya_hfs_behave1_t4:ya_hfs_worry18_t4,
         ya_paid1_t4:ya_paid20_t4)
ya_surveys_4[,3:ncol(ya_surveys_4)] <- lapply(ya_surveys_4[,3:ncol(ya_surveys_4)],as.numeric)
colnames(ya_surveys_4) <- sub("_t4","",colnames(ya_surveys_4))
colnames(ya_surveys_4)[2] <- "Timepoint"
ya_surveys <- bind_rows(ya_surveys_b,ya_surveys_1,ya_surveys_2,
                           ya_surveys_3,ya_surveys_4)
colnames(ya_surveys) <- sub("ya_","",colnames(ya_surveys))
colnames(ya_surveys) <- sub("hfs_","",colnames(ya_surveys))
ya_surveys <- ya_surveys %>%
  arrange(as.numeric(record_id),Timepoint)
# Parents
parent_surveys_b <- parent_full %>%
  select(record_id,timepoint_baselinesurvey:p_hfs_worry26,p_paid1:p_paid18)
colnames(parent_surveys_b)[2] <- "Timepoint"
parent_surveys_1 <- parent_full %>%
  select(record_id,timepoint_survey1:p_hfs_worry26_t1,p_paid1_t1:p_paid18_t1)
colnames(parent_surveys_1) <- sub("_t1","",colnames(parent_surveys_1))
colnames(parent_surveys_1)[2] <- "Timepoint"
parent_surveys_2 <- parent_full %>%
  select(record_id,timepoint_survey2:p_hfs_worry26_t2,p_paid1_t2:p_paid18_t2)
colnames(parent_surveys_2) <- sub("_t2","",colnames(parent_surveys_2))
colnames(parent_surveys_2)[2] <- "Timepoint"
parent_surveys_3 <- parent_full %>%
  select(record_id,timepoint_survey3:p_hfs_worry26_t3,p_paid1_t3:p_paid18_t3)
colnames(parent_surveys_3) <- sub("_t3","",colnames(parent_surveys_3))
colnames(parent_surveys_3)[2] <- "Timepoint"
parent_surveys_4 <- parent_full %>%
  select(record_id,timepoint_survey4:p_hfs_worry26_t4,p_paid1_t4:p_paid18_t4)
colnames(parent_surveys_4) <- sub("_t4","",colnames(parent_surveys_4))
colnames(parent_surveys_4)[2] <- "Timepoint"
parent_surveys <- bind_rows(parent_surveys_b,parent_surveys_1,parent_surveys_2,
                           parent_surveys_3,parent_surveys_4)
colnames(parent_surveys) <- sub("p_","",colnames(parent_surveys))
colnames(parent_surveys) <- sub("hfs_","",colnames(parent_surveys))
parent_surveys <- parent_surveys %>%
  filter(!(record_id %in% c("1a","74a"))) %>% # exclude 1a and 74a per Cari
  arrange(as.numeric(record_id),Timepoint)
```

```{r eval=FALSE}
# Find those with an M1 but no T1
# Per Cari, we should use M1 surveys as T1 for those with T2 and M1 but no T2. This was fixed in REDCap. Record IDs emailed to Cari for her records. Each of these should have 0 rows now.
m1_not1_child <- child_surveys %>%
  group_by(record_id) %>%
  filter(any(Timepoint  == "month 1")) %>%
  summarise(Timepoints = paste(Timepoint, collapse = ", ")) %>%
  filter(Timepoints == "baseline, month 1, Time 2")
m1_not1_ya <- ya_surveys %>%
  group_by(record_id) %>%
  filter(any(Timepoint  == "Month 1")) %>%
  summarise(Timepoints = paste(Timepoint, collapse = ", ")) %>%
  filter(Timepoints == "baseline, Month 1, Time 2")
m1_not1_parent <- parent_surveys %>%
  group_by(record_id) %>%
  filter(any(Timepoint  == "month 1")) %>%
  summarise(Timepoints = paste(Timepoint, collapse = ", ")) %>%
  filter(Timepoints == "baseline, month 1, Time 2")
```

```{r echo=FALSE,cache=TRUE}
# Survey scoring
# Subtract 1 to code from 0-4
child_surveys[,3:ncol(child_surveys)] <- lapply(child_surveys[,3:ncol(child_surveys)],function(x){as.numeric(x)-1})
ya_surveys[,3:ncol(ya_surveys)] <- lapply(ya_surveys[,3:ncol(ya_surveys)],function(x){as.numeric(x)-1})
parent_surveys[,3:ncol(parent_surveys)] <- lapply(parent_surveys[,3:ncol(parent_surveys)],function(x){as.numeric(x)-1})
# Split into PAID and HFS subscales
# Child
child_surveys_paid <- child_surveys %>%
  select(record_id,Timepoint,paid1:paid20)
child_surveys_behave <- child_surveys %>%
  select(record_id,Timepoint,behave1:behave10)
child_surveys_worry <- child_surveys %>%
  select(record_id,Timepoint,worry11:worry25)
# YA
ya_surveys_paid <- ya_surveys %>%
  select(record_id,Timepoint,paid1:paid20)
ya_surveys_behave <- ya_surveys %>%
  select(record_id,Timepoint,behave1:behave15)
ya_surveys_worry <- ya_surveys %>%
  select(record_id,Timepoint,worry1:worry18)
# Parent
parent_surveys_paid <- parent_surveys %>%
  select(record_id,Timepoint,paid1:paid18)
parent_surveys_behave <- parent_surveys %>%
  select(record_id,Timepoint,behave1:behave11)
parent_surveys_worry <- parent_surveys %>%
  select(record_id,Timepoint,worry12:worry26)
# Replace missing data with means if > 75% answered
# Children
# PAID
missing_threshold <- ceiling(length(3:ncol(child_surveys_paid)) * 0.25)
for (r in 1:nrow(child_surveys_paid)) { # Couldn't get apply to work for some reason
  x <- child_surveys_paid[r,3:ncol(child_surveys_paid)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  child_surveys_paid[r,3:ncol(child_surveys_paid)] <- x
}
# Behave
missing_threshold <- ceiling(length(3:ncol(child_surveys_behave)) * 0.25)
for (r in 1:nrow(child_surveys_behave)) { # Couldn't get apply to work for some reason
  x <- child_surveys_behave[r,3:ncol(child_surveys_behave)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  child_surveys_behave[r,3:ncol(child_surveys_behave)] <- x
}
# Worry
missing_threshold <- ceiling(length(3:ncol(child_surveys_worry)) * 0.25)
for (r in 1:nrow(child_surveys_worry)) { # Couldn't get apply to work for some reason
  x <- child_surveys_worry[r,3:ncol(child_surveys_worry)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  child_surveys_worry[r,3:ncol(child_surveys_worry)] <- x
}
# YA
#PAID
missing_threshold <- ceiling(length(3:ncol(ya_surveys_paid)) * 0.25)
for (r in 1:nrow(ya_surveys_paid)) { # Couldn't get apply to work for some reason
  x <- ya_surveys_paid[r,3:ncol(ya_surveys_paid)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  ya_surveys_paid[r,3:ncol(ya_surveys_paid)] <- x
}
# Behave
missing_threshold <- ceiling(length(3:ncol(ya_surveys_behave)) * 0.25)
for (r in 1:nrow(ya_surveys_behave)) { # Couldn't get apply to work for some reason
  x <- ya_surveys_behave[r,3:ncol(ya_surveys_behave)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  ya_surveys_behave[r,3:ncol(ya_surveys_behave)] <- x
}
# Worry
missing_threshold <- ceiling(length(3:ncol(ya_surveys_worry)) * 0.25)
for (r in 1:nrow(ya_surveys_worry)) { # Couldn't get apply to work for some reason
  x <- ya_surveys_worry[r,3:ncol(ya_surveys_worry)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  ya_surveys_worry[r,3:ncol(ya_surveys_worry)] <- x
}
# Parents
# PAID
missing_threshold <- ceiling(length(3:ncol(parent_surveys_paid)) * 0.25)
for (r in 1:nrow(parent_surveys_paid)) { # Couldn't get apply to work for some reason
  x <- parent_surveys_paid[r,3:ncol(parent_surveys_paid)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  parent_surveys_paid[r,3:ncol(parent_surveys_paid)] <- x
}
# Behave
missing_threshold <- ceiling(length(3:ncol(parent_surveys_behave)) * 0.25)
for (r in 1:nrow(parent_surveys_behave)) { # Couldn't get apply to work for some reason
  x <- parent_surveys_behave[r,3:ncol(parent_surveys_behave)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  parent_surveys_behave[r,3:ncol(parent_surveys_behave)] <- x
}
# Worry
missing_threshold <- ceiling(length(3:ncol(parent_surveys_worry)) * 0.25)
for (r in 1:nrow(parent_surveys_worry)) { # Couldn't get apply to work for some reason
  x <- parent_surveys_worry[r,3:ncol(parent_surveys_worry)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  parent_surveys_worry[r,3:ncol(parent_surveys_worry)] <- x
}
# Score children
# PAID
child_surveys_paid$paid_score <- 
  apply(child_surveys_paid[3:ncol(child_surveys_paid)],1,
        function(x) (mean(4-x))*25)
# Behave
child_surveys_behave$behave_score <- 
  apply(child_surveys_behave[3:ncol(child_surveys_behave)],1,sum)
# Worry
child_surveys_worry$worry_score <- 
  apply(child_surveys_worry[3:ncol(child_surveys_worry)],1,sum)

# Score YA
# PAID
ya_surveys_paid$paid_score <- 
  apply(ya_surveys_paid[3:ncol(ya_surveys_paid)],1,
        function(x) (sum(x))*1.25)
# Behave
ya_surveys_behave$behave_score <- 
  apply(ya_surveys_behave[3:ncol(ya_surveys_behave)],1,sum)
# Worry
ya_surveys_worry$worry_score <- 
  apply(ya_surveys_worry[3:ncol(ya_surveys_worry)],1,sum)

# Score parents
# PAID
parent_surveys_paid$paid_score <- 
  apply(parent_surveys_paid[3:ncol(parent_surveys_paid)],1,
        function(x) (mean(4-x))*25)
# Behave
parent_surveys_behave$behave_score <- 
  apply(parent_surveys_behave[3:ncol(parent_surveys_behave)],1,sum)
# Worry
parent_surveys_worry$worry_score <- 
  apply(parent_surveys_worry[3:ncol(parent_surveys_worry)],1,sum)
```

```{r echo=FALSE}
# Per Cari Berget 5/1/19:
# "Subjects 4,8,16,17,21 completed the child survey versions in the baseline survey form and adult surveys for the rest of the time points.  The young adult surveys are the correct ones"
ya_surveys_correct <- as.character(c(4,8,16,17,21))
# 6 month survey analysis
child_surveys_6_month <- child_surveys_paid %>%
  select(record_id,Timepoint,paid_score) %>%
  left_join(child_surveys_behave[,c("record_id","Timepoint","behave_score")],
            by=c("record_id", "Timepoint")) %>%
  left_join(child_surveys_worry[,c("record_id","Timepoint","worry_score")],
            by=c("record_id", "Timepoint")) %>%
  mutate(total_hfs_score = worry_score + behave_score) %>%
  filter(Timepoint %in% c("baseline","Time 1", "Time 2"))
# Plot

```
