---
title: "GRI CGM ADD"
author: "Casey Sakamoto"
date: "2022-10-25"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(readxl) # data import
library(knitr) # tables
library(tidyverse) # data manip
library(ggplot2) # plots
library(table1)
library(cgmanalysis)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "S:/Laura/BDC/Projects/Viral Shah/GRI"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Viral Shah/GRI"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Viral Shah/GRI"
}
knitr::opts_knit$set(root.dir = home_dir)

setwd(home_dir)
rm(home_dir)
```

## original only had tir so i had to use cgm package to add in tbr as requested by reviewers

```{r import A1c data}
# Import
setwd("S:/Laura/BDC/Projects/Kaan Akturk/CGM Sampling/")
subjects <- read.csv("./Data_Cleaned/subject_info.csv",na.strings = c("","(-)"))
# Names to lower case and no middle or suffixes for matching
subjects[,c("FirstName","LastName")] <- 
  lapply(subjects[,c("FirstName","LastName")],function(x){
    x <- tolower(x)
    x <- sub(" .*","",x)
  })
subjects$name <- paste0(subjects$FirstName,subjects$LastName)
subjects$name <- gsub(" ","",subjects$name)
# Set days and sampling percentages
days <- c(7,14,30,60,90)
sampling <- seq(55,95,by = 5)
```

```{r cgmvariables,eval=FALSE}
# CGM variables on each folder
setwd("S:/Laura/BDC/Projects/Kaan Akturk/CGM Sampling/")
outdir <- "./Data_Cleaned/cgm"

for (d in days) {
  cgmvariables(paste0(outdir,"/",paste0("day",d)),
               "./Data_Cleaned/test",
               outputname = paste0("day",d,"variables"))
}
```

```{r}
setwd("S:/Laura/BDC/Projects/Kaan Akturk/CGM Sampling/Data_Cleaned/test")
vars <- c("percent_time_70_180","percent_time_over_180",
          "percent_time_over_250","percent_time_under_70",
          "percent_time_under_54","cv")
var_names <- c("% TIR 70-180","% Time > 180","% Time > 250",
               "% Time < 70","% Time < 54","CV","Mean Glucose")
# Import cgm variables by days from HbA1c
# day7variables <- read.csv("S:/Laura/BDC/Projects/Kaan Akturk/CGM Sampling/Data_Cleaned/test/day7variables.csv")
# day14variables <- read.csv("S:/Laura/BDC/Projects/Kaan Akturk/CGM Sampling/Data_Cleaned/test/day14variables.csv")
# day30variables <- read.csv("S:/Laura/BDC/Projects/Kaan Akturk/CGM Sampling/Data_Cleaned/test/day30variables.csv")
# day60variables <- read.csv("S:/Laura/BDC/Projects/Kaan Akturk/CGM Sampling/Data_Cleaned/test/day60variables.csv")
day90variables <- read.csv("S:/Laura/BDC/Projects/Kaan Akturk/CGM Sampling/Data_Cleaned/test/day90variables.csv")
# cgm = rbind(day7variables, day14variables)
# cgm = rbind(cgm, day30variables)
# cgm = rbind(cgm, day60variables)
# cgm = rbind(cgm, day90variables)

# Add Hba1c data
cgm = cgm %>% select(subject_id, percent_cgm_wear, all_of(vars))
cgm <- left_join(cgm,subjects[,c("name","MostRecentA1C")],by = c("subject_id" = "name"))
```

```{r, eval = F}
write.csv(cgm, file = "S:/Laura/BDC/Projects/Viral Shah/GRI/Data Clean/extracgm.csv")
```


