---
title: "A1c and TIR"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

library(knitr)
library(readxl)
library(tableone)
library(dplyr)
library(tidyr)
library(nlme)

data <- read.csv("B:\\Projects\\Todd Alonso\\A1c and TIR\\Raw data\\Peds_T1D_5groups_5_11_withDKAcol.csv",na.strings = c(" ","","NULL","#VALUE","#VALUE!","?"))

### LIMIT TO >= 70% SENSOR WEAR...SHOULD BE N=1952

corsave <- cor(data$A1C_Value,data$CGMInRange,use = "complete.obs")
mod <- glm(data$CGMInRange~data$A1C_Value)

```

# Background


# Methods

# Results

## Scatterplot and unadjusted model

The unadjusted correlation was `r corsave`.

```{r echo=FALSE, comment=""}
plot(data$CGMInRange,data$A1C_Value)

summary(mod)
```
<br>

## Model with interaction with age group and duration

```{r echo=FALSE, comment=""}
modint <- glm(data=data,CGMInRange~A1C_Value * Age_Groups + A1C_Value * DiabetesDuration_LastVisitDate)

summary(modint)

```
<br>


