---
title: "Pima Metabolomics"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = "/Users/timvigers/petter_metabolomics")
library(arsenal)
library(skimr)
library(knitr)
library(mixOmics)
library(tidyverse)
```

```{r data}
# Import data
raw_data <- read.csv("./Raw data/2020-03-20 Bjornstad discovery mode results jrh v2.csv", 
               stringsAsFactors=TRUE,na.strings = "")
samples <- read.csv("./Clean data/KNN_serum.csv_sampledata.csv")
samples$X <- NULL
# Transpose
compounds <- paste0("W",raw_data$Molecular.Weight,raw_data$RT..min.)
df <- raw_data %>% dplyr::select(CS.01:RH.47.L) %>% t()
colnames(df) <- compounds
df <- as.data.frame(df)
# Sample data
df$ID <- sub("\\.","-",sub(".L","",rownames(df)))
df <- left_join(df,samples,by = "ID")
# Reorganize
df <- df %>% dplyr::select(ID:group,everything())
```

# Preprocessing

```{r preprocessing}
# Check for samples missing > 80% of compounds, remove them
missing <- which(rowSums(is.na(df[,11:ncol(df)])) / length(11:ncol(df)) > 0.8)
if (length(missing)>0){df <- df[-missing,]}
# Same for 0 instead of NA - none
missing0 <- which(rowSums(df[,11:ncol(df)] == 0) / length(11:ncol(df)) > 0.8)
```

Removed `r length(missing)` samples missing > 80% of compounds and `r length(missing0)` samples with > 80% of compounds equal to 0. 

```{r}
X <- df[,11:ncol(df)]
```

# PCA

```{r pca}
# 4 PCs
pca.res <- pca(X, ncomp = 5, center = TRUE, scale = FALSE)
# Plot
plotIndiv(pca.res,group = df$group,legend = TRUE,ind.names = T,
          title = 'PCA by Group (PCs 1 & 2)',ellipse = T)
plotIndiv(pca.res,comp = c(1,3),group = df$group,legend = TRUE,ind.names = FALSE,
          title = 'PCA by Group (PCs 1 & 3)',ellipse = T)
plotIndiv(pca.res,comp = c(2,3),group = df$group,legend = TRUE,ind.names = FALSE,
          title = 'PCA by Group (PCs 2 & 3)',ellipse = T)
```

# PLS-DA

```{r plsda,cache=TRUE}
# Group as outcome
Y <- as.factor(df$group)
# PLS-DA function
plsda.res <- plsda(X, Y, ncomp = 5)
# Check error
perf.plsda <- perf(plsda.res, validation = "loo",progressBar=FALSE, auc=TRUE)
# Plot performance
plot(perf.plsda,legend.position = "horizontal")
```

# sPLS-DA

```{r splsda,cache=TRUE}
# Tune
tune.splsda <- tune.splsda(X, Y, ncomp = 10, validation = 'loo',
                           progressBar = FALSE,nrepeat = 100)
plot(tune.splsda)
choice.ncomp <- 1
choice.keepX <- tune.splsda$choice.keepX[1:choice.ncomp]
# sPLS-DA function
splsda.res <- splsda(X, Y, ncomp = choice.ncomp, keepX = choice.keepX)
# Performance
perf.splsda <- perf(splsda.res, validation = "loo",progressBar = FALSE,
                    auc = TRUE)
# Select variables
selectVar(splsda.res, comp = 1)$value
```

sPLS-DA AUC: perf.splsda$auc
