---
title: "670G 3 and 6 Month"
author: "Tim Vigers"
date: "5/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/670g CGM/")
library(dplyr)
library(lubridate)
library(cgmanalysis)
```

```{r echo=FALSE}
# Read in dates
dates <- read.csv("./Data_Cleaned/MASTER LIST FINAL.csv",stringsAsFactors = F)
# Format
datecols <- c("DOB","X670..start.date","Month.3.670.start.date",
              "Month.3.670.end.date","Month.6.670.start.date",
              "Month.6.670.end.date")
dates[,datecols] <- lapply(dates[datecols], mdy)
# Iterate through files, put in one big dataframe
indir <- "./Data_Raw/670g Files"
outdir <- "./Data_Cleaned/"
files <- list.files(indir,full.names = T)
bigframe <- as.data.frame(matrix(ncol = 3))
colnames(bigframe) <- c("subjectid","timestamp","sensorglucose")
for (f in files) {
  dat <- read.csv(f,stringsAsFactors = F,na.strings = "")
  id <- as.numeric(as.character(dat$Patient.ID[1]))
  sensorstart <- which(dat$Patient.ID=="Sensor")[1] + 2
  colnames(dat) <- as.character(dat[(sensorstart-1),])
  dat <- dat[sensorstart:nrow(dat),]
  dat$timestamp <- paste(dat$Date,dat$Time)
  dat$subjectid <- id
  colnames(dat)[which(colnames(dat) == "Sensor Glucose (mg/dL)")] <- "sensorglucose"
  dat <- dat[,c("subjectid","timestamp","sensorglucose")]
  bigframe <- rbind(bigframe,dat)
}
bigframe <- bigframe[-c(1),]
bigframe$timestamp <- mdy_hms(bigframe$timestamp)
# Split by subject ID, get correct dates
framelist <- split(bigframe,bigframe$subjectid)
for (f in framelist) {
  dat <- as.data.frame(f)
  colnames(dat) <- c("subjectid","timestamp","sensorglucose")
# If they have a start and end date, write CSV file with only those dates.
  start <- dates$Month.3.670.start.date[which(dates$Patient.ID == dat$subjectid[1])]
  end <- dates$Month.3.670.end.date[which(dates$Patient.ID == dat$subjectid[1])] + 1
  month3 <- dat[which(dat$timestamp >= start & dat$timestamp < end),]
  month3 <- month3[order(month3$timestamp),]
  month3 <- unique(month3)
  filename <- paste0(outdir,"3 Month Data/",dat$subjectid[1],"_3_Month.csv")
  if (nrow(month3) > 0 & length(which(is.na(month3$sensorglucose))) < nrow(month3)) {
    month3$subjectid[2:nrow(month3)] <- NA
    write.csv(month3,file = filename,row.names = F,na="")
    }
# Same again for month 6  
  start <- dates$Month.6.670.start.date[which(dates$Patient.ID == dat$subjectid[1])]
  end <- dates$Month.6.670.end.date[which(dates$Patient.ID == dat$subjectid[1])] + 1
  month6 <- dat[which(dat$timestamp >= start & dat$timestamp < end),]
  month6 <- month6[order(month6$timestamp),]
  month6 <- unique(month6)
  filename <- paste0(outdir,"6 Month Data/",dat$subjectid[1],"_6_Month.csv")
  if (nrow(month6) > 0 & length(which(is.na(month6$sensorglucose))) < nrow(month6)) {
    month6$subjectid[2:nrow(month6)] <- NA
    write.csv(month6,file = filename,row.names = F,na="")
    }
}
# 3 month variables
cgmvariables("./Data_Cleaned/3 Month Data",
             "./Data_Cleaned",
             outputname = "3 month variables")
# 6 month variables
cgmvariables("./Data_Cleaned/6 Month Data",
             "./Data_Cleaned",
             outputname = "6 month variables")
```