---
title: "670g Study"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, include=FALSE}
# Load libraries and functions
source('~/Documents/GitHub/Tim-and-Laura/tim_R_functions.R')
pathstart <- os.check()
library(readxl)
library(tools)
library(lubridate)
```

```{r echo=FALSE}
filename <- paste(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Laura Tim projects/Janet Snell-Bergeon/670g CGM /Data_Cleaned/DATA Set 670 Master_Cleaned.xlsx",sep="")
sheets <- excel_sheets(filename)
files <- lapply(sheets, function(x) read_excel(filename, sheet = x))
formatted.files <- lapply(files, as.data.frame)
for (f in 1:length(formatted.files)) {
  write.csv(formatted.files[f],file = paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Laura Tim projects/Janet Snell-Bergeon/670g CGM /Data_Cleaned/Original Individual Files/",sheets[f],".csv"),row.names = F)
}
```

```{r echo=FALSE}
# Format CSVs
folder <- paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Laura Tim projects/Janet Snell-Bergeon/670g CGM /Data_Cleaned/Original Individual Files/")
files <- list.files(folder)
files <- files[-c(which(files == "Data set.csv"))]
for (f in 1:length(files)) {
  id <- file_path_sans_ext(files[f])
  table <- read.csv(paste0(folder,files[f]),stringsAsFactors = F)
  colnames(table) <- tolower(colnames(table))
  colnames(table) <- gsub(" ","",colnames(table))
  colnames(table) <- gsub("\\.","",colnames(table))
  if (ncol(table) == 3 & colnames(table)[1] != "subjectid") {
    table$t <- substr(table$time, nchar(table$time)-8+1, nchar(table$time))
    table$timestamp <- paste(table$date,table$t)
    table$timestamp <- ymd_hms(table$timestamp)
    table$subjectid <- NA
    table <- table[,c("subjectid","timestamp","sensorglucose")]
    table$subjectid[1] <- id
  } else if (ncol(table) == 3 & colnames(table)[1] == "subjectid") {
    table$timestamp <- sub("T"," ",table$timestamp)
    table$timestamp <- ymd_hms(table$timestamp)
    table$subjectid <- NA
    table$subjectid[1] <- id
  } else if (ncol(table) == 2) {
    colnames(table) <- c("timestamp","sensorglucose")
    table$timestamp <- gsub("T"," ",table$timestamp)
    table$timestamp <- ymd_hms(table$timestamp)
    table$subjectid <- NA
    table$subjectid[1] <- id
    table <- table[,c("subjectid","timestamp","sensorglucose")]
  } else if (ncol(table) == 4 & colnames(table)[1] == "subjectid") {
    table$t <- substr(table$time, nchar(table$time)-8+1, nchar(table$time))
    table$timestamp <- paste(table$date,table$t)
    table$timestamp <- ymd_hms(table$timestamp)
    table$subjectid <- NA
    table <- table[,c("subjectid","timestamp","sensorglucose")]
    table$subjectid[1] <- id
  } else {
    stop("unknown format")
  }
write.csv(table,file = paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Laura Tim projects/Janet Snell-Bergeon/670g CGM /Data_Cleaned/Formatted/",id,".csv"),row.names = F,na = "")
}
```

```{r eval=FALSE}
# Manual edits:
# Deleted first row of 1160613, edited column names
# Deleted 1407718
# Deleted 1408822
# Deleted 1409429
# Deleted 1423211
# Deleted 1466234
# Deleted 1754477
# Deleted 1987172
# Deleted 2029614
# Deleted 476259
# Deleted 532227
# Deleted 672864
# Deleted 685905
# Deleted extra columns in 1420076
# Changed column names of 1420964
# Changed column names of 1429068
# Changed column names of 676305
```