---
title: "QCGM Plot"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(scales)
library(tidyverse)
# Check OS and alter file path accordingly.
if (.Platform$OS.type == "windows") {pathstart <- "//ucdenver.pvt/"} else if (.Platform$OS.type == "unix"){pathstart <- "/Volumes/"}
```

```{r echo=FALSE,message=FALSE}
# Read in data
filename <- paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/670g CGM/QCGM Plot/Data_Raw/QCGM_plot.txt")
plot_data <- read.delim(filename,stringsAsFactors=FALSE)
# Keep study days 1-28, format times
plot_data <- plot_data %>%
  filter(StudyDay %in% 1:28)
plot_data$Time <- as.POSIXct(strptime(plot_data$Time,format="%H:%M:%S"))
plot_data$Glucose.Value <- as.numeric(plot_data$Glucose.Value)
plot_data$randomization_group <- as.factor(plot_data$randomization_group)
plot_data$Patient_Number <- as.factor(plot_data$Patient_Number)
# Plot
baseplot <- ggplot(plot_data, aes(x = Time,y = Glucose.Value)) +
  ylab("Glucose Value")
plot <- baseplot + 
  geom_smooth(aes(group = randomization_group, color = randomization_group))
plot2 <- baseplot + 
  geom_smooth(aes(group = randomization_group, color = randomization_group)) +
  expand_limits(y = c(100, 300))
plot3 <- baseplot +
  geom_smooth(aes(group = Patient_Number, color = randomization_group),se = F,size = 0.2)
plot
plot2
plot3
```