---
title: "pQCT Data Check"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_width: 6
    fig_height: 3.5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(knitr)
# Read in.
pqct <- read.csv("\\\\ucdenver.pvt\\som\\PEDS\\RI Biostatistics Core\\Shared\\Laura Kaci projects\\Bone studies\\pQCT\\DATA\\QTable1_BaselineData_9.17.18.csv",
                 na.strings = c("No record","Incomplete"))
# Remove people without pQCT data and controls with A1c > 7%.
pqct <- pqct[-c(which(pqct$Diabetic == "No" & pqct$HbA1c >= 7.0)),]
# Define columns of interest.
cols <- colnames(pqct)[grep("Peri_C",colnames(pqct))]
cols <- c(cols,colnames(pqct)[grep("PeriC",colnames(pqct))])
cols <- c(cols,colnames(pqct)[grep("EndoC",colnames(pqct))])
cols <- c(cols,colnames(pqct)[grep("Endo_C",colnames(pqct))])
cols <- cols[order(cols)]
cols <- c("StudyID",cols)
check <- pqct[,cols]
```

```{r echo=FALSE}
for (c in 2:length(cols)) {
  hist(check[,cols[c]],main = paste("Histogram of",cols[c]),xlab = "Value")
}

boxplot(check[,2:ncol(check)],use.cols = T,las = 2)
```
\pagebreak

```{r echo=FALSE}
example <- as.data.frame(cbind(pqct$PeriC_R33,pqct$EndoC_R33,pqct$CRT_THK_R33))
colnames(example) <- c("PeriC_R33","EndoC_R33","CRT_THK_R33")
example$calculated.thk <- 
  abs((example$PeriC_R33/(2*pi)) - (example$EndoC_R33/(2*pi)))
example <- example[complete.cases(example),]
kable(example)
```