---
title: "Insulitis manuscript"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:   
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
# required libraries
library(purrr)
library(tableone)
library(dplyr)
library(plyr)
library(zoo)
library(nlme)
library(lme4)
library(emmeans)
library(knitr)
library(car)
library(tidyr)
library(stringr)
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=F}
# read in data

bT_interactions <- read.csv("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Rachel Friedman/early stage b-T interactions.csv")

islet_wise_new <- read.csv("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Rachel Friedman/islet wise insulitis progression new.csv")

islet_wise_old <- read.csv("/Volumes/PEDS/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Rachel Friedman/islet wise insulitis progression old.csv")


```

# Methods

# Results

```{r, echo=FALSE, message=FALSE}
mod <- lme(l.clonality ~ tp,random=~1|ID,data = dat1_long,na.action = na.omit)
mod_anova <- anova.lme(mod, type="marginal")
mod_means <- emmeans(mod,"tp")
mod_pairs <-  pairs(mod_means,adjust="tukey")

kable(mod_anova,caption="Type 3 tests of fixed effects.",format.args = list(scientific = FALSE))
kable(mod_means,caption="Time point means.",format.args = list(scientific = FALSE))
kable(mod_pairs,caption="Pair-wise comparisons between time points.",format.args = list(scientific = FALSE))

qqnorm(resid(mod))
qqline(resid(mod))
```
