---
title: "JDRFCAV Model Selection"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
editor: visual
---

```{r include=FALSE}
library(caret)
library(tidyverse)
library(tidymodels)
library(doParallel)
library(DataExplorer)
library(knitr)
set.seed(1017)
# Import data 
# load("~/Documents/Work/BDC/Howard Davidson/R01/Data_Raw/JDRFCAV_preprocessed.Rdata")
# load("S:/Laura/BDC/Projects/Howard Davidson/R01/Data_Raw/JDRFCAV_preprocessed.Rdata")
# load("/run/user/1011/gvfs/smb-share:server=ucdenver.pvt,share=som/peds/ri biostatistics core/shared/Shared Projects/Laura/BDC/Projects/Howard Davidson/R01/Data_Raw/JDRFCAV_preprocessed.Rdata")
```

# Methods

```{r}
# Base recipe
# Need to use role updating for large dimension datasets
cpep_recipe <- recipe(df) %>%
  update_role(cpep_model_decayrate,new_role = "outcome") %>%
  update_role(-one_of("cpep_model_decayrate"),new_role = "predictor") %>%
  step_nzv(all_predictors())
```

```{r echo=FALSE,eval=FALSE}
# EDA
eda = prep(cpep_recipe)
eda = bake(eda,new_data = NULL)
eda %>%
    create_report(
        output_file = "EDA.html",
        output_dir = "/run/user/1011/gvfs/smb-share:server=ucdenver.pvt,share=som/peds/ri biostatistics core/shared/Shared Projects/Laura/BDC/Projects/Howard Davidson/R01/Reports",
        y = "cpep_model_decayrate"
    )
```
