---
title: "Tandem Patient Reported Outcomes (PROs)"
author: "Kristen Campbell"
date: "August 5, 2019"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
setwd("C:/Users/campbkri/Documents/GitHub/BDC-Code/Laurel Messer/Tandem/Code")
source("S:/Shared Material/Shared Code/R/temp_table1.R")

##functions specifically for this project
source("00_data.R")
table(dat$BaselineMethod)
#demographics table:
demo<-final_table(dat,c('B_RESPONDENT','Age','duration_of_diabetes_at_baseline_years',
                        'DiabetesType','Baseline_A1C','B_CGMUSE'),
                     as.factor(dat$allcomplete),margin=2,single=F,2,col.names=T, summary.stat='mean')
demo.2<-final_table(dat,c('BaselineMethod'),
                     rep(1:nrow(dat)),margin=2,single=F,2,col.names=T, summary.stat='mean')
demo.2$`0 (n=730)`<-NA
demo.2$`1 (n=409)`<-NA
demo.2$`P Value`<-NA
demo<-rbind(demo,demo.2)
demo$Characteristic<-gsub("\\*","",demo$Characteristic)

# miss.demo<-missing_table(dat,c('B_RESPONDENT','Age','duration_of_diabetes_at_baseline_years',
#                         'DiabetesType','Baseline_A1C','B_CGMUSE','BaselineMethod'),group=rep(1,nrow(dat)),col.names=T)[,c(1,3)]
# colnames(miss.demo)<-c("Characteristic","Missing, n(%)")
# 
# demo.final<-merge(demo,miss.demo,by="Characteristic",all.x=T)
# demo.final<-demo.final[,c(1,6,2:5)]

#opt in data:

opt_in<-final_table(dat,c('Baseline_SurveyStudy_OptIn','post2m_BIQuse','post4m_BIQuse','post6m_BIQuse',
                          'post2m_BIQ_YES','post4m_BIQ_YES','post6m_BIQ_YES'),
                     rep(1:nrow(dat)),margin=2,single=F,2,col.names=T, summary.stat='mean')
opt_in
#missing data:
missing<-final_table(dat,colnames(dat[,c(which(colnames(dat)=="baseline_num_complete"):
                                        which(colnames(dat)=="allcomplete"))]),
                     rep(1:nrow(dat)),margin=2,single=F,2,col.names=T, summary.stat='mean')
missing

#baseline survey summary:
baseline_surv<-final_table(dat,colnames(dat[,c(which(colnames(dat)=="Baseline_1"):
                                        which(colnames(dat)=="Baseline_12"))]),
                     rep(1:nrow(dat)),margin=2,single=F,2,col.names=T, summary.stat='median')
baseline_surv
post2mo_surv<-final_table(dat,colnames(dat[,c(which(colnames(dat)=="post2m_1"):
                                        which(colnames(dat)=="post2m_12"))]),
                     rep(1:nrow(dat)),margin=2,single=F,2,col.names=T, summary.stat='median')
post2mo_surv

post4mo_surv<-final_table(dat,colnames(dat[,c(which(colnames(dat)=="post4m_1"):
                                        which(colnames(dat)=="post4m_12"))]),
                     rep(1:nrow(dat)),margin=2,single=F,2,col.names=T, summary.stat='median')
post4mo_surv

post6mo_surv<-final_table(dat,colnames(dat[,c(which(colnames(dat)=="post6m_1"):
                                        which(colnames(dat)=="post6m_12"))]),
                     rep(1:nrow(dat)),margin=2,single=F,2,col.names=T, summary.stat='median')
post6mo_surv



```


##Summary Stats
**Table 1: Patient Demographics**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(demo, align = c("l", "l"))
```

##Survey Data
**Table 2a: Opt-in data**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(opt_in, align = c("l", "l"))
```
**Table 2b: Missing Data**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(missing, align = c("l", "l"))
```

**Table 3: Baseline Survey**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(baseline_surv, align = c("l", "l"))
```

**Table 3: 2mo Survey**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(post2mo_surv, align = c("l", "l"))
```

**Table 3: 4mo Survey**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(post4mo_surv, align = c("l", "l"))
```

**Table 3: 6mo Survey**
```{r,echo=FALSE,message=FALSE,results='asis',warning=FALSE}
kable(post6mo_surv, align = c("l", "l"))
```
