---
title: "SEEDS Pilot"
author: "Casey Sakamoto & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(performance)
library(knitr)
library(readr)

# data upload from 3 redcap DB
pilot_hcp <- read_csv("S:/Laura/BDC/Projects/Sarit Polsky/SEEDS/SEEDSPilotHCP_DATA_2024-07-17_0910.csv")

pilot_pat <- read_csv("S:/Laura/BDC/Projects/Sarit Polsky/SEEDS/SEEDSPilotPatient_DATA_2024-07-17_0910.csv")

pilot_res <- read_csv("S:/Laura/BDC/Projects/Sarit Polsky/SEEDS/SEEDSPilotResearchSt_DATA_2024-07-17_0911.csv")
```

```{r dc, include = FALSE}
# redcap instruments: SEEDS Pilot HCP: HCP_Enrollment Survey*, HCP_confidence, HCP_Time&Encounter, HCP_confidence_EOS, HCP Pilot Final Questionnaire
pilot_pat = pilot_pat %>% select(record_id, pt_enroll_dob:pt_enroll_complete, worremoval_practicetype:participant_withdrawal_or_removal_complete)


```
