---
title: "670G Combined Analysis  "
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,dpi = 600)
knitr::opts_knit$set(root.dir = "/Users/timvigers/Desktop/670G Combined")
library(Hmisc)
library(arsenal)
library(skimr)
library(mice)
library(nlme)
library(emmeans)
library(knitr)
library(tidyverse)
```

```{r data import and clean,include=FALSE}
na_strings <- c("","999","-999","NULL"," ")
# Kaan's data
# Read in
adult_demographics <- read.csv("./Data_Cleaned/adult_demographics.csv",
                               na.strings = na_strings)
adult <- read.csv("./Data_Cleaned/670Excel.csv",na.strings = na_strings)
adult_2 <- read.csv("./Data_Cleaned/Data set 670 Master.csv",na.strings = na_strings)
adult_new <- read.csv("./Data_Cleaned/670Excel.new55patients.csv",
                      na.strings = na_strings)
adult_pump <- read.csv("./Data_Cleaned/pdf_summary.csv",
                       na.strings = na_strings)
# Format and combine
adult <- adult %>% select(Patient.ID,start.date,contains("HbA1C"))
adult_2 <- adult_2 %>% select(Patient.ID,start.date,Ethnicity,Insurance,contains("HbA1C"))
adult <- full_join(adult,adult_2)
adult_new <- adult_new %>% select(Patient.ID,start.date,Ethnicity,Insurance,contains("HbA1C"))
adult <- full_join(adult,adult_new) 
adult <- adult %>% select(Patient.ID,start.date,Ethnicity,Insurance,HbA1C.Baseline,everything())
# Get demographic data
adult <- adult %>% filter(!is.na(HbA1C.Baseline))
adult <- left_join(adult,adult_demographics,by = "Patient.ID")
adult$age <- 
  as.numeric(difftime(as.Date(adult$start.date,format = "%m/%d/%Y"),
                      as.Date(adult$DOB,format = "%m/%d/%Y"),units = "days")/365.25)
# Get pdf data
adult$last_name <- tolower(sapply(strsplit(adult$LastName," "),"[[",1))
adult$first_name <- tolower(sapply(strsplit(adult$FirstName," "),"[[",1))
adult <- adult %>% 
  pivot_longer(cols = contains("HbA1C"),
               names_to = c(".value","timepoint"),
               names_sep = "\\.")
adult <- left_join(adult,adult_pump,by = c("last_name", "first_name", "timepoint"))
adult <- adult %>% group_by(Patient.ID) %>% 
  mutate(hba1c_baseline = HbA1C[timepoint == "Baseline"]) %>% ungroup()
# Delete rows without PDF information
pdf_start <- which(colnames(adult)=="days_worn")
remove_rows <- which(rowSums(is.na(adult[,pdf_start:(pdf_start+20)]))==20)
adult <- adult[-c(remove_rows),]
# Combine am exit columns to match Cari's
adult$amexits = 
  rowSums(adult[,c(which(colnames(adult) == "no_calib_exit"):
                     which(colnames(adult) == "other_exit"))])
adult <- adult %>% 
  mutate(time_am = am_use,time_mm = manual,sensor_mean = avg_sensor,
         sensor_sd = sd_sensor,gmi = 3.31 + (sensor_mean * 0.02392),
         amexit_hyper = high_sg_exit/amexits,
         amexit_manual = user_disabled_exit/amexits,
         amexits_other = other_exit/amexits,
         amexits_day = amexits / days_worn,
         cohort = "Adult",hba1c = HbA1C,
         record_id = Patient.ID,race = Ethnicity,
         insurance = Insurance,sex = Gender)
# Re-level factors
adult$race <- as.factor(adult$race)
levels(adult$race) <- c("Non-white","Non-white","White","White","Non-white","Non-white","Non-white","More Than One Race","More Than One Race","Unknown / Not Reported")
adult$race <- as.character(adult$race)
adult$insurance <- as.factor(adult$insurance)
levels(adult$insurance) <- c("Other","Public","Private")
adult$insurance <- as.character(adult$insurance)
# Select columns
vars <- c("record_id","cohort","timepoint","age","sex","race","insurance",
          "hba1c_baseline","hba1c","gmi","time_am","time_mm","sensor_wear",
          "sensor_mean","sensor_sd","amexits","amexit_hyper","amexit_manual",
          "amexits_day","amexits_other")
adult <- adult %>%
  select(all_of(vars))
# Cari's data
source("/Users/timvigers/Documents/GitHub/BDC-Code/Cari Berget/670G Combined/data_clean.r")
data <- data[as.numeric(as.character(data$record_id)) < 116,]
data$cohort <- "Peds"
# Format
data$timepoint = 
  as.character(factor(data$gyl_timepoint,levels = 0:5,
                      labels = c("Baseline","M1","M3","M6","M9","M12")))
levels(data$demographics_sex.factor) = c("F","M")
# Age
data$age <- as.numeric(difftime(as.Date(data$automode_start,"%Y-%m-%d"),
                               as.Date(data$demographics_dob,"%Y-%m-%d"),
                                   units = "days"))/365.25
# Baseline A1c
data <- data %>% filter(!is.na(timepoint)) %>% group_by(record_id) %>% 
  mutate(hba1c_baseline = hba1c[timepoint == "Baseline"],
         age = age[timepoint == "Baseline"]) %>% ungroup()
# Make, fill down and select columns
data <- data %>%
  fill(demographics_dob,demographics_insurance.factor,demographics_sex.factor,
       demographics_race.factor) %>%
  mutate(race = demographics_race.factor,sex = as.character(demographics_sex.factor),
         insurance = demographics_insurance.factor,amexit_hyper = amexit_hyper / amexits,
         amexit_manual = amexit_manual / amexits,amexits_other = amexits_other / amexits,
         gmi = 3.31 + (sensor_mean * 0.02392),) %>%
  select(all_of(vars))
# One data frame
df = rbind(adult,data)
factor_vars = c("record_id","timepoint","sex","race","insurance","cohort")
df[,factor_vars] <- lapply(df[,factor_vars], as.factor)
```

```{r}
skim(df)
```

<!-- # Table 1: Descriptive Characteristics -->

<!-- ```{r table 1,echo=FALSE,results='asis',message=FALSE} -->

<!-- # Table 1 -->
<!-- t1 <- tableby(cohort ~ Age_Diagnosis + Gender,data = demographics) -->
<!-- # Print -->
<!-- summary(t1) -->
<!-- ``` -->

<!-- # Table 2: Days From AM Start by Timepoint -->

<!-- ```{r echo=FALSE,results='asis'} -->
<!-- t2 <- tableby(timepoint ~ notest(days_from_start,"Nmiss","median","q1q3"), -->
<!--               total = F,df) -->
<!-- summary(t2) -->
<!-- ``` -->

<!-- # Figure 1: HbA1c Over Time by Cohort -->

<!-- ```{r echo=FALSE,warning=FALSE,message=FALSE} -->
<!-- ggplot(df[!is.na(df$timepoint),],aes(x = timepoint,y = hba1c)) + -->
<!--   geom_line(alpha = 0.2,aes(group = record_id,color = cohort)) + -->
<!--   geom_smooth(aes(group = cohort,color = cohort),se = F) + -->
<!--   theme_bw() -->
<!-- ``` -->

<!-- # Model Results -->

<!-- ```{r models,echo=FALSE} -->
<!-- # AR1 correlation structure better by AIC - residuals look okay in general -->
<!-- hba1c_mod_ar1 <- lme(hba1c ~ timepoint*cohort,random = ~1|record_id,df, -->
<!--                      correlation=corAR1(),na.action = na.omit) -->
<!-- # Same model structure for all tests -->
<!-- mods <- -->
<!--   lapply(c("time_am","sensor_mean","amexits_day"), -->
<!--          function(x){ -->
<!--            form <- as.formula(paste(x,"~timepoint*cohort")) -->
<!--            mod <- lme(form,random = ~1|record_id,df, -->
<!--                       correlation=corAR1(),na.action = na.omit) -->
<!--          }) -->
<!-- ``` -->

<!-- ```{r results, echo=FALSE} -->
<!-- # HbA1c -->
<!-- res <- broom::tidy(hba1c_mod_ar1,effects = "fixed") -->
<!-- res$term <- gsub("timepoint|cohort","",res$term) -->
<!-- res[,2:ncol(res)] <- lapply(res[,2:ncol(res)],function(x){round(x,3)}) -->
<!-- t3_res <- as.data.frame(anova.lme(hba1c_mod_ar1)) -->
<!-- t3_res[,3:4] <- lapply(t3_res[,3:4], function(x){round(x,3)}) -->
<!-- kable(t3_res,caption = "HbA1c Overall Results") -->
<!-- kable(res,caption = "HbA1c Detailed Results") -->
<!-- # AM Time -->
<!-- res <- broom::tidy(mods[[1]],effects = "fixed") -->
<!-- res$term <- gsub("timepoint|cohort","",res$term) -->
<!-- res[,2:ncol(res)] <- lapply(res[,2:ncol(res)],function(x){round(x,3)}) -->
<!-- t3_res <- as.data.frame(anova.lme(mods[[1]])) -->
<!-- t3_res[,3:4] <- lapply(t3_res[,3:4], function(x){round(x,3)}) -->
<!-- kable(t3_res,caption = "% Time AM Overall Results") -->
<!-- kable(res,caption = "% Time AM Detailed Results") -->
<!-- # Sensor mean -->
<!-- res <- broom::tidy(mods[[2]],effects = "fixed") -->
<!-- res$term <- gsub("timepoint|cohort","",res$term) -->
<!-- res[,2:ncol(res)] <- lapply(res[,2:ncol(res)],function(x){round(x,3)}) -->
<!-- t3_res <- as.data.frame(anova.lme(mods[[2]])) -->
<!-- t3_res[,3:4] <- lapply(t3_res[,3:4], function(x){round(x,3)}) -->
<!-- kable(t3_res,caption = "Sensor Mean Overall Results") -->
<!-- kable(res,caption = "Sensor Mean Detailed Results") -->
<!-- # AM exits per day -->
<!-- res <- broom::tidy(mods[[3]],effects = "fixed") -->
<!-- res$term <- gsub("timepoint|cohort","",res$term) -->
<!-- res[,2:ncol(res)] <- lapply(res[,2:ncol(res)],function(x){round(x,3)}) -->
<!-- t3_res <- as.data.frame(anova.lme(mods[[3]])) -->
<!-- t3_res[,3:4] <- lapply(t3_res[,3:4], function(x){round(x,3)}) -->
<!-- kable(t3_res,caption = "AM Exits per Day Overall Results") -->
<!-- kable(res,caption = "AM Exits per Day Detailed Results") -->
<!-- ``` -->

<!-- # Questions/Notes -->

<!-- 1. There are no dates for Kaan's 55 new patients' A1c values, but  -->
