#Clear existing data and graphics
rm(list=ls())
graphics.off()
#Read Data
data=read.csv('/home/tim/Desktop/combined670g/Data_Cleaned/data.csv')
#Setting Factors(will create new variable for factors)
data$redcap_event_name.factor = factor(data$redcap_event_name,levels=c("baseline_arm_1","1_arm_1","2_arm_1","3_arm_1","4_arm_1","5_arm_1","baseline_arm_2","1_arm_2","2_arm_2","3_arm_2","4_arm_2","5_arm_2","baseline_arm_3","1_arm_3","2_arm_3","3_arm_3","4_arm_3","5_arm_3"))
data$child_ya.factor = factor(data$child_ya,levels=c("1","2"))
data$demographics_hcl.factor = factor(data$demographics_hcl,levels=c("0","1"))
data$demographics_ethnicity.factor = factor(data$demographics_ethnicity,levels=c("0","1","2"))
data$demographics_race.factor = factor(data$demographics_race,levels=c("0","1","2","3","4","5","6"))
data$demographics_sex.factor = factor(data$demographics_sex,levels=c("0","1"))
data$demographics_insurance.factor = factor(data$demographics_insurance,levels=c("1","2","3"))
data$demographics_pumphx.factor = factor(data$demographics_pumphx,levels=c("1","2","3","4","5","6","7"))
data$demographics_cgmhx.factor = factor(data$demographics_cgmhx,levels=c("1","2","3","4","5","6","7"))
data$demographics_complete.factor = factor(data$demographics_complete,levels=c("0","1","2"))
data$gyl_timepoint.factor = factor(data$gyl_timepoint,levels=c("0","1","2","3","4","5"))
data$glycemic_data_2d4b_complete.factor = factor(data$glycemic_data_2d4b_complete,levels=c("0","1","2"))
data$timepoint.factor = factor(data$timepoint,levels=c("0","1","2","3","4","5"))
data$baseline_surveys_complete.factor = factor(data$baseline_surveys_complete,levels=c("0","1","2"))
data$tech1.factor = factor(data$tech1,levels=c("0","1","2","3","4"))
data$tech2.factor = factor(data$tech2,levels=c("0","1","2","3","4"))
data$tech3.factor = factor(data$tech3,levels=c("0","1","2","3","4"))
data$tech4.factor = factor(data$tech4,levels=c("0","1","2","3","4"))
data$tech5.factor = factor(data$tech5,levels=c("0","1","2","3","4"))
data$diabetes_technology_survey_complete.factor = factor(data$diabetes_technology_survey_complete,levels=c("0","1","2"))
data$inspire_b1.factor = factor(data$inspire_b1,levels=c("0","1","2","3","4","5"))
data$inspire_b2.factor = factor(data$inspire_b2,levels=c("0","1","2","3","4","5"))
data$inspire_b3.factor = factor(data$inspire_b3,levels=c("0","1","2","3","4","5"))
data$inspire_b4.factor = factor(data$inspire_b4,levels=c("0","1","2","3","4","5"))
data$inspire_b5.factor = factor(data$inspire_b5,levels=c("0","1","2","3","4","5"))
data$inspire_b6.factor = factor(data$inspire_b6,levels=c("0","1","2","3","4","5"))
data$inspire_b7.factor = factor(data$inspire_b7,levels=c("0","1","2","3","4","5"))
data$inspire_b8.factor = factor(data$inspire_b8,levels=c("0","1","2","3","4","5"))
data$inspire_b9.factor = factor(data$inspire_b9,levels=c("0","1","2","3","4","5"))
data$inspire_b10.factor = factor(data$inspire_b10,levels=c("0","1","2","3","4","5"))
data$inspire_b11.factor = factor(data$inspire_b11,levels=c("0","1","2","3","4","5"))
data$inspire_b12.factor = factor(data$inspire_b12,levels=c("0","1","2","3","4","5"))
data$inspire_b13.factor = factor(data$inspire_b13,levels=c("0","1","2","3","4","5"))
data$inspire_b14.factor = factor(data$inspire_b14,levels=c("0","1","2","3","4","5"))
data$inspire_b15.factor = factor(data$inspire_b15,levels=c("0","1","2","3","4","5"))
data$inspire_b16.factor = factor(data$inspire_b16,levels=c("0","1","2","3","4","5"))
data$inspire_b17.factor = factor(data$inspire_b17,levels=c("0","1","2","3","4","5"))
data$inspire_youth_baseline_complete.factor = factor(data$inspire_youth_baseline_complete,levels=c("0","1","2"))
data$inspire_f1.factor = factor(data$inspire_f1,levels=c("0","1","2","3","4","5"))
data$inspire_f2.factor = factor(data$inspire_f2,levels=c("0","1","2","3","4","5"))
data$inspire_f3.factor = factor(data$inspire_f3,levels=c("0","1","2","3","4","5"))
data$inspire_f4.factor = factor(data$inspire_f4,levels=c("0","1","2","3","4","5"))
data$inspire_f5.factor = factor(data$inspire_f5,levels=c("0","1","2","3","4","5"))
data$inspire_f6.factor = factor(data$inspire_f6,levels=c("0","1","2","3","4","5"))
data$inspire_f7.factor = factor(data$inspire_f7,levels=c("0","1","2","3","4","5"))
data$inspire_f8.factor = factor(data$inspire_f8,levels=c("0","1","2","3","4","5"))
data$inspire_f9.factor = factor(data$inspire_f9,levels=c("0","1","2","3","4","5"))
data$inspire_f10.factor = factor(data$inspire_f10,levels=c("0","1","2","3","4","5"))
data$inspire_f11.factor = factor(data$inspire_f11,levels=c("0","1","2","3","4","5"))
data$inspire_f12.factor = factor(data$inspire_f12,levels=c("0","1","2","3","4","5"))
data$inspire_f13.factor = factor(data$inspire_f13,levels=c("0","1","2","3","4","5"))
data$inspire_f14.factor = factor(data$inspire_f14,levels=c("0","1","2","3","4","5"))
data$inspire_f15.factor = factor(data$inspire_f15,levels=c("0","1","2","3","4","5"))
data$inspire_f16.factor = factor(data$inspire_f16,levels=c("0","1","2","3","4","5"))
data$inspire_f17.factor = factor(data$inspire_f17,levels=c("0","1","2","3","4","5"))
data$inspire_youth_follow_up_complete.factor = factor(data$inspire_youth_follow_up_complete,levels=c("0","1","2"))
data$ya_baseline1.factor = factor(data$ya_baseline1,levels=c("1","2","3","4","5","6","7"))
data$ya_baseline2.factor = factor(data$ya_baseline2,levels=c("0","1","2","3","4","5","6","7","8","9"))
data$ya_baseline3.factor = factor(data$ya_baseline3,levels=c("0","1","2","3","4","5","6","7","8","9"))
data$ya_baseline4.factor = factor(data$ya_baseline4,levels=c("1","2"))
data$ya_baseline6.factor = factor(data$ya_baseline6,levels=c("1","2","3","4","5"))
data$ya_baseline7.factor = factor(data$ya_baseline7,levels=c("1","2"))
data$ya_baseline9.factor = factor(data$ya_baseline9,levels=c("1","2","3","4"))
data$ya_baseline_survey_complete.factor = factor(data$ya_baseline_survey_complete,levels=c("0","1","2"))
data$ya_paid1.factor = factor(data$ya_paid1,levels=c("0","1","2","3","4"))
data$ya_paid2.factor = factor(data$ya_paid2,levels=c("0","1","2","3","4"))
data$ya_paid3.factor = factor(data$ya_paid3,levels=c("0","1","2","3","4"))
data$ya_paid4.factor = factor(data$ya_paid4,levels=c("0","1","2","3","4"))
data$ya_paid5.factor = factor(data$ya_paid5,levels=c("0","1","2","3","4"))
data$ya_paid6.factor = factor(data$ya_paid6,levels=c("0","1","2","3","4"))
data$ya_paid7.factor = factor(data$ya_paid7,levels=c("0","1","2","3","4"))
data$ya_paid8.factor = factor(data$ya_paid8,levels=c("0","1","2","3","4"))
data$ya_paid9.factor = factor(data$ya_paid9,levels=c("0","1","2","3","4"))
data$ya_paid10.factor = factor(data$ya_paid10,levels=c("0","1","2","3","4"))
data$ya_paid11.factor = factor(data$ya_paid11,levels=c("0","1","2","3","4"))
data$ya_paid12.factor = factor(data$ya_paid12,levels=c("0","1","2","3","4"))
data$ya_paid13.factor = factor(data$ya_paid13,levels=c("0","1","2","3","4"))
data$ya_paid14.factor = factor(data$ya_paid14,levels=c("0","1","2","3","4"))
data$ya_paid15.factor = factor(data$ya_paid15,levels=c("0","1","2","3","4"))
data$ya_paid16.factor = factor(data$ya_paid16,levels=c("0","1","2","3","4"))
data$ya_paid17.factor = factor(data$ya_paid17,levels=c("0","1","2","3","4"))
data$ya_paid18.factor = factor(data$ya_paid18,levels=c("0","1","2","3","4"))
data$ya_paid19.factor = factor(data$ya_paid19,levels=c("0","1","2","3","4"))
data$ya_paid20.factor = factor(data$ya_paid20,levels=c("0","1","2","3","4"))
data$ya_paid_survey_complete.factor = factor(data$ya_paid_survey_complete,levels=c("0","1","2"))
data$ya_hfs_b_behave1.factor = factor(data$ya_hfs_b_behave1,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave2.factor = factor(data$ya_hfs_b_behave2,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave3.factor = factor(data$ya_hfs_b_behave3,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave4.factor = factor(data$ya_hfs_b_behave4,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave5.factor = factor(data$ya_hfs_b_behave5,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave6.factor = factor(data$ya_hfs_b_behave6,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave7.factor = factor(data$ya_hfs_b_behave7,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave8.factor = factor(data$ya_hfs_b_behave8,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave9.factor = factor(data$ya_hfs_b_behave9,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave10.factor = factor(data$ya_hfs_b_behave10,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave11.factor = factor(data$ya_hfs_b_behave11,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave12.factor = factor(data$ya_hfs_b_behave12,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave13.factor = factor(data$ya_hfs_b_behave13,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave14.factor = factor(data$ya_hfs_b_behave14,levels=c("0","1","2","3","4"))
data$ya_hfs_b_behave15.factor = factor(data$ya_hfs_b_behave15,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry16.factor = factor(data$ya_hfs_b_worry16,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry17.factor = factor(data$ya_hfs_b_worry17,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry18.factor = factor(data$ya_hfs_b_worry18,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry19.factor = factor(data$ya_hfs_b_worry19,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry20.factor = factor(data$ya_hfs_b_worry20,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry21.factor = factor(data$ya_hfs_b_worry21,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry22.factor = factor(data$ya_hfs_b_worry22,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry23.factor = factor(data$ya_hfs_b_worry23,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry24.factor = factor(data$ya_hfs_b_worry24,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry25.factor = factor(data$ya_hfs_b_worry25,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry26.factor = factor(data$ya_hfs_b_worry26,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry27.factor = factor(data$ya_hfs_b_worry27,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry28.factor = factor(data$ya_hfs_b_worry28,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry29.factor = factor(data$ya_hfs_b_worry29,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry30.factor = factor(data$ya_hfs_b_worry30,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry31.factor = factor(data$ya_hfs_b_worry31,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry32.factor = factor(data$ya_hfs_b_worry32,levels=c("0","1","2","3","4"))
data$ya_hfs_b_worry33.factor = factor(data$ya_hfs_b_worry33,levels=c("0","1","2","3","4"))
data$ya_hfs__b_hypo_sev.factor = factor(data$ya_hfs__b_hypo_sev,levels=c("1","2","3","4","5","6","7","8","9","10"))
data$ya_hfs_b_hypo_sev_upset.factor = factor(data$ya_hfs_b_hypo_sev_upset,levels=c("1","2","3","4","5"))
data$ya_hfs_b_hypo_mod.factor = factor(data$ya_hfs_b_hypo_mod,levels=c("0","1","2","3","4","5","6","7","8","9"))
data$ya_hfs_b_hypo_mod_upset.factor = factor(data$ya_hfs_b_hypo_mod_upset,levels=c("0","1","2","3","4"))
data$ya_hfs_b_hypo_mild.factor = factor(data$ya_hfs_b_hypo_mild,levels=c("0","1","2","3","4","5","6","7","8","9"))
data$ya_hfs_b_hypo_mild_upset.factor = factor(data$ya_hfs_b_hypo_mild_upset,levels=c("0","1","2","3","4"))
data$ya_hfs_baseline_survey_complete.factor = factor(data$ya_hfs_baseline_survey_complete,levels=c("0","1","2"))
data$ya_hfs_f_behave1.factor = factor(data$ya_hfs_f_behave1,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave2.factor = factor(data$ya_hfs_f_behave2,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave3.factor = factor(data$ya_hfs_f_behave3,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave4.factor = factor(data$ya_hfs_f_behave4,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave5.factor = factor(data$ya_hfs_f_behave5,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave6.factor = factor(data$ya_hfs_f_behave6,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave7.factor = factor(data$ya_hfs_f_behave7,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave8.factor = factor(data$ya_hfs_f_behave8,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave9.factor = factor(data$ya_hfs_f_behave9,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave10.factor = factor(data$ya_hfs_f_behave10,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave11.factor = factor(data$ya_hfs_f_behave11,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave12.factor = factor(data$ya_hfs_f_behave12,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave13.factor = factor(data$ya_hfs_f_behave13,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave14.factor = factor(data$ya_hfs_f_behave14,levels=c("0","1","2","3","4"))
data$ya_hfs_f_behave15.factor = factor(data$ya_hfs_f_behave15,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry16.factor = factor(data$ya_hfs_f_worry16,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry17.factor = factor(data$ya_hfs_f_worry17,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry18.factor = factor(data$ya_hfs_f_worry18,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry19.factor = factor(data$ya_hfs_f_worry19,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry20.factor = factor(data$ya_hfs_f_worry20,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry21.factor = factor(data$ya_hfs_f_worry21,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry22.factor = factor(data$ya_hfs_f_worry22,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry23.factor = factor(data$ya_hfs_f_worry23,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry24.factor = factor(data$ya_hfs_f_worry24,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry25.factor = factor(data$ya_hfs_f_worry25,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry26.factor = factor(data$ya_hfs_f_worry26,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry27.factor = factor(data$ya_hfs_f_worry27,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry28.factor = factor(data$ya_hfs_f_worry28,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry29.factor = factor(data$ya_hfs_f_worry29,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry30.factor = factor(data$ya_hfs_f_worry30,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry31.factor = factor(data$ya_hfs_f_worry31,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry32.factor = factor(data$ya_hfs_f_worry32,levels=c("0","1","2","3","4"))
data$ya_hfs_f_worry33.factor = factor(data$ya_hfs_f_worry33,levels=c("0","1","2","3","4"))
data$ya_hfs_f_hypo_sev.factor = factor(data$ya_hfs_f_hypo_sev,levels=c("1","2","3","4","5","6","7","8","9","10"))
data$ya_hfs_f_hypo_sev_upset.factor = factor(data$ya_hfs_f_hypo_sev_upset,levels=c("1","2","3","4","5"))
data$ya_hfs_f_hypo_mod.factor = factor(data$ya_hfs_f_hypo_mod,levels=c("0","1","2","3","4","5","6","7","8","9"))
data$ya_hfs_f_hypo_mod_upset.factor = factor(data$ya_hfs_f_hypo_mod_upset,levels=c("0","1","2","3","4"))
data$ya_hfs_f_hypo_mild.factor = factor(data$ya_hfs_f_hypo_mild,levels=c("0","1","2","3","4","5","6","7","8","9"))
data$ya_hfs_f_hypo_mild_upset.factor = factor(data$ya_hfs_f_hypo_mild_upset,levels=c("0","1","2","3","4"))
data$ya_hfs_follow_up_survey_complete.factor = factor(data$ya_hfs_follow_up_survey_complete,levels=c("0","1","2"))
data$c_hfs_behave1.factor = factor(data$c_hfs_behave1,levels=c("0","1","2","3","4"))
data$c_hfs_behave2.factor = factor(data$c_hfs_behave2,levels=c("0","1","2","3","4"))
data$c_hfs_behave3.factor = factor(data$c_hfs_behave3,levels=c("0","1","2","3","4"))
data$c_hfs_behave4.factor = factor(data$c_hfs_behave4,levels=c("0","1","2","3","4"))
data$c_hfs_behave5.factor = factor(data$c_hfs_behave5,levels=c("0","1","2","3","4"))
data$c_hfs_behave6.factor = factor(data$c_hfs_behave6,levels=c("0","1","2","3","4"))
data$c_hfs_behave7.factor = factor(data$c_hfs_behave7,levels=c("0","1","2","3","4"))
data$c_hfs_behave8.factor = factor(data$c_hfs_behave8,levels=c("0","1","2","3","4"))
data$c_hfs_behave9.factor = factor(data$c_hfs_behave9,levels=c("0","1","2","3","4"))
data$c_hfs_behave10.factor = factor(data$c_hfs_behave10,levels=c("0","1","2","3","4"))
data$c_hfs_worry11.factor = factor(data$c_hfs_worry11,levels=c("0","1","2","3","4"))
data$c_hfs_worry12.factor = factor(data$c_hfs_worry12,levels=c("0","1","2","3","4"))
data$c_hfs_worry13.factor = factor(data$c_hfs_worry13,levels=c("0","1","2","3","4"))
data$c_hfs_worry14.factor = factor(data$c_hfs_worry14,levels=c("0","1","2","3","4"))
data$c_hfs_worry15.factor = factor(data$c_hfs_worry15,levels=c("0","1","2","3","4"))
data$c_hfs_worry16.factor = factor(data$c_hfs_worry16,levels=c("0","1","2","3","4"))
data$c_hfs_worry17.factor = factor(data$c_hfs_worry17,levels=c("0","1","2","3","4"))
data$c_hfs_worry18.factor = factor(data$c_hfs_worry18,levels=c("0","1","2","3","4"))
data$c_hfs_worry19.factor = factor(data$c_hfs_worry19,levels=c("0","1","2","3","4"))
data$c_hfs_worry20.factor = factor(data$c_hfs_worry20,levels=c("0","1","2","3","4"))
data$c_hfs_worry21.factor = factor(data$c_hfs_worry21,levels=c("0","1","2","3","4"))
data$c_hfs_worry22.factor = factor(data$c_hfs_worry22,levels=c("0","1","2","3","4"))
data$c_hfs_worry23.factor = factor(data$c_hfs_worry23,levels=c("0","1","2","3","4"))
data$c_hfs_worry24.factor = factor(data$c_hfs_worry24,levels=c("0","1","2","3","4"))
data$c_hfs_worry25.factor = factor(data$c_hfs_worry25,levels=c("0","1","2","3","4"))
data$child_hfs_survey_complete.factor = factor(data$child_hfs_survey_complete,levels=c("0","1","2"))
data$c_paid1.factor = factor(data$c_paid1,levels=c("1","2","3","4","5"))
data$c_paid2.factor = factor(data$c_paid2,levels=c("1","2","3","4","5"))
data$c_paid3.factor = factor(data$c_paid3,levels=c("1","2","3","4","5"))
data$c_paid4.factor = factor(data$c_paid4,levels=c("1","2","3","4","5"))
data$c_paid5.factor = factor(data$c_paid5,levels=c("1","2","3","4","5"))
data$c_paid6.factor = factor(data$c_paid6,levels=c("1","2","3","4","5"))
data$c_paid7.factor = factor(data$c_paid7,levels=c("1","2","3","4","5"))
data$c_paid8.factor = factor(data$c_paid8,levels=c("1","2","3","4","5"))
data$c_paid9.factor = factor(data$c_paid9,levels=c("1","2","3","4","5"))
data$c_paid10.factor = factor(data$c_paid10,levels=c("1","2","3","4","5"))
data$c_paid11.factor = factor(data$c_paid11,levels=c("1","2","3","4","5"))
data$c_paid12.factor = factor(data$c_paid12,levels=c("1","2","3","4","5"))
data$c_paid13.factor = factor(data$c_paid13,levels=c("1","2","3","4","5"))
data$c_paid14.factor = factor(data$c_paid14,levels=c("1","2","3","4","5"))
data$c_paid15.factor = factor(data$c_paid15,levels=c("1","2","3","4","5"))
data$c_paid16.factor = factor(data$c_paid16,levels=c("1","2","3","4","5"))
data$c_paid17.factor = factor(data$c_paid17,levels=c("1","2","3","4","5"))
data$c_paid18.factor = factor(data$c_paid18,levels=c("1","2","3","4","5"))
data$c_paid19.factor = factor(data$c_paid19,levels=c("1","2","3","4","5"))
data$c_paid20.factor = factor(data$c_paid20,levels=c("1","2","3","4","5"))
data$child_paid_survey_complete.factor = factor(data$child_paid_survey_complete,levels=c("0","1","2"))
data$inspire_b1_adult.factor = factor(data$inspire_b1_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b2_adult.factor = factor(data$inspire_b2_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b3_adult.factor = factor(data$inspire_b3_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b4_adult.factor = factor(data$inspire_b4_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b5_adult.factor = factor(data$inspire_b5_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b6_adult.factor = factor(data$inspire_b6_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b7_adult.factor = factor(data$inspire_b7_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b8_adult.factor = factor(data$inspire_b8_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b9_adult.factor = factor(data$inspire_b9_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b10_adult.factor = factor(data$inspire_b10_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b11_adult.factor = factor(data$inspire_b11_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b12_adult.factor = factor(data$inspire_b12_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b13_adult.factor = factor(data$inspire_b13_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b14_adult.factor = factor(data$inspire_b14_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b15_adult.factor = factor(data$inspire_b15_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b16_adult.factor = factor(data$inspire_b16_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b17_adult.factor = factor(data$inspire_b17_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b18_adult.factor = factor(data$inspire_b18_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b19_adult.factor = factor(data$inspire_b19_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b20_adult.factor = factor(data$inspire_b20_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b21_adult.factor = factor(data$inspire_b21_adult,levels=c("0","1","2","3","4","5"))
data$inspire_b22_adult.factor = factor(data$inspire_b22_adult,levels=c("0","1","2","3","4","5"))
data$inspire_adult_baseline_complete.factor = factor(data$inspire_adult_baseline_complete,levels=c("0","1","2"))
data$inspire_f1_adult.factor = factor(data$inspire_f1_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f2_adult.factor = factor(data$inspire_f2_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f3_adult.factor = factor(data$inspire_f3_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f4_adult.factor = factor(data$inspire_f4_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f5_adult.factor = factor(data$inspire_f5_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f6_adult.factor = factor(data$inspire_f6_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f7_adult.factor = factor(data$inspire_f7_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f8_adult.factor = factor(data$inspire_f8_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f9_adult.factor = factor(data$inspire_f9_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f10_adult.factor = factor(data$inspire_f10_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f11_adult.factor = factor(data$inspire_f11_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f12_adult.factor = factor(data$inspire_f12_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f13_adult.factor = factor(data$inspire_f13_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f14_adult.factor = factor(data$inspire_f14_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f15_adult.factor = factor(data$inspire_f15_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f16_adult.factor = factor(data$inspire_f16_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f17_adult.factor = factor(data$inspire_f17_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f18_adult.factor = factor(data$inspire_f18_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f19_adult.factor = factor(data$inspire_f19_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f20_adult.factor = factor(data$inspire_f20_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f21_adult.factor = factor(data$inspire_f21_adult,levels=c("0","1","2","3","4","5"))
data$inspire_f22_adult.factor = factor(data$inspire_f22_adult,levels=c("0","1","2","3","4","5"))
data$inspire_adult_follow_up_complete.factor = factor(data$inspire_adult_follow_up_complete,levels=c("0","1","2"))
data$a_baseline1.factor = factor(data$a_baseline1,levels=c("1","2","3","4","5","6","7"))
data$a_baseline2.factor = factor(data$a_baseline2,levels=c("0","1","2","3","4","5","6","7","8","9"))
data$a_baseline3.factor = factor(data$a_baseline3,levels=c("1","2"))
data$a_baseline5.factor = factor(data$a_baseline5,levels=c("1","2","3","4","5"))
data$a_baseline6.factor = factor(data$a_baseline6,levels=c("1","2"))
data$a_baseline8.factor = factor(data$a_baseline8,levels=c("1","2","3","4"))
data$adult_baseline_survey_complete.factor = factor(data$adult_baseline_survey_complete,levels=c("0","1","2"))

levels(data$redcap_event_name.factor)=c("Baseline (Arm 1: Child)","1 (Arm 1: Child)","2 (Arm 1: Child)","3 (Arm 1: Child)","4 (Arm 1: Child)","5 (Arm 1: Child)","Baseline (Arm 2: Young Adult )","1 (Arm 2: Young Adult )","2 (Arm 2: Young Adult )","3 (Arm 2: Young Adult )","4 (Arm 2: Young Adult )","5 (Arm 2: Young Adult )","Baseline (Arm 3: Adult)","1 (Arm 3: Adult)","2 (Arm 3: Adult)","3 (Arm 3: Adult)","4 (Arm 3: Adult)","5 (Arm 3: Adult)")
levels(data$child_ya.factor)=c("Child (0-17 years)","Adult (18+ years)")
levels(data$demographics_hcl.factor)=c("670G","Control IQ")
levels(data$demographics_ethnicity.factor)=c("Hispanic or Latino","NOT Hispanic or Latino","Unknown / Not Reported")
levels(data$demographics_race.factor)=c("American Indian/Alaska Native","Asian","Native Hawaiian or Other Pacific Islander","Black or African American","White","More Than One Race","Unknown / Not Reported")
levels(data$demographics_sex.factor)=c("Female","Male")
levels(data$demographics_insurance.factor)=c("Public","Private","Other")
levels(data$demographics_pumphx.factor)=c("< 1 month","1-6 months","6 mnths - 1 yr","1-3 years","3-5 years",">5 years","None")
levels(data$demographics_cgmhx.factor)=c("< 1 month","1-6 months","6 mnths - 1 yr","1-3 years","3-5 years",">5 years","None")
levels(data$demographics_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$gyl_timepoint.factor)=c("Baseline","Month 1/ Training F/U","3 Months","6 Months","9 Months","12 Months")
levels(data$glycemic_data_2d4b_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$timepoint.factor)=c("Baseline","Month 1/ Training F/U","3 Months","6 Months","9 Months","12 Months")
levels(data$baseline_surveys_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$tech1.factor)=c("Strongly Disagree","Disagree","Neutral","Agree","Strongly Agree")
levels(data$tech2.factor)=c("Strongly Disagree","Disagree","Neutral","Agree","Strongly Agree")
levels(data$tech3.factor)=c("Strongly Disagree","Disagree","Neutral","Agree","Strongly Agree")
levels(data$tech4.factor)=c("Strongly Disagree","Disagree","Neutral","Agree","Strongly Agree")
levels(data$tech5.factor)=c("Strongly Disagree","Disagree","Neutral","Agree","Strongly Agree")
levels(data$diabetes_technology_survey_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$inspire_b1.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b2.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b3.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b4.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b5.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b6.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b7.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b8.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b9.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b10.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b11.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b12.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b13.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b14.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b15.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b16.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b17.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_youth_baseline_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$inspire_f1.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f2.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f3.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f4.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f5.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f6.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f7.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f8.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f9.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f10.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f11.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f12.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f13.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f14.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f15.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f16.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f17.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_youth_follow_up_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$ya_baseline1.factor)=c("< $25,000 per year","$25,000 to less than $35,000 per year","$35,000 to less than $50,000 per year","$50,000 to less than $75,000 per year","$75,000 to less than $100,000 per year","$100,000 or more per year","Decline to answer")
levels(data$ya_baseline2.factor)=c("Not Known/ Decline to answer","< 7th grade","Junior High School","Partial High School (10th or 11th grade)","High School Graduate/GED","Partial College","Associates Degree","Bachelors Degree","Masters Degree","Doctorate Degree")
levels(data$ya_baseline3.factor)=c("Not Known/ Decline to answer","< 7th grade","Junior High School","Partial High School (10th or 11th grade)","High School Graduate/GED","Partial College","Associates Degree","Bachelors Degree","Masters Degree","Doctorate Degree")
levels(data$ya_baseline4.factor)=c("Yes","No")
levels(data$ya_baseline6.factor)=c("Animas (One Touch Ping or Vibe)","Medtronic (530G, 630G)","Tandem (t:slim x2)","Omnipod (Omnipod system or Omnipod dash system)","Other")
levels(data$ya_baseline7.factor)=c("Yes","No")
levels(data$ya_baseline9.factor)=c("Medtronic (Guardian 3 or Enlite)","Dexcom (Dexcom G4, G5 or G6)","Freestyle Libre","Other")
levels(data$ya_baseline_survey_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$ya_paid1.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid2.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid3.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid4.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid5.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid6.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid7.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid8.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid9.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid10.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid11.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid12.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid13.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid14.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid15.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid16.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid17.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid18.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid19.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid20.factor)=c("Not a problem","Minor problem","Moderate problem","Somewhat serious problem","Serious Problem")
levels(data$ya_paid_survey_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$ya_hfs_b_behave1.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave2.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave3.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave4.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave5.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave6.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave7.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave8.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave9.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave10.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave11.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave12.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave13.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave14.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_behave15.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry16.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry17.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry18.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry19.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry20.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry21.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry22.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry23.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry24.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry25.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry26.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry27.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry28.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry29.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry30.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry31.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry32.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_b_worry33.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs__b_hypo_sev.factor)=c("0","1","2","3","4","5","6","7","8","9 or more")
levels(data$ya_hfs_b_hypo_sev_upset.factor)=c("0 Not Upsetting at all","1","2 Somewhat upsettin","3","4 Extremely upsetting")
levels(data$ya_hfs_b_hypo_mod.factor)=c("0","1","2","3","4","5","6","7","8","9 or more")
levels(data$ya_hfs_b_hypo_mod_upset.factor)=c("0 Not at all upsetting","1","2 Somewhat upsetting","3","4 Extremely Upsetting")
levels(data$ya_hfs_b_hypo_mild.factor)=c("0","1","2","3","4","5","6","7","8","9 or more")
levels(data$ya_hfs_b_hypo_mild_upset.factor)=c("0 Not at all Upsetting","1","2 Somewhat upsetting","3","4 Extremely upsetting")
levels(data$ya_hfs_baseline_survey_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$ya_hfs_f_behave1.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave2.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave3.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave4.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave5.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave6.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave7.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave8.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave9.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave10.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave11.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave12.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave13.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave14.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_behave15.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry16.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry17.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry18.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry19.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry20.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry21.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry22.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry23.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry24.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry25.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry26.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry27.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry28.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry29.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry30.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry31.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry32.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_worry33.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$ya_hfs_f_hypo_sev.factor)=c("0","1","2","3","4","5","6","7","8","9 or more")
levels(data$ya_hfs_f_hypo_sev_upset.factor)=c("0 Not Upsetting at all","1","2 Somewhat upsettin","3","4 Extremely upsetting")
levels(data$ya_hfs_f_hypo_mod.factor)=c("0","1","2","3","4","5","6","7","8","9 or more")
levels(data$ya_hfs_f_hypo_mod_upset.factor)=c("0 Not at all upsetting","1","2 Somewhat upsetting","3","4 Extremely Upsetting")
levels(data$ya_hfs_f_hypo_mild.factor)=c("0","1","2","3","4","5","6","7","8","9 or more")
levels(data$ya_hfs_f_hypo_mild_upset.factor)=c("0 Not at all Upsetting","1","2 Somewhat upsetting","3","4 Extremely upsetting")
levels(data$ya_hfs_follow_up_survey_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$c_hfs_behave1.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_behave2.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_behave3.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_behave4.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_behave5.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_behave6.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_behave7.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_behave8.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_behave9.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_behave10.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry11.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry12.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry13.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry14.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry15.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry16.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry17.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry18.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry19.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry20.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry21.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry22.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry23.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry24.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$c_hfs_worry25.factor)=c("Never","Rarely","Sometimes","Often","Almost Always")
levels(data$child_hfs_survey_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$c_paid1.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid2.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid3.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid4.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid5.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid6.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid7.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid8.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid9.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid10.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid11.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid12.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid13.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid14.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid15.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid16.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid17.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid18.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid19.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$c_paid20.factor)=c("Agree","Somewhat Agree","Neutral","Somewhat Disagree","Disagree")
levels(data$child_paid_survey_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$inspire_b1_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b2_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b3_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b4_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b5_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b6_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b7_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b8_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b9_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b10_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b11_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b12_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b13_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b14_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b15_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b16_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b17_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b18_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b19_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b20_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b21_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_b22_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_adult_baseline_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$inspire_f1_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f2_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f3_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f4_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f5_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f6_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f7_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f8_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f9_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f10_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f11_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f12_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f13_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f14_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f15_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f16_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f17_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f18_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f19_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f20_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f21_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_f22_adult.factor)=c("Strongly Disagree","Disagree","Neither Agree nor Disagree","Agree","Strongly Agree","N/A")
levels(data$inspire_adult_follow_up_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$a_baseline1.factor)=c("< $25,000 per year","$25,000 to less than $35,000 per year","$35,000 to less than $50,000 per year","$50,000 to less than $75,000 per year","$75,000 to less than $100,000 per year","$100,000 or more per year","Decline to answer")
levels(data$a_baseline2.factor)=c("Not Known/ Decline to answer","< 7th grade","Junior High School","Partial High School (10th or 11th grade)","High School Graduate/GED","Partial College","Associates Degree","Bachelors Degree","Masters Degree","Doctorate Degree")
levels(data$a_baseline3.factor)=c("Yes","No")
levels(data$a_baseline5.factor)=c("Animas (One Touch Ping or Vibe)","Medtronic (530G, 630G)","Tandem (t:slim x2)","Omnipod (Omnipod system or Omnipod dash system)","Other")
levels(data$a_baseline6.factor)=c("Yes","No")
levels(data$a_baseline8.factor)=c("Medtronic (Guardian 3 or Enlite)","Dexcom (Dexcom G4, G5 or G6)","Freestyle Libre","Other")
levels(data$adult_baseline_survey_complete.factor)=c("Incomplete","Unverified","Complete")
