---
title: "T1D MEGA Preliminary Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/peds/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Kimber Simmons/GWAS/Data_Cleaned/association")
library(qqman) 
```

```{bash echo=FALSE,eval=FALSE}
# Directory
cd /Volumes/peds/RI\ Biostatistics\ Core/Shared/Shared\ Projects/Laura/BDC/Projects/Kimber\ Simmons/GWAS/Data_Cleaned/association
# Plink logistic regression
plink --bfile final_merge --covar covar_mds.txt --hide-covar --logistic --out logistic_results --memory 6144
# Permutation testing
plink --bfile final_merge --logistic --model mperm=1000000 --out perm_result --memory 6144
```

# Logistic Regression

```{r echo=FALSE,warning=FALSE}
# Import SNPs of interest
snps <- read.table("t1d_snps.txt",header = T)
# Import logistic results
results_log <- read.table("logistic_results.assoc.logistic",header = T)
# Remove rows without p values or p = 0
results_log <- results_log[!is.na(results_log$P) & results_log$P > 0,]
# Plots
manhattan(results_log,chr="CHR",bp="BP",p="P",snp="SNP", 
          main = "Manhattan plot: logistic",highlight = snps$SNP,
          annotatePval = 1e-20, annotateTop = FALSE)
qq(results_log$P)
```

<!-- # Logistic Regression with Permutation Adjustment -->

<!-- ```{r echo=FALSE,warning=FALSE} -->
<!-- # re-import logistic results -->
<!-- results_log <- read.table("logistic_results.assoc.logistic",header = T) -->
<!-- # Import permutation results, add to logistic results -->
<!-- perm <- read.table("perm_result.model.best.mperm",header = T) -->
<!-- results_log <- merge(results_log,perm[,c(2,4)],by = "SNP") -->
<!-- results_log <- results_log[!is.na(results_log$EMP2) & results_log$EMP2 > 0,] -->
<!-- # Plots -->
<!-- manhattan(results_log,chr="CHR",bp="BP",p="EMP2",snp="SNP",  -->
<!--           main = "Manhattan plot: logistic (permutation)",highlight = snps$SNP, -->
<!--           annotatePval = 1e-75, annotateTop = FALSE) -->
<!-- qq(results_log$P) -->
<!-- ``` -->
