---
title: "Kim Driscoll Pump Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
```

```{r echo=FALSE, include=FALSE}
# Data notes:
#   - manually added subject IDs for 129, 213, 319
#   - deleted 213 blood glucose file
#   - manually deleted top rows for T2_302, T2_308 through T2_327, and T3_300 through T3_327
#   - manually deleted "Timestamp" column for T3_325
#   - manually combined T2_148 into a single file
#   - manually changed 327 dates:
    # T1 3/6/2017
    # T2 6/26/2017
    # T3 9/20/2017
    # T4 12/4/2017
    # T5 6/15/2018
```

```{r echo=FALSE,eval=FALSE}
# Data management
# Study dates
dates <- read.csv("/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Kim Driscoll/Baseline Pump Paper/Data_Cleaned/PumpItUp_Appt Times.csv")
# Format 
dates[,2:ncol(dates)] <- lapply(dates[,2:ncol(dates)],lubridate::mdy)
indir <- "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Kim Driscoll/Baseline Pump Paper/Data_Cleaned/Pump Files Original/"
outdir <- "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Kim Driscoll/Baseline Pump Paper/Data_Cleaned/Pump Files Cleaned/"
files <- list.files(indir,full.names = T)
for (f in 1:length(files)) {
  dat <- read.csv(files[f],stringsAsFactors = FALSE,header = TRUE,
                  na.strings = "")
  id <- sub("_pump.csv","",basename(files[f]))
  id_no_timepoint <- sub(".*_","",id)
# Check file format.  
  if (id == "") {
    stop("No ID")
  } else if (ncol(dat) < 33) {
    stop("Not enough columns",call. = F)
  }
  if (colnames(dat)[1] != "Index") {
# Delete nonessential rows.
    rowstart <- which(dat$Last.Name == "-------")[1]
    pump <- dat[c((rowstart + 2):(nrow(dat)-3)),]
    colnames(pump) <- dat[rowstart+1,]
  } else {
    pump <- dat
  }
# Remove sensor data  
  pumpend <- which(dat$Patient.ID == "Sensor")
  if (length(pumpend) > 0) {dat <- dat[-c(pumpend:nrow(dat)),]}
# Get dates
  if (grepl("T1",id) == T) {
    end <- dates$T1_Date[which(dates$ID == id_no_timepoint)]
    start <- end - 90
  } else if (grepl("T2",id) == T) {
    start <- dates$T1_Date[which(dates$ID == id_no_timepoint)]
    end <- dates$T2_Date[which(dates$ID == id_no_timepoint)]
  } else if (grepl("T3",id) == T) {
    start <- dates$T2_Date[which(dates$ID == id_no_timepoint)]
    end <- dates$T3_Date[which(dates$ID == id_no_timepoint)]
  }
# Format timestamp, remove rows without datetime data.
  pump$timestamp <- paste(pump$Date,pump$Time)
  pump$timestamp <- lubridate::mdy_hms(pump$timestamp)
  pump <- pump[which(!is.na(pump$timestamp)),]
# Remove rows with data outside study time range if there is any.
  pump <- pump %>% filter(timestamp > start & timestamp < end)
# Standardize column names, delete irrelevant ones
  colnames(pump) <- tolower(gsub(c("[[:punct:]]"),"",colnames(pump)))
  colnames(pump) <- gsub(c(" "),"",colnames(pump))
  pump <- pump[,c("timestamp","bolustype","bwzestimateu",
                  "bolusvolumeselectedu","bolusvolumedeliveredu",
                  "bwzcarbinputgrams","bwzbginputmgdl",
                  "bgreadingmgdl")]
  colnames(pump) <- c(c("timestamp","bolustype","bwzestimate",
                        "bolusvolselected","bolusvoldelivered","carbinput",
                        "bginput","bgreading"))
  # Order by timestamp, delete leading rows with all NA.  
  pump <- pump[order(pump$timestamp),]
  if (rowSums(is.na(pump))[1]==8) {
    pump <- pump[-c(1:(as.numeric(which(rowSums(is.na(pump)) < 8)[1]))-1),]
  }
# Combine BG columns
  pump$bgreading <- pmax(pump$bginput,pump$bgreading,na.rm = T)
  for (r in 1:nrow(pump)) {
    bg <- pump$bgreading[r]
    time <- pump$timestamp[r]
    time15 <- time:(time+900) 
    rows15 <- which(pump$timestamp %in% time15)
    if (length(which(pump$bgreading[rows15]==bg)) > 1) {
      pump$bgreading[rows15[which(pump$bgreading[rows15]==bg)[-1]]] <- NA
    }
  }
# Classify BGs using Bergensthal White Paper Categories and Pump It Up! 
# categories.
  pump$piu <- cut(as.numeric(pump$bgreading),
                       breaks = c(1,70,150,250,Inf),
                       right = F,
                       labels = c("<70","70-149","150-249","250+"))
  pump$bwp <- cut(as.numeric(pump$bgreading),
                       breaks = c(1,70,181,251,400,Inf),
                       right = F,
                       labels = c("<70","70-180","181-250","251-400","400+"))
# Write to folder.
  filename <- paste(outdir,id,".csv",sep = "")
  write.csv(pump,file = filename,row.names = F,na="")
}
```

```{r echo=FALSE,include=FALSE}
# Summary variables.
# Import data
indir <- "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Kim Driscoll/Baseline Pump Paper/Data_Cleaned/Pump Files Cleaned/"
outdir <- "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Kim Driscoll/Baseline Pump Paper/Data_Cleaned/"
files <- list.files(indir,full.names = T)
# Make a summary variables table.
summary <- data.frame(matrix(nrow = length(files),ncol = 0))
# Iterate through files and calculate variables.
for (f in 1:length(files)) {
  dat <- read.csv(files[f],header = T,stringsAsFactors = FALSE,na.strings = "")
  dat$timestamp <- lubridate::ymd_hms(dat$timestamp)
  id <- sub(".csv","",basename(files[f]))
  summary[f,"subject_id"] <- id
# Calculate number of days of data  
  days <- as.numeric(difftime(max(dat$timestamp),min(dat$timestamp),
                              units = "days"))
  summary[f,"days_worn"] <- days
# Combine rows, remove rows with all NA.
  dat$timestamp <- strftime(dat$timestamp,"%Y-%m-%d %H:%M", tz = "UTC")
  dat <- aggregate(dat[,2:ncol(dat)],list(dat[,1]),
                   function(x) ifelse(length(x[which(!is.na(x))]) > 0,x[which(!is.na(x))],NA))
  dat <- dat[-c(which(rowSums(is.na(dat[,2:ncol(dat)])) >= (length(2:ncol(dat))-1))),]
# Format timestamp
  colnames(dat)[1] <- "timestamp"
  dat$timestamp <- lubridate::ymd_hm(dat$timestamp)
# Get BG readings by PIU and BWP categories  
  reading.times <- dat$timestamp[which(dat$bgreading > 0)]
  pius <- dat$piu[which(!is.na(dat$bgreading))]
  bwps <- dat$bwp[which(!is.na(dat$bgreading))]
# Find date, weekday, hour of the day
  dat$date <- lubridate::date(dat$timestamp)
  dat$weekday <- lubridate::wday(dat$timestamp)
  dat$hour <- lubridate::hour(dat$timestamp)
# Average number of BG checks and carb inputs on weekdays and weekends
  weekdat <- dat[dat$weekday %in% 2:6,]
  weekdays <- length(unique(weekdat$date))
# On weekends
  weekend <- dat[dat$weekday %in% c(1,7),]
  weekends <- length(unique(weekend$date))
  # Carb inputs and BG readings
  dat$piu[which(dat$bgreading == 0)] <- NA
  dat$bwp[which(dat$bgreading == 0)] <- NA
  carbs <- length(which(dat$carbinput > 0))
  summary[f,"total_piu<70"] <- length(which(dat$piu == "<70"))
  summary[f,"total_piu_70-149"] <- length(which(dat$piu == "70-149"))
  summary[f,"total_piu_150-249"] <- length(which(dat$piu == "150-249"))
  summary[f,"total_piu_250+"] <- length(which(dat$piu == "250+"))
  summary[f,"total_bwp<70"] <- length(which(dat$bwp == "<70"))
  summary[f,"total_bwp_70-180"] <- length(which(dat$bwp == "70-180"))
  summary[f,"total_bwp_181-250"] <- length(which(dat$bwp == "181-250"))
  summary[f,"total_bwp_251-400"] <- length(which(dat$bwp == "251-400"))
  summary[f,"total_bwp_400+"] <- length(which(dat$bwp == "400+"))
# BG checks
  BGcount <- length(which(dat$bgreading > 0))
  summary[f,"total_readings"] <- BGcount
  summary[f,"readings_per_day"] <- length(which(dat$bgreading > 0))/days
  summary[f,"readings_per_weekday"] <- 
    length(which(weekdat$bgreading > 0)) / weekdays
  summary[f,"readings_per_weekend"] <- 
    length(which(weekend$bgreading > 0)) / weekends
# Carbs
  summary[f,"total_carb_inputs"] <- carbs
  summary[f,"carb_inputs_per_day"] <- carbs/days
  summary[f,"carb_inputs_per_weekday"] <- 
    length(which(weekdat$carbinput > 0)) / weekdays
  summary[f,"carb_inputs_per_weekend"] <- 
    length(which(weekend$carbinput > 0)) / weekends
# Carbs only  
  carbs_dat <- dat[which(dat$carbinput > 0),]
  six_hour_carbs <- setDT(carbs_dat)[, indx := date][, .SD[1:(.N+1)], indx][,indx := NULL][!.N]
  six_hour_carbs$hour[which(is.na(six_hour_carbs$hour))] <- 24
# Days with >= 3 carbs
  carbs_days <- six_hour_carbs
  carbs_days$carbs_binary <- ifelse(!is.na(carbs_days$carbinput),1,0)
  carbs_days <- carbs_days %>%
    filter(!is.na(date)) %>%
    group_by(date) %>%
    summarise(num_carbs = sum(carbs_binary,na.rm = T))
  summary[f,"perc_days_>=3_carbs"] <- 
    (length(which(carbs_days$num_carbs >=4))/ceiling(days))*100
# Boluses only  
  bolus_dat <- dat[which(!is.na(dat$bolusvoldelivered)),]
  bolus_dat$carbinput[which(is.na(bolus_dat$carbinput))] <- 0
# Check for days with >= 6 hours without a bolus.
# Add a midnight row to calculate last bolus before midnight
  six_hour_bolus <- data.table::setDT(bolus_dat)[, indx := date][, .SD[1:(.N+1)], indx][,indx := NULL][!.N]
  six_hour_bolus$hour[which(is.na(six_hour_bolus$hour))] <- 24
# Days with >= 3 boluses
  bolus_days <- six_hour_bolus
  bolus_days$bolus_binary <- ifelse(!is.na(bolus_days$bolusvoldelivered),1,0)
  bolus_days <- bolus_days %>%
    filter(!is.na(date)) %>%
    group_by(date) %>%
    summarise(num_boluses = sum(bolus_binary,na.rm = T))
# Count time between 6am, boluses, and midnight by date  
  six_hour_bolus <- six_hour_bolus %>% 
    fill(date) %>%
    group_by(date) %>%
    filter(hour %in% 6:24) %>%
    mutate(time_diff = hour - lag(hour, default = 6))
# Summarize
  six_hour_bolus <- six_hour_bolus %>% group_by(date) %>% 
    summarise(n = sum(time_diff > 6)) %>% as.data.frame()
# Counting variables and placeholder
  total.bolus <- 1
  if (bolus_dat$weekday[1] %in% 2:6) {
    weekday.total.bolus <- 1
    weekend.total.bolus <- 0
  } else {
      weekday.total.bolus <- 0
      weekend.total.bolus <- 1
      }
  bolus.times <- bolus_dat$timestamp[1]
  pius.within.15 <- character()
  pius.within.30 <- character()
  bwps.within.15 <- character()
  bwps.within.30 <- character()
# Iterate through data rows. Count total boluses
  for (r in 2:nrow(bolus_dat)) {
    bolus.time <- bolus_dat$timestamp[r]
    prev.bolus.time <- bolus_dat$timestamp[r-1]
    time.diff <- as.numeric(difftime(bolus.time,prev.bolus.time,units = "mins"))
    time.range.15 <- (bolus.time - 900):(bolus.time-1)
    time.range.20 <- (bolus.time - 1200):(bolus.time-1)
    time.range.30 <- (bolus.time - 1800):(bolus.time-1)
    if (time.diff > 20) {
      total.bolus <- total.bolus + 1
      bolus.times <- c(bolus.times,bolus.time)
      if (bolus_dat$weekday[r] %in% 2:6) {
        weekday.total.bolus <- weekday.total.bolus + 1
      } else {
        weekend.total.bolus <- weekend.total.bolus + 1
      }
    } else if (bolus_dat$carbinput[r] > 0 & bolus_dat$carbinput[r-1] > 0) {
      total.bolus <- total.bolus + 1
      bolus.times <- c(bolus.times,bolus.time)
      if (bolus_dat$weekday[r] %in% 2:6) {
        weekday.total.bolus <- weekday.total.bolus + 1
      } else {
        weekend.total.bolus <- weekend.total.bolus + 1
      }
    } else {
      double.bolus <- 1
    }
  }
  summary[f,"total_bolus"] <- total.bolus
  summary[f,"boluses_per_day"] <- total.bolus/days
  summary[f,"boluses_per_weekday"] <- weekday.total.bolus/weekdays
  summary[f,"boluses_per_weekend"] <- weekend.total.bolus/weekends
  summary[f,"perc_days_>=3_boluses"] <- 
    (length(which(bolus_days$num_boluses >=3))/ceiling(days))*100
# Iterate through boluses and check reading information
  for (t in bolus.times) {
    time.range.15 <- (t - 900):t
    time.range.30 <- (t - 1800):t
    piu15 <- pius[which(reading.times %in% time.range.15)]
    piu30 <- pius[which(reading.times %in% time.range.30)]
    bwp15 <- bwps[which(reading.times %in% time.range.15)]
    bwp30 <- bwps[which(reading.times %in% time.range.30)]
    if (length(piu15) > 0) {
      pius.within.15 <- c(pius.within.15,piu15)
      bwps.within.15 <- c(bwps.within.15,bwp15)
    } 
    if (length(piu30) > 0) {
      pius.within.30 <- c(pius.within.30,piu30)
      bwps.within.30 <- c(bwps.within.30,bwp30)
    }
  }
  summary[f,"bolus_within_15_piu<70"] <- length(which(pius.within.15 == "<70"))
  summary[f,"bolus_within_15_piu_70-149"] <- length(which(pius.within.15 == "70-149"))
  summary[f,"bolus_within_15_piu_150-249"] <- length(which(pius.within.15 == "150-249"))
  summary[f,"bolus_within_15_piu_250+"] <- length(which(pius.within.15 == "250+"))
  summary[f,"bolus_within_15_bwp<70"] <- length(which(bwps.within.15 == "<70"))
  summary[f,"bolus_within_15_bwp_70-180"] <- length(which(bwps.within.15 == "70-180"))
  summary[f,"bolus_within_15_bwp_181-250"] <- length(which(bwps.within.15 == "181-250"))
  summary[f,"bolus_within_15_bwp_251-400"] <- length(which(bwps.within.15 == "251-400"))
  summary[f,"bolus_within_15_bwp_400+"] <- length(which(bwps.within.15 == "400+"))
  
  summary[f,"bolus_within_30_piu<70"] <- length(which(pius.within.30 == "<70"))
  summary[f,"bolus_within_30_piu_70-149"] <- length(which(pius.within.30 == "70-149"))
  summary[f,"bolus_within_30_piu_150-249"] <- length(which(pius.within.30 == "150-249"))
  summary[f,"bolus_within_30_piu_250+"] <- length(which(pius.within.30 == "250+"))
  summary[f,"bolus_within_30_bwp<70"] <- length(which(bwps.within.30 == "<70"))
  summary[f,"bolus_within_30_bwp_70-180"] <- length(which(bwps.within.30 == "70-180"))
  summary[f,"bolus_within_30_bwp_181-250"] <- length(which(bwps.within.30 == "181-250"))
  summary[f,"bolus_within_30_bwp_251-400"] <- length(which(bwps.within.30 == "251-400"))
  summary[f,"bolus_within_30_bwp_400+"] <- length(which(bwps.within.30 == "400+"))
  
  summary[f,"days_bolus>=6_hours"] <- sum(six_hour_bolus$n > 0)
# Bolus wizard
  bolus_dat$wizard_diff <- bolus_dat$bolusvoldelivered - bolus_dat$bwzestimate
  bolus_dat$wizard_diff <- ifelse(bolus_dat$wizard_diff < 0,"lower",
                                  ifelse(bolus_dat$wizard_diff > 0,"higher","equal"))
  wizard <- bolus_dat %>%
    filter(!is.na(wizard_diff)) %>%
    ungroup() %>%
    count(wizard_diff) %>%
    mutate(percentage = (n/sum(n))*100)
  summary[f,"perc_bolus_equal_bwz"] <- wizard$percentage[1]
  summary[f,"perc_bolus_higher_bwz"] <- wizard$percentage[2]
  summary[f,"perc_bolus_lower_bwz"] <- wizard$percentage[3]
# BG as the anchor.
# BGs only  
  BG_dat <- dat[which(dat$bgreading > 0),]
# Check for days with >= 6 hours without a BG.
# Add a midnight row to calculate last BG before midnight
  six_hour_BG <- setDT(BG_dat)[, indx := date][, .SD[1:(.N+1)], indx][,indx := NULL][!.N]
  six_hour_BG$hour[which(is.na(six_hour_BG$hour))] <- 24
# Days with >=4 BG checks
  bg_days <- six_hour_BG
  bg_days$bg_binary <- ifelse(!is.na(bg_days$bgreading),1,0)
  bg_days <- bg_days %>%
    filter(!is.na(date)) %>%
    group_by(date) %>%
    summarise(num_bgs = sum(bg_binary,na.rm = T))
# Count time between 6am, BGs, and midnight by date  
  six_hour_BG <- six_hour_BG %>% 
    fill(date) %>%
    group_by(date) %>%
    filter(hour %in% 6:24) %>%
    mutate(time_diff = hour - lag(hour, default = 6))
# Summarize
  six_hour_BG <- six_hour_BG %>% group_by(date) %>% 
    summarise(n = sum(time_diff >= 6)) %>% as.data.frame()
  summary[f,"days_reading>=6_hours"] <- sum(six_hour_BG$n > 0)
  summary[f,"perc_days_>=4_bgs"] <- 
    (length(which(bg_days$num_bgs >=4))/ceiling(days))*100
# Total BGs in ranges BWP
  lowBGcount <- length(which(dat$bgreading < 70))
  intargetBGcount <- length(which(dat$bgreading %in% 70:180))
  highBGcount <- length(which(dat$bgreading %in% 181:250))
  veryhighBGcount <- length(which(dat$bgreading %in% 251:400))
  extremeBGcount <- length(which(dat$bgreading > 400))
# BG count variables BWP
  lowBG_followed_by_bolus <- 0
  lowBG_followed_by_carb_bolus <- 0
  intargetBG_followed_by_bolus <- 0
  intargetBG_followed_by_carb_bolus <- 0
  highBG_followed_by_bolus <- 0
  highBG_followed_by_carb_bolus <- 0
  veryhighBG_followed_by_bolus <- 0
  veryhighBG_followed_by_carb_bolus <- 0
  extremeBG_followed_by_bolus <- 0
  extremeBG_followed_by_carb_bolus <- 0
  carbtimes <- dat$timestamp[which(dat$carbinput > 0)]
  lowBG_with_carb <- 0
  lowBG_with_carb_bolus <- 0
  intargetBG_with_carb <- 0
  intargetBG_with_carb_bolus <- 0
  highBG_with_carb <- 0
  highBG_with_carb_bolus <- 0
  veryhighBG_with_carb <- 0 
  veryhighBG_with_carb_bolus <- 0
  extremeBG_with_carb <- 0
  extremeBG_with_carb_bolus <- 0
# Total BGs in ranges PIU
  lowBGcount_piu <- length(which(dat$bgreading < 70))
  intargetBGcount_piu <- length(which(dat$bgreading %in% 70:149))
  highBGcount_piu <- length(which(dat$bgreading %in% 150:249))
  extremeBGcount_piu <- length(which(dat$bgreading >= 250))
# BG count variables PIU
  lowBG_followed_by_bolus_piu <- 0
  lowBG_followed_by_carb_bolus_piu <- 0
  intargetBG_followed_by_bolus_piu <- 0
  intargetBG_followed_by_carb_bolus_piu <- 0
  highBG_followed_by_bolus_piu <- 0
  highBG_followed_by_carb_bolus_piu <- 0
  extremeBG_followed_by_bolus_piu <- 0
  extremeBG_followed_by_carb_bolus_piu <- 0
  lowBG_with_carb_piu <- 0
  lowBG_with_carb_bolus_piu <- 0
  intargetBG_with_carb_piu <- 0
  intargetBG_with_carb_bolus_piu <- 0
  highBG_with_carb_piu <- 0
  highBG_with_carb_bolus_piu <- 0
  extremeBG_with_carb_piu <- 0
  extremeBG_with_carb_bolus_piu <- 0
# Iterate through each BG reading
  bgreadings <- which(dat$bgreading > 0)
  for (r in bgreadings) {
    bg <- dat$bgreading[r]
    time.range.15 <- (dat$timestamp[r]:(dat$timestamp[r]+900))
# BWP    
    if ((TRUE %in% (bolus.times %in% time.range.15)) & 
        (TRUE %in% (carbtimes %in% time.range.15))) {
      if (bg < 70) {lowBG_followed_by_carb_bolus <- lowBG_followed_by_carb_bolus + 1}
      else if (bg %in% 70:180) {intargetBG_followed_by_carb_bolus <- intargetBG_followed_by_carb_bolus + 1}
      else if (bg %in% 181:250) {highBG_followed_by_carb_bolus <- highBG_followed_by_carb_bolus + 1}
      else if (bg %in% 251:400) {veryhighBG_followed_by_carb_bolus <- veryhighBG_followed_by_carb_bolus + 1}
      else if (bg > 400) {extremeBG_followed_by_carb_bolus <- extremeBG_followed_by_carb_bolus + 1}
    } else if (TRUE %in% (bolus.times %in% time.range.15)){
      if (bg < 70) {lowBG_followed_by_bolus <- lowBG_followed_by_bolus + 1}
      else if (bg %in% 70:180) {intargetBG_followed_by_bolus <- intargetBG_followed_by_bolus + 1}
      else if (bg %in% 181:250) {highBG_followed_by_bolus <- highBG_followed_by_bolus + 1}
      else if (bg %in% 251:400) {veryhighBG_followed_by_bolus <- veryhighBG_followed_by_bolus + 1}
      else if (bg > 400) {extremeBG_followed_by_bolus <- extremeBG_followed_by_bolus + 1}
    }
    if (TRUE %in% (carbtimes %in% time.range.15)) {
      if (bg < 70) {lowBG_with_carb <- lowBG_with_carb + 1}
      if (bg < 70 & (TRUE %in% (bolus.times %in% time.range.15))) {lowBG_with_carb_bolus <- lowBG_with_carb_bolus + 1}
      if (bg %in% 70:180) {intargetBG_with_carb <- intargetBG_with_carb + 1}
      if (bg %in% 70:180 & (TRUE %in% (bolus.times %in% time.range.15))) {
        intargetBG_with_carb_bolus <- intargetBG_with_carb_bolus + 1}
      if (bg %in% 181:250) {highBG_with_carb <- highBG_with_carb + 1}
      if (bg %in% 181:250 & TRUE %in% (bolus.times %in% time.range.15)) {highBG_with_carb_bolus <- highBG_with_carb_bolus + 1}
      if (bg %in% 251:400) {veryhighBG_with_carb <- veryhighBG_with_carb + 1}
      if (bg %in% 251:400 & (TRUE %in% (bolus.times %in% time.range.15))) {
        veryhighBG_with_carb_bolus <- veryhighBG_with_carb_bolus + 1}
      if (bg > 400) {extremeBG_with_carb <- extremeBG_with_carb + 1}
      if (bg > 400 & (TRUE %in% (bolus.times %in% time.range.15))) {extremeBG_with_carb_bolus <- extremeBG_with_carb_bolus + 1}
    }
# PIU    
    if ((TRUE %in% (bolus.times %in% time.range.15)) & 
        (TRUE %in% (carbtimes %in% time.range.15))) {
      if (bg < 70) {lowBG_followed_by_carb_bolus_piu <- lowBG_followed_by_carb_bolus_piu + 1}
      else if (bg %in% 70:149) {intargetBG_followed_by_carb_bolus_piu <- intargetBG_followed_by_carb_bolus_piu + 1}
      else if (bg %in% 150:249) {highBG_followed_by_carb_bolus_piu <- highBG_followed_by_carb_bolus_piu + 1}
      else if (bg >=250) {extremeBG_followed_by_carb_bolus_piu <- extremeBG_followed_by_carb_bolus_piu + 1}
    } else if (TRUE %in% (bolus.times %in% time.range.15)){
      if (bg < 70) {lowBG_followed_by_bolus_piu <- lowBG_followed_by_bolus_piu + 1}
      else if (bg %in% 70:149) {intargetBG_followed_by_bolus_piu <- intargetBG_followed_by_bolus_piu + 1}
      else if (bg %in% 150:249) {highBG_followed_by_bolus_piu <- highBG_followed_by_bolus_piu + 1}
      else if (bg >=250) {extremeBG_followed_by_bolus_piu <- extremeBG_followed_by_bolus_piu + 1}
    }
    if (TRUE %in% (carbtimes %in% time.range.15)) {
      if (bg < 70) {lowBG_with_carb_piu <- lowBG_with_carb_piu + 1}
      if (bg < 70 & (TRUE %in% (bolus.times %in% time.range.15))) {lowBG_with_carb_bolus_piu <- lowBG_with_carb_bolus_piu + 1}
      if (bg %in% 70:149) {intargetBG_with_carb_piu <- intargetBG_with_carb_piu + 1}
      if (bg %in% 70:149 & (TRUE %in% (bolus.times %in% time.range.15))) {
        intargetBG_with_carb_bolus_piu <- intargetBG_with_carb_bolus_piu + 1}
      if (bg %in% 150:249) {highBG_with_carb_piu <- highBG_with_carb_piu + 1}
      if (bg %in% 150:249 & TRUE %in% (bolus.times %in% time.range.15)) {highBG_with_carb_bolus_piu <- highBG_with_carb_bolus_piu + 1}
      if (bg >=250) {extremeBG_with_carb_piu <- extremeBG_with_carb_piu + 1}
      if (bg >=250 & (TRUE %in% (bolus.times %in% time.range.15))) {extremeBG_with_carb_bolus_piu <- extremeBG_with_carb_bolus_piu + 1}
    }
  }
# As percentages in summary table
# BWP
  summary[f,"perc_lowBG_followed_by_carb_bolus"] <- 
    (lowBG_followed_by_carb_bolus/lowBGcount)*100
  summary[f,"perc_lowBG_followed_by_bolus"] <- 
    ((lowBG_followed_by_carb_bolus + lowBG_followed_by_bolus)/lowBGcount)*100
  
  summary[f,"perc_intargetBG_followed_by_carb_bolus"] <- 
    (intargetBG_followed_by_carb_bolus/intargetBGcount)*100
  summary[f,"perc_intargetBG_followed_by_bolus"] <- 
    ((intargetBG_followed_by_carb_bolus + intargetBG_followed_by_bolus)/intargetBGcount)*100
  
  summary[f,"perc_highBG_followed_by_carb_bolus"] <- 
    (highBG_followed_by_carb_bolus/highBGcount)*100
  summary[f,"perc_highBG_followed_by_bolus"] <- 
    ((highBG_followed_by_carb_bolus + highBG_followed_by_bolus)/highBGcount)*100
  
  summary[f,"perc_veryhighBG_followed_by_carb_bolus"] <- 
    (veryhighBG_followed_by_carb_bolus/veryhighBGcount)*100
  summary[f,"perc_veryhighBG_followed_by_bolus"] <- 
    ((veryhighBG_followed_by_carb_bolus + veryhighBG_followed_by_bolus)/veryhighBGcount)*100
  
  summary[f,"perc_extremeBG_followed_by_carb_bolus"] <- 
    (extremeBG_followed_by_carb_bolus/extremeBGcount)*100
  summary[f,"perc_extremeBG_followed_by_bolus"] <- 
    ((extremeBG_followed_by_carb_bolus + extremeBG_followed_by_bolus)/extremeBGcount)*100
  
  summary[f,"lowBG_without_carb_with_bolus"] <- (lowBG_followed_by_bolus/(lowBGcount-lowBG_with_carb))*100
  summary[f,"lowBG_with_carb_and_bolus"] <- (lowBG_with_carb_bolus/lowBG_with_carb)*100
  
  summary[f,"intargetBG_without_carb_with_bolus"] <- (intargetBG_followed_by_bolus/(intargetBGcount-intargetBG_with_carb))*100
  summary[f,"intargetBG_with_carb_and_bolus"] <- (intargetBG_with_carb_bolus/intargetBG_with_carb)*100
  
  summary[f,"highBG_without_carb_with_bolus"] <- (highBG_followed_by_bolus/(highBGcount-highBG_with_carb))*100
  summary[f,"highBG_with_carb_and_bolus"] <- (highBG_with_carb_bolus/highBG_with_carb)*100
  
  summary[f,"veryhighBG_without_carb_with_bolus"] <- (veryhighBG_followed_by_bolus/(veryhighBGcount-veryhighBG_with_carb))*100
  summary[f,"veryhighBG_with_carb_and_bolus"] <- (veryhighBG_with_carb_bolus/veryhighBG_with_carb)*100
  
  summary[f,"extremeBG_without_carb_with_bolus"] <- (extremeBG_followed_by_bolus/(extremeBGcount-extremeBG_with_carb))*100
  summary[f,"extremeBG_with_carb_and_bolus"] <- (extremeBG_with_carb_bolus/extremeBG_with_carb)*100
# PIU
  summary[f,"perc_lowBG_followed_by_carb_bolus_piu"] <- 
    (lowBG_followed_by_carb_bolus_piu/lowBGcount_piu)*100
  summary[f,"perc_lowBG_followed_by_bolus_piu"] <- 
    ((lowBG_followed_by_carb_bolus_piu + lowBG_followed_by_bolus_piu)/lowBGcount_piu)*100
  
  summary[f,"perc_intargetBG_followed_by_carb_bolus_piu"] <- 
    (intargetBG_followed_by_carb_bolus_piu/intargetBGcount_piu)*100
  summary[f,"perc_intargetBG_followed_by_bolus_piu"] <- 
    ((intargetBG_followed_by_carb_bolus_piu + intargetBG_followed_by_bolus_piu)/intargetBGcount_piu)*100
  
  summary[f,"perc_highBG_followed_by_carb_bolus_piu"] <- 
    (highBG_followed_by_carb_bolus_piu/highBGcount_piu)*100
  summary[f,"perc_highBG_followed_by_bolus_piu"] <- 
    ((highBG_followed_by_carb_bolus_piu + highBG_followed_by_bolus_piu)/highBGcount_piu)*100
  
  summary[f,"perc_extremeBG_followed_by_carb_bolus_piu"] <- 
    (extremeBG_followed_by_carb_bolus_piu/extremeBGcount_piu)*100
  summary[f,"perc_extremeBG_followed_by_bolus_piu"] <- 
    ((extremeBG_followed_by_carb_bolus_piu + extremeBG_followed_by_bolus_piu)/extremeBGcount_piu)*100
  
  summary[f,"lowBG_without_carb_with_bolus_piu"] <- (lowBG_followed_by_bolus_piu/(lowBGcount_piu-lowBG_with_carb_piu))*100
  summary[f,"lowBG_with_carb_and_bolus_piu"] <- (lowBG_with_carb_bolus_piu/lowBG_with_carb_piu)*100
  
  summary[f,"intargetBG_without_carb_with_bolus_piu"] <- (intargetBG_followed_by_bolus_piu/(intargetBGcount_piu-intargetBG_with_carb_piu))*100
  summary[f,"intargetBG_with_carb_and_bolus_piu"] <- (intargetBG_with_carb_bolus_piu/intargetBG_with_carb_piu)*100
  
  summary[f,"highBG_without_carb_with_bolus_piu"] <- (highBG_followed_by_bolus_piu/(highBGcount_piu-highBG_with_carb_piu))*100
  summary[f,"highBG_with_carb_and_bolus_piu"] <- (highBG_with_carb_bolus_piu/highBG_with_carb_piu)*100
  
  summary[f,"extremeBG_without_carb_with_bolus_piu"] <- (extremeBG_followed_by_bolus_piu/(extremeBGcount_piu-extremeBG_with_carb_piu))*100
  summary[f,"extremeBG_with_carb_and_bolus_piu"] <- (extremeBG_with_carb_bolus_piu/extremeBG_with_carb_piu)*100

# Rebound BGs. Same as above for low BGs, but 24 hour range. Check how many 
# >300 BGs occur within 24 hour ranges.
  lowBGs <- unique(unlist(lapply((as.list(dat$timestamp[which(dat$bgreading < 70)])),function(x) x:(x+14400))))
  reboundBGs <- dat$timestamp[which(dat$bgreading > 300)]
  summary[f,"num_rebound_bgs"] <- sum(reboundBGs %in% lowBGs)
}
# Output
filename <- paste0(outdir,"summary.csv")
write.csv(summary,file = filename,row.names = F,na = "")
filename <- paste0(outdir,"rounded_summary.csv")
summary[,-1] <- round(summary[,-1],2)
write.csv(summary,file = filename,row.names = F,na = "")
```