---
title: "T1D MEGA Preliminary Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/peds/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Kimber Simmons/GWAS/Data_Cleaned/association")
library(qqman) 
```

```{bash echo=FALSE,eval=FALSE}
# Directory
cd /Volumes/peds/RI\ Biostatistics\ Core/Shared/Shared\ Projects/Laura/BDC/Projects/Kimber\ Simmons/GWAS/Data_Cleaned/association
# Association
plink --bfile final_merge --assoc --out assoc_results --memory 6144
plink --bfile final_merge --covar covar_mds.txt --logistic --out logistic_results --memory 6144
plink --bfile final_merge --assoc --adjust --out adjusted_assoc_results
```

# Logistic

```{r echo=FALSE,warning=FALSE}
# Import SNPs of interest
snps <- read.table("t1d_snps.txt",header = T)
# Import logistic results
results_log <- read.table("logistic_results.assoc.logistic",header = T)
# Remove rows without p values or p = 0
results_log <- results_log[!is.na(results_log$P) & results_log$P > 0,]
# Plots
manhattan(results_log,chr="CHR",bp="BP",p="P",snp="SNP", 
          main = "Manhattan plot: logistic",highlight = snps$SNP)
qq(results_log$P)
```

# Association

```{r echo=FALSE,warning=FALSE}
# Import association results
results_as <- read.table("assoc_results.assoc",header = T)
# Remove rows without p values or p = 0
results_as <- results_as[!is.na(results_as$P) & results_as$P > 0,]
# Plots
manhattan(results_as,chr="CHR",bp="BP",p="P",snp="SNP", 
          main = "Manhattan plot: assoc",highlight = snps$SNP)
qq(results_as$P)
```