---
title: "Latino Program - Gerard Gonzalez - effect of tech within LP"
author: "Kristen Campbell/Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
editor_options: 
  chunk_output_type: console
---


```{r,echo=FALSE,message=FALSE,results='hide',warning=FALSE}
library(knitr)
library(dplyr)
library(nlme)
library(emmeans)

#setwd("C:/Users/campbkri/Documents/GitHub/BDC-Code/Gerard Gonzalez/Year4 Code")
setwd("C:/Users/pylell/Documents/GitHub/BDC-Code/Gerard Gonzalez/Year4 Code")
source('01_functions.R')
source('00_data_yr4.R')
#setwd("C:/Users/campbkri/Documents/GitHub/BDC-Code/Gerard Gonzalez/Year4 Code")
setwd("C:/Users/pylell/Documents/GitHub/BDC-Code/Gerard Gonzalez/Year4 Code")
#source('02_tables_yr4.R')
#source('03_mixed_yr4.R')

lp_dat <- dat %>% filter(trt_grp=="LP")
lp_dat$any_tech <- ifelse(lp_dat$technology_type_inyear=="No CGM or Pump",0,1)

# comparing all tech groups
mod <- lme(a1c_last_in_year~baseline_a1c+factor(yeargrouping)+group+technology_type_inyear+
                       duration_of_diagnosis,random=~1|MRN,data=lp_dat)
mod.anova <- anova.lme(mod, type="marginal")
modmeans <- emmeans(mod,"technology_type_inyear")
pairs <- pairs(modmeans,adjust="tukey")

# any tech vs. no tech
mod1 <- lme(a1c_last_in_year~baseline_a1c+factor(yeargrouping)+group+any_tech+
                       duration_of_diagnosis,random=~1|MRN,data=lp_dat)
mod1.anova <- anova.lme(mod1, type="marginal")
modmeans1 <- emmeans(mod1,"any_tech")
pairs1 <- pairs(modmeans1,adjust="tukey")

```

# Comparison of 4 tech groups

## ANOVA table

```{r, echo=FALSE, message=FALSE}
kable(mod.anova,format.args = list(scientific = FALSE))
```

## Estimated means

```{r, echo=FALSE, message=FALSE}
kable(modmeans,format.args = list(scientific = FALSE))
```

## Pairwise comparison of means

```{r, echo=FALSE, message=FALSE}
kable(pairs,format.args = list(scientific = FALSE))
```

# Comparison of any tech use (1) vs. none (0)

## ANOVA table

```{r, echo=FALSE, message=FALSE}
kable(mod1.anova,format.args = list(scientific = FALSE))
```

## Estimated means

```{r, echo=FALSE, message=FALSE}
kable(modmeans1,format.args = list(scientific = FALSE))
```

## Pairwise comparison of means

```{r, echo=FALSE, message=FALSE}
kable(pairs1,format.args = list(scientific = FALSE))
```
