---
title: "Suicide Risk Assessment"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Shideh Majidi/Depression")
source("/Users/timvigers/Documents/GitHub/BDC-Code/Shideh Majidi/Depression/sra.r")
source("/Users/timvigers/Documents/GitHub/Tim-and-Laura/tim_r_functions.R")
library(arsenal)
library(VGAM)
library(nlme)
library(splines)
library(skimr)
library(knitr)
library(reshape2)
library(tidyverse)
```

```{r a1c data import,echo=FALSE}
a1cs <- read.csv("/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Shideh Majidi/Depression/Data_Cleaned/a1cs.csv")
a1cs$A1cResultDate <- lubridate::mdy(a1cs$A1cResultDate)
temp <- data
temp$record_id <- as.numeric(as.character(temp$record_id))
# Add screen date to A1c data, find days between
a1cs <- left_join(a1cs,temp[,c("record_id","screen_date","charttreatafter")],
                  by = "record_id")
a1cs$days_from_screen <- 
  round(as.numeric(difftime(a1cs$A1cResultDate,a1cs$screen_date,units = "days")))
# 1 year pre-/post-screening
a1cs <- a1cs[abs(a1cs$days_from_screen) < 365.25,]
# Clean up
rm(temp)
```

# Table 1: Descriptive Characteristics

```{r table 1,echo=FALSE,results='asis'}
t1 <- tableby(charttreatafter.factor ~ age + diabetes_duration + a1c + total_score_epic +
                followupscore + 
                sex.factor + race.factor + ethnicity.factor + insurance.factor + 
                pump_use.factor + cgm.factor + si_pos.factor + followupphq9.factor + 
                followupsi,data)
newlabels <- list(sex.factor = "Sex",race.factor = "Race",
                  ethnicity.factor = "Ethnicity",insurance.factor = "Insurance",
                  insulin_type.factor = "Insulin Type",pump_use.factor = "Pump Use", 
                  cgm.factor = "CGM Use",followupphq9.factor = "Follow-Up PHQ 9?",
                  followupsi = "Follow-Up SI?")
summary(t1,pfootnote = T,labelTranslations = newlabels)
```

## Plot All A1cs by Days From Screening

```{r echo=FALSE,warning=FALSE,message=FALSE}
ggplot(a1cs,aes(x = days_from_screen,y = A1cValue)) + theme_bw() +
  geom_point() +
  geom_smooth(aes(color = charttreatafter)) + 
  geom_point(data = a1cs[which(a1cs$A1cValue == 14.1),],color = "red")
```

About `r round(length(which(a1cs$A1cValue == 15))/length(a1cs$A1cValue),3)*100`% of the values are 15% and another `r round(length(which(a1cs$A1cValue == 14.1))/length(a1cs$A1cValue),3)*100`% of the values are 14.1% (in red above).

## First, Screening, and Last A1cs

```{r echo=FALSE,warning=FALSE,message=FALSE,include=FALSE}
random <- a1cs %>% group_by(record_id) %>% 
  slice(which.min(days_from_screen),which(days_from_screen == 0), 
        which.max(days_from_screen))
ggplot(random,aes(x = days_from_screen,y = A1cValue)) + 
  theme_bw() +
  geom_line(aes(group = record_id,color = factor(charttreatafter)))
```

## Piecewise Regression

```{r}
# Correlation structure
mod <- lme(A1cValue ~ days_from_screen,random = ~1|record_id,data = a1cs,method = "ML")
mod_ar1 <- lme(A1cValue ~ days_from_screen,random = ~1|record_id,data = a1cs,
               correlation = corAR1(),method = "ML")
# AR(1) is much better, so refit with REML and check polynomials. 
a1c_mod_poly <- lme(A1cValue ~ poly(days_from_screen,4),random = ~1|record_id,
               data = a1cs,correlation = corAR1())
# Can use linear time. Use splines for knot at 0. Random intercept and slope for subject.
a1cs$days_star <- ifelse(a1cs$days_from_screen < 0,0,a1cs$days_from_screen)
a1c_mod_ri <- lme(A1cValue ~ days_from_screen*charttreatafter + days_star*charttreatafter,
               random = ~1|record_id,data = a1cs,correlation = corAR1())
a1c_mod_ris <- lme(A1cValue ~ days_from_screen*charttreatafter + 
                     days_star*charttreatafter,
               random = ~days_from_screen|record_id,data = a1cs,correlation = corAR1())
AIC(a1c_mod_ri,a1c_mod_ris) # RI only better by AIC
# Censored
a1cs$A1cCensored <- a1cs$A1cValue
a1cs$A1cCensored[a1cs$A1cCensored > 14.1] <- 14.1
cens <- vglm(A1cValue ~ days_from_screen*charttreatafter + 
                     days_star*charttreatafter, tobit(Upper = 14.1), 
             data = a1cs)
uncens <- glm(A1cValue ~ days_from_screen*charttreatafter + 
                     days_star*charttreatafter,data = a1cs)
```

```{r echo=FALSE,include=FALSE}
# Plot splines
plot_piecewise_single_knot(a1cs,a1c_mod_ri,xknot = 0,
                           xvar = "days_from_screen",
                           yvar = "A1cValue", group = "factor(charttreatafter)") + 
  xlab("Days from Start") + ylab("HbA1c (%)")
# Spline results
format_nlme_out(a1c_mod_ri,round = F)
```

### Censored

```{r echo=FALSE}
summary(cens)
```

### Uncensored

```{r echo=FALSE}
summary(uncens)
```
