---
title: "CIQ 3D Agreement"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(ggpubr)
library(plotly)
library(patchwork)
library(knitr)
library(rgl)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects/Cari Berget/Control IQ 12 Month MS"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Cari Berget/Control IQ 12 Month MS"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Cari Berget/Control IQ 12 Month MS"
}
knitr::opts_knit$set(root.dir = home_dir)
knitr::opts_chunk$set(echo = FALSE,message = FALSE)
setupKnitr(autoprint = TRUE)
```

```{r data,include=FALSE}
# Import
source("~/GitHub/BDC-Code/Cari Berget/Control IQ 12 month analysis/import_peds_data.r")
source("~/GitHub/BDC-Code/Cari Berget/Control IQ 12 month analysis/import_parent_data.r")
# Survey scoring function
source("~/GitHub/BDC-Code/Surveys/scoring_function.R")
# Format date columns
date_cols = c("date","date_visit","demographics_diabetesdx","demographics_dob")
data[,date_cols] = lapply(data[,date_cols],lubridate::mdy)
# Fill down by participant, baseline HbA1c group
data = data %>% group_by(record_id) %>% 
  fill(demographics_diabetesdx,demographics_dob,demographics_sex.factor,demographics_age)
# Calculate variables
data = data %>% filter(!is.na(gyl_timepoint.factor),record_id >= 119,
                       !grepl("arm_3",redcap_event_name)) %>%
  mutate(age = as.numeric(difftime(date,demographics_dob,units = "days"))/365.25,
         sensor_over_180 = sensor_181_250 + sensor_g250,
         sensor_under_70 = sensor_54_69 + sensor_u54) %>%
  group_by(record_id) %>%
  mutate(hba1c_group = cut(hba1c[row_number() == 1],c(-Inf,7,9,Inf),
                           labels = c("<7%","7-9%",">=9%"),right = F),
         age_group = cut(demographics_age[row_number() == 1],c(-Inf,14,18,Inf),
                         labels = c("<14","14-17",">=18"),right = F))
# Score surveys
data = peds_scores(data)
parent_data = parent_scores(parent_data)
# Parent surveys to long
parent_data = parent_data %>% select(record_id,p_paid_b:p_tech_b) %>%
  pivot_longer(p_paid_b:p_tech_b,
               names_to = c("survey","gyl_timepoint.factor"),
               names_pattern = "p_(.*)_(.*)") %>%
  pivot_wider(names_from = "survey",names_prefix = "p_")
parent_data$gyl_timepoint.factor =
  factor(parent_data$gyl_timepoint.factor,
         levels = c("b","m1","t1","t2","t3","t4"),
         labels = c("Baseline","Month 1/ Training F/U","3 Months",
                    "6 Months","9 Months","12 Months"))
# Dicontinuers
discontinuers = unique(data$record_id[data$time_am < 10])
discontinuers = discontinuers[!is.na(discontinuers)]
# Numeric time
data$numeric_time = data$gyl_timepoint.factor
levels(data$numeric_time) = c(0,1,3,6,9,12)
data$numeric_time = as.numeric(as.character(data$numeric_time))
# Select relevant columns, exclude discontinuers
data = data %>% 
  filter(!record_id %in% discontinuers,
         !grepl("arm_3",redcap_event_name)) %>%
  select(record_id,gyl_timepoint.factor,numeric_time,age_group,demographics_age,
         hba1c_group,hba1c,
         demographics_sex.factor,time_am,sensor_wear,tdd,tdd_bolus,tdd_basal,
         dailymealbolus,sleep,exercise,sensor_mean,sensor_70_180,
         sensor_over_180,sensor_g250,sensor_under_70,sensor_u54,
         all_of(peds_surveys))
# Add parent scores
data$record_id = as.character(data$record_id)
parent_data$record_id = as.character(parent_data$record_id)
data = left_join(data,parent_data,by = c("record_id", "gyl_timepoint.factor"))
# Write cleaned CSV
write.csv(data,file = "./Data_Cleaned/ciq_analysis_dataset.csv",row.names = F,na = "")
# Clean workspace
rm(list = ls()[-which(ls() %in% c("data","discontinuers"))])
```

# Table 1: Participant Characteristics at Baseline

A total of `r length(discontinuers)` participants were excluded due to HCL use <10% at 1 or more visits. 

```{r table 1,results='asis'}
t1 = tableby(~age_group + demographics_age +  hba1c_group + hba1c + demographics_sex.factor + 
               sensor_wear + tdd + tdd_bolus + tdd_basal + dailymealbolus + 
               sensor_mean + sensor_70_180,
             data = data[data$gyl_timepoint.factor == "Baseline",])
summary(t1,labelTranslations = 
          list(age_group = "Age Group",hba1c_group = "HbA1c Group",
               demographics_sex.factor = "Sex"))
```

# 3D Regression: TIR, HbA1c, and Mean Sensor Glucose

```{r fig.height=10,fig.width=10}
possible_outliers = c("507","666","670")
pca_data = na.omit(data[,c("sensor_mean","hba1c","sensor_70_180")])
pca = prcomp(pca_data)
plot3d(pca_data,col = "darkblue",size = 2,
       xlab = "Mean Glucose",ylab = "HbA1c",zlab = "TIR")
abclines3d(pca$center,a = pca$rotation[,1],col = "orange")
```

## Pairwise linear models

```{r}
p3d = plot_ly(x = pca_data$sensor_mean,y = pca_data$sensor_70_180,z = pca_data$hba1c,
              type="scatter3d", mode="markers",size = 4,color = I('black'),alpha = 0.5) %>%
  layout(scene = list(xaxis = list(title = 'Sensor Mean'),
                      yaxis = list(title = 'TIR'),zaxis = list(title = 'HbA1c')))

p1 = ggscatter(pca_data, x = "sensor_mean", y = "hba1c", add = "reg.line") +
  stat_cor(
    aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), 
    label.y = 11.5
  ) +
  stat_regline_equation(label.y = 11) +
  xlab("Mean Sensor Glucose") + ylab("HbA1c") + ggtitle("HbA1c vs. Mean Glucose")
p2 = ggscatter(pca_data, x = "sensor_70_180", y = "hba1c", add = "reg.line") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), 
           label.y = 11.5,label.x = 80) +
  stat_regline_equation(label.y = 11,label.x = 80) +
  xlab("TIR") + ylab("HbA1c") + ggtitle("HbA1c vs. TIR")
p3 = ggscatter(pca_data, y = "sensor_70_180", x = "sensor_mean", add = "reg.line") +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),
           label.y = 90,label.x = 250) +
  stat_regline_equation(label.y = 85,label.x = 250) +
  xlab("Mean Sensor Glucose") + ylab("TIR") + ggtitle("Mean Glucose vs. TIR")
# Arrange
(plot_spacer() + p1) / (p2 + p3)
```

```{r}
mod = lm(hba1c ~ sensor_70_180,data = pca_data)
t = summary(mod)$coefficients


seg_df1 = data.frame(x1 = min(pca_data$sensor_70_180), x2 = (7-t[1,1])/t[2,1], y1 = 7, y2 = 7)
seg_df2 = data.frame(x1 = (7-t[1,1])/t[2,1], x2 = (7-t[1,1])/t[2,1], y1 = 5, y2 = 7)
p2 +
  geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), colour = "red",
               data = seg_df1) + 
  geom_segment(aes(x = x1, y = y1, xend = x2, yend = y2), colour = "red",
               data = seg_df2)
```
