---
title: "Medicaid CGM"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nlme)
library(tableone)
library(nortest)
library(knitr)
library(tidyverse)
# Check OS and alter file path accordingly.
if (.Platform$OS.type == "windows") {pathstart <- "//ucdenver.pvt/"} else if (.Platform$OS.type == "unix"){pathstart <- "/Volumes/"}
source('~/Documents/GitHub/Tim-and-Laura/tim_R_functions.R')
```

```{r echo=FALSE}
# Read in demographic data
filename <- paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Sonalee Ravi/Medicaid CGM/Data_Cleaned/Demographics.csv")
demographics <- read.csv(filename)
# Read in CGM data
filename <- paste0(pathstart,"som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Sonalee Ravi/Medicaid CGM/Data_Cleaned/30 day CGM data missing studio.csv")
dat <- read.csv(filename,na.strings = c("","NULL"))
# Format CGM data
dat$EncounterDate <- lubridate::mdy(as.character(dat$EncounterDate))
# Remove rows with no A1c
dat <- dat[which(!is.na(dat$HbA1c)),]
# Replace CGMUse = "No" with NA, fill down "Yes" values (by subject), set NAs back to "No"
# This ensures everything prior to a "Yes" is a "No" and every visit after the first "Yes" is also "Yes"
# Remove CGMUse column (not a good indicator because it's just a field in Epic)
# and Dexcom/Medtronic-specific columns.
dat$CGMUse <- NULL
dat$Dexcom.CGM.Days <- NULL
dat$Medtronic.CGM.Days <- NULL
# Fill pump use up (Use last encounter when adjusting for pump use)
dat <- dat %>%
  arrange(EPICMRN,EncounterDate) %>%
  group_by(EPICMRN) %>%
  mutate(PumpUse = PumpUse[n()])
# Get the first CGM use >0 for each participant. Set this CGMUse == "Yes"
temp <- dat %>% arrange(EPICMRN,EncounterDate) %>% 
  group_by(EPICMRN) %>%
  filter(X30.day.CGM.use > 0) %>%
  filter(row_number() == 1)
temp$CGMUse <- "Yes"
# Merge the yes dataframe back into the full data set. 
dat <- left_join(dat,temp,by = colnames(dat))
# Fill down CGM use == Yes by ID, replace remaining NAs with No
dat <- dat %>% arrange(EPICMRN,EncounterDate) %>%
  group_by(EPICMRN) %>%
  fill(CGMUse)
dat$CGMUse[is.na(dat$CGMUse)] <- "No"
# Make CMG usage a percentage
dat$CGM_Perc <- (dat$X30.day.CGM.use / 30)*100
# Get the last "No" and all "Yes" for each subject
no <- dat[dat$CGMUse == "No",] %>%
  arrange(EPICMRN,EncounterDate) %>%
  group_by(EPICMRN) %>%
  filter(row_number()==n())
yes <- dat[dat$CGMUse == "Yes",] %>%
  arrange(EPICMRN,EncounterDate)
# Filter out those without on/off data (all yes or all no)
no <- no[no$EPICMRN %in% yes$EPICMRN,]
yes <- yes[yes$EPICMRN %in% no$EPICMRN,]
# Bind together, calculate time difference, filter out all but last no and first yes > 75 days.
delta <- rbind(yes,no) %>%
  arrange(EPICMRN,EncounterDate) %>%
  mutate(diff = difftime(EncounterDate,EncounterDate[1],units = "days"))
yes <- delta %>% filter(CGMUse == "Yes",diff > 75) %>%
  group_by(EPICMRN) %>%
  filter(row_number()==1)
no <- no[no$EPICMRN %in% yes$EPICMRN,]
# Bind yes and no
delta <- rbind(yes, no) %>% arrange(EPICMRN,EncounterDate)
```

```{r echo=FALSE}
# Format demographic data
demo_datecols <- c("DOB","DateOfDiabetesDiagnosis","FirstVisitDate") 
demographics[,demo_datecols] <- lapply(demographics[,demo_datecols], lubridate::mdy)
# New variables
demographics$AgeFirstVisit <- as.numeric(round(difftime(demographics$FirstVisitDate,
                                             demographics$DOB,units = "days")/365.25,2))
demographics$DiabetesDuration <- as.numeric(round(difftime(demographics$DateOfDiabetesDiagnosis,
                                             demographics$DOB,units = "days")/365.25,2))
# Remove demographics participants who don't have with and without CGM data
demographicsyn <- demographics[which(demographics$EPICMRN %in% unique(delta$EPICMRN)),]
```

```{r echo=FALSE,include=FALSE}
# Table 1 for cohort of 134
vars <- c("AgeFirstVisit","DiabetesDuration","Gender","Race.Ethnicity")
nonnormal <- norm.check(demographicsyn[,c("AgeFirstVisit","DiabetesDuration")])
t1_last_first <- CreateTableOne(vars,data = demographicsyn)
t1_last_first <- as.data.frame(print(t1_last_first,nonnormal = nonnormal))
```

```{r echo=FALSE,include=FALSE}
delta <- delta %>% 
  unite(cgm_pump,CGMUse,PumpUse,remove = F) %>%
  mutate(cgm_pump = factor(cgm_pump, levels = c("No_No","No_Yes","Yes_No","Yes_Yes","No_NA","Yes_NA")))
# Mixed model testing last no/first yes
# Random intercept
mod_int <- lme(HbA1c ~ cgm_pump,random=~1|EPICMRN,data = delta,na.action = na.omit)
on_off_results <- as.data.frame(summary(mod_int)$tTable)
rownames(on_off_results) <- c("Intercept","cgmNo:pumpYes","cgmYes:pumpNo","cgmYes:pumpYes","cgmNo:pumpNA","cgmYes:pumpNA")
# cgmNo:pumpNo is the reference group
```

```{r echo=FALSE,include=FALSE}
# For each person, average HbA1c on CGM and off, remove those without both
avg_on_off <- dat %>%
  group_by(EPICMRN,CGMUse) %>%
  summarise(mean(HbA1c)) %>%
  group_by(EPICMRN) %>% 
  filter(n() > 1) %>% 
  arrange(EPICMRN,CGMUse)
# Compare
on_off_avg_results <- CreateTableOne("mean(HbA1c)",strata = "CGMUse",data = avg_on_off,
                                     testNonNormal = wilcox.test,argsNonNormal = list(paired = T))
on_off_avg_results <- as.data.frame(print(on_off_avg_results, nonnormal = "mean(HbA1c)"))
p <- wilcox.test(formula = `mean(HbA1c)` ~ CGMUse, data = avg_on_off,paired = T)$p.value
rownames(on_off_avg_results)[2] <- "Mean HbA1c"
on_off_avg_results$p <- as.character(on_off_avg_results$p)
on_off_avg_results$p[2] <- round(p,5)
# Demographics
demographicsoo <- demographics[which(demographics$EPICMRN %in% unique(avg_on_off$EPICMRN)),]
vars <- c("AgeFirstVisit","DiabetesDuration","Gender","Race.Ethnicity")
nonnormal <- norm.check(demographicsoo[,c("AgeFirstVisit","DiabetesDuration")])
t1_on_off <- CreateTableOne(vars,data = demographicsoo)
t1_on_off <- as.data.frame(print(t1_on_off,nonnormal = nonnormal))
```

### Table 1: Descriptive statistics for full cohort with on and off CGM data
```{r echo=FALSE}
kable(t1_on_off)
```

### Table 2: Mean HbA1c on CGM and off CGM
```{r echo=FALSE}
kable(on_off_avg_results[,1:4])
```

### Table 3: Descriptive statistics for full cohort (last off CGM vs. first on CGM)
```{r echo=FALSE}
kable(t1_last_first)
```

### Table 4: Mixed model comparing last HbA1c not on CGM to first HbA1c on CGM, by CGM and pump status
```{r echo=FALSE}
kable(on_off_results, caption = "Fixed Effects")
kable(anova.lme(mod_int), caption = "Type 3 Tests of Fixed Effects")
```

```{r echo=FALSE,include=FALSE}
# Add demographic info to main data
dat <- left_join(dat,demographics,by = "EPICMRN")
dat$DiabetesDuration <- difftime(dat$EncounterDate,dat$DateOfDiabetesDiagnosis,units = "weeks")
dat$EPICMRN <- as.factor(dat$EPICMRN)
# Model A1c continuously vs. CGM percentage, adjusting for pump, age, diabetes duration
mod_adj_int <- lme(HbA1c ~ CGM_Perc + Age_AtEncounterDate + DiabetesDuration + PumpUse,
               random=~1|EPICMRN,data = dat, na.action = na.omit)
mod_adj_int_slp <- lme(HbA1c ~ CGM_Perc + Age_AtEncounterDate + DiabetesDuration + PumpUse,
               random=~1|EPICMRN/CGM_Perc,data = dat, na.action = na.omit)
# Model selection
summary(mod_adj_int)
summary(mod_adj_int_slp) # Best by AIC
```

```{r echo=FALSE}
# Plot
mm_plot <- ggplot(data = dat, aes(x = CGM_Perc, y = HbA1c,group = EPICMRN)) +
  geom_line(size = 0.2, aes(color = EPICMRN)) +
  xlab("CGM % Use") + 
  ylab("HbA1c (%)")
mm_plot
```