---
title: ""
author: "Casey Sakamoto & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: no
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(performance)
library(knitr)
library(table1)
library(tableone)
library(lubridate)
# knitr::opts_chunk$set(echo = FALSE)
# if(Sys.info()["sysname"] == "Windows"){
#   home_dir = "S:/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Erin Cobry/Sleep Disruptors in t1d Adolescents"
# } else if (Sys.info()["sysname"] == "Linux"){
#   home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
# } else if (Sys.info()["sysname"] == "Darwin"){
#   home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
# }
# knitr::opts_knit$set(root.dir = home_dir)
# rm(home_dir)
```

```{r data step, include=FALSE, echo=FALSE}
# upload data
sleep_disruptors = read.csv("S:/Laura/BDC/Projects/Erin Cobry/Sleep Disruptors in t1d Adolescents/Data/SleepDisruptorsInAdo_DATA_2023-01-09_1208.csv")
sleep_disruptors = sleep_disruptors %>%
  mutate(group = case_when(as.numeric(substr(record_id, 3,4)) < 11 ~ "Summer",
                                                                 TRUE ~ "Spring/Fall"))
# for table1 right now we need age, gender, race, a1c and maybe therapy
df = sleep_disruptors %>% select(record_id , redcap_event_name, season, age, parent_gender, race___1:race___8, insulinmethod, currenthcltech, current_cgm_use) %>% filter(redcap_event_name == "enrollment_arm_1")

# new variabls
df = df %>% mutate(group = case_when(as.numeric(substr(record_id, 3,4)) < 11 ~ "Summer",
                                     TRUE ~ "Spring/Fall"),
                   race = case_when(race___1 == 1 ~ "White, Non-Hispanic",
                                    race___2 == 1 ~ "Black/African American",
                                    race___3 == 1 ~ "Hispanic/Latino",
                                    race___4 == 1 ~ "Native Hawaiian/Pacific Islander",
                                    race___5 == 1 ~ "Asian",
                                    race___6 == 1 ~ "American Indian/Alaska Native",
                                    TRUE ~ "Unknown"),
                   gender = case_when(parent_gender == 1 ~ "Male",
                                      parent_gender == 2 ~ "Female",
                                      parent_gender == 3 ~ "Other"),
                   age_cat = case_when(age < 13 ~ "11-12",
                                       age > 12 & age < 18 ~ "13-17"))
# labels
df$insulinmethod = factor(df$insulinmethod, labels = c("Injections", "Insulin Pump"))
df$current_cgm_use = factor(df$current_cgm_use, labels = c("Yes", "No"))
df$currenthcltech = factor(df$currenthcltech, labels = c("Yes", "No"))

# glycemic for t1
df_a1c = sleep_disruptors %>% select(record_id , hba1c, diabetesduration, dxdate, enrollementdate) %>% filter(!is.na(hba1c) | !is.na(diabetesduration))


# t1 df
t1_df = full_join(df, df_a1c) %>% select(record_id, group,age, age_cat,gender, race, insulinmethod, currenthcltech, current_cgm_use, hba1c, diabetesduration)

t1 = CreateTableOne(vars = c("age", "age_cat", "gender", "race", "insulinmethod", "currenthcltech", "current_cgm_use","hba1c", "diabetesduration"), factorVars = c( "age_cat", "gender", "race", "insulinmethod", "currenthcltech", "current_cgm_use"), strata = "group", data = t1_df)

t1 = print(t1)



```

# table 1 (all patients)
```{r table1, echo=FALSE}
kable(t1)
```

# Outstanding data remarks:

Patients to exclude before matching: 17,18,25,28,32,34

```{r, include=FALSE}
# Variables:
# Sleep measures (RedCap wrist actigraphy variable)
# Total sleep
# Sleep latency
# Sleep efficiency
# WASO
# 
# Diabetes measures (RedCap Pump & CGM Glycemic Data OR Injection & BG Meter Glycemic Data Instruments [depending on the insulin method for each patient])
# Time in range (70-180)
# Time hypoglycemic (<70 – combine <54 and 55-69)
# Time hyperglycemic (>180 – combine 181-250 and >250)
# HCL use (for those on HCL, if RedCap value blank do not include)
# Sensor use (for those on sensor, if RedCap value blank do not include)
# group,age, age_cat,gender, race, insulinmethod, currenthcltech, current_cgm_use, hba1c, diabetesduration
```

```{r matching, include = FALSE, echo=FALSE}
# summer group has 3 `11-12` group and 7 `13-17` group
# other group has 4 and 21
# df %>% filter(group == "Summer") %>% select(age_cat) %>% table()
# df %>% filter(group != "Summer") %>% select(age_cat) %>% table()


# sample 3 11-12 and 7 13-17 in the fall spring groups
samplingdf = t1_df %>% filter(group != "Summer") %>% select(record_id, age_cat)

# exclude from matcing: 17,18,28,32,34
samplingdf = samplingdf %>% filter(!(record_id %in% c("1017OW", "1018KN", "1025LH", "1028SE", "1032AH", "1034SA")))
samplingdf_12 = samplingdf %>% filter(age_cat == "11-12") %>% unique.data.frame()
samplingdf_17 = samplingdf %>% filter(age_cat == "13-17") %>% unique.data.frame()

# reproducible
set.seed(512)
control_ids = c(sample(samplingdf_12$record_id, 3, replace = FALSE), sample(samplingdf_17$record_id, 7, replace = FALSE))

# t1_df for matched
t1_df_matched = t1_df %>% filter(group == "Summer" | record_id %in% control_ids) 

t1_df_matched = t1_df_matched %>% group_by(record_id) %>% fill(c(hba1c, diabetesduration), .direction = "downup") %>% ungroup()
t1_df_matched = t1_df_matched %>% unique.data.frame()
t1_m = CreateTableOne(vars = c("age", "age_cat", "gender", "race", "insulinmethod", "currenthcltech", "current_cgm_use","hba1c", "diabetesduration"), factorVars = c( "age_cat", "gender", "race", "insulinmethod", "currenthcltech", "current_cgm_use"), strata = "group", data = t1_df_matched)

t1_m = print(t1_m)

# create analysis dataset for sleep
t1_grps = t1_df_matched %>% select(record_id, group)
sleep_disruptors = left_join(t1_grps, sleep_disruptors)

# sleep measures
sleep_meas = sleep_disruptors %>% select(record_id,group,redcap_event_name,totalsleep_avg, onsetlatency_avg,
                                         sleepefficency_avg, waso_avg, avg_bedtime, getup_avg, timeinbed_avg, awake_avg ) %>%
  mutate(totalsleep_m = hour(hm(totalsleep_avg))*60 + minute(hm(totalsleep_avg)),
         totaltimeinbed_m = hour(hm(timeinbed_avg))*60 + minute(hm(timeinbed_avg)))%>% unique.data.frame()

sleep_meas = sleep_meas %>%  filter(redcap_event_name == "surveys_arm_1") %>% select(group, onsetlatency_avg:totaltimeinbed_m)

sleep_t = print(CreateTableOne(vars = c("onsetlatency_avg", "sleepefficency_avg","waso_avg","totalsleep_m",  "totaltimeinbed_m", "awake_avg"), strata = "group", data = sleep_meas))
#,"avg_bedtime","getup_avg"


# diabetes measures
# Diabetes measures (RedCap Pump & CGM Glycemic Data OR Injection & BG Meter Glycemic Data Instruments [depending on the insulin method for each patient])
# Time in range (70-180)
# Time hypoglycemic (<70 – combine <54 and 55-69)
# Time hyperglycemic (>180 – combine 181-250 and >250)
# HCL use (for those on HCL, if RedCap value blank do not include)
# Sensor use (for those on sensor, if RedCap value blank do not include)
diab_meas = sleep_disruptors %>% filter(redcap_event_name == "surveys_arm_1") %>% select(record_id,group,redcap_event_name, sensor_u54, sensor_55_69, sensor_70_180, sensor_181_250, sensor_g251, sensor_wear, insulinmethod, sensor_mean) %>% select(-redcap_event_name)

diab_meas = diab_meas %>% mutate(sensor_hypo = sensor_u54 + sensor_55_69,
                                 sensor_hyper = sensor_181_250 + sensor_g251)%>% unique.data.frame()

diab_t = print(CreateTableOne(vars = c("sensor_70_180", "sensor_hypo", "sensor_hyper","sensor_mean"), strata = "group", data = diab_meas))
```

# table 1(matched subjects)
```{r table 1 matched, echo=FALSE}
print("control ids used")
kable(control_ids)

kable(t1_m)
```


# Sleep measures (RedCap wrist actigraphy variable)

```{r Sleep Measures}
kable(sleep_t)
```

# diabetes measures

```{r diabetes}
kable(diab_t)
```


