---
title: "Holly's Dissertation"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tableone)
library(skimr)
library(knitr)
library(tidyverse)
library(lme4)
library(nlme)
```

```{r echo=FALSE,include=FALSE}
# import data
dat <- read.csv("/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Holly O'Donnell/Dissertation/Data_Raw/data_7.7.19.csv",na.strings = "")
# format and fill down date of birth,diagnosis date, income level
dat$DateofBirth <- lubridate::mdy(dat$DateofBirth)
dat$DiagnosisDate <- lubridate::mdy(dat$DiagnosisDate)
dat <- dat %>% group_by(ID) %>% fill(DateofBirth) %>% fill(IncomeLevel) %>% fill(DiagnosisDate)
# format visit date
dat$VisitDate <- lubridate::mdy(dat$VisitDate)
# Calculate age and T1D duration at each visit
dat$age_days <- difftime(dat$VisitDate,dat$DateofBirth,units = "days")
dat$age_years <- as.numeric(dat$age_days / 365.25)
dat$T1D_dur_days <- difftime(dat$VisitDate,dat$DiagnosisDate,units = "days")
dat$T1D_dur_years <- as.numeric(dat$T1D_dur_days / 365.25)
# Make study visit and treatment categorical
dat$StudyVisit <- as.factor(dat$StudyVisit)
dat$Treatment <- as.factor(dat$Treatment)
```

# Model Selection

## Start with the full model

```{r echo=FALSE}
mod1_l <- lmer(readings_per_day ~ Treatment + StudyVisit + HbA1c + age_years + T1D_dur_years + IncomeLevel + (1|ID), data = dat)
mod1 <- lme(readings_per_day ~ Treatment + StudyVisit + HbA1c + age_years + T1D_dur_years + IncomeLevel,random =~1|ID, data = dat,na.action = na.omit)
```