---
title: "Control IQ 6 Month Analysis"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(redcapAPI)
library(reshape2)
library(tidyverse)
library(skimr)
library(knitr)
library(tableone)
library(readxl)
library(nlme)
library(gridExtra)
library(psych)
library(stringr)
library(dplyr)
# Check OS and alter file path accordingly.
if (.Platform$OS.type == "windows") {pathstart <- "//ucdenver.pvt/"} else if (.Platform$OS.type == "unix"){pathstart <- "/Volumes/"}
```

```{r echo=FALSE,include=FALSE}

#### NOTE: WHEN I HEAR BACK RE PPT 143, NEED TO WALK THROUGH ALL THIS CODE AND FIGURE OUT WHY
#### THEIR VISITS KEEP GETTING DUPLICATED
###  ALSO, NEED TO RE-EXPORT DATA, PROBABLY IDEALLY AFTER CARI UPDATES BASELINE INFO

source("T:\\Cari Berget\\Control IQ 6 Month MS\\Data raw\\ClinicalObservationC_R_2020-12-11_1426.r")
child_full <- data

source("T:\\Cari Berget\\Control IQ 6 Month MS\\Data raw\\ClinicalObservationP_R_2020-12-11_1425.r")
parent_full <- data

# filter control IQ users
child_full_iq <- child_full[child_full$record_id>=119,]

# there were 4 ppts from adult clinic who should be removed
child_full_iq <- child_full_iq[!(child_full_iq$record_id %in% c(181,182,183,184)),]

# convert to numeric 
child_full_iq$date_visit <- as.Date(as.character(child_full_iq$date_visit),format="%Y-%m-%d")
child_full_iq$demographics_age <- as.numeric(as.character(child_full_iq$demographics_age))
child_full_iq$hba1c <- as.numeric(as.character(child_full_iq$hba1c))

# keep 6 months of data
child_full_iq <- child_full_iq[child_full_iq$gyl_timepoint.factor %in% c("Baseline","Month 1/ Training F/U","3 Months",
                                                                         "6 Months"),]
child_full_iq$gyl_timepoint.factor <- droplevels(child_full_iq$gyl_timepoint.factor)

# get rid of person with duplicate visit
dat143 <- child_full_iq[child_full_iq$record_id==143,]
write.csv(dat143,"T:\\Cari Berget\\Control IQ 6 Month MS\\Data clean\\data_143.csv")
child_full_iq <- child_full_iq[child_full_iq$record_id!=143,]

# read in prior insulin mode
ins <- read.csv("T:\\Cari Berget\\Control IQ 6 Month MS\\Data raw\\Prior_insulin_mode_11-16-2020.csv")
ins$a <- NULL
child_full_iq <- merge(child_full_iq,ins,by="record_id",all.x=T,all.y = F)
child_full_iq$prior.insulin.mode <- as.factor(child_full_iq$prior.insulin.mode)

# read in 6 month alarm data
alarm <- read.csv("T:\\Cari Berget\\Control IQ 6 Month MS\\Data raw\\6 month_alerts_11-20-2020.csv")
alarm$Start.date <- NULL
alarm$end.date <- NULL
alarm$HIGH.alarm.6mo <- alarm$HIGH
alarm$LOW.alarm.6mo <- alarm$LOW
alarm$HIGH <- NULL
alarm$LOW <- NULL
alarm <- alarm[!is.na(alarm$record_id),]
child_full_iq <- merge(child_full_iq,alarm,by=c("record_id"),all.x=T,all.y = F)

# classify age and A1c
child_full_iq$age_cat <- ifelse(child_full_iq$demographics_age<=13,"<=13  years",
                                ifelse(child_full_iq$demographics_age<=17,"14-17 years","18+ years"))
child_full_iq$base_a1c_cat <- ifelse(child_full_iq$hba1c<=7,"<= 7%",ifelse(child_full_iq$hba1c<=9,">7% and <9%",">= 9%"))
child_full_iq <- child_full_iq[!is.na(child_full_iq$record_id),]

# score INSPIRE
# Baseline, under 18
a <- child_full_iq[child_full_iq$demographics_age<18 & child_full_iq$gyl_timepoint.factor=="Baseline",]
a <- a[,c("record_id","gyl_timepoint.factor","inspire_b1","inspire_b2","inspire_b3","inspire_b4","inspire_b5",
          "inspire_b6","inspire_b7","inspire_b8","inspire_b9","inspire_b10","inspire_b11","inspire_b12",
          "inspire_b13","inspire_b14","inspire_b15","inspire_b16","inspire_b17")]
a$inspire_tot <- NA
a$inspire_tot <- rowMeans(a[,-c(1:2)],na.rm = T)*25
a <- a[,c("record_id","gyl_timepoint.factor","inspire_tot")]
# follow-up, under 18
b <- child_full_iq[child_full_iq$gyl_timepoint.factor %in% c("Month 1/ Training F/U","3 Months","6 Months"),]
b <- b[,c("record_id","gyl_timepoint.factor","inspire_f1","inspire_f2","inspire_f3","inspire_f4","inspire_f5",
          "inspire_f6","inspire_f7","inspire_f8","inspire_f9","inspire_f10","inspire_f11","inspire_f12",
          "inspire_f13","inspire_f14","inspire_f15","inspire_f16","inspire_f17")]
b <- b[!is.na(b$"inspire_f1"),]
b$inspire_tot <- NA
b$inspire_tot <- rowMeans(b[,-c(1:2)],na.rm = T)*25
b <- b[,c("record_id","gyl_timepoint.factor","inspire_tot")]
# combine scored INSPIRE and merge back
inspire <- rbind(a,b)
child_full_iq <- merge(child_full_iq,inspire,by=c("record_id","gyl_timepoint.factor"),all.x = T,all.y = T)
child_full_iq <- child_full_iq[!is.na(child_full_iq$record_id),]

# score PAID - child
# there are no records with partial missing data, but I will include this code in case we need it in the future
paid <- child_full_iq %>% dplyr::select(record_id,gyl_timepoint.factor,c_paid1:c_paid20)
missing_threshold <- ceiling(length(3:ncol(paid)) * 0.25)
for (r in 1:nrow(paid)) { # Couldn't get apply to work for some reason
  x <- paid[r,3:ncol(paid)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  paid[r,3:ncol(paid)] <- x
}
# subtract 1 from every variable
paid[,3:ncol(paid)] <- lapply(paid[,3:ncol(paid)],function(x){as.numeric(x)-1})
# score
paid$paid_score_c <- apply(paid[3:ncol(paid)],1,function(x) (mean(4-x))*25)
paid <- paid[,c("record_id","gyl_timepoint.factor","paid_score_c")]
child_full_iq <- merge(child_full_iq,paid,by=c("record_id","gyl_timepoint.factor"), all.x = T, all.y = T)

# score PAID YA
paidya <- child_full_iq %>% dplyr::select(record_id,gyl_timepoint.factor,ya_paid1:ya_paid20)
missing_threshold <- ceiling(length(3:ncol(paidya)) * 0.25)
for (r in 1:nrow(paidya)) { # Couldn't get apply to work for some reason
  x <- paidya[r,3:ncol(paidya)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  paidya[r,3:ncol(paidya)] <- x
}
# score
paidya$paid_score_ya <- apply(paidya[3:ncol(paidya)],1,function(x) (mean(4-x))*25)
paidya <- paidya[,c("record_id","gyl_timepoint.factor","paid_score_ya")]
child_full_iq <- merge(child_full_iq,paidya,by=c("record_id","gyl_timepoint.factor"), all.x = T, all.y = T)
child_full_iq$paid_score <- NA
child_full_iq$paid_score <- pmax(child_full_iq$paid_score_c,child_full_iq$paid_score_ya,na.rm = T)

# score HFS child
hfsc <- child_full_iq %>% dplyr::select(record_id,gyl_timepoint.factor,c_hfs_behave1:c_hfs_behave10,
                                 c_hfs_worry11:c_hfs_worry25)
missing_threshold <- ceiling(length(3:ncol(hfsc)) * 0.25)
for (r in 1:nrow(hfsc)) { # Couldn't get apply to work for some reason
  x <- hfsc[r,3:ncol(hfsc)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  hfsc[r,3:ncol(hfsc)] <- x
}
hfsc$hfs_total_c <- apply(hfsc[,3:ncol(hfsc)],1,sum)
hfsc$hfs_worry_c <- apply(hfsc[,3:12],1,sum)
hfsc$hfs_behave_c <- apply(hfsc[,13:27],1,sum)
hfsc <- hfsc[!is.na(hfsc$hfs_total_c),]
hfsc <- hfsc[,c("record_id","gyl_timepoint.factor","hfs_total_c","hfs_behave_c","hfs_worry_c")]
child_full_iq <- merge(child_full_iq,hfsc,by=c("record_id","gyl_timepoint.factor"),all.x = T,all.y = F)

# score HFS YA - baseline and follow-up are separate
# baseline
hfsya_b <- child_full_iq %>% dplyr::select(record_id,gyl_timepoint.factor,ya_hfs_b_behave1:ya_hfs_b_behave15,
                                 ya_hfs_b_worry16:ya_hfs_b_worry33)
missing_threshold <- ceiling(length(3:ncol(hfsya_b)) * 0.25)
for (r in 1:nrow(hfsya_b)) { # Couldn't get apply to work for some reason
  x <- hfsya_b[r,3:ncol(hfsya_b)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  hfsya_b[r,3:ncol(hfsya_b)] <- x
}
hfsya_b$hfs_total_ya <- apply(hfsya_b[,3:ncol(hfsya_b)],1,sum)
hfsya_b$hfs_worry_ya <- apply(hfsya_b[,3:12],1,sum)
hfsya_b$hfs_behave_ya <- apply(hfsya_b[,13:27],1,sum)
hfsya_b <- hfsya_b[!is.na(hfsya_b$hfs_total_ya),]
hfsya_b <- hfsya_b[,c("record_id","gyl_timepoint.factor","hfs_total_ya","hfs_worry_ya","hfs_behave_ya")]
# follow-up
hfsya_f <- child_full_iq %>% dplyr::select(record_id,gyl_timepoint.factor,ya_hfs_f_behave1:ya_hfs_f_behave15,
                                 ya_hfs_f_worry16:ya_hfs_f_worry33)
missing_threshold <- ceiling(length(3:ncol(hfsya_f)) * 0.25)
for (r in 1:nrow(hfsya_f)) { # Couldn't get apply to work for some reason
  x <- hfsya_f[r,3:ncol(hfsya_f)]
  replacement <- mean(as.numeric(x),na.rm = T)
  num_missing <- length(which(is.na(x)))
  if (num_missing<=missing_threshold && num_missing>0) {
    x[which(is.na(x))] <- replacement
    } else if (num_missing > missing_threshold) {
      x <- rep(NA,length(x))
    }
  hfsya_f[r,3:ncol(hfsya_f)] <- x
}
hfsya_f$hfs_total_ya <- apply(hfsya_f[,3:ncol(hfsya_f)],1,sum)
hfsya_f$hfs_worry_ya <- apply(hfsya_f[,3:12],1,sum)
hfsya_f$hfs_behave_ya <- apply(hfsya_f[,13:27],1,sum)
hfsya_f <- hfsya_f[!is.na(hfsya_f$hfs_total_ya),]
hfsya_f <- hfsya_f[,c("record_id","gyl_timepoint.factor","hfs_total_ya","hfs_behave_ya","hfs_worry_ya")]
hfsya <- rbind(hfsya_b,hfsya_f)
child_full_iq <- merge(child_full_iq,hfsya,by=c("record_id","gyl_timepoint.factor"),all.x = T,all.y = F)
# NOW NEED TO CHOOSE BETWEEN CHILD AND YA SCORES FOR EACH OF THE SCALES
child_full_iq$hfs_total <- NA
child_full_iq$hfs_behave <- NA
child_full_iq$hfs_worry <- NA
child_full_iq$hfs_total <- pmax(child_full_iq$hfs_total_c,child_full_iq$hfs_total_ya,na.rm = T)
child_full_iq$hfs_worry <- pmax(child_full_iq$hfs_worry_c,child_full_iq$hfs_worry_ya,na.rm = T)
child_full_iq$hfs_behave <- pmax(child_full_iq$hfs_behave_c,child_full_iq$hfs_behave_ya,na.rm = T)

# score technology attitudes
tech <- child_full_iq[,c("record_id","gyl_timepoint.factor","tech1","tech2","tech3","tech4","tech5")]
tech <- tech[!is.na(tech$tech1),]
tech$tech1 <- tech$tech1+1
tech$tech2 <- tech$tech2+1
tech$tech3 <- tech$tech3+1
tech$tech4 <- tech$tech4+1
tech$tech5 <- tech$tech5+1
tech$tech_sum <- NA
tech$tech_sum <- rowSums(tech[,-c(1:2)],na.rm = T)
tech <- tech[,c("record_id","gyl_timepoint.factor","tech_sum")]
child_full_iq <- merge(child_full_iq,tech,by=c("record_id","gyl_timepoint.factor"),all.x = T, all.y = F)

# find people with only baseline visit
checkvisits <- child_full_iq[,c("record_id","gyl_timepoint.factor")]
checkvisits$flag <- 1
checkvisits_wide <- reshape(checkvisits,idvar = "record_id",timevar = "gyl_timepoint.factor",direction = "wide")

never_trained <- checkvisits_wide[is.na(checkvisits_wide$`flag.Month 1/ Training F/U`) & 
                               is.na(checkvisits_wide$`flag.3 Months`) &
                               is.na(checkvisits_wide$`flag.6 Months`),]
never_trained$trained <- 0
never_trained <- never_trained[,c("record_id","trained")]
trained_and_withdrawn <- checkvisits_wide[!is.na(checkvisits_wide$`flag.Month 1/ Training F/U`) & 
                               is.na(checkvisits_wide$`flag.3 Months`) &
                               is.na(checkvisits_wide$`flag.6 Months`),]
trained_and_withdrawn$withdrawn <- 1
trained_and_withdrawn <- trained_and_withdrawn[,c("record_id","withdrawn")]
child_full_iq <- merge(child_full_iq,never_trained,by="record_id",all.x=T,all.y=T)
child_full_iq <- merge(child_full_iq,trained_and_withdrawn,by="record_id",all.x=T,all.y=T)
child_full_iq$trained <- ifelse(is.na(child_full_iq$trained),1,0)
child_full_iq$withdrawn <- ifelse(is.na(child_full_iq$withdrawn),0,1)

# check for discontinuers
# discontinuation is defined as AM <10% at either time point
child_full_iq$t1_discont <- ifelse(child_full_iq$trained==1 & child_full_iq$withdrawn==0 & 
                                     child_full_iq$gyl_timepoint.factor=="3 Months" & 
                                     (is.na(child_full_iq$time_am) | child_full_iq$time_am<10),1,0)
child_full_iq$t2_discont <- ifelse(child_full_iq$trained==1 & child_full_iq$withdrawn==0 & 
                                     child_full_iq$gyl_timepoint.factor=="6 Months" & 
                                     (is.na(child_full_iq$time_am) | child_full_iq$time_am<10),1,0)
t1_discont <- child_full_iq[,c("record_id","t1_discont")]
t1_discont <- t1_discont[order(t1_discont$record_id,desc(t1_discont$t1_discont)),]
t1_discont <- t1_discont %>% group_by(record_id) %>% filter(row_number() == 1)
t2_discont <- child_full_iq[,c("record_id","t2_discont")]
t2_discont <- t2_discont[order(t2_discont$record_id,desc(t2_discont$t2_discont)),]
t2_discont <- t2_discont %>% group_by(record_id) %>% filter(row_number() == 1)
child_full_iq$t1_discont <- NULL
child_full_iq$t2_discont <- NULL
child_full_iq <- merge(child_full_iq,t1_discont,by="record_id",all.x=T,all.y=T)
child_full_iq <- merge(child_full_iq,t2_discont,by="record_id",all.x=T,all.y=T)
n_t1_discont <- length(unique(child_full_iq[child_full_iq$t1_discont==1,]$record_id))
n_t2_discont <- length(unique(child_full_iq[child_full_iq$t2_discont==1,]$record_id))
a <- child_full_iq[child_full_iq$record_id==245,c("record_id","gyl_timepoint.factor","automode_start")]
n_only_baseline <- length(unique(a$record_id))
b <- child_full[child_full$record_id %in% c(276,300,313,318,321),c("record_id","gyl_timepoint.factor",
                                                                  "date_visit","automode_start")]
n_only_1mo <- length(unique(b$record_id))
c <- child_full_iq[child_full_iq$t1_discont==1,c("record_id","gyl_timepoint.factor","time_am")]
d <- child_full_iq[child_full_iq$t2_discont==1,c("record_id","gyl_timepoint.factor","date_visit","time_am")]
write.csv(d,"T:\\Cari Berget\\Control IQ 6 Month MS\\Data clean\\T2_discontinuers.csv")

# remove those never trained, withdrawn, discontinued at T1
child_full_iq <- child_full_iq[child_full_iq$trained==1 & child_full_iq$withdrawn==0 & child_full_iq$t1_discont==0,]
# if discontinued at T2, remove T2
child_full_iq <- child_full_iq[!(child_full_iq$gyl_timepoint.factor=="6 Months" & child_full_iq$t2_discont==1),]

# View(child_full_iq[,c("record_id","gyl_timepoint.factor","trained","withdrawn","time_am","t1_discont","t2_discont")])

# make baseline dataset
baseline <- child_full_iq[child_full_iq$gyl_timepoint.factor=="Baseline",]



# missing demographics data
miss_demo <- baseline[is.na(baseline$demographics_age) | is.na(baseline$demographics_sex) |
                                     is.na(baseline$demographics_ethnicity) |
                                             is.na(baseline$demographics_race) |
                                                   is.na(baseline$demographics_insurance),c("record_id",demovars)]
write.csv(miss_demo,"T:\\Cari Berget\\Control IQ 6 Month MS\\Data clean\\missing demographics.csv")

# dataframe without M1
data_no_m1 <- child_full_iq[child_full_iq$gyl_timepoint.factor != "Month 1/ Training F/U",]
data_no_m1$gyl_timepoint.factor <- droplevels(data_no_m1$gyl_timepoint.factor)

# % time CIQ
# AM time compare to 1 mo - dataset with no baseline
# use baseline for CGM variables
amtime_mod <- lme(time_am ~ gyl_timepoint.factor,random=~1|record_id,data = data_no_m1,na.action = na.omit)
# use emmeans 
amtime_mod_means <- lme(time_am ~ gyl_timepoint.factor-1,random=~1|record_id,data = data_no_m1,na.action = na.omit)

# questions for Tim:
# 1.  when I run the first model, why do I only have a fixed effect of 6 months?
# 2.  I don't understand the syntax of the second model

# table of demographics
demovars <- c("demographics_age","age_cat","hba1c","base_a1c_cat","demographics_sex.factor",
              "demographics_ethnicity.factor","demographics_race.factor","demographics_insurance.factor",
              "prior.insulin.mode")
t1 <- CreateTableOne(vars=demovars,data=baseline)
t1 <- print(t1,printToggle = F,varLabels=TRUE,missing=T,showAllLevels = T,nonnorm=c("hba1c","demographics_age"))

```

# Background

# Methods

# Results

# There were `r n_only_baseline` participants with no 1 mo, 3 mo, or 6 mo visits

```{r echo=FALSE}
# look at people who never trained to see if they have start dates
kable(a)
```

# There were `r n_only_1mo` participants with a 1 mo visit, but no 3 mo 6 mo visits

```{r echo=FALSE}
# look at duration of CIQ use in those who withdrew
kable(b)
```

# There were `r n_t1_discont` discontinuers at T1.

```{r echo=FALSE}
kable(c)
```

# There were `r n_t2_discont` discontinuers at T2.

```{r echo=FALSE}
kable(d)
```

<br>

```{r, echo=FALSE, message=FALSE}
kable(t1,caption="Table 1. Demographics and clinical characteristics.")
```
