---
title: "AHA Lipidomics"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(skimr)
library(knitr)
library(readxl)
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE)
home_dir = ifelse(.Platform$OS.type != "unix","T:/",
                  "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant/Lipidomics/")
knitr::opts_knit$set(root.dir = home_dir)
```

```{r}
# Import data
intensities = read.csv("./Data_Raw/20210517 Lipid list (ANA-239) by Skyline_Final.csv",
                       stringsAsFactors = F)
# Get compound info in separate frame
compound_info = intensities[,1:5]
intensities[,1:5] = NULL
# Transpose and format
intensities = as.data.frame(log(t(intensities)))
colnames(intensities) = compound_info$LipidMolec
intensities$StudyID = gsub("\\.","_p",rownames(intensities))
# Import sample info
sample.info = read.csv("./Data_Cleaned/targeted.csv")
# Add lipids to sample info
order = read_excel("./Data_Raw/20210509 Sample Information of AHA-239 study.xlsx")
intensities$StudyID = 
  order$`Original SampleID`[match(intensities$StudyID,order$`sample order`)]

df = left_join(sample.info,intensities)
write.csv(df,"./Data_Cleaned/lipidomics.csv",row.names = F,na = "")
```
