---
title: "JDRF Prelim Analysis"
author: "Casey Sakamoto"
date: "7/26/2022"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(readxl)
library(tidyverse) # data manipulation
library(lubridate)
library(ggplot2)
library(readr)
library(table1)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "S:/Laura/BDC/Projects/Viral Shah/JDRF"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Viral Shah/JDRF"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Viral Shah/JDRF"
}
knitr::opts_knit$set(root.dir = home_dir)

jdrf_data_clean <- read_csv("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Cleaned/jdrf_data_clean.csv")
```


```{r var summarizing, include=FALSE} 
# commented out old var names
# here we are averaging subjects across visits, and then comparing these averages between groups
jdrf_data_clean = jdrf_data_clean %>% mutate(a1c = case_when(a1c == "televisit" ~ NA_character_,
                                                             a1c == "-" ~ NA_character_,
                                                             TRUE ~ a1c))
jdrf_data_clean$a1c = as.numeric(jdrf_data_clean$a1c)
cgm_table_df = jdrf_data_clean %>% group_by(`Study ID`, Group) %>% summarise(
                                                                                                                                             mean_a1c = mean(a1c, na.rm = T),
                                                                                                                                             mean_tir = mean(tir, na.rm = T),
                                                                                                                                             mean_tbr = mean(tbr, na.rm = T),
                                                                                                                                             mean_tar = mean(tar, na.rm = T),
                                                                                                                                             mean_ttir = mean(ttir, na.rm = T),
                                                                                                                                             mean_glucose = mean(mean_glucose, na.rm = T))
# all of the variables we are interested in here is collected at basaeline i believe
# so i will filter out the mrn lab data and only include those with a study id
lab_table_df = jdrf_data_clean %>% 
  select(`Study ID`,Group, Age_DateOfEyeExam, Sex, Race_Ethnicity, Htcm, Wtkg, BMI, InsuranceCategory_DateOfEyeExam, DiabetesDuration_DateOfEyeExam, HistoryOfCardiovascularDisease_YesNo,
         Hyperthyroidism_YesNo, GravesDisease_YesNo, AddisonsDisease_YesNo, CeliacDisease_YesNo) %>% 
  group_by(`Study ID`, Group) %>%
  filter(!is.na(`Study ID`)) %>% distinct()

# remove dupe rows
lab_table_df = lab_table_df %>% group_by(`Study ID`) %>% fill(c(Wtkg, Htcm, BMI), .direction = "up") %>% distinct()

# combine the two for table 1
table1_df = full_join(lab_table_df, cgm_table_df) %>% filter(!is.na(Group))
table1_df = table1_df %>% ungroup 
```


```{r table1, echo=FALSE}
# T1D_lab_table1 =  table1( ~ `duration_of_t1d (years)` + home_regimen + hba1c + ph + bicarbonate + glargine_dose_per_kg 
#                        | diabetes_diagnosis, data = EG_patient_char, topclass="Rtable1-zebra",
#                         render.continuous=c( "Median [IQR]"="Median [Q1, Q3]"), overall=F, extra.col=list(`P-value`=pvalue))


jdrf_table1 = table1( ~ .| Group,
                      data = table1_df,
                      topclass ="Rtable1-zebra",
                      render.continuous=c( "Mean (SD)"="Mean (SD)"))
jdrf_table1
```


```{r dataset output, include=FALSE}
# 
# setwd("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Cleaned")
# write.csv(combined_jdrf, file = "jdrf_reallylong_long.csv")
# output the long duped out jdrf data for tim, sorry dude its ugly
```