---
title: "JDRF Data Clean"
author: "Casey Sakamoto"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(readxl)
library(tidyverse) # data manipulation
library(lubridate)


knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "S:/Laura/BDC/Projects/Viral Shah/JDRF"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Viral Shah/JDRF"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Viral Shah/JDRF"
}
knitr::opts_knit$set(root.dir = home_dir)



```

## Data notes
- in demographics there is a "comments" variable for group 2 but not group 1

```{r demographics}
# import demographics data
Group_1_Demographic_data =  read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Demographic data_2-3-2022.xlsx", 
    col_types = c("numeric", "numeric", "text", 
        "text", "text", "text", "date", "date", 
        "numeric", "text", "text", "text", 
        "date", "numeric", "numeric", "numeric", 
        "text", "date", "numeric", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text"))

Group_2_Demographic_Data = read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Demographic Data_2-3-2022.xlsx", 
    col_types = c("numeric", "numeric", "text", 
        "text", "text", "text", "date", "text", 
        "date", "numeric", "text", "text", 
        "text", "date", "numeric", "numeric", 
        "numeric", "text", "date", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text"))

# add group number variable
Group_1_Demographic_data$group = 1
Group_2_Demographic_Data$group = 2

# note there is a comment variable in group 2 not in group 1
Demographic_data = full_join(Group_1_Demographic_data, Group_2_Demographic_Data)
rm(Group_1_Demographic_data, Group_2_Demographic_Data)
```


```{r lab data, not changing date name}
# need mrn, date, order value, named after sheet

# UrineAlbuminCreatinineRatio
uacr_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "UrineAlbuminCreatinineRatio")
uacr_1$group = 1
uacr_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "UrineAlbuminCreatinineRatio")
uacr_2$group = 2
# merge and rename vars
uacr = full_join(uacr_1, uacr_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( uacr = OrderValue)
# coerce date to date form
# values are pretty ugly, mix of numbers, sci notation numbers, characters saying "note, no test, less than ..."
# truncated measurements, weird range (99 for 3 values, under 10 for the rest)
rm(uacr_1, uacr_2)

# Hemoglobin
hemo_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "Hemoglobin")
hemo_1$group = 1
hemo_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "Hemoglobin")
hemo_2$group = 2
# hemo2 is type char vector, looks like only one obs thats a problem; convert hemo1 to char for now
hemo_1$OrderValue = as.character(hemo_1$OrderValue)

hemo = full_join(hemo_1, hemo_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(hemoglobin = OrderValue)
rm(hemo_1, hemo_2)

# MCV
MCV_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "MCV")
MCV_1$group = 1
MCV_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "MCV")
MCV_2$group = 2
# mcv2 is type char, same reason and subj as hemoglobin above
MCV_1$OrderValue = as.character(MCV_1$OrderValue)

mcv = full_join(MCV_1, MCV_2) %>% select(MRN, group,ResultDate, OrderValue) %>% rename( mcv = OrderValue)
rm(MCV_1, MCV_2)


# Serum Ferritin
sf_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "SerumFerritin ")
sf_1$group = 1
sf_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "SerumFerritin ")
sf_2$group = 2
# sf2 is type char, same reason one subj has "canceled"
sf_1$OrderValue = as.character(sf_1$OrderValue)

sf = full_join(sf_1, sf_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( sf = OrderValue)
rm(sf_1, sf_2)

# TotalIron
ti_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "TotalIron")
ti_1$group = 1
ti_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "TotalIron")
ti_2$group = 2
ti = full_join(ti_1, ti_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( ti = OrderValue)
rm(ti_1, ti_2)

# TIBC
tibc_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "TIBC ")
tibc_1$group = 1
tibc_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "TIBC ")
tibc_2$group = 2
tibc = full_join(tibc_1, tibc_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( tibc = OrderValue)
rm(tibc_1, tibc_2)

# transferrinsaturation
ts_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "TransferrinSaturation")
ts_1$group = 1
ts_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "TransferrinSaturation")
ts_2$group = 2
ts = full_join(ts_1, ts_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( ts = OrderValue)

rm(ts_1, ts_2)

#total cholesterol
tc_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "TotalCholesterol ")
tc_1$group = 1
tc_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "TotalCholesterol ")
tc_2$group = 2
# 1 "TNP" in tc2
tc_1$OrderValue = as.character(tc_1$OrderValue)
tc = full_join(tc_1, tc_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( tc = OrderValue)
rm(tc_1, tc_2)

# triglycerides
trig_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "Triglycerides ")
trig_1$group = 1
trig_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "Triglycerides ")
trig_2$group = 2
trig_1$OrderValue = as.character(trig_1$OrderValue)

trig = full_join(trig_1, trig_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( trig = OrderValue)
rm(trig_1,trig_2)


# HDL
hdl_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "HDL ")
hdl_1$group = 1
hdl_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "HDL ")
hdl_2$group = 2
hdl_1$OrderValue = as.character(hdl_1$OrderValue)
hdl = full_join(hdl_1, hdl_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( hdl = OrderValue)
rm(hdl_1, hdl_2)


# LDL
ldl_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "LDL")
ldl_1$group=1
ldl_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "LDL")
ldl_2$group = 2

ldl_1$OrderValue = as.character(ldl_1$OrderValue)

ldl = full_join(ldl_1, ldl_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( ldl = OrderValue)
rm(ldl_1, ldl_2)


# serumcreatinine
sc_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "SerumCreatinine")
sc_1$group = 1
sc_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "SerumCreatinine")
sc_2$group = 2
sc = full_join(sc_1, sc_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( sc = OrderValue)
rm(sc_1,sc_2)


# egfr
egfr_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "eGFR")
egfr_1$group = 1
egfr_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "eGFR")
egfr_2$group = 2
egfr = full_join(egfr_1, egfr_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename( egfr = OrderValue)
rm(egfr_1, egfr_2)
```

```{r combine sets}
# this should remove duplicate values by date
# uacr, hemo, mcv, sf, ti, tibc, ts, tc, trig, hdl, ldl, sc, egfr
analysis = full_join(Demographic_data, uacr)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     hemo %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     mcv %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     sf %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     ti %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     tibc %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     ts %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     tc %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     trig %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     hdl %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     ldl %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     sc %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
analysis = full_join(analysis %>% group_by(ResultDate) %>% mutate(dummy = row_number()),
                     egfr %>% group_by(ResultDate) %>% mutate(dummy = row_number())) %>% select(-dummy)
```

```{r output dataset}
write.csv2(analysis, file = "S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Cleaned/jdrf_data_clean.csv")
```

note: when i was cleaning data and joining sets, was running into a huge duplicate problem with full join. found a solution at: 

https://community.rstudio.com/t/dplyr-joins-dealing-with-multiple-matches-duplicates-in-key-column/14528

This involved using resultdate rather than renaming each specific date.
```{r lab data, changing date name DONT RUN}
# need mrn, date, order value, named after sheet

# UrineAlbuminCreatinineRatio
uacr_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "UrineAlbuminCreatinineRatio")
uacr_1$group = 1
uacr_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "UrineAlbuminCreatinineRatio")
uacr_2$group = 2
# merge and rename vars
uacr = full_join(uacr_1, uacr_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(uacr_date = ResultDate, uacr = OrderValue)
# coerce date to date form
uacr$uacr_date = as.Date(uacr$uacr_date)
# values are pretty ugly, mix of numbers, sci notation numbers, characters saying "note, no test, less than ..."
# truncated measurements, weird range (99 for 3 values, under 10 for the rest)
rm(uacr_1, uacr_2)

# Hemoglobin
hemo_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "Hemoglobin")
hemo_1$group = 1
hemo_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "Hemoglobin")
hemo_2$group = 2
# hemo2 is type char vector, looks like only one obs thats a problem; convert hemo1 to char for now
hemo_1$OrderValue = as.character(hemo_1$OrderValue)

hemo = full_join(hemo_1, hemo_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(hemo_date = ResultDate, hemoglobin = OrderValue)
rm(hemo_1, hemo_2)

# MCV
MCV_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "MCV")
MCV_1$group = 1
MCV_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "MCV")
MCV_2$group = 2
# mcv2 is type char, same reason and subj as hemoglobin above
MCV_1$OrderValue = as.character(MCV_1$OrderValue)

mcv = full_join(MCV_1, MCV_2) %>% select(MRN, group,ResultDate, OrderValue) %>% rename(mcv_date = ResultDate, mcv = OrderValue)
rm(MCV_1, MCV_2)


# Serum Ferritin
sf_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "SerumFerritin ")
sf_1$group = 1
sf_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "SerumFerritin ")
sf_2$group = 2
# sf2 is type char, same reason one subj has "canceled"
sf_1$OrderValue = as.character(sf_1$OrderValue)

sf = full_join(sf_1, sf_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(sf_date = ResultDate, sf = OrderValue)
rm(sf_1, sf_2)

# TotalIron
ti_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "TotalIron")
ti_1$group = 1
ti_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "TotalIron")
ti_2$group = 2
ti = full_join(ti_1, ti_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(ti_date = ResultDate, ti = OrderValue)
rm(ti_1, ti_2)

# TIBC
tibc_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "TIBC ")
tibc_1$group = 1
tibc_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "TIBC ")
tibc_2$group = 2
tibc = full_join(tibc_1, tibc_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(tibc_date = ResultDate, tibc = OrderValue)
rm(tibc_1, tibc_2)

# transferrinsaturation
ts_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "TransferrinSaturation")
ts_1$group = 1
ts_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "TransferrinSaturation")
ts_2$group = 2
ts = full_join(ts_1, ts_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(ts_date = ResultDate, ts = OrderValue)

rm(ts_1, ts_2)

#total cholesterol
tc_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "TotalCholesterol ")
tc_1$group = 1
tc_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "TotalCholesterol ")
tc_2$group = 2
# 1 "TNP" in tc2
tc_1$OrderValue = as.character(tc_1$OrderValue)
tc = full_join(tc_1, tc_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(tc_date = ResultDate, tc = OrderValue)
rm(tc_1, tc_2)

# triglycerides
trig_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "Triglycerides ")
trig_1$group = 1
trig_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "Triglycerides ")
trig_2$group = 2
trig_1$OrderValue = as.character(trig_1$OrderValue)

trig = full_join(trig_1, trig_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(trig_date = ResultDate, trig = OrderValue)
rm(trig_1,trig_2)


# HDL
hdl_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "HDL ")
hdl_1$group = 1
hdl_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "HDL ")
hdl_2$group = 2
hdl_1$OrderValue = as.character(hdl_1$OrderValue)
hdl = full_join(hdl_1, hdl_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(hdl_date = ResultDate, hdl = OrderValue)
rm(hdl_1, hdl_2)


# LDL
ldl_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "LDL")
ldl_1$group=1
ldl_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "LDL")
ldl_2$group = 2

ldl_1$OrderValue = as.character(ldl_1$OrderValue)

ldl = full_join(ldl_1, ldl_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(ldl_date = ResultDate, ldl = OrderValue)
rm(ldl_1, ldl_2)


# serumcreatinine
sc_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "SerumCreatinine")
sc_1$group = 1
sc_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "SerumCreatinine")
sc_2$group = 2
sc = full_join(sc_1, sc_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(sc_date = ResultDate, sc = OrderValue)
rm(sc_1,sc_2)


# egfr
egfr_1 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 1_Lab Variables_2-22-2022.xlsx", 
    sheet = "eGFR")
egfr_1$group = 1
egfr_2 <- read_excel("S:/Laura/BDC/Projects/Viral Shah/JDRF/Data_Raw/Group 2_Lab Variables_2-22-2022.xlsx", 
    sheet = "eGFR")
egfr_2$group = 2
egfr = full_join(egfr_1, egfr_2) %>% select(MRN,group, ResultDate, OrderValue) %>% rename(egfr_date = ResultDate, egfr = OrderValue)
rm(egfr_1, egfr_2)
```
