---
title: ""
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(readxl)
library(performance)
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/BDC/Shah Students 2021/13. JDRF_TIR_Startig August 1_Anagha"
}
knitr::opts_knit$set(root.dir = home_dir)
rm(home_dir)
```

```{r}
# Combine summaries into one dataset
cases_files = list.files("./3. Data Collection/Cleaned Final Data/Cases_T1D+DR",
                         recursive = T,full.names = T)
cases_files = cases_files[grepl("summary",tolower(cases_files))]
case_df = lapply(cases_files, function(d){
  id = gsub("[[:alpha:]]|[[:punct:]]|[[:space:]]","",basename(d))
  id = as.numeric(id)
  df = suppressMessages(read_excel(d,na = c("","n/a")))
  df$id = id
  df = df[,c("id","DOB","Visit No.","Office Visit Date","A1c","CGM type at visit")]
  return(df)
})
case_df = do.call(rbind,case_df)
```
