---
title: ""
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(arsenal)
library(tidyverse)
library(performance)
library(knitr)
library(mice)
knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
```

# Regression on Imputed Data

```{r}
load("./Janet Snell-Bergeon/AHA collaborative grant/aha_master_data.Rdata")
# Columns from Laura's model
columns_from_laura = c(snps,"gly_P02671.7","gly_P02671.5",
                       "gly_P02671.4","gly_P02671.3","AAA01201000179.0807263.4",
                       "gly_P02679","HMDB00510161.0696402.9",
                       "AAA01201000179.0809235.7","gly_P02675.4","gly_P02675",
                       "gly_P02647","P02655","gly_P02647.1",
                       "HMDB00510161.0694436","gly_P02652","gly_P01009",
                       "gly_P01834.11","P01817","AcCa 10:3",
                       "HMDB0028822260.1378628.6","AAA01201000179.0807263.4",
                       "gly_P02671.3","gly_P02671.7","age", "onhypermedsV1",
                       "onlipidmedsV1", "ldlV1", "smknum","SmkStatusV1","race","cholV1", 
                       "duration_cat")
outcomes = c("CACanyV1")
columns_from_laura = gsub(" |[[:punct:]]","_",columns_from_laura)
# Load data
load("./Janet Snell-Bergeon/AHA collaborative grant/aha_imputed_data.Rdata")
# Regress on imputed
f = as.formula(paste0("CACanyV1~",paste0(columns_from_laura,collapse = "+")))
fit <- with(imputed_aha, glm(f))
# Results
summary(pool(fit))
```
