---
title: "Analysis of AHA omics data"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
library(arsenal)
library(skimr)
library(knitr)
library(mixOmics)
library(tidyverse)
library(limma)
library(webchem)
library(omu)
library(PCAtools)
library(openxlsx)
library(dplyr)
library(multtest)
library(pls)
library(parallel)
library(readxl)
library(ActivePathways)
home_dir = ifelse(.Platform$OS.type != "unix","Z:/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant",
                  "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Janet Snell-Bergeon/AHA collaborative grant/")
knitr::opts_knit$set(root.dir = home_dir)

```

```{r ,echo=FALSE}
# read in file with p-values - for now, just global proteomics
global_prot_p <- read_excel("./Reports/AHA_omics_ttests.xlsx", sheet="global_prot_moderated_FDR")
global_prot_p <- global_prot_p[,c("...1","P.Value")]
colnames(global_prot_p) <- c("Accession","Global_prot")

# merge p-values with gene names
global_prot_dat <- read_excel("./Proteomics/Data_Raw/AHA_WP_global proteome_PD_Proteins export.xlsx", sheet="Proteins")
global_prot_dat <- global_prot_dat[,c("Accession","Gene Symbol")]
global_prot_p <- merge(global_prot_p,global_prot_dat,by="Accession",all.x = T, all.y = F)
global_prot_p$Accession <- NULL

# trying the package with just one dataset
temp <- global_prot_p
rownames(temp) <- temp$`Gene Symbol`
# there are duplicate row names

# read in Reactome pathways gene set
gmt_file <- read.GMT("~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Material/Multiomics/Reactome Pathways Gene Set.gmt")


```