---
title: "RIP-GC"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(arsenal)
library(skimr)
library(knitr)
library(Epi)
library(epiR)
library(tidyverse)
```

```{r data import,echo=FALSE}
source("/Users/timvigers/Documents/GitHub/BDC-Code/Shideh Majidi/RIP-GC/rip_gc_data.r")
```

# Table 1: Characteristics of patients with T1D stratified by RIPGC risk category

```{r table one,echo=FALSE,results='asis'}
table_one <- tableby(RiskCategory_coded ~ Duration + Age + 
                       Sex + RaceEthnicity_combined + notest(Insurance) + cgm_use + 
                       pump_use,
                     data = demographics)
summary(table_one,digits = 2)
```

# Poor Glycemic Control (HbA1c >= 9.5%)

## Sensitivity and Specificity

```{r glyc sens spec,echo=FALSE}
# Define poor glycemic control as 9.5% - Schwartz et al. 2014
roc_data$glycemic_control <- cut(roc_data$a1c,c(-Inf,9.5,Inf),right = F,
                                 labels = c("Good","Poor"))
glyc_roc <- ROC(stat = roc_data$glycemic_control, test = roc_data$ripgc,plot =NULL,MI=F)
results <- as.data.frame(glyc_roc$res)
colnames(results)[5] <- "RI-PGC Score"
kable(results,row.names = F)
```

## ROC

```{r ROC glyc}
ROC(stat = roc_data$glycemic_control, test = roc_data$ripgc,plot = "roc",MI=F)
```

# TIR < 70%

## Sensitivity and Specificity

```{r tir sens spec,echo=FALSE}
roc_data$tir <- cut(roc_data$cgm_ok,c(-Inf,70,Inf),right = F,
                                 labels = c("Poor","Good"))
tir_roc <- ROC(stat = roc_data$tir, test = roc_data$ripgc,plot =NULL,MI=F)
results <- as.data.frame(tir_roc$res)
colnames(results)[5] <- "RI-PGC Score"
kable(results,row.names = F)
```

## ROC

```{r ROC tir}
ROC(stat = roc_data$tir, test = roc_data$ripgc,plot = "roc",MI=F)
```

# DKA

## Sensitivity and Specificity

```{r dka sens spec,echo=FALSE}
dka_roc <- ROC(stat = roc_data$DKA, test = roc_data$ripgc,plot =NULL,MI=F)
results <- as.data.frame(dka_roc$res)
colnames(results)[5] <- "RI-PGC Score"
results$`RI-PGC Score` <- c("-Inf",as.character(c(0:8)))
kable(results,row.names = F)
```

## ROC

```{r ROC DKA}
ROC(stat = roc_data$DKA, test = roc_data$ripgc,plot = "roc",MI=F)
```