---
title: "JDRF Models"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/home/tim/Documents/GitHub/BDC-Code/Greg Forlenza/JDRF")
library(Hmisc)
library(arsenal)
library(skimr)
library(knitr)
library(glmnet)
library(tidyverse)
```

```{r import data,echo=FALSE}
source("/home/tim/Documents/GitHub/BDC-Code/Greg Forlenza/JDRF/data_import.R")
```

```{r data cleaning,echo=FALSE}
# Exclude participants after 115
data <- data %>% filter(record_id <= 115)
# Binary endpoint and predictors
# The primary endpoint of interest will be percent time in closed loop at 1 year 
# captured as a continuous percentage for the 2 weeks prior to the 1 year clinical 
# follow up visit, and will be converted to a binary variable with ≥60% representing 
# successful AP use and <60% representing unsuccessful AP use.
df <- left_join(data %>% group_by(record_id) %>% 
                  filter(gyl_timepoint.factor =="12 Months") %>%
                  summarise(am_12_months = time_am), 
                data %>% filter(grepl("baseline",redcap_event_name)) %>%
                  select(record_id,hba1c,demographics_age,demographics_t1d_duration,
                         demographics_sex.factor,demographics_insurance.factor,
                         demographics_race.factor,demographics_ethnicity.factor,
                         demographics_cgmhx.factor,demographics_pumphx.factor),
                by = "record_id")
# Remove duplicates
df <- df[-c(which(duplicated(df$record_id))-1),]
# Add 1 month variables
df <- left_join(df,data %>% 
                  filter(gyl_timepoint.factor == "Month 1/ Training F/U") %>%
                  select(record_id,sensor_wear,time_am,sensor_70_180),
                by = "record_id")
# Binary outcome
df$success <- as.factor(ifelse(df$am_12_months >= 60,"Success","Failure"))
```

# Skim

```{r echo=FALSE}
skim(df)
```

# Table 1: Descriptive Characteristics

```{r table 1,echo=FALSE,results='asis'}
t1_form <- paste(colnames(df)[2:ncol(df)],collapse = "+")
t1 <- tableby(as.formula(paste("~",t1_form)),data = df)
summary(t1)
```

# Models

```{r models,echo=FALSE}
# Lasso
# Make model matrix and outcome vector
form <- 
  as.formula(paste("success~",paste(colnames(df)[3:(ncol(df)-1)],
                                    collapse = "+")))
cc <- df[complete.cases(df),]

x <- model.matrix(form,cc)[,-1]
y <- cc$success
# Fit
fit <- glmnet(x,y,family = "binomial")
plot(fit,xvar = "lambda")
# Cross validation for lambda
cv.fit <- cv.glmnet(x, y, alpha=1, family = "binomial")
plot(cv.fit)
coef(cv.fit)
```

### Clarifying questions for Greg

1. Only 87 patients have a 12 month timepoint. Should we use average AM use across all timepoints? Slightly different outcome from use at 1 year. Or AM use at final visit?
2. Where are SES and parental education?
3. What timepoints are we using surveys from?