---
title: "JDRF Model Validation"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
library(knitr)
library(tidyverse)
library(Epi)
```

```{r clean data,echo=FALSE,warning=FALSE,message=FALSE}
# Read in
stanford <- 
  read.csv("./Greg Forlenza/JDRF/Data_Cleaned/stanford.csv",
           na.strings = c("","NA","na","N/A"),stringsAsFactors = F)
# Format
num_vars <- c("Baseline.A1c","Auto.Mode...1","Time.in.range.....1")
stanford[,num_vars] <- lapply(stanford[,num_vars], as.numeric)
# Age groups
stanford$demographics_age <- 
  cut(stanford$Age,c(5,13,18,Inf),right = T,
      labels = c("6 - 13","14 - 18","18+"))
# Model df
df <- stanford %>% group_by(Participant.ID) %>%
  summarise(hba1c = Baseline.A1c[Event.Name=="670G Start"],
            m3_am_time = Auto.Mode...1[Event.Name=="3 month visit"],
            m3_tir = Time.in.range.....1[Event.Name=="3 month visit"],
            demographics_age = demographics_age[Event.Name=="Baseline"],
            demographics_sex.factor = Gender[Event.Name=="Baseline"]) %>%
  filter(demographics_sex.factor != "Trans female")
df$demographics_sex.factor <- as.factor(df$demographics_sex.factor)
# Get am use at final timepoint
success <- stanford %>% group_by(Participant.ID) %>%
  filter(Event.Name == "12 month visit" | 
           Event.Name =="9 month visit") %>%
  filter(row_number() == n()) %>%
  summarise(am_final = Auto.Mode...1)
# Combine
df <- left_join(df,success,by = "Participant.ID")
df$success <- as.factor(ifelse(df$am_final >= 60,1,0))
```

What to do about trans female (n = 1) in this cohort? Treat as female? For now I've just excluded them.

```{r test model,echo=FALSE}
# Model formula
final_model <- 
  as.formula("success ~ scale(hba1c,scale=F) + scale(m3_am_time,scale=F) + 
  scale(m3_tir,scale=F) + demographics_age + demographics_sex.factor")
# Fit
model_stanford <- glm(final_model,family = "binomial",df)
# Results
t = broom::tidy(model_stanford,conf.int = T)
t$term[2:nrow(t)] = c("Baseline HbA1c","M3 AM %","M3 TIR",
                      "Baseline Age 14 - 18","Baseline Age 18+","Male")
kable(t)
# ROC
r = ROC(form = final_model,data = df,MX=F,MI=F,PV=F,plot = "ROC")
```