---
title: "Vira Kravets - Mixed model"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

library(nlme)
library(robustlmm)
library(geoR)
library(sjstats)
library(car)
library(readxl)

# read in data, log transform after adding a small number to account for zeroes
data <- read.csv("B:\\Projects\\Vira Kravets\\Data raw\\T-Tswap-Median,% - Fig2C.csv")
data$um <- NULL
colnames(data) <- c("islet","initial","repeated","distance")
data$l_initial <- log(data$initial+0.0001)

# read in data for figure 3
fig3 <- read.csv("B:\\Projects\\Vira Kravets\\Data raw\\fig 3.csv")

# read in data for figure 2
fig2e <- read_xlsx("B:\\Projects\\Vira Kravets\\Data raw\\Figure2 for LP mixed model.xlsx",sheet = "Fig.2 E 1st rep")
fig2e$...2 <- NULL
fig2e$Islet <- NULL
colnames(fig2e) <- c("islet","initial","repeated")
fig2e$l_initial <- log(fig2e$initial+0.0001)

###########
# FIG 2c  #
###########

# run a mixed model with log-transformed initial values
mod_2c <- lme(repeated ~ l_initial,random=~1|islet,data = data)
resid <- residuals(mod_2c)
pred <- predict(mod_2c)
data_with_pred <- cbind(data,pred)

# write residuals and predicted values to file
#write.csv(resid,"B:\\Projects\\Vira Kravets\\Output\\residuals_fig2c.csv",row.names = F)
#write.csv(data_with_pred,"B:\\Projects\\Vira Kravets\\Output\\data_with_predicted_values_fig2c.csv",row.names = F)

# QQplot
a <- qqnorm(mod_2c,abline = c(0,1))
x <- a$panel.args[[1]]$x
y <- a$panel.args[[1]]$y
points <- cbind(x,y)
write.csv(points,"B:\\Projects\\Vira Kravets\\Output\\qqplot_fig2c.csv")

###############
# FIG 2c <40  #
###############
resid <- NULL
pred <- NULL
points <- NULL
data_with_pred <- NULL
a <- NULL
x <- NULL
y <- NULL
# run a mixed model with log-transformed initial values
mod_2c_lt40 <- lme(repeated ~ l_initial,random=~1|islet,data = data[data$distance<40,])
resid <- residuals(mod_2c_lt40)
pred <- predict(mod_2c_lt40)
data_with_pred <- cbind(data[data$distance<40,],pred)

# write residuals and predicted values to file
#write.csv(resid,"B:\\Projects\\Vira Kravets\\Output\\residuals_fig2c_lt40.csv",row.names = F)
#write.csv(data_with_pred,"B:\\Projects\\Vira Kravets\\Output\\data_with_predicted_values_fig2c_lt40.csv",row.names = F)

# QQplot
a <- qqnorm(mod_2c_lt40,abline = c(0,1))
x <- a$panel.args[[1]]$x
y <- a$panel.args[[1]]$y
points <- cbind(x,y)
write.csv(points,"B:\\Projects\\Vira Kravets\\Output\\qqplot_fig2c_lt40.csv")

###############
# FIG 2c <50  #
###############
resid <- NULL
pred <- NULL
points <- NULL
data_with_pred <- NULL
a <- NULL
x <- NULL
y <- NULL
# run a mixed model with log-transformed initial values
mod_2c_lt50 <- lme(repeated ~ l_initial,random=~1|islet,data = data[data$distance<50,])
resid <- residuals(mod_2c_lt50)
pred <- predict(mod_2c_lt50)
data_with_pred <- cbind(data[data$distance<50,],pred)

# write residuals and predicted values to file
#write.csv(resid,"B:\\Projects\\Vira Kravets\\Output\\residuals_fig2c_lt50.csv",row.names = F)
#write.csv(data_with_pred,"B:\\Projects\\Vira Kravets\\Output\\data_with_predicted_values_fig2c_lt50.csv",row.names = F)

# QQplot
a <- qqnorm(mod_2c_lt50,abline = c(0,1))
x <- a$panel.args[[1]]$x
y <- a$panel.args[[1]]$y
points <- cbind(x,y)
write.csv(points,"B:\\Projects\\Vira Kravets\\Output\\qqplot_fig2c_lt50.csv")

###############
# FIG 2c <60  #
###############
resid <- NULL
pred <- NULL
points <- NULL
data_with_pred <- NULL
a <- NULL
x <- NULL
y <- NULL
# run a mixed model with log-transformed initial values
mod_2c_lt60 <- lme(repeated ~ l_initial,random=~1|islet,data = data[data$distance<60,])
resid <- residuals(mod_2c_lt60)
pred <- predict(mod_2c_lt60)
data_with_pred <- cbind(data[data$distance<60,],pred)

# write residuals and predicted values to file
#write.csv(resid,"B:\\Projects\\Vira Kravets\\Output\\residuals_fig2c_lt60.csv",row.names = F)
#write.csv(data_with_pred,"B:\\Projects\\Vira Kravets\\Output\\data_with_predicted_values_fig2c_lt60.csv",row.names = F)

# QQplot
a <- qqnorm(mod_2c_lt60,abline = c(0,1))
x <- a$panel.args[[1]]$x
y <- a$panel.args[[1]]$y
points <- cbind(x,y)
write.csv(points,"B:\\Projects\\Vira Kravets\\Output\\qqplot_fig2c_lt60.csv")

###########
# FIG 3   #
###########
resid <- NULL
pred <- NULL
points <- NULL
data_with_pred <- NULL
a <- NULL
x <- NULL
y <- NULL
# no islet indicator?
# have not fixed the code below

# run a mixed model with log-transformed initial values
# mod_3 <- lme(glibencl ~ glucose,random=~1|islet,data = data)
# resid <- residuals(mod_2c)
# pred <- predict(mod_2c)
# data_with_pred <- cbind(data,pred)

# write residuals and predicted values to file
#write.csv(resid,"B:\\Projects\\Vira Kravets\\Output\\residuals_fig2c.csv",row.names = F)
#write.csv(data_with_pred,"B:\\Projects\\Vira Kravets\\Output\\data_with_predicted_values_fig2c.csv",row.names = F)

# QQplot
# a <- qqnorm(mod_2c,abline = c(0,1))
# x <- a$panel.args[[1]]$x
# y <- a$panel.args[[1]]$y
# points <- cbind(x,y)
# write.csv(points,"B:\\Projects\\Vira Kravets\\Output\\qqplot_fig2c.csv")

###########
# FIG 2e  #
###########

# I don't think a repeated measures model is needed for the situation where there is only one value of repeated

resid <- NULL
pred <- NULL
points <- NULL
data_with_pred <- NULL
a <- NULL
x <- NULL
y <- NULL

# run a mixed model with log-transformed initial values
mod_2e <- lme(repeated ~ l_initial,random=~1|islet,data = fig2e)
resid <- residuals(mod_2e)
pred <- predict(mod_2e)
data_with_pred <- cbind(fig2e,pred)

# write residuals and predicted values to file
#write.csv(resid,"B:\\Projects\\Vira Kravets\\Output\\residuals_fig2e.csv",row.names = F)
#write.csv(data_with_pred,"B:\\Projects\\Vira Kravets\\Output\\data_with_predicted_values_fig2e.csv",row.names = F)

# QQplot
a <- qqnorm(mod_2e,abline = c(0,1))
x <- a$panel.args[[1]]$x
y <- a$panel.args[[1]]$y
points <- cbind(x,y)
write.csv(points,"B:\\Projects\\Vira Kravets\\Output\\qqplot_fig2e.csv")

```

# Figure 2c 

## All data

```{r echo=FALSE, comment=""}
summary(mod_2c)
```

Interpretation of model above: for a 1% increase in initial, repeated increases by `r summary(mod_2c)$tTable[2,1]`%.

```{r echo=FALSE, comment=""}
a
shapiro.test(resid(mod_2c))
r2(mod_2c)
```
<br>

## Distance <40

```{r echo=FALSE, comment=""}
summary(mod_2c_lt40)
```

Interpretation of model above: for a 1% increase in initial, repeated increases by `r summary(mod_2c_lt40)$tTable[2,1]`%.

```{r echo=FALSE, comment=""}
a
shapiro.test(resid(mod_2c_lt40))
r2(mod_2c_lt40)
```
<br>

## Distance <50

```{r echo=FALSE, comment=""}
summary(mod_2c_lt50)
```

Interpretation of model above: for a 1% increase in initial, repeated increases by `r summary(mod_2c_lt50)$tTable[2,1]`%.

```{r echo=FALSE, comment=""}
a
shapiro.test(resid(mod_2c_lt50))
r2(mod_2c_lt50)
```
<br>

## Distance <60

```{r echo=FALSE, comment=""}
summary(mod_2c_lt60)
```

Interpretation of model above: for a 1% increase in initial, repeated increases by `r summary(mod_2c_lt60)$tTable[2,1]`%.

```{r echo=FALSE, comment=""}
a
shapiro.test(resid(mod_2c_lt60))
r2(mod_2c_lt60)
```
<br>

# Figure 2e

```{r echo=FALSE, comment=""}
summary(mod_2e)
```

Interpretation of model above: for a 1% increase in initial, repeated increases by `r summary(mod_2c)$tTable[2,1]`%.

```{r echo=FALSE, comment=""}
a
shapiro.test(resid(mod_2e))
r2(mod_2e)
```
<br>
