---
title: "Daily Predictors for Diabetes Management"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
library(arsenal)
library(skimr)
library(knitr)
library(tidyverse)
library(Hmisc)
library(lubridate)
library(lme4)
library(lmerTest)
library(performance)
library(broom.mixed)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "B:/Projects"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r clean data}
source("/Users/timvigers/Documents/GitHub/BDC-Code/Laurel Messer/Daily Predictors/clean_data.r")
# Combine race columns
race_cols = paste0("pt_race___",1:6)
races = c("White","Black or African American","American Indian or Alaskan Native",
          "Asian","Native Hawaiian or Pacific Islander","Other")
data$race = apply(data[,race_cols], 1, function(r){
  paste0(races[which(r == 1)],collapse = ", ")
})
# Calculate age and duration
data$age = as.numeric(ymd(data$pt_visit_date) - ymd(data$pt_dob))/365.25
data$duration = as.numeric(ymd(data$pt_visit_date) - ymd(data$dxdate))/365.25
# ID as factor for glmmLasso
data$record_id = as.factor(data$record_id)
# Correlation between engagement survey items and subscores and:
#   Number of insulin boluses
#   Average glucose level
#   Percent time glucose levels 70-180 mg/dl (“Time-in-Range”, TIR)
#   Goal Survey Scores
morning_items = colnames(data)[grep("esq\\d+$",colnames(data))]
evening_items = colnames(data)[grep("esq\\d+_eve$",colnames(data))]
# Outcomes
outcomes = c("boluses","smg","tir","n_highalerts","dm_caretime","dm_thinktime","gsq","combined")
# ID Variables
id_vars = c("record_id","redcap_event_name","date")
# Combine date columns
data$es_date = as.Date.character(lubridate::ymd_hm(data$es_datetimecapture))
data$es_date_eve = as.Date.character(lubridate::ymd_hm(data$es_datetimecapture_eve))
data = data %>% unite(date,dmi_date,es_date,es_date_eve,remove = F,na.rm = T)
data$date = sapply(strsplit(data$date,"_"),function(x){
  ifelse(length(x)==0,NA,
         unique(strsplit(x,"_")[[1]]))
})
# Average gsq scores
data$gsq = rowMeans(data[,c("gsq1","gsq2","gsq3")],na.rm = T)
data$gsq[is.nan(data$gsq)] = NA
# % of HA per day that had either a 1 for HAB or 1 for bgdrop or 1 for both
for (i in 1:10) {
  vars = c(paste0("hab",i),paste0("bgdrop_ha",i)) # Each alert has two separate columns that need to be combined
  n = paste0("combined_hab",i)
  data = data %>% unite(!!n,all_of(vars),remove = F)
  data[,n] = sapply(data[,n],function(x){
    if(x == "NA_NA"){NA}else{as.numeric(grepl("1",x))} # Don't count NAs as 1 or 0
  })
}
combined = paste0("combined_hab",1:10)
data$combined = rowMeans(data[,combined],na.rm = T) # Percentage of 1s
data$combined[is.nan(data$combined)] = NA
data$combined = cut(data$combined,c(-Inf,0.5,Inf),right = T)
data$combined = as.numeric(data$combined)-1
# Fill outcome in by date
data = data %>% group_by(record_id,date) %>%
  fill(all_of(outcomes),.direction = "downup") %>%
  ungroup()
# Remove outcomes not on a 24 hour scale
data = data[-which(data$n_highalerts > 500),]
data = data[-which(data$dm_thinktime > 12000),]
# Remove 0  and too high BG
data$esq1[data$esq1 == 0] = NA
# Evening outcomes - look at association with the next day's outcome
data = data %>% group_by(record_id) %>% 
  mutate(next_day_boluses = lead(boluses),
         next_day_smg = lead(smg),
         next_day_tir = lead(tir),
         next_day_n_highalerts = lead(n_highalerts),
         next_day_dm_caretime = lead(dm_caretime),
         next_day_dm_thinktime = lead(dm_thinktime),
         next_day_gsq = lead(gsq),
         next_day_combined = lead(combined),
         next_day_esq = lead(esq1))
# Convert to dataframe since these functions can't handle tibbles
data = data.frame(data)
```

# Participant Characteristics

```{r results = 'asis'}
# Get first row for each person
demographics = data %>% group_by(record_id) %>% filter(row_number() == 1)
# Table 
t1 = tableby(~ age + duration + pt_a1c + pt_baseline1.factor + pt_baseline5.factor + 
               pt_gender.factor + race + pt_eth.factor + p1_hedu.factor + 
               p2_hedu.factor,demographics)
# Labels
new_labels = list(age = "Age", duration = "Diabetes Duration", pt_a1c = "Baseline HbA1c",
                  pt_baseline1.factor = "Pump Hx",pt_baseline5.factor = "CGM Hx",
                  pt_gender.factor = "Gender", race = "Race", pt_eth.factor = "Ethnicity", 
                  p1_hedu.factor = "Parent 1 Education", p2_hedu.factor = "Parent 2 Education")
summary(t1,labelTranslations = new_labels)
```

# Psychological Predictors

```{r results='asis'}
marg_r2s = NA
length(marg_r2s) = length(2:length(morning_items))
for (v in 2:length(morning_items)) {
  df = data
  # Title
  cat("\n")
  cat(paste0("### ",morning_items[v]))
  cat("\n")
  # Get factor if necessary
  var = morning_items[v]
  # Fit simple model
  f = as.formula(paste0("esq1~",var,"+(1|record_id)"))
  m = lmer(f,data = df)
  r = tidy(m,"fixed")
  r$effect = NULL
  print(kable(r,digits = 3)) 
  r2 = r2_nakagawa(m)
  print(paste("Marginal R2:",round(r2$R2_marginal,3)))
  marg_r2s[v] = round(r2$R2_marginal,3)
}
```

Maximum marginal $R^2$: `r max(marg_r2s,na.rm=T)`

# How many minutes do you think you spent caring for your diabetes today?

```{r results='asis'}
outs = c("tir","smg","boluses","combined","gsq")
data$combined = factor(data$combined,levels = c(0,1),labels = c("No","Yes"))
for (v in outs) {
  # Title
  cat("\n")
  cat(paste0("### ",v))
  cat("\n")
  # Fit simple model
  f = as.formula(paste0(v,"~dm_caretime","+(1|record_id)"))
  if(v == "combined"){
    m = glmer(f,data = data,family = "binomial")
    cat("\n")
    cat("The 'combined' outcome is a binary variable, so the results are interpreted on the odds ratio scale.")
    cat("\n")
  } else {
    m = lmer(f,data = data)
  }
  r = tidy(m,"fixed")
  r$effect = NULL
  print(kable(r,digits = 3))
}
```

# How many minutes do you think you spent thinking about your diabetes today?

```{r results='asis'}
for (v in outs) {
  # Title
  cat("\n")
  cat(paste0("### ",v))
  cat("\n")
  f = as.formula(paste0(v,"~dm_thinktime","+(1|record_id)"))
  if(v == "combined"){
    m = glmer(f,data = data,family = "binomial")
    cat("\n")
    cat("The 'combined' outcome is a binary variable, so the results are interpreted on the odds ratio scale.")
    cat("\n")
  } else {
    m = lmer(f,data = data)
  }
  r = tidy(m,"fixed")
  r$effect = NULL
  print(kable(r,digits = 3))
}
```

# Characterizing variability

```{r results='asis',message=FALSE}
preds = outs[-4]
for (v in preds) {
  # Title
  cat("\n")
  cat(paste0("### ",v))
  cat("\n")
  # Calculate change over time 
  df = data %>% filter(!grepl("E_",redcap_event_name.factor)) %>%
    select(record_id,redcap_event_name.factor,all_of(v)) %>%
    mutate(delta = abs((!!sym(v)) - lag((!!sym(v))))) %>%
    group_by(record_id) %>% mutate(vis_num = row_number())
  # Plot
  p = ggplot(data,aes_string(x = "record_id",y = v)) + 
    geom_boxplot() + theme_bw() + 
    theme(axis.text.x=element_blank(),axis.title.x = element_blank(),
          axis.ticks.x=element_blank())
  cat("\n")
  print(p)
  cat("\n")
  # Fit simple model
  m = lmer(delta ~ 1+ (1|record_id),data = df)
  r = tidy(m,"fixed")
  r$effect = NULL
  cat("\n")
  cat(paste0("The mean absolute value of daily change was ",round(r$estimate[1],2),
             " +/- ",round(r$std.error[1],2),". (p = ",
             format.pval(r$p.value,eps = 0.001),")"))
  cat("\n")
}
```

```{r warning=FALSE,fig.height=12,fig.width=12,dpi=1200}
library(patchwork)
p_tir = ggplot(data,aes_string(x = "record_id",y = "tir")) + 
    geom_boxplot() + theme_bw(base_size = 20) + ylab("TIR") +
    theme(axis.text.x=element_blank(),axis.title.x = element_blank(),
          axis.ticks.x=element_blank())
p_smg = ggplot(data,aes_string(x = "record_id",y = "smg")) + 
    geom_boxplot() + theme_bw(base_size = 20) + ylab("Mean Glucose") +
    theme(axis.text.x=element_blank(),axis.title.x = element_blank(),
          axis.ticks.x=element_blank())
p_bol = ggplot(data[data$boluses < 40,],aes_string(x = "record_id",y = "boluses")) + 
    geom_boxplot() + theme_bw(base_size = 20) + ylab("Boluses") +
    theme(axis.text.x=element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x=element_blank(),)
p_tir / p_smg / p_bol + plot_annotation(tag_levels = "A")
```

# Boluses

## TIR

```{r results='asis',message=FALSE}
m = lmer(tir ~ boluses + (1|record_id),data = data)
r = tidy(m,"fixed")
r$effect = NULL
p = ggplot(m@frame,aes(x=boluses,y=tir,color=record_id)) + 
  geom_point() +
  geom_smooth(method = "lm",se = F,aes(x=boluses,y=tir),inherit.aes = F) + 
  theme_bw() + theme(legend.position = "none")
print(p)
kable(r,digits = 3)
```

## SMG 

```{r results='asis',message=FALSE}
m = lmer(smg ~ boluses + (1|record_id),data = data)
r = tidy(m,"fixed")
r$effect = NULL
p = ggplot(m@frame,aes(x=boluses,y=smg,color=record_id)) + 
  geom_point() +
  geom_smooth(method = "lm",se = F,aes(x=boluses,y=smg),inherit.aes = F) + 
  theme_bw() + theme(legend.position = "none")
print(p)
kable(r,digits = 3)
```

# Demographic information

```{r results='asis'}
ids = data %>% select(record_id,tir)
ids = ids[complete.cases(ids),]
ids = unique(as.character(ids$record_id))

# Get first row for each person
demographics = data %>% filter(record_id %in% ids) %>% group_by(record_id) %>% filter(row_number() == 1)
# Table 
t1 = tableby(~ age + duration + pt_a1c + pt_baseline1.factor + pt_baseline5.factor + 
               pt_gender.factor + race + pt_eth.factor + p1_hedu.factor + 
               p2_hedu.factor,demographics)
# Labels
new_labels = list(age = "Age", duration = "Diabetes Duration", pt_a1c = "Baseline HbA1c",
                  pt_baseline1.factor = "Pump Hx",pt_baseline5.factor = "CGM Hx",
                  pt_gender.factor = "Gender", race = "Race", pt_eth.factor = "Ethnicity", 
                  p1_hedu.factor = "Parent 1 Education", p2_hedu.factor = "Parent 2 Education")
summary(t1,labelTranslations = new_labels)
```

# Means

```{r}
m = lmer(dm_thinktime ~ 1 + (1|record_id),data = data)
```