---
title: ""
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
# library(arsenal)
library(tidyverse)
# library(readxl)
# library(performance)
# library(knitr) 
# library(data.table)
# library(broom)
# library(pROC)
# library(caTools)
# library(glmnet)
# analysis pckgs
library(Seurat) # need these for Differential expression testing
library(SeuratObject)
# library(DESeq2)
# #library(scran)
# library(pzfx)
# library(SingleCellExperiment)
# library(S4Vectors)
# cell express %
#library(scCustomize)

###
#library(cowplot)
#library(Matrix.utils)
#library(edgeR)
# library(Matrix)
# library(reshape2)
# library(S4Vectors)
# library(SingleCellExperiment)
# library(pheatmap)
# #library(apeglm)
# library(png)
# library(DESeq2)
# library(RColorBrewer)
# library(data.table)
#library(Matrix.utils)
###

# data
#home_dir = "/run/user/1001/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Howard Davidson/R01/Data_Raw/Davidson pilot data/"
knitr::opts_knit$set(root.dir = home_dir)
#setwd("/run/user/1001/gvfs/smb-share:server=ucdenver.pvt,share=som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects/Howard Davidson/R01/Data_Raw/Davidson pilot data/")
# cd4_processed = readRDS(paste0(home_dir, "OneDrive_1_6-28-2023/cd4_cells_processed.rds"))
# cd8_processed = readRDS(paste0(home_dir, "OneDrive_1_6-28-2023/cd8_cells_processed.rds"))
#df = readRDS()
#use regular clusters
#df2 = df

# casey workspace on lambda
filename = file.choose()
df = readRDS(filename)

# new clusters
#df2 = SetIdent(df, value= df@meta.data$RNA_clustifyr_celltype_individual)
#rm(df)
```

```{r}
# Tim's code
# Convert Seurat to cell by gene matrix, add cluster
gene_list <- unique(rownames(df))
cells <- FetchData(df, vars = gene_list)
cells$cluster <- Idents(df)
# Calculate average expression level for each gene
mean_expr <- cells %>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = T)))
# Calculate the percentage of cells expressing
perc_exp <- cells %>%
  summarise(across(where(is.numeric), ~ mean(.x > 0, na.rm = T) * 100))
# By cluster
# Calculate average expression level for each gene
mean_expr_clust <- cells %>%
  group_by(cluster) %>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = T)))
# Calculate the percentage of cells expressing
perc_exp_clust <- cells %>%
  group_by(cluster) %>%
  summarise(across(where(is.numeric), ~ mean(.x > 0, na.rm = T) * 100))

# write 
#getwd()
# write_csv(mean_expr_clust, "mean_express_cluster.csv")
# write_csv(perc_exp_clust, "perc_express_cluster.csv")

```

