---
title: "Comparison of machine learning approaches to model selection in identifying biomarkers of islet autoimmunity in type 1 diabetes"
author: "Tim Vigers, Bobbie-Jo M. Webb-Robertson, Howard Davidson, Laura Pyle"
institute: "University of Colorado Anschutz Medical Campus, Aurora, Colorado, USA"
date: "July 12, 2022"
output: 
  ioslides_presentation:
    widescreen: true
    autosize: true
    slide_level: 3
    css: custom.css
    bibliography: "bibliography.bib"
    csl: american-medical-association-no-url.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style>
div.footnotes {
  position: absolute;
  bottom: 0;
  margin-bottom: 10px;
  width: 80%;
  font-size: 0.6em;
}
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
  $('slide:not(.backdrop):not(.title-slide)').append('<div class=\"footnotes\">');

  $('footnote').each(function(index) {
    var text  = $(this).html();
    var fnNum = (index+1).toString();
    $(this).html(fnNum.sup());

    var footnote   = fnNum + '. ' + text + '<br/>';
    var oldContent = $(this).parents('slide').children('div.footnotes').html();
    var newContent = oldContent + footnote;
    $(this).parents('slide').children('div.footnotes').html(newContent);
  });
});
</script>

<script>
$(document).ready(function() {
  $('slide:not(.backdrop):not(.title-slide)').append('<div class=\"footnotes\">');

  $('footnote_nonum').each(function(index) {
    var text  = $(this).html();
    var fnNum = ("").toString();
    $(this).html(fnNum.sup());

    var footnote   = text + '<br/>';
    var oldContent = $(this).parents('slide').children('div.footnotes').html();
    var newContent = oldContent + footnote;
    $(this).parents('slide').children('div.footnotes').html(newContent);
  });
});
</script>

## Outline

### Outline

## Background

### Type 1 diabetes

- Type 1 diabetes (T1D) is an autoimmune disease that leads to destruction of the pancreatic &#x3B2;-cells and the loss of insulin production
- T1D requires life-long insulin therapy and is associated with complications including cardiovascular disease, kidney disease, and microvascular complications
- On average, a 20-year-old male loses 11.1 years and a 20-year-old female loses 12.9 years of life expectancy [@livingstone_estimated_2015]
- The global incidence of T1D is increasing by 3-5% annually

### Type 1 diabetes

- T1D is typically preceded by development of islet autoimmunity (IA)
- what is IA
- HLA
- other risk factors and potential biomarkers (genetic, etc)

### The TEDDY study

### Objective

- Our goal was to develop a risk prediction model for IA (see proposals for additional description) in TEDDY study participants
- The pool of candidate markers is large and complex, including high-dimensional omics data such as single-nucleotide polymorphisms (SNPs) and metabolomics
- We compared three machine learning (ML) approaches to model selection:
  - An ensemble ML approach (need more here?)
  - DIFAcTO pipeline [@ref]
  - Elastic net regression

## Methods

### Methods

- describe variables from TEDDY that were included

### Ensemble ML approach

- From Bobbi-Jo's paper

### DIFAcTO pipeline

- Variables were scaled and clustered using Pearson's correlation
- The variable within a cluster with the strongest association with the outcome was selected to represent the cluster
- The minimum within-cluster correlation was selected using cross-validation
- LASSO regression was used to perform model selection on the remaining features

### Elastic net regression

- The *ensr* package in R was used to perform a grid search for $\alpha$ and $\lambda$ values that minimized the cross-validation error

### Simulation methods

- To further compare the DIFAcTO pipeline and elastic net regression, we applied these methods to a simulated high-dimensional dataset
- We used metabolomic data from the COPD Gene study (ref) as well as proteomic data from the TODAY study (ref) to inform our choices of simulation parameters
- We simulated 1000 datasets of each of the following scenarios:
    - 50 or 200 features 
    - 30, 100, 200, 500 samples
- We first generated a random correlation matrix and controlled the sparsity by randomly setting some elements of the correlation matrix to zero, using a probability of a non-zero correlation at 5%

### Simulation methods

- Means were drawn from a $N(1500,830)$ distribution and SDs were drawn from a $U(1,500)$ distribution
- We regressed metabolites on age and simulated $\beta \sim N(0.002, 0.04)$, with $\epsilon \sim N(0,8)$
- We randomly selected features to be included in the simulation model
- We evaluated the performance of DIFAcTO and elastic net by calculating the Jaccard similarity and RMSE vs. the true model

## Results

### TEDDY study results

### Simulation results

- make a table of the Jaccard similarity and RMSE for each of the simulation scenarios

### Simulation results

- Show one plot
- Comments:
  - EN had higher Jaccard similarity and lower RMSE for all scenarios
  - EN tended to choose larger models

## Conclusions

### Conclusions

### Future work

- structured correlation matrix, although there was not much structure in the COPD Gene data
- other simulation parameters, including sparsity

### Acknowledgments

### References
