---
title: "TODAY Somalogic associations"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = ""
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# merge in complication data
base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# only keep observations with nonmissing values of covariates
# otherwise size of contrast matrix will be incorrect
base <- base %>% filter(!is.na(HbA1c) & !is.na(log_trig) & !is.na(sbp) & !is.na(si_1_ins0))

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
# no_var = caret::nearZeroVar(base[,seq])
# none

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)
```

```{r, include=FALSE}
# continuous variables: AGEBASE, HbA1c, si_1_ins0

# age
age = matrix(base$AGEBASE)
data = base[,39:7500]
# Get betas and error from univariate models
betas = sapply(data, function(m){
  mod = lm(age~m)
  return(summary(mod)$coefficients[2,1])
})
epsilon_resid = unlist(lapply(data, function(m){
  mod = lm(age~m)
  return(residuals(mod))
}))
# Plots
hist(betas) 
mean(betas)
sd(betas)
hist(epsilon_resid)
mean(epsilon_resid)
sd(epsilon_resid)


# HbA1c
a1c = matrix(base$HbA1c)
data = base[,39:7500]
# Get betas and error from univariate models
betas = sapply(data, function(m){
  mod = lm(a1c~m)
  return(summary(mod)$coefficients[2,1])
})
epsilon_resid = unlist(lapply(data, function(m){
  mod = lm(age~m)
  return(residuals(mod))
}))
# Plots
hist(betas) 
mean(betas)
sd(betas)
hist(epsilon_resid)
mean(epsilon_resid)
sd(epsilon_resid)
```

# Results

## Descriptive statistics

```{r echo=FALSE, include=FALSE}

```

```{r echo=FALSE, include=TRUE}
kable(t1)
```
