---
title: "PIU! Imputation"
author: "Tim Vigers & Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/BDC/Projects")
library(arsenal)
library(skimr)
library(knitr)
library(mice)
library(lavaan)
library(tidyverse)
```

```{r data import and combine,echo=FALSE,include=FALSE}
nastrings <- c("-999","999","NA","","#N/A")
# Child data
# Read in and combine
child <- read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_biological.csv",na.strings = nastrings)
child$Respondent <- 3
child <- left_join(child,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/background.csv",
                                  na.strings = nastrings))
child <- left_join(child,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_depression.csv",
                                  na.strings = nastrings))
child <- left_join(child,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_foh.csv",
                                  na.strings = nastrings))
child <- left_join(child,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_qol.csv",
                                  na.strings = nastrings))
child <- left_join(child,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_puberty.csv",
                                  na.strings = nastrings))
child <- left_join(child,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_meter_skills.csv",
                                  na.strings = nastrings))
child <- left_join(child,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/bdi.csv",na.strings = nastrings))
child <- left_join(child,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_parent_pump_knowledge.csv",
                                  na.strings = nastrings))
child <- left_join(child,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_parent_t1d_responsibility.csv",
                                  na.strings = nastrings))
child <- 
  left_join(child,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_parent_general_responsibility.csv",
                           na.strings = nastrings))
# Format
datecols <- c("Date","DateofBirth")
child[,datecols] <- lapply(child[,datecols], lubridate::mdy)
# Calculated variables
child$Age <- 
  as.numeric(difftime(as.Date(child$Date),as.Date(child$DateofBirth))/365.25)
# Parent data
parent <- read.csv("./Kim Driscoll/Imputation Model/Data_Clean/parent_depression.csv",na.strings = nastrings)

parent <- left_join(parent,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/parent_foh.csv",
                                    na.strings = nastrings))
parent <- left_join(parent,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_parent_pump_knowledge.csv",
                                    na.strings = nastrings))
parent <- left_join(parent,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_parent_t1d_responsibility.csv",
                                    na.strings = nastrings))
parent <- left_join(parent,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/child_parent_general_responsibility.csv",
                                    na.strings = nastrings))
parent <- left_join(parent,read.csv("./Kim Driscoll/Imputation Model/Data_Clean/parent_qol.csv",
                                    na.strings = nastrings))
# Write to baseline paper data folder
write.csv(child,file = "./Kim Driscoll/PIU Baseline Paper/Data_Cleaned/child.csv",
          row.names = F,na = "")
write.csv(parent,file = "./Kim Driscoll/PIU Baseline Paper/Data_Cleaned/parent.csv",
          row.names = F,na = "")
```

```{r mean imputation,echo=FALSE,eval=FALSE}
mean_impute <- function(x,missing_proportion = 0.25){
  prop = sum(is.na(x))/length(x)
  if(prop <= missing_proportion){
    x[is.na(x)] <- mean(as.numeric(x),na.rm = T)
  }
  return(round(x,1))
}
# Impute child data
# CDI
child[,grep("CDI",colnames(child))] <- 
  t(apply(child[,grep("CDI",colnames(child))],1,mean_impute))
# FOH
child[,grep("FOH",colnames(child))] <- 
  t(apply(child[,grep("FOH",colnames(child))],1,mean_impute))
# PEDSQL
child[,grep("PEDSQL",colnames(child))] <- 
  t(apply(child[,grep("PEDSQL",colnames(child))],1,mean_impute))
# METER
child[,grep("METER",colnames(child))] <- 
  t(apply(child[,grep("METER",colnames(child))],1,mean_impute))
# BDIQ
child[,grep("BDIQ",colnames(child))] <- 
  t(apply(child[,grep("BDIQ",colnames(child))],1,mean_impute))
# tdk
child[,grep("tdk",colnames(child))] <- 
  t(apply(child[,grep("tdk",colnames(child))],1,mean_impute))
# BGMIPR
child[,grep("BGMIPR",colnames(child))] <- 
  t(apply(child[,grep("BGMIPR",colnames(child))],1,mean_impute))
# DFRQ
child[,grep("DFRQ",colnames(child))] <- 
  t(apply(child[,grep("DFRQ",colnames(child))],1,mean_impute))
# Impute adult data
# CESD
parent[,grep("CESD",colnames(parent))] <- 
  t(apply(parent[,grep("CESD",colnames(parent))],1,mean_impute))
# FOH
parent[,grep("FOH",colnames(parent))] <- 
  t(apply(parent[,grep("FOH",colnames(parent))],1,mean_impute))
# WECARE
parent[,grep("WECARE",colnames(parent))] <- 
  t(apply(parent[,grep("WECARE",colnames(parent))],1,mean_impute))
# Write CSVs
write.csv(child,file = "./Kim Driscoll/Imputation Model/Data_Clean/child_mean_imputed.csv",row.names = F,na="")
write.csv(parent,file = "./Kim Driscoll/Imputation Model/Data_Clean/parent_mean_imputed.csv",row.names = F,na="")
```