---
title: "Biosample proposal power calculations"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
# required libraries
library(purrr)
library(tableone)
library(dplyr)
library(plyr)
library(zoo)
library(nlme)
library(lme4)
library(emmeans)
library(knitr)
library(car)
library(simr)
```

```{r, include=F}
###########################################################################
# THIS SECTION OF CODE CALCULATES POWER FOR INTERACTION OF GROUP AND TIME #
# FOUR TIMEPOINTS                                                         #
###########################################################################

# read in data
dat <- read.csv("/Volumes/BDC/Projects/Aaron Michels/Collaborative research using biosamples proposal/sample data for power calculation.csv",
                 na.strings = c("NA"," ","","N/R"))
dat$PPI.CD4.TCRs.Present <- ifelse(dat$PPI.CD4.TCRs.Present==2,1,dat$PPI.CD4.TCRs.Present)
length(unique(dat$Dummy.ID))

# note that this is testing the interaction, not difference at any time point
mod <- glmer(PPI.CD4.TCRs.Present ~ Case_control*Sample.Timepoint +
    (1|Dummy.ID), data = dat, family = binomial)
summary(mod)$coef

doTest(mod, fixed("Case_controlcontrol:Sample.Timepoint"))
fixef(mod)["Case_controlcontrol:Sample.Timepoint"] <- -0.44
sim1 <- powerSim(mod, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

# extend sample size to 60
mod_extend <- extend(mod, within = "Case_control + Sample.Timepoint", n=60)
sim2 <- powerSim(mod_extend, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

# extend sample size to 80
mod_extend <- extend(mod, within = "Case_control + Sample.Timepoint", n=80)
sim3 <- powerSim(mod_extend, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

# extend sample size to 100
mod_extend <- extend(mod, within = "Case_control + Sample.Timepoint", n=100)
sim4 <- powerSim(mod_extend, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

# extend sample size to 120
mod_extend <- extend(mod, within = "Case_control + Sample.Timepoint", n=120)
sim5 <- powerSim(mod_extend, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

# extend sample size to 150
mod_extend <- extend(mod, within = "Case_control + Sample.Timepoint", n=150)
sim6 <- powerSim(mod_extend, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

```

```{r, include=F}
###########################################################################
# THIS SECTION OF CODE CALCULATES POWER FOR INTERACTION OF GROUP AND TIME #
# FIVE TIMEPOINTS                                                         #
###########################################################################

# read in data
dat <- read.csv("/Volumes/BDC/Projects/Aaron Michels/Collaborative research using biosamples proposal/sample data for power calculation.csv",
                 na.strings = c("NA"," ","","N/R"))
dat$PPI.CD4.TCRs.Present <- ifelse(dat$PPI.CD4.TCRs.Present==2,1,dat$PPI.CD4.TCRs.Present)
length(unique(dat$Dummy.ID))

# note that this is testing the interaction, not difference at any time point
mod <- glmer(PPI.CD4.TCRs.Present ~ Case_control*Sample.Timepoint +
    (1|Dummy.ID), data = dat, family = binomial)
summary(mod)$coef

doTest(mod, fixed("Case_controlcontrol:Sample.Timepoint"))
fixef(mod)["Case_controlcontrol:Sample.Timepoint"] <- -0.44
sim1 <- powerSim(mod, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

# extend number of timepoints to 5 and also increase sample size
mod_extend <- extend(mod, along="Sample.Timepoint", n=5)
mod_extend <- extend(mod_extend, within = "Case_control + Sample.Timepoint", n=70)
sim2 <- powerSim(mod_extend, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

```

```{r, include=F}
###########################################################################
# THIS SECTION OF CODE CALCULATES POWER FOR INTERACTION OF GROUP AND TIME #
# SIX TIMEPOINTS                                                          #
###########################################################################

# read in data
dat <- read.csv("/Volumes/BDC/Projects/Aaron Michels/Collaborative research using biosamples proposal/sample data for power calculation.csv",
                 na.strings = c("NA"," ","","N/R"))
dat$PPI.CD4.TCRs.Present <- ifelse(dat$PPI.CD4.TCRs.Present==2,1,dat$PPI.CD4.TCRs.Present)
length(unique(dat$Dummy.ID))

# note that this is testing the interaction, not difference at any time point
mod <- glmer(PPI.CD4.TCRs.Present ~ Case_control*Sample.Timepoint +
    (1|Dummy.ID), data = dat, family = binomial)
summary(mod)$coef

doTest(mod, fixed("Case_controlcontrol:Sample.Timepoint"))
fixef(mod)["Case_controlcontrol:Sample.Timepoint"] <- -0.44
sim1 <- powerSim(mod, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)



# extend number of timepoints to 6, N=50 
mod_extend <- extend(mod, along="Sample.Timepoint", n=6)
mod_extend <- extend(mod_extend, within = "Case_control + Sample.Timepoint", n=50)
sim2 <- powerSim(mod_extend, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

# extend number of timepoints to 6, N=60 
mod_extend <- extend(mod, along="Sample.Timepoint", n=6)
mod_extend <- extend(mod_extend, within = "Case_control + Sample.Timepoint", n=60)
sim3 <- powerSim(mod_extend, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

# try N=40???
mod_extend <- extend(mod, along="Sample.Timepoint", n=6)
mod_extend <- extend(mod_extend, within = "Case_control + Sample.Timepoint", n=40)
sim4 <- powerSim(mod_extend, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

# try N=35???
mod_extend <- extend(mod, along="Sample.Timepoint", n=6)
mod_extend <- extend(mod_extend, within = "Case_control + Sample.Timepoint", n=35)
sim5 <- powerSim(mod_extend, fixed("Case_controlcontrol:Sample.Timepoint","z"), nsim=100)

```
